Support registering KeyLoaders
world-federation-of-advertisers/panel-exchange-client pull request #101
Opened 2021-08-31 23:01 UTC by efoxepstein

This provides a hook to inject customization into JNIed C++ without
needing to modify the code. Instead, it just requires clients to link in
a library that statically registers a "KeyLoader", which can be used to
load crypto keys in different ways.

https://rally1.rallydev.com/#/604612930531ud/workviews/collection?detail=%2Ftask%2F607976795807&itemRef=%2Fhierarchicalrequirement%2F607976794839&previousTokens=%2F604612930531ud%2Fworkviews%3Fdetail%3D%252Fuserstory%252F607976794839%26view%3D295a0465-1160-4b45-92f5-4c1c70030166&project=%2Fproject%2F604612930531&ref=%2Fhierarchicalrequirement%2F607976794839&relationship=tasks&fdp=true?fdp=true

2021-09-01 00:24 UTC, jonmolle approved these changes
LGTM, just one minor comment.

Also, I'm not a big JNI user, so this may not be important, but are the passed-in KeyLoader objects expected to also be JNIed C++ as well?

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101#-:-MiTbevS8347azsWGcic:bcz7dej)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @yunyeng)

___
*[src/main/cc/wfa/panelmatch/common/crypto/key_loader.cc, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101#-MiTfonZDAJ4HryVFyYO:-MiTfonZDAJ4HryVFyYP:bhn31x0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7b3c3d42613a4c43273702fa650d40a1959ed798/src/main/cc/wfa/panelmatch/common/crypto/key_loader.cc#L69)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   if (KeyLoader* key_loader = GetGlobalKeyLoader(); key_loader != nullptr) {
>     return key_loader->LoadKey(key_name);
>   }
>   return SecretDataFromStringView(key_name);
> ```
</details>


Do you think it might be a problem to have this able to work invisibly without error before a custom KeyLoader is loaded? It seems to work just fine, it just seems a bit weird to have something able to return before being set (sort of).


<!-- Sent from Reviewable.io -->

2021-09-01 00:29 UTC, efoxepstein reviewed
This is th trick, you don't need to pass them in. You just need to link a C++ library that calls the registration function.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101#-:-MiTk8Ih69g6jP_vbWMG:b-bkgohv)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle and @yunyeng)

___
*[src/main/cc/wfa/panelmatch/common/crypto/key_loader.cc, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101#-MiTfonZDAJ4HryVFyYO:-MiTkMeV2nsf2O0_J7WQ:b-x7dtte) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7b3c3d42613a4c43273702fa650d40a1959ed798/src/main/cc/wfa/panelmatch/common/crypto/key_loader.cc#L69)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

> ```
>   if (KeyLoader* key_loader = GetGlobalKeyLoader(); key_loader != nullptr) {
>     return key_loader->LoadKey(key_name);
>   }
>   return SecretDataFromStringView(key_name);
> ```

Do you think it might be a problem to have this able to work invisibly without error before a custom KeyLoader is loaded? It seems to work just fine, it just seems a bit weird to have something able to return before being set (sort of).
</blockquote></details>

It's loaded via registration so it will be set before `main` executes 


<!-- Sent from Reviewable.io -->

2021-09-01 18:42 UTC, yunyeng approved these changes

2021-09-01 21:26 UTC, robinsons approved these changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle)



<!-- Sent from Reviewable.io -->

2021-09-02 00:31 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101)* status: 1 of 20 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @jonmolle, @oliver-amzn, @robinsons, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/common/crypto/key_loader.cc, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101#-MiTfonZDAJ4HryVFyYO:-MiYuYkr21Qev5Is9QPs:bejl6bh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7b3c3d42613a4c43273702fa650d40a1959ed798/src/main/cc/wfa/panelmatch/common/crypto/key_loader.cc#L69)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's loaded via registration so it will be set before `main` executes 
</blockquote></details>

@jonmolle -- please take another pass on this PR. It now will return an error if no KeyLoader is configured.


<!-- Sent from Reviewable.io -->

2021-09-02 04:42 UTC, stevenwarejones requested changes
> Reviewed 1 of 9 files at r1, 1 of 17 files at r2, 3 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101)* status: 5 of 20 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @jonmolle, @oliver-amzn, and @robinsons)

___
*[src/main/cc/wfa/panelmatch/common/crypto/BUILD.bazel, line 112 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101#-MiZlTU87hGnWJEv7xRW:-MiZlTU87hGnWJEv7xRX:btgq0av) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6c0d8460eca18a2cc75b4fc79bc61a3c8e5fec5c/src/main/cc/wfa/panelmatch/common/crypto/BUILD.bazel#L112)):*
> ```Starlark
>     strip_include_prefix = _INCLUDE_PREFIX,
>     deps = [
>         "@com_github_glog_glog//:glog",
> ```

since you're using glog here, please see my questions about com_github_glog_glog vs com_github_github_glog
___
*[src/main/cc/wfa/panelmatch/common/crypto/key_loader.h, line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101#-MiZnqAc5TNtOvHjHiWw:-MiZnqAc5TNtOvHjHiWx:bfpuxu5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6c0d8460eca18a2cc75b4fc79bc61a3c8e5fec5c/src/main/cc/wfa/panelmatch/common/crypto/key_loader.h#L63)):*
> ```objc
> // If GetGlobalKeyLoader() is null, returns an error. Otherwise, calls LoadKey
> // on it with the given `key_name`.
> absl::StatusOr<::crypto::tink::util::SecretData> LoadKey(
> ```

does secretdata work for non-tink repos like private join and compute with commutative keys? or maybe just call it loadTinkKey


<!-- Sent from Reviewable.io -->

2021-09-02 16:30 UTC, robinsons approved these changes
> Reviewed 4 of 17 files at r2, 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @jonmolle, and @oliver-amzn)



<!-- Sent from Reviewable.io -->

2021-09-02 16:31 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @jonmolle, @oliver-amzn, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/common/crypto/BUILD.bazel, line 112 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101#-MiZlTU87hGnWJEv7xRW:-MibLOFA3O0R--8dO_z4:by2ud1k) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6c0d8460eca18a2cc75b4fc79bc61a3c8e5fec5c/src/main/cc/wfa/panelmatch/common/crypto/BUILD.bazel#L112)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

since you're using glog here, please see my questions about com_github_glog_glog vs com_github_github_glog
</blockquote></details>

We should eventually migrate to com_github_google_glog....
___
*[src/main/cc/wfa/panelmatch/common/crypto/key_loader.h, line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101#-MiZnqAc5TNtOvHjHiWw:-MibLKNh5ye6KGzR1bjb:bmcp66g) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6c0d8460eca18a2cc75b4fc79bc61a3c8e5fec5c/src/main/cc/wfa/panelmatch/common/crypto/key_loader.h#L63)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

does secretdata work for non-tink repos like private join and compute with commutative keys? or maybe just call it loadTinkKey
</blockquote></details>

SecretData is just a vector with a special deleter.


<!-- Sent from Reviewable.io -->

2021-09-07 16:25 UTC, stevenwarejones requested changes
> Reviewed 2 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @jonmolle, and @oliver-amzn)

___
*[src/main/cc/wfa/panelmatch/common/crypto/key_loader.h, line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101#-MiZnqAc5TNtOvHjHiWw:-Mj03V4PAipW6M-lahY-:b-7ztz97) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed9255375d871f4d64f6bff34e05dbe2c7b04f8d/src/main/cc/wfa/panelmatch/common/crypto/key_loader.h#L63)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

SecretData is just a vector with a special deleter.
</blockquote></details>

your response was helpful to me. can you add this as a comment in the code as well?


<!-- Sent from Reviewable.io -->

2021-09-07 16:47 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @jonmolle, @oliver-amzn, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/common/crypto/key_loader.h, line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101#-MiZnqAc5TNtOvHjHiWw:-Mj08xgu5UPLw5eYPV9Q:b-uipqia) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed9255375d871f4d64f6bff34e05dbe2c7b04f8d/src/main/cc/wfa/panelmatch/common/crypto/key_loader.h#L63)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

your response was helpful to me. can you add this as a comment in the code as well?
</blockquote></details>

This is thoroughly documented here: https://github.com/google/tink/blob/master/cc/util/secret_data.h#L44 

It really doesn't make sense to me to denormalize this documentation each place that we use SecretData (which is in many places already)


<!-- Sent from Reviewable.io -->

2021-09-07 19:28 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @jonmolle, and @oliver-amzn)

___
*[src/main/cc/wfa/panelmatch/common/crypto/key_loader.h, line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101#-MiZnqAc5TNtOvHjHiWw:-Mj0ipNv6jymXBsf011p:b-skl1yg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed9255375d871f4d64f6bff34e05dbe2c7b04f8d/src/main/cc/wfa/panelmatch/common/crypto/key_loader.h#L63)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is thoroughly documented here: https://github.com/google/tink/blob/master/cc/util/secret_data.h#L44 

It really doesn't make sense to me to denormalize this documentation each place that we use SecretData (which is in many places already)
</blockquote></details>

Hmmmm... you have a good point. Not sure the best way to onboard people to using Tink SecretData. I'll approve for now.


<!-- Sent from Reviewable.io -->

2021-09-07 19:29 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @jonmolle, @oliver-amzn, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/common/crypto/key_loader.h, line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101#-MiZnqAc5TNtOvHjHiWw:-Mj0j6Dp3X51KBy85mz_:bpc5aoo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed9255375d871f4d64f6bff34e05dbe2c7b04f8d/src/main/cc/wfa/panelmatch/common/crypto/key_loader.h#L63)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Hmmmm... you have a good point. Not sure the best way to onboard people to using Tink SecretData. I'll approve for now.
</blockquote></details>

I'd say the best way is for them to just look at the code


<!-- Sent from Reviewable.io -->

2021-09-07 19:33 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @jonmolle, and @oliver-amzn)



<!-- Sent from Reviewable.io -->

2021-09-07 22:59 UTC, jonmolle reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/101#-:-Mj1U4jY5qGzVA0KAhYJ:bnfp4nl)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @duliomatos1, @oliver-amzn, @robinsons, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-09-07 23:02 UTC, efoxepstein commented
This is for https://rally1.rallydev.com/#/604612930531ud/workviews/collection?detail=%2Ftask%2F607976795807&itemRef=%2Fhierarchicalrequirement%2F607976794839&previousTokens=%2F604612930531ud%2Fworkviews%3Fdetail%3D%252Fuserstory%252F607976794839%26view%3D295a0465-1160-4b45-92f5-4c1c70030166&project=%2Fproject%2F604612930531&ref=%2Fhierarchicalrequirement%2F607976794839&relationship=tasks&fdp=true?fdp=true

2021-09-07 23:02 UTC, merged