initial tasks for Single Blind; Double Blind; Prepare Lookup keys
world-federation-of-advertisers/panel-exchange-client pull request #13
Opened 2021-05-17 21:15 UTC by stevenwarejones

2021-05-17 21:28 UTC, stevenwarejones commented on src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt
> +    println(singleBlindedOutputs)
remove

2021-05-17 21:32 UTC, efoxepstein requested changes
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DoubleBlindJoinKeysTask.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-M_wD_tG9Uq4JLP7pvUH:-M_wD_tG9Uq4JLP7pvUI:brgeun4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/66cf76f852315a330ddaa2fa11480601d95b98df/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DoubleBlindJoinKeysTask.kt#L32)):*
> ```Kotlin
>           .addAllData(
>             reApplyCommutativeEncryption(
>               input["commutative-deterministic-key"]!!,
> ```

Maybe the first step of `execute` should be sanity-checking the inputs.

```
val foo: ByteString = requireNotNull(input["foo"]) { "foo not present in inputs" }
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DoubleBlindJoinKeysTask.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-M_wDONvAdmA9C0t5xvn:-M_wDONvAdmA9C0t5xvo:b-b1or1l) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/66cf76f852315a330ddaa2fa11480601d95b98df/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DoubleBlindJoinKeysTask.kt#L37)):*
> ```Kotlin
>           )
>           .build()
>           .toByteString()
> ```

How about a helper function:

```
fun makeSerializedSharedInputs(data: List<ByteString>): SharedInputs {
  return SharedInputs.newBuilder().addAllData(data).build().toByteString()
}
```
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-M_wELKJ8R3Q22VN-bZK:-M_wELKJ8R3Q22VN-bZL:bw9hto2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/66cf76f852315a330ddaa2fa11480601d95b98df/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt#L43)):*
> ```Kotlin
>     val randomCommutativeDeterministicKey1: ByteString = ByteString.copyFromUtf8("random-key-000")
>     val randomCommutativeDeterministicKey2: ByteString = ByteString.copyFromUtf8("random-key-222")
>     val fakeSendDebugLog: suspend (String) -> Unit = {}
> ```

Can we exercise this somehow? Like maybe:

```
val debugLog = mutableListOf<String>
val fakeSendDebugLog: suspend (String) -> Unit = { debugLog.add(it) }
```

and then pass in some garbage input and make sure something is written to `debugLog`?


<!-- Sent from Reviewable.io -->

2021-05-17 22:11 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13)* status: 7 of 13 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DoubleBlindJoinKeysTask.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-M_wD_tG9Uq4JLP7pvUH:-M_wN6RL5VNqJOtLn_Pl:b-kwgol9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/66cf76f852315a330ddaa2fa11480601d95b98df/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DoubleBlindJoinKeysTask.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe the first step of `execute` should be sanity-checking the inputs.

```
val foo: ByteString = requireNotNull(input["foo"]) { "foo not present in inputs" }
```
</blockquote></details>

i thought this would be done by taskWrapper since it maps inputs anyways
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DoubleBlindJoinKeysTask.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-M_wDONvAdmA9C0t5xvn:-M_wNCZV24GV6lxAqf2O:b-rsbupz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/66cf76f852315a330ddaa2fa11480601d95b98df/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DoubleBlindJoinKeysTask.kt#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How about a helper function:

```
fun makeSerializedSharedInputs(data: List<ByteString>): SharedInputs {
  return SharedInputs.newBuilder().addAllData(data).build().toByteString()
}
```
</blockquote></details>

I don't feel like its a long-term function and will go away when we add in consent and encryption.... didn't want to add a transient helper but can if you want me to


<!-- Sent from Reviewable.io -->

2021-05-17 22:58 UTC, efoxepstein requested changes
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/OutputWriter.kt, line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-M_wY0i2BLNLfyf21dQG:-M_wY0i2BLNLfyf21dQH:b-yqwl8c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dec934e642aab84e19503896efaed08b16a4c0e1/src/main/kotlin/org/wfanet/panelmatch/client/storage/OutputWriter.kt#L20)):*
> ```Kotlin
> 
> /** Interface for OutputWriter adapter. */
> interface OutputWriter {
> ```

Revert this change?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DoubleBlindJoinKeysTask.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-M_wD_tG9Uq4JLP7pvUH:-M_wXUPCER2WvFnPuFTu:bbusupl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/66cf76f852315a330ddaa2fa11480601d95b98df/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DoubleBlindJoinKeysTask.kt#L32)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i thought this would be done by taskWrapper since it maps inputs anyways
</blockquote></details>

Maybe I'm just scarred from Java but I'm super wary of anything but explicitly handling nullable values.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DoubleBlindJoinKeysTask.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-M_wDONvAdmA9C0t5xvn:-M_wW5ZmC9j22IKtgvwh:b8h0uyj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/66cf76f852315a330ddaa2fa11480601d95b98df/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DoubleBlindJoinKeysTask.kt#L37)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I don't feel like its a long-term function and will go away when we add in consent and encryption.... didn't want to add a transient helper but can if you want me to
</blockquote></details>

I'd prefer it but I won't block you here


<!-- Sent from Reviewable.io -->

2021-05-18 14:44 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/OutputWriter.kt, line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-M_wY0i2BLNLfyf21dQG:-M_zrWLx-BiMhht2Ium3:b-7fxq63) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dec934e642aab84e19503896efaed08b16a4c0e1/src/main/kotlin/org/wfanet/panelmatch/client/storage/OutputWriter.kt#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Revert this change?
</blockquote></details>

yuck.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-M_wELKJ8R3Q22VN-bZK:-M_ztPsV6ifl7os35eYz:b-wcp31n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/66cf76f852315a330ddaa2fa11480601d95b98df/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can we exercise this somehow? Like maybe:

```
val debugLog = mutableListOf<String>
val fakeSendDebugLog: suspend (String) -> Unit = { debugLog.add(it) }
```

and then pass in some garbage input and make sure something is written to `debugLog`?
</blockquote></details>

qq: I thought the philosophy was that c++ wouldn't throw exceptions but that Kotlin could... Are we wanting to catch the Kotlin exceptions too and write those to the debug log and then re-throw the exception? I guess what I'm also asking is why not let the error bubble up and have the taskWrapper or jobStarter catch the exception and add it to the debug log?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DoubleBlindJoinKeysTask.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-M_wD_tG9Uq4JLP7pvUH:-M_znbkd7mrdM70oiQqO:bv1exib) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/66cf76f852315a330ddaa2fa11480601d95b98df/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DoubleBlindJoinKeysTask.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe I'm just scarred from Java but I'm super wary of anything but explicitly handling nullable values.
</blockquote></details>

Currently, it throws a null pointer exception, but I'll add in some `requireNotNull` which changes it to illegal argument exception which is more explicit.


<!-- Sent from Reviewable.io -->

2021-05-18 19:02 UTC, efoxepstein requested changes
> Reviewed 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/protocol/common/Utils.kt, line 24 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma-qV-X6OJIfQ5Ro9d5:-Ma-qV-X6OJIfQ5Ro9d6:bylhti0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d86f2f66f1146748d750e0c5f8d447ce4a16f4e0/src/main/kotlin/org/wfanet/panelmatch/protocol/common/Utils.kt#L24)):*
> ```Kotlin
> }
> 
> fun parseSerializedSharedInputs(data: ByteString?): List<ByteString> {
> ```

I feel like we'd want to throw some meaningful error instead of passing a null value here -- I'd recommend not allowing the input to be nullable.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/EncryptTask.kt, line 28 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma-q2YsCVg4hi-T0sjs:-Ma-q2YsCVg4hi-T0sjt:b-9mi9aq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d86f2f66f1146748d750e0c5f8d447ce4a16f4e0/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/EncryptTask.kt#L28)):*
> ```Kotlin
>     sendDebugLog: suspend (String) -> Unit
>   ): Map<String, ByteString> {
>     requireNotNull(input["encryption-key"])
> ```

Note that this is insufficient because `input` could change between this access and the next. How about:

```
val foo = requireNotNull(input["foo"])
...

makeSerializedSharedInputs(applySomething(foo, ...))
```


<!-- Sent from Reviewable.io -->

2021-05-18 20:37 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13)* status: 10 of 21 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/OutputWriter.kt, line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-M_wY0i2BLNLfyf21dQG:-M_zvn5WA8vO_c49b4E5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dec934e642aab84e19503896efaed08b16a4c0e1/src/main/kotlin/org/wfanet/panelmatch/client/storage/OutputWriter.kt#L20)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yuck.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/protocol/common/Utils.kt, line 24 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma-qV-X6OJIfQ5Ro9d5:-Ma06c8333Ig9fC3kbgj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d86f2f66f1146748d750e0c5f8d447ce4a16f4e0/src/main/kotlin/org/wfanet/panelmatch/protocol/common/Utils.kt#L24)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I feel like we'd want to throw some meaningful error instead of passing a null value here -- I'd recommend not allowing the input to be nullable.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/EncryptTask.kt, line 28 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma-q2YsCVg4hi-T0sjs:-Ma06exJ0x4LEBZSbxvB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d86f2f66f1146748d750e0c5f8d447ce4a16f4e0/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/EncryptTask.kt#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Note that this is insufficient because `input` could change between this access and the next. How about:

```
val foo = requireNotNull(input["foo"])
...

makeSerializedSharedInputs(applySomething(foo, ...))
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-18 22:10 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r5, 8 of 9 files at r6, 2 of 2 files at r7, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)



<!-- Sent from Reviewable.io -->

2021-05-19 15:50 UTC, yunyeng commented on src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ReEncryptTask.kt
> +// Copyright 2020 The Cross-Media Measurement Authors
2021

2021-05-19 15:50 UTC, yunyeng commented on src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/EncryptTask.kt
> +// Copyright 2020 The Cross-Media Measurement Authors
2021

2021-05-19 15:50 UTC, yunyeng commented on src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptTask.kt
> +// Copyright 2020 The Cross-Media Measurement Authors
2021

2021-05-19 15:51 UTC, yunyeng commented on src/main/kotlin/org/wfanet/panelmatch/protocol/common/Utils.kt
> +// Copyright 2020 The Cross-Media Measurement Authors
2021

2021-05-19 15:51 UTC, yunyeng commented on src/main/proto/wfanet/panelmatch/protocol/exchangesteps/exchangesteps.proto
> +// Copyright 2020 The Cross-Media Measurement Authors
ditto

2021-05-19 15:51 UTC, yunyeng commented on src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt
> +// Copyright 2020 The Cross-Media Measurement Authors
ditto

2021-05-19 15:51 UTC, yunyeng commented on src/test/kotlin/org/wfanet/panelmatch/protocol/common/UtilsTest.kt
> +// Copyright 2020 The Cross-Media Measurement Authors
ditto

2021-05-19 15:52 UTC, yunyeng commented on src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ReEncryptTask.kt
> +class ReEncryptTask : ExchangeTask {
1 line of comment describes this would be great!

2021-05-19 15:53 UTC, yunyeng approved these changes

2021-05-19 18:10 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13)* status: all files reviewed, 9 unresolved discussions (waiting on @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma4o7Hi4ggJBAOaxy9h:-Ma4o7Hi4ggJBAOaxy9i:b-4y8e1j) (no related file):*
Do you mind updating the Git commit message to be in the imperative mood?

https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html has some pretty good guidance on this, as does https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches?id=HEAD#n139

---


<!-- Sent from Reviewable.io -->

2021-05-19 18:45 UTC, efoxepstein requested changes
> Reviewed 22 of 22 files at r10.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13)* status: all files reviewed, 10 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/EncryptTask.kt, line 22 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma4w98B2oGUEqlVIyU1:-Ma4w98B2oGUEqlVIyU2:b-2z1c7z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f07a319025424cdaaf2a1412ddbb3f579b1bf593/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/EncryptTask.kt#L22)):*
> ```Kotlin
> import org.wfanet.panelmatch.protocol.common.parseSerializedSharedInputs
> 
> // Encrypts a plaintext using commutative encryption
> ```

Alas, these should probably be in KDoc format for consistency with the rest of our codebase. (Also, it encrypts many plaintexts, right?)


<!-- Sent from Reviewable.io -->

2021-05-20 16:19 UTC, efoxepstein requested changes
> Reviewed 1 of 1 files at r11, 6 of 6 files at r12.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13)* status: all files reviewed, 14 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt, line 33 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma9Yo3L3I6i54MBhqx9:-Ma9Yo3L3I6i54MBhqxA:bdh6ojp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1363b0e227854da030c893879a6704c147c332b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L33)):*
> ```Kotlin
>    * @throws ExchangeTaskRuntimeException if any failures during the execution.
>    */
>   @Throws(ExchangeTaskRuntimeException::class)
> ```

Any reason we need this instead of just sticking with the usual runtime exceptions like IllegalArgumentException?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt, line 122 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma9Z9Y1DenS-Fnz1TVW:-Ma9Z9Y1DenS-Fnz1TVX:b81a3cy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1363b0e227854da030c893879a6704c147c332b3/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt#L122)):*
> ```Kotlin
>       )
> 
>     val encryptException =
> ```

```
val encryptException = assertFailsWith(ExchangeTaskRuntimeException::class) {
  your code
}
```
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt, line 139 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma9Z0wj51_bOqjeCqk3:-Ma9Z0wj51_bOqjeCqk4:bo894k0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1363b0e227854da030c893879a6704c147c332b3/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt#L139)):*
> ```Kotlin
>     assertThat(encryptException?.message)
>       .isEqualTo(
>         "java.lang.RuntimeException: INVALID_ARGUMENT: Failed to create the protocol cipher"
> ```

This is quite brittle -- do we actually care about the message?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptTask.kt, line 39 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma9Yb81-FnB5Uqjhxr_:-Ma9Yb81-FnB5Uqjhxra:b-54egmn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1363b0e227854da030c893879a6704c147c332b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptTask.kt#L39)):*
> ```Kotlin
>       val encryptionKey = requireNotNull(input["encryption-key"])
>       val encryptedData = requireNotNull(input["encrypted-data"])
>       requireNotNull(input["encrypted-data"])
> ```

Delete this?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptTask.kt, line 47 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma9YcleEViuAvySmDFP:-Ma9YcleEViuAvySmDFQ:bhvix7e) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1363b0e227854da030c893879a6704c147c332b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptTask.kt#L47)):*
> ```Kotlin
>       )
>     } catch (e: Exception) {
>       throw ExchangeTaskRuntimeException(e.toString())
> ```

Why do we need this? Let's not catch and rewrap if possible.


<!-- Sent from Reviewable.io -->

2021-05-20 16:44 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13)* status: all files reviewed, 9 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt, line 33 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma9Yo3L3I6i54MBhqx9:-Ma9d0uR1zetoGmhQvcB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1363b0e227854da030c893879a6704c147c332b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Any reason we need this instead of just sticking with the usual runtime exceptions like IllegalArgumentException?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/protocol/common/Utils.kt, line 1 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma-WymhjhBl0FD_QakK-r9-1:-Ma9ak4l7QqaR0O9hAp-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90e63c99f96fcbcc318539628b550b9bc8b93983/src/main/kotlin/org/wfanet/panelmatch/protocol/common/Utils.kt#L1)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.
___
*[src/main/proto/wfanet/panelmatch/protocol/exchangesteps/exchangesteps.proto, line 1 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma08mavnFT1yHNvmotR-r9-1:-Ma9ajqeAUNyLjQSgu4d:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90e63c99f96fcbcc318539628b550b9bc8b93983/src/main/proto/wfanet/panelmatch/protocol/exchangesteps/exchangesteps.proto#L1)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt, line 1 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-M_wD9YqoONnV8Gcc2TH-r9-1:-Ma9bCPj6MKy83m_iuVN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90e63c99f96fcbcc318539628b550b9bc8b93983/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt#L1)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt, line 122 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma9Z9Y1DenS-Fnz1TVW:-Ma9beWjAd2XJ7I9cYNg:b-ki6nf1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1363b0e227854da030c893879a6704c147c332b3/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt#L122)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

```
val encryptException = assertFailsWith(ExchangeTaskRuntimeException::class) {
  your code
}
```
</blockquote></details>

i thought the way I had it was easier for checking not only exception class but also the message
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt, line 139 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma9Z0wj51_bOqjeCqk3:-Ma9bNEG4hMSgL8jZzcz:bk9flzn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1363b0e227854da030c893879a6704c147c332b3/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt#L139)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is quite brittle -- do we actually care about the message?
</blockquote></details>

it could just check that it contains `INVALID_ARGUMENT` - nice to make sure errors are bubbling up correctly
___
*[src/test/kotlin/org/wfanet/panelmatch/protocol/common/UtilsTest.kt, line 1 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma-WymiC7oRKqNYKL_i-r9-1:-Ma9bU7p4Qvv6Argm1ry:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90e63c99f96fcbcc318539628b550b9bc8b93983/src/test/kotlin/org/wfanet/panelmatch/protocol/common/UtilsTest.kt#L1)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptTask.kt, line 1 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-M_wN136jYxpNNYGoojB-r9-1:-Ma9byCkCxiOT1byPLFl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90e63c99f96fcbcc318539628b550b9bc8b93983/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptTask.kt#L1)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptTask.kt, line 39 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma9Yb81-FnB5Uqjhxr_:-Ma9bxWLEuUtfpt3o4PQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1363b0e227854da030c893879a6704c147c332b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptTask.kt#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Delete this?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptTask.kt, line 47 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma9YcleEViuAvySmDFP:-Ma9c-MsEn2HR05M4qOk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1363b0e227854da030c893879a6704c147c332b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptTask.kt#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why do we need this? Let's not catch and rewrap if possible.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/EncryptTask.kt, line 22 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-Ma4w98B2oGUEqlVIyU1:-Ma9an6ZDx03OGPYUoZt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f07a319025424cdaaf2a1412ddbb3f579b1bf593/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/EncryptTask.kt#L22)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Alas, these should probably be in KDoc format for consistency with the rest of our codebase. (Also, it encrypts many plaintexts, right?)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ReEncryptTask.kt, line 1 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13#-M_wN136jYxpNNYGoojD-r9-1:-Ma9alPWCDnp-0cgAcaS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90e63c99f96fcbcc318539628b550b9bc8b93983/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ReEncryptTask.kt#L1)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ReEncryptTask.kt, line 22 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-cli [...]

2021-05-20 17:37 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/13)* status: all files reviewed, 8 unresolved discussions (waiting on @stevenwarejones and @yunyeng)



<!-- Sent from Reviewable.io -->

2021-05-20 17:38 UTC, merged