Refactor Apache Beam pipelines to fix serialization issues
world-federation-of-advertisers/panel-exchange-client pull request #143
Opened 2021-09-30 22:48 UTC by efoxepstein

2021-10-01 13:55 UTC, stevenwarejones requested changes
> Reviewed 38 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143)* status: all files reviewed, 10 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTask.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw4ACoDB1k804A2om8:-Mkw4ACoDB1k804A2om9:b29j1nk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTask.kt#L52)):*
> ```Kotlin
>   }
> 
>   protected fun PCollection<ByteString>.write(shardedFileName: ShardedFileName) {
> ```

do we want to generalize this to also write out things like the dictionary?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ModelProviderApacheBeamTask.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw4aQXAlS8G0FWO4Oz:-Mkw4aQXAlS8G0FWO4P-:b-93mxdn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ModelProviderApacheBeamTask.kt#L22)):*
> ```Kotlin
> import org.wfanet.panelmatch.common.beam.toSingletonView
> 
> abstract class ModelProviderApacheBeamTask : ApacheBeamTask() {
> ```

do we need this specific abstraction? Two tasks require the model's provider's rlwe keys. Feels a little funny to make this for those steps. What if we have other Model Provider Beam tasks in the future that don't take rlwe keys as input?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 123 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw55nuE7jL1EcEXiOM:-Mkw55nuE7jL1EcEXiON:bu0irqq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/12430fdcb52a6105b1270e346889e1d1a9c2acf3/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L123)):*
> ```Kotlin
> 
>   /**
>    * Adds or deletes queries from sharded data until it is the desired size. We keep track of which
> ```

why did this move down?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw5MhU3PblnsXL1x7a:-Mkw5MhU3PblnsXL1x7b:bfqou6x) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L42)):*
> ```Kotlin
>   private val hkdfPepper: ByteString,
>   private val compressorFactory: CompressorFactory,
> ) : Serializable {
> ```

I thought you were saying we should not make these workflow tasks Serializable
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw5qiJ9oBdZrLthvBP:-Mkw5qiJ9oBdZrLthvBQ:byhk8tv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt#L96)):*
> ```Kotlin
> 
>     // shardsAndQueries requires an explicit coder to be set because of differences in how Java and
>     // Kotlin handle type inference around Lists/Iterables.
> ```

does using `@JvmWildcard` instead work?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniQueryEvaluator.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw65jr32BO8vN5Hxi5:-Mkw65jr32BO8vN5Hxi6:bcqqx0h) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniQueryEvaluator.kt#L28)):*
> ```Kotlin
> 
> /** [QueryEvaluator] that calls into C++ via JNI. */
> class JniQueryEvaluator(private val privateMembershipParameters: Parameters) : QueryEvaluator {
> ```

maybe only pass in serialized parameters here.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/JniQueryEvaluatorContext.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw6VJRB0cEqsCcCBeC:-Mkw6VJRB0cEqsCcCBeD:bove1sz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/JniQueryEvaluatorContext.kt#L26)):*
> ```Kotlin
> import org.wfanet.panelmatch.client.privatemembership.JniPrivateMembership
> 
> class JniQueryEvaluatorContext(shardCount: Int, bucketsPerShardCount: Int) : Serializable {
> ```

whats the purpose of this file again?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt, line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw6zqQ9nw6DzucBCoY:-Mkw6zqQ9nw6DzucBCoZ:byddob5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt#L79)):*
> ```Kotlin
> 
> private val PRIVATE_MEMBERSHIP_PARAMETERS = parameters {
>   cryptoParameters =
> ```

dont we have a test parameters constant somewhere?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt, line 101 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw6q4w6jwiXOE-YcaE:-Mkw6q4w6jwiXOE-YcaF:b-qryjpz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt#L101)):*
> ```Kotlin
> }
> 
> fun main(args: Array<String>) {
> ```

glad you added this. Might be good to abstract it out a little. Maybe add a TODO to abstract it for other cloud providers?
___
*[src/test/kotlin/org/wfanet/panelmatch/common/compression/BrotliCompressorTest.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw7RwkC32DwA8o-u3m:-Mkw7RwkC32DwA8o-u3n:b-ice6e0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/test/kotlin/org/wfanet/panelmatch/common/compression/BrotliCompressorTest.kt#L28)):*
> ```Kotlin
> @RunWith(JUnit4::class)
> class BrotliCompressorTest : AbstractCompressorTest() {
>   private val dictionary: ByteString = ByteString.EMPTY
> ```

do you really need an explicit type here?


<!-- Sent from Reviewable.io -->

2021-10-01 14:25 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143)* status: all files reviewed, 10 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTask.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw4ACoDB1k804A2om8:-MkwDqPY5ibPkQeWtDOm:bdqci12) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTask.kt#L52)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do we want to generalize this to also write out things like the dictionary?
</blockquote></details>

The dictionary is produced in preprocessing, so it's not written out by a subclass of `ApacheBeamTask`. But yeah, I see your point and if I run into a single-shard output then I'll add that.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ModelProviderApacheBeamTask.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw4aQXAlS8G0FWO4Oz:-MkwEN6091I_JehLuBNp:b12q7yq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ModelProviderApacheBeamTask.kt#L22)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do we need this specific abstraction? Two tasks require the model's provider's rlwe keys. Feels a little funny to make this for those steps. What if we have other Model Provider Beam tasks in the future that don't take rlwe keys as input?
</blockquote></details>

Yeah, it should probably just be an extension property -- will do
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 123 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw55nuE7jL1EcEXiOM:-MkwA7fy1gJcnQ_KuZeu:b-he9hlb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/12430fdcb52a6105b1270e346889e1d1a9c2acf3/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L123)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why did this move down?
</blockquote></details>

I moved things out of the parent class. In general I prefer to minimize what's inside of a class because:

1. It reduces indentation
2. It makes it clear that the inner class doesn't close over anything in the outer one
3. It makes outlines of the code simpler in IntelliJ and other code visualization tools

Does that make sense?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw5MhU3PblnsXL1x7a:-MkwAdR_DzzphaHp4sXP:b-cykh8f) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L42)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I thought you were saying we should not make these workflow tasks Serializable
</blockquote></details>

It's a little annoying to do that because you basically need to do stuff like:

```
val localFoo = this.foo
something.map { f(localFoo) }
```

Ultimately it seemed like more hassle than benefit. WDYT?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw5qiJ9oBdZrLthvBP:-MkwBEBd1FAOZCtPated:b8m7d7k) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt#L96)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

does using `@JvmWildcard` instead work?
</blockquote></details>

It didn't work for some reason, not sure why. Maybe I needed `@JvmWildcard` in front of `List<` too? Like `KV<@JvmWildcard List<@JvmWildcard Foo>, ...`?

Is it OK if I just put a TODO in here to investigate more?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniQueryEvaluator.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw65jr32BO8vN5Hxi5:-MkwCUEPBOAFb4edJEP9:bb76mu4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniQueryEvaluator.kt#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

maybe only pass in serialized parameters here.
</blockquote></details>

Why?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/JniQueryEvaluatorContext.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw6VJRB0cEqsCcCBeC:-MkwCY3D9DfBkidvJu39:b-kvo8m8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/JniQueryEvaluatorContext.kt#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

whats the purpose of this file again?
</blockquote></details>

It's a test helper to build and hold the various parameters for `JniQueryEvaluator` so I don't need to repeat the same stuff in a bunch of different tests
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt, line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw6zqQ9nw6DzucBCoY:-MkwCmUL9sTNnX3R8dNw:bqfjnk1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt#L79)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

dont we have a test parameters constant somewhere?
</blockquote></details>

They're in a `testonly` library -- here, we want production-ready parameters. (Which happen to be the same but might not always be.)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt, line 101 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw6q4w6jwiXOE-YcaE:-MkwEaq7-Hbii7SahF1T:bebrt1w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt#L101)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

glad you added this. Might be good to abstract it out a little. Maybe add a TODO to abstract it for other cloud providers?
</blockquote></details>

Will do
___
*[src/test/kotlin/org/wfanet/panelmatch/common/compression/BrotliCompressorTest.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw7RwkC32DwA8o-u3m:- [...]

2021-10-01 15:22 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143)* status: all files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw5MhU3PblnsXL1x7a:-MkwKTMG19dG5MmYTjRF:b-xtu861) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L42)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's a little annoying to do that because you basically need to do stuff like:

```
val localFoo = this.foo
something.map { f(localFoo) }
```

Ultimately it seemed like more hassle than benefit. WDYT?
</blockquote></details>

I thought it was a good safeguard to make sure we aren't accidentally asking Beam to serialize it since the Runners will crash out do to the serialized size?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw5qiJ9oBdZrLthvBP:-MkwKnE87ggHxAHjJnjB:bjdu6w0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt#L96)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It didn't work for some reason, not sure why. Maybe I needed `@JvmWildcard` in front of `List<` too? Like `KV<@JvmWildcard List<@JvmWildcard Foo>, ...`?

Is it OK if I just put a TODO in here to investigate more?
</blockquote></details>

sure. it would simplify it to not have to have a custom coder
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniQueryEvaluator.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw65jr32BO8vN5Hxi5:-MkwRErY1p0fzJ5r5CCn:b8lm411) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniQueryEvaluator.kt#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

it just means the caller needs to import that proto. We're serializing it in the workflow. Why not parse it within here.


<!-- Sent from Reviewable.io -->

2021-10-01 18:35 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143)* status: all files reviewed, 7 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw5MhU3PblnsXL1x7a:-Mkx3dB_D6UzkjAiKHIn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L42)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I thought it was a good safeguard to make sure we aren't accidentally asking Beam to serialize it since the Runners will crash out do to the serialized size?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw5qiJ9oBdZrLthvBP:-Mkx5LHp-5RgUD0MvtiF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt#L96)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

sure. it would simplify it to not have to have a custom coder
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniQueryEvaluator.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw65jr32BO8vN5Hxi5:-Mkx5prtAElKHmdp_pak:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniQueryEvaluator.kt#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

it just means the caller needs to import that proto. We're serializing it in the workflow. Why not parse it within here.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt, line 101 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw6q4w6jwiXOE-YcaE:-Mkx6seuEOm6An8K44HB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt#L101)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-01 19:15 UTC, stevenwarejones requested changes
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 171 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-MkxGesX14W9XGRWyZo3:-MkxGesY9hiGV7x6SkCF:bxqgmz1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4463be1ad31133f64199d8321e1eb0d1d0a9fcc/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L171)):*
> ```Kotlin
>   ): PCollection<EncryptedQueryBundle> {
>     // Local reference because DecryptQueryResultsWorkflow is not serializable.
>     val privateMembershipCryptor = privateMembershipCryptor
> ```

should we just pass around the cryptor as input to all these functions?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-MkxGlx_0MTrYvpnRyx4:-MkxGlx_0MTrYvpnRyx5:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4463be1ad31133f64199d8321e1eb0d1d0a9fcc/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L60)):*
> ```Kotlin
>     val serializedParameters = this.serializedParameters
>     val hkdfPepper = this.hkdfPepper
>     val queryResultsDecryptor = this.queryResultsDecryptor
> ```

ditto
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt, line 107 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-MkxGpXD5YeQn4gd0EVy:-MkxGpXD5YeQn4gd0EVz:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4463be1ad31133f64199d8321e1eb0d1d0a9fcc/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt#L107)):*
> ```Kotlin
>     // Local references because EvaluatorQueriesWorkflow is not serializable.
>     val maxQueriesPerShard = parameters.maxQueriesPerShard
>     val queryEvaluator = this.queryEvaluator
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-10-01 20:03 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 171 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-MkxGesX14W9XGRWyZo3:-MkxRpwX85ACpngR2iZY:brm4shj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4463be1ad31133f64199d8321e1eb0d1d0a9fcc/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L171)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should we just pass around the cryptor as input to all these functions?
</blockquote></details>

At that point there's no purpose to even having this be a class. Should we break it apart into some free functions?


<!-- Sent from Reviewable.io -->

2021-10-01 20:19 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-MkxGlx_0MTrYvpnRyx4:-MkxVgy-BACaBxnwNid6:bihgubj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4463be1ad31133f64199d8321e1eb0d1d0a9fcc/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L60)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

It would be ideal to deal with this in a different PR
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt, line 107 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-MkxGpXD5YeQn4gd0EVy:-MkxVlAb0S6u3BeRD00q:bihgubj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4463be1ad31133f64199d8321e1eb0d1d0a9fcc/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt#L107)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

It would be ideal to deal with this in a different PR


<!-- Sent from Reviewable.io -->

2021-10-04 12:29 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 171 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-MkxGesX14W9XGRWyZo3:-MlAGVpD7BEvxKAVuoog:b-6o49m) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4463be1ad31133f64199d8321e1eb0d1d0a9fcc/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L171)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

At that point there's no purpose to even having this be a class. Should we break it apart into some free functions?
</blockquote></details>

well, you could still pass in the parameters in the constructor. It feels like maybe anything that needs a local reference shouldn't be part of the constructor.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-MkxGlx_0MTrYvpnRyx4:-MlAGirt1k3yPhvM81ug:but5znf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4463be1ad31133f64199d8321e1eb0d1d0a9fcc/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L60)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It would be ideal to deal with this in a different PR
</blockquote></details>

I'm fine with a TODO to think about this.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt, line 107 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-MkxGpXD5YeQn4gd0EVy:-MlAGlfI-sK3gKd3HaMq:brgmmo2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4463be1ad31133f64199d8321e1eb0d1d0a9fcc/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt#L107)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It would be ideal to deal with this in a different PR
</blockquote></details>

sure. just add a TODO.


<!-- Sent from Reviewable.io -->

2021-10-04 19:05 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143)* status: 33 of 39 files reviewed, 5 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 171 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-MkxGesX14W9XGRWyZo3:-MlB8rdHCZ55c9zqNFlj:bkd5ega) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4463be1ad31133f64199d8321e1eb0d1d0a9fcc/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L171)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

well, you could still pass in the parameters in the constructor. It feels like maybe anything that needs a local reference shouldn't be part of the constructor.
</blockquote></details>

Added a TODO
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-MkxGlx_0MTrYvpnRyx4:-MlB8tZvBw65WH_RtcyT:bkd5ega) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4463be1ad31133f64199d8321e1eb0d1d0a9fcc/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L60)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm fine with a TODO to think about this.
</blockquote></details>

Added a TODO
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt, line 107 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-MkxGpXD5YeQn4gd0EVy:-MlB8vo4BkCasgJqUIL3:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4463be1ad31133f64199d8321e1eb0d1d0a9fcc/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt#L107)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

sure. just add a TODO.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-10-04 21:44 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143)* status: 32 of 39 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTask.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw4ACoDB1k804A2om8:-MlCEdrY5FL81U1NDFeg:bbx5mco) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTask.kt#L52)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The dictionary is produced in preprocessing, so it's not written out by a subclass of `ApacheBeamTask`. But yeah, I see your point and if I run into a single-shard output then I'll add that.
</blockquote></details>

Added a TODO to consider this. There's really nothing wrong with using this for single-shard files so I don't see it as critical.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ModelProviderApacheBeamTask.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143#-Mkw4aQXAlS8G0FWO4Oz:-MlCFpPx-lGLvFIoJHYV:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f97bce9148fe1dc7e1cf479fa47a4ef6a03de7/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ModelProviderApacheBeamTask.kt#L22)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Yeah, it should probably just be an extension property -- will do
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-10-04 21:49 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/143)* status: 28 of 39 files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-10-04 21:54 UTC, merged