Add step for building private membership queries
world-federation-of-advertisers/panel-exchange-client pull request #151
Opened 2021-10-06 22:44 UTC by duliomatos1

* Connecting the step to `BuildPrivateMembershipQueriesTask`
* 3 new variables needs to be passed down to `ApacheBeamTask` common task implementation:
  * `localCertificate` (from constructor)
  * `privateKey` (exposed from `VerifiedStorageClient`)
  * `uriPrefix` (should come from the storage client in another PR)

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151)

2021-10-08 00:38 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-MlROvxE6JBFVmcbEBhQ:-MlSHIbD2-64lrKjQaFG:boybltp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/95213e9e2fdc2ce0304668533f40bc06b8909f1c/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Note that even this will change from exchange to exchange. Instead, what we want is an abstract to get root certificates.

Can you add the following interface or similar?

```
interface RootCertificateStore {
  /** Returns the root certificate for the given API resource name. */
  fun get(parentName: String): X509Certificate
}
```

Then here in this Daemon we need `abstract val rootCertificateStore: RootCertificateStore` as well as `abstract val ownResourceName: String`.
</blockquote></details>

perfect, will do
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-MlPokxa7vcQhrjaqQl-:-MlSIhcx7QRIuYUZ9IJh:bcdeefc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/95213e9e2fdc2ce0304668533f40bc06b8909f1c/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L38)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

depending on the order that things get merged, maybe you should just add TODOs to derive the uriPrefix, privateStorage, and localCertificate below and take these out of the constructor here
</blockquote></details>

If it is a `TODO()` here rathen than at one level up it will show an horrible `code unreachable` warning and wouldn't facilitate testing. Could also add a `// TODO ` comment in the constructor if it makes it clearer it's to be changed
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-MlRQFKd16qBKcxInZNI:-MlSHUzvC3uuvsxW27tK:b-ongs5s) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/95213e9e2fdc2ce0304668533f40bc06b8909f1c/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why is this necessary?
</blockquote></details>

`ApacheBeamTask` asks to pass down the `privateKey` to the task. The key exists inside `VerifiedStorageClient` so I'm simply exposing it. Another option is to pass the key again as a parameter to the task, but then it would need to also be a parameter to `ExchangeTaskMapperForJoinKeyExchange()`


<!-- Sent from Reviewable.io -->

2021-10-08 13:21 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-MlROvxE6JBFVmcbEBhQ:-MlV2p026Gy4OyTS381g:b-nu0pg5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/95213e9e2fdc2ce0304668533f40bc06b8909f1c/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L57)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

perfect, will do
</blockquote></details>

@jonmolle -- you have an implementation of `rootCertificateStorage` somewhere? Let's make sure to get that CertificateManager PR merged as soon as we can
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-MlRQFKd16qBKcxInZNI:-MlV36GQ1g7ZJxMwdPr_:b4gtapb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/95213e9e2fdc2ce0304668533f40bc06b8909f1c/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L41)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

`ApacheBeamTask` asks to pass down the `privateKey` to the task. The key exists inside `VerifiedStorageClient` so I'm simply exposing it. Another option is to pass the key again as a parameter to the task, but then it would need to also be a parameter to `ExchangeTaskMapperForJoinKeyExchange()`
</blockquote></details>

Yes, but why `var`?
The only different between `var` and `val` is in whether it can be reassigned to, not its visibility.


<!-- Sent from Reviewable.io -->

2021-10-08 14:31 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @jonmolle)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-MlROvxE6JBFVmcbEBhQ:-MlVIw4H4Ap_b971qSCu:bhre460) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/95213e9e2fdc2ce0304668533f40bc06b8909f1c/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@jonmolle -- you have an implementation of `rootCertificateStorage` somewhere? Let's make sure to get that CertificateManager PR merged as soon as we can
</blockquote></details>

@efoxepstein - i was thinking dulio could leave the store as a TODO since I think jon's PRs touch all that.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-MlPokxa7vcQhrjaqQl-:-MlVJ3MUDESNXSPAM9Ko:bxiloiw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/95213e9e2fdc2ce0304668533f40bc06b8909f1c/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L38)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

If it is a `TODO()` here rathen than at one level up it will show an horrible `code unreachable` warning and wouldn't facilitate testing. Could also add a `// TODO ` comment in the constructor if it makes it clearer it's to be changed
</blockquote></details>

yeah - I meant TODO comment


<!-- Sent from Reviewable.io -->

2021-10-08 17:58 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @jonmolle)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-MlROvxE6JBFVmcbEBhQ:-MlW2dVODSrthS-Yy_-J:b-hfghm4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/95213e9e2fdc2ce0304668533f40bc06b8909f1c/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L57)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@efoxepstein - i was thinking dulio could leave the store as a TODO since I think jon's PRs touch all that.
</blockquote></details>

Sounds good


<!-- Sent from Reviewable.io -->

2021-10-08 19:14 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-MlROvxE6JBFVmcbEBhQ:-MlWJG_T1zj2QzXaspXW:btra2bj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/95213e9e2fdc2ce0304668533f40bc06b8909f1c/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Sounds good
</blockquote></details>

ok, will include TODO's to point for removal in the places I've added `uriPrefix` and `localCertificate` 
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-MlPokxa7vcQhrjaqQl-:-MlWJzwJ04a1Q5ox6KNz:b-q8jzb0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/95213e9e2fdc2ce0304668533f40bc06b8909f1c/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L38)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah - I meant TODO comment
</blockquote></details>

got it
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-MlRQFKd16qBKcxInZNI:-MlWJ3qgDayojEba8qj5:bo37w8k) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/95213e9e2fdc2ce0304668533f40bc06b8909f1c/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Yes, but why `var`?
The only different between `var` and `val` is in whether it can be reassigned to, not its visibility.
</blockquote></details>

you're right, I can just initialize a public val in the constructor


<!-- Sent from Reviewable.io -->

2021-10-09 00:06 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 73 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-MlWwIjz-w-fchQIs8H1:-MlXMXhY33eUMXN_XI_3:b-76gjy8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ea386dd118d2ea493091b7bf338345845fa05ee6/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L73)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`step.outputLabelsMap.getValue("encrypted-queries")`
</blockquote></details>

got it, thx Eli.


<!-- Sent from Reviewable.io -->

2021-10-09 00:19 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-10-09 00:29 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @efoxepstein, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 73 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-MlWwIjz-w-fchQIs8H1:-MlXS7jh39UanXXflKG0:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ea386dd118d2ea493091b7bf338345845fa05ee6/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L73)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

got it, thx Eli.
</blockquote></details>

done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 76 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-MlWwsud9px1xIcv8tPK:-MlXSAHc7_bKVa9rBtw0:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ea386dd118d2ea493091b7bf338345845fa05ee6/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L76)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`step.outputLabelsMap.getValue("query-decryption-keys")`
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2021-10-09 13:38 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 67 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-Ml_G5hf8dSMPcmTNt3u:-Ml_G5hg4vihR4fTz2vL:b57cufh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bf34179292b2fd5027ba5aa117120d812719d795/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L67)):*
> ```Kotlin
>       StepCase.GENERATE_CERTIFICATE_STEP -> TODO()
>       StepCase.EXECUTE_PRIVATE_MEMBERSHIP_QUERIES_STEP -> TODO()
>       StepCase.BUILD_PRIVATE_MEMBERSHIP_QUERIES_STEP -> {
> ```

Since this block of code is fairly large, I'm wondering if we should move each case to a separate private helper function -- so the body of the `when` is just calls to the appropriate helper functions. WDYT?


<!-- Sent from Reviewable.io -->

2021-10-12 13:10 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @jonmolle)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-MlROvxE6JBFVmcbEBhQ:-MlobqWw-HssMdhke9yl:b-41391r) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/95213e9e2fdc2ce0304668533f40bc06b8909f1c/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L57)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

done
</blockquote></details>

yeah - it shouldn't even be derived here. it should be derived in the exchange task mapper impl. But I think its fine to keep here temporarily until that code exists.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 67 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-Ml_G5hf8dSMPcmTNt3u:-MloaNlAD8v3dzzgR4-U:blomn9a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bf34179292b2fd5027ba5aa117120d812719d795/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L67)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since this block of code is fairly large, I'm wondering if we should move each case to a separate private helper function -- so the body of the `when` is just calls to the appropriate helper functions. WDYT?
</blockquote></details>

yeah - probably


<!-- Sent from Reviewable.io -->

2021-10-13 14:07 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @efoxepstein, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 67 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/151#-Ml_G5hf8dSMPcmTNt3u:-MltyTIeAddKb1dNE94J:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bf34179292b2fd5027ba5aa117120d812719d795/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L67)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you add a TODO if you're not going to do it in this PR before marking this comment as resolved?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-10-13 18:14 UTC, merged