StorageSelector implementation using StorageFactory
world-federation-of-advertisers/panel-exchange-client pull request #173
Opened 2021-10-18 18:41 UTC by jonmolle

Adds a selection class that can be used to build a StorageClient (private storage), VerifiedStorageClient (shared storage), or StorageFactory (StorageClient builder, serializable, for Apache Beam and wherever else necessary).

It expects a mapping of storage factory constructors that is built by the daemon to know what is the set of allowable storage clients as well as locally stored information on how to connect to each exchange's shared and private storage.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173)

2021-10-18 18:46 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmJiW_237JF7hM-G3Fw:-MmJiW_3-Pgn15qyh0tU:b-ean84m) (no related file):*
Can you fix build/lint?

---


<!-- Sent from Reviewable.io -->

2021-10-18 19:45 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173)* status: 9 of 12 files reviewed, 7 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @jonmolle, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmJiW_237JF7hM-G3Fw:-MmJpB4pBsMZ7OVBtgR9:bevb7g8) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you fix build/lint?
</blockquote></details>

Working on it. The lint was a license header, which is done, but I can't reproduce the build error locally. Checking the build logs now.

---
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/GcsStorageFactory.kt, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmJj4oM3iAg5YixMfe-:-MmJpQIK8sZpvWLatNyR:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a7c10a1367fce4be28c669f318251b60018888f4/src/main/kotlin/org/wfanet/panelmatch/client/storage/GcsStorageFactory.kt#L21)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

For consistency, rename `AwsS3StorageClient` to `S3StorageFactory`?
</blockquote></details>

Done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageSelector.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmJjIX1AvV32ThZbqg7:-MmJs5i-BDq7xnXExlQk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a7c10a1367fce4be28c669f318251b60018888f4/src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageSelector.kt#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Move to KDoc please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageSelector.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmJjQIZ-AYm_3RrBXBf:-MmJuGx_CmTD0tlkvZt5:b-xpln9g) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a7c10a1367fce4be28c669f318251b60018888f4/src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageSelector.kt#L36)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Does `(StorageDetails) -> StorageFactory` work instead of KFunction1?

Another alternative: replace `StorageFactory` with `interface SerializableStorageClient : StorageClient, Serializable` and then add `interface SerializableStorageClientFactory`.
</blockquote></details>

It does not, the lambda notation requires you to refer to a member function rather than the constructor, which would require a built StorageFactory class. I don't think the alternative would solve that, either, and I think KFunction is actually the intended use case here? I don't really mind changing it, but I'm curious what the concern is with it.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageSelector.kt, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmJnfDw-oNevFGlTDhq:-MmJsBz24VxDa-AKH62P:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a7c10a1367fce4be28c669f318251b60018888f4/src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageSelector.kt#L44)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you remove the default here? I feel like this ought to be very explicitly specified.
</blockquote></details>

Done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageSelector.kt, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmJnqXV1Mz9YE0FnNQU:-MmJsKDw2MxOudnDmHRl:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a7c10a1367fce4be28c669f318251b60018888f4/src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageSelector.kt#L60)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I feel like our only use case for a `StorageFactory` is with Apache Beam, which only needs private storage. Can we restrict it to private storage?
</blockquote></details>

Done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageSelector.kt, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmJoDPv0ooYYj5q7crB:-MmJslAA8WJPBle3cJ7j:bqq8q54) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a7c10a1367fce4be28c669f318251b60018888f4/src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageSelector.kt#L71)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

When is this null? Can you add KDoc to all the functions here?
</blockquote></details>

Working on it


<!-- Sent from Reviewable.io -->

2021-10-18 22:16 UTC, efoxepstein reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173)* status: all files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-10-18 23:35 UTC, efoxepstein approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-:-MmKkbEJ8qf2Tm54A-2W:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-10-19 00:04 UTC, efoxepstein requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/PrivateStorageSelector.kt, line 48 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmKrKId3i7A728cuulw:-MmKrKId3i7A728cuulx:bvfu121) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bfb537d9725a51625cbba306ff98616b74d68abc/src/main/kotlin/org/wfanet/panelmatch/client/storage/PrivateStorageSelector.kt#L48)):*
> ```Kotlin
>   private suspend fun getStorageFactory(storageDetails: StorageDetails): StorageFactory =
>     requireNotNull(privateStorageFactories[storageDetails.platformCase]) {
>       "Missing private StorageFactory for ${storageDetails.platformCase}"
> ```

This is kind of hard to read, can you please introduce a local variable?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/SharedStorageSelector.kt, line 49 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmKrC0272iOctD1MxpH:-MmKrC035bwdUE9xP4F6:bvfu121) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bfb537d9725a51625cbba306ff98616b74d68abc/src/main/kotlin/org/wfanet/panelmatch/client/storage/SharedStorageSelector.kt#L49)):*
> ```Kotlin
>     requireNotNull(sharedStorageFactories[storageDetails.platformCase]) {
>       "Missing shared StorageFactory for ${storageDetails.platformCase}"
>     }(storageDetails)
> ```

This is kind of hard to read, can you please introduce a local variable?


<!-- Sent from Reviewable.io -->

2021-10-19 00:09 UTC, stevenwarejones requested changes
> Reviewed 8 of 12 files at r1, 2 of 3 files at r2, 1 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1 and @jonmolle)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/PrivateStorageSelector.kt, line 31 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmKqyP37DJajXU74KU-:-MmKqyP37DJajXU74KU0:b-7vauzb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bfb537d9725a51625cbba306ff98616b74d68abc/src/main/kotlin/org/wfanet/panelmatch/client/storage/PrivateStorageSelector.kt#L31)):*
> ```Kotlin
>  * - provides a [VerifiedStorageClient]
>  *
>  * The class takes in exchange-specific storage information ([sharedStorageInfo] and
> ```

i'm still a little confused how this information is shared. 
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/PrivateStorageSelector.kt, line 69 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmKrZeE4dEvV93jqbnf:-MmKrZeE4dEvV93jqbng:bt4dobf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bfb537d9725a51625cbba306ff98616b74d68abc/src/main/kotlin/org/wfanet/panelmatch/client/storage/PrivateStorageSelector.kt#L69)):*
> ```Kotlin
>    * a StorageFactory for private storage, this does not ever check [sharedStorageInfo].
>    */
>   suspend fun getStorageFactory(attemptKey: ExchangeStepAttemptKey): StorageFactory {
> ```

i don't think we want to key these to the attempt number, right? https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d7348e7bcb5817f3591b38530969198aca775ce6/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L50

shouldn't we be using `ExchangeStepKey`?

https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d7348e7bcb5817f3591b38530969198aca775ce6/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L66


<!-- Sent from Reviewable.io -->

2021-10-19 18:27 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/PrivateStorageSelector.kt, line 31 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmKqyP37DJajXU74KU-:-MmOlzd4ECyUlji1ZuvS:bs0nyhu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bfb537d9725a51625cbba306ff98616b74d68abc/src/main/kotlin/org/wfanet/panelmatch/client/storage/PrivateStorageSelector.kt#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Are you asking how the two parties agree on a `sharedStorageInfo`?
</blockquote></details>

My general thought is that any SecretMap here here can be roughly analogized to a static StorageClient (although it could be a KMS or cloud-specific helper). The idea is that the following steps will happen when setting up an exchange, in some order:

- Agree on a rough workflow
- Exchange information on where shared storage is and how to connect to it. That's stored here.
- Decide on your own where you want to keep your own private storage for this exchange. I initially had a default so you only had to think of this once if you didn't want to be complicated, but Eli had a point that that introduced a potential for misconfiguration. Store that in a different place.
- exchange root certs for the recurring exchange. That stored in a different Secret area, but it can be backed by the same thing (IE: you can have a storage client pointing at two paths in your own private S3, or filesystem, or KMS).
- build the official workflow with things like start date, etc, and register with the Kingdom. Store the signed workflow you've both email each other locally

All of these "Store X somewhere where the Kingdom doesn't have access to it" steps are prerequisites. I'd love a script of some kind for users who "just want to use X" as a helper, but I think each of these values are independent long-lived values and should be able to be set up separately.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/PrivateStorageSelector.kt, line 48 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmKrKId3i7A728cuulw:-MmOkqE2BB0ekuw3Cjud:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bfb537d9725a51625cbba306ff98616b74d68abc/src/main/kotlin/org/wfanet/panelmatch/client/storage/PrivateStorageSelector.kt#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is kind of hard to read, can you please introduce a local variable?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/PrivateStorageSelector.kt, line 69 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmKrZeE4dEvV93jqbnf:-MmOlNYG55iM1k6c-P4c:b-w1k7ou) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bfb537d9725a51625cbba306ff98616b74d68abc/src/main/kotlin/org/wfanet/panelmatch/client/storage/PrivateStorageSelector.kt#L69)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's only actually keyed to the `recurringExchangeId` in this PR -- but I agree that using `ExchangeStepKey` or even `ExchangeKey` could be better
</blockquote></details>

I pass around ExchangeStepAttemptKey a lot because that's what we get from the Kingdom and I didn't want to randomly introduce a transform somewhere that isn't strictly necessary. I agree that ExchangeKey or ExchangeStepKey would be just fine; as long as it has the recurring exchange id somewhere in there. In fact, looking at it again, there's no reason currently to not just pass the recurring ID, if you like.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/SharedStorageSelector.kt, line 49 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmKrC0272iOctD1MxpH:-MmOlxJ7EHQO3ktT7Rh2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bfb537d9725a51625cbba306ff98616b74d68abc/src/main/kotlin/org/wfanet/panelmatch/client/storage/SharedStorageSelector.kt#L49)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is kind of hard to read, can you please introduce a local variable?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-19 21:08 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173)* status: 8 of 14 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/PrivateStorageSelector.kt, line 51 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmPAOBr1cAFDiRj_haz:-MmPJ-1HELB_k__LR-42:bd8w0iz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/21a17de77cb5d28ffaaa325b34edb84dabeee4a8/src/main/kotlin/org/wfanet/panelmatch/client/storage/PrivateStorageSelector.kt#L51)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

To implement different buckets per exchange, will you need the `Exchange` name in here too?
</blockquote></details>

Yes, but I'm adding that downstream, there's no support in the cloud builders yet, either. I've added a TODO and the param, though, for clarity.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/SharedStorageSelector.kt, line 73 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmPAnEq1iQDt9iqCWY8:-MmPNU_m9TEODSL3IcWk:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/21a17de77cb5d28ffaaa325b34edb84dabeee4a8/src/main/kotlin/org/wfanet/panelmatch/client/storage/SharedStorageSelector.kt#L73)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Nit: `@param storageType ...` is the typical KDoc format
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-10-19 23:34 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/testing/InMemoryStorageFactory.kt, line 25 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmPS2Y-5VeZMfPoQN4J:-MmPkflAADBXfNH4e7C3:b-273sd5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/69b4f62a5f683ea2fb850c46203290ec648399e8/src/main/kotlin/org/wfanet/panelmatch/client/storage/testing/InMemoryStorageFactory.kt#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since these aren't used, maybe instead of adding any properties here, you can replace `::InMemoryStorageFactory` with `{ _: StorageDetails, _:ExchangeKey -> InMemoryStorageFactory() }` -- WDYT? This makes it super clear these aren't used for anything
</blockquote></details>

I kind of like keeping it around at least as a guide for how to build the factories.


<!-- Sent from Reviewable.io -->

2021-10-20 13:53 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/testing/InMemoryStorageFactory.kt, line 25 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmPS2Y-5VeZMfPoQN4J:-MmSxt_70tz5S9Gs5Xh4:bhtv4qv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/69b4f62a5f683ea2fb850c46203290ec648399e8/src/main/kotlin/org/wfanet/panelmatch/client/storage/testing/InMemoryStorageFactory.kt#L25)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

I kind of like keeping it around at least as a guide for how to build the factories.
</blockquote></details>

OK, at a minimum, can you do:

```
class InMemoryStorageFactory() {
  constructor(storageDetails: StorageDetails, exchangeKey: ExchangeKey) : this()
}
```

so (1) it's not the primary constructor and (2) it doesn't store the unused fields?

Another option is to keep a cache of InMemoryStorageClients keyed by recurringExchange:

```
// Outside of class:
private val clients = ConcurrentHashMap<String, InMemoryStorageClient>()

// Within class:
override fun build(): StorageClient {
  return clients.getOrPut(exchangeKey.recurringExchangeId) { InMemoryStorageClient() }
}
```


<!-- Sent from Reviewable.io -->

2021-10-20 15:02 UTC, stevenwarejones approved these changes
> Reviewed 1 of 4 files at r5, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @jonmolle)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/PrivateStorageSelector.kt, line 31 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/173#-MmKqyP37DJajXU74KU-:-MmTDQa6BdYuzhpIlN7D:b-542ach) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bfb537d9725a51625cbba306ff98616b74d68abc/src/main/kotlin/org/wfanet/panelmatch/client/storage/PrivateStorageSelector.kt#L31)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

My general thought is that any SecretMap here here can be roughly analogized to a static StorageClient (although it could be a KMS or cloud-specific helper). The idea is that the following steps will happen when setting up an exchange, in some order:

- Agree on a rough workflow
- Exchange information on where shared storage is and how to connect to it. That's stored here.
- Decide on your own where you want to keep your own private storage for this exchange. I initially had a default so you only had to think of this once if you didn't want to be complicated, but Eli had a point that that introduced a potential for misconfiguration. Store that in a different place.
- exchange root certs for the recurring exchange. That stored in a different Secret area, but it can be backed by the same thing (IE: you can have a storage client pointing at two paths in your own private S3, or filesystem, or KMS).
- build the official workflow with things like start date, etc, and register with the Kingdom. Store the signed workflow you've both email each other locally

All of these "Store X somewhere where the Kingdom doesn't have access to it" steps are prerequisites. I'd love a script of some kind for users who "just want to use X" as a helper, but I think each of these values are independent long-lived values and should be able to be set up separately.
</blockquote></details>

Can this get documented somewhere or added as TODOs?


<!-- Sent from Reviewable.io -->

2021-10-20 20:05 UTC, merged