Add Coroutine Job Starter
world-federation-of-advertisers/panel-exchange-client pull request #20
Opened 2021-06-10 16:14 UTC by stevenwarejones

* Adds support for async concurrent task jobs
* Adds support for FileSystemStorage
* Adds support for private and public storage on different storage types

2021-06-10 17:54 UTC, efoxepstein requested changes
> Reviewed 1 of 15 files at r2, 40 of 45 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 41 of 46 files reviewed, 19 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[WORKSPACE, line 186 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mbqjd7Y2aMDtLBonPaC:-Mbqjd7Y2aMDtLBonPaD:bbqkd05) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/WORKSPACE#L186)):*
> ```Starlark
> container_deps()
> 
> load("//build/io_bazel_rules_docker:base_images.bzl", "base_java_images")
> ```

Does `load("@wfa_measurement_system//build/iu_bazel_rules_docker:base_images.bzl", "base_java_images")` work? I'm wondering if we really need these things in this repo
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CryptorExchangeTask.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqjypL2z1g5wsABz2U:-MbqjypL2z1g5wsABz2V:b10lxxi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CryptorExchangeTask.kt#L32)):*
> ```Kotlin
>   private val inputKeyLabel: String = DEFAULT_INPUT_KEY_LABEL
> ) : ExchangeTask {
>   private val LOGGER = loggerFor(javaClass)
> ```

This can be in a companion object, I think. We also have a convention of only using UPPERCASE for constants.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 52 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqkF5yBR_5lxeypt7n:-MbqkF5yBR_5lxeypt7o:b1iiohx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L52)):*
> ```Kotlin
>         CryptorExchangeTask.forReEncryption(deterministicCommutativeCryptor)
>       ExchangeWorkflow.Step.StepCase.DECRYPT_STEP ->
>         CryptorExchangeTask.forDecryption(deterministicCommutativeCryptor)
> ```

Very optional: consider pulling out a map to make it easier to see the correspondence:

```
val stepFactoriesOrSomeGoodName = mapOf(
  ENCRYPT_STEP to CryptorExchangeTask::forEncryption,
  REENCRYPT_STEP to CryptorExchangeTask::forReEncryption,
  DECRYPT_STEP to CryptorExchangeTask::forDecryption,
)

...

private suspend fun getExchangeTaskForStep(step: ExchangeWorkflow.Step): ExchangeTask {
  val factory = stepFactoriesOrSomeGoodName[step.getStepCase()] ?: error("Unsupported step type")
  return factory(deterministicCommutatorCryptor)
}
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqmUzt3sEfwU7GyqtD:-MbqmUzt3sEfwU7GyqtE:b-9oz8q8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L63)):*
> ```Kotlin
>     val sharedInputLabels = step.getSharedInputLabelsMap()
>     val sharedOutputLabels = step.getSharedOutputLabelsMap()
>     if (step.getStepCase() == ExchangeWorkflow.Step.StepCase.INPUT_STEP) {
> ```

I think wen can avoid special-casing this with a small tweak to the ExchangeTask interface:

```
class InputTask(storage: Storage) : ExchangeTask {
  override suspend fun execute(input: Map<String, ByteString>, expectedOutputLabels: List<String>): Map<String, ByteString> {
    require(input.isEmpty)
    return expectedOutputLabels.associateWith { storage.read(it) }
  }
}
```

I /really/ don't want to have to special case anything.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 81 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqpDYm-zOz6CpE-LYK:-MbqpDYm-zOz6CpE-LYL:b-o3elwq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L81)):*
> ```Kotlin
>       val taskPrivateInput =
>         async(start = CoroutineStart.DEFAULT) {
>           batchRead(
> ```

Maybe a friendlier interface would be for `batchRead` to take in a list of private input labels and a list of shared input labels instead of an enum? That way we can hide this async stuff.

Alternative (less preferable) -- just pull this code out to a helper function. It distracts from the basic flow of this method, which should basically read like:

```
val inputs = getInputs()
val outputs = runTask(inputs)
writeOutputs(outputs)
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mbqur7j3NBXz3VTnpcP:-Mbqur7j3NBXz3VTnpcQ:b-861400) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L34)):*
> ```Kotlin
> ) : JobLauncher {
>   private val LOGGER = loggerFor(javaClass)
>   private val scope = CoroutineScope(Dispatchers.Default)
> ```

Can you inject this as a constructor parameter?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 74 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqvoPoAzdJ_U8DTL9K:-MbqvoPoAzdJ_U8DTL9L:b6ar2cc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L74)):*
> ```Kotlin
>     attempt: ExchangeStepAttempt.Key
>   ) {
>     val job: Job =
> ```

Since `job` is unused, maybe there's no need to return it in `executeStep`?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/JobLauncher.kt, line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mbqw1-F1z1gQaXvvElQ:-Mbqw1-F1z1gQaXvvElR:b-lbbxw4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/launcher/JobLauncher.kt#L34)):*
> ```Kotlin
>     exchangeStepAttemptKey: String,
>     exchangeStep: ExchangeStep,
>     attempt: ExchangeStepAttempt.Key
> ```

Are `attempt` and `exchangeStepAttemptKey` redundant?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 102 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqwsCJEsAB83eOq6OG:-MbqwsCJEsAB83eOq6OH:b-yhrriu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L102)):*
> ```Kotlin
>   suspend fun buildAndExecute() = runBlocking {
>     val builtStep: ExchangeWorkflow.Step = build()
>     whenever(deterministicCommutativeCryptor.encrypt(any(), any())).thenReturn(SINGLE_BLINDED_KEYS)
> ```

It might be easier to just use a Fake here:

```
object FakeCryptor : Cryptor {
  override fun encrypt(some, thing) = SINGLE_BLINDED_KEYS
  ...
}

...

    CoroutineLauncher(FakeCryptor)
      .execute(...)
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 106 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqwfEj6zG3iuWDOAw_:-MbqwfEk8OusFRSr9KdZ:bkuciw) ([raw file](https://github.com/wo [...]

2021-06-10 21:36 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 41 of 46 files reviewed, 19 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 74 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqvoPoAzdJ_U8DTL9K:-Mbrqc7T-hhE80JZAGyC:b-yo2y3c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L74)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since `job` is unused, maybe there's no need to return it in `executeStep`?
</blockquote></details>

I was thinking if we ever want to have a cancel.


<!-- Sent from Reviewable.io -->

2021-06-10 22:21 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 41 of 46 files reviewed, 17 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[WORKSPACE, line 186 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mbqjd7Y2aMDtLBonPaC:-Mbs-qrt8__Ywil-voGd:brxp9sq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/WORKSPACE#L186)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i was getting problems importing the storage class which is why I included these. I'm sure they could be separated, but was planning to leave that for future todos.
</blockquote></details>

Sounds good.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 74 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqvoPoAzdJ_U8DTL9K:-MbrzgflCwjc_6Ak_R7k:bbjaevo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L74)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I was thinking if we ever want to have a cancel.
</blockquote></details>

In the spirit of [YAGNI](https://testing.googleblog.com/2017/08/code-health-eliminate-yagni-smells.html), let's remove it for now?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/JobLauncher.kt, line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mbqw1-F1z1gQaXvvElQ:-MbrzomK8r3Uamw8Pv3X:bcctmht) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/launcher/JobLauncher.kt#L34)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

The requirement is to have a unique key per exchange (used for storage across the exchange) and a unique key per exchange step attempt (used to denote which logs are from which exchange step attempt)

Hopefully I'm using them correctly here: https://github.com/world-federation-of-advertisers/panel-exchange-client/pull/20/files#diff-08e66cd5e66623bce6307430bca312deb9f2e32931aa589d2bc0e24dc16e5633R43

Currently, they can both be derived from the ExchangeStepAttempt.Key.exchangeId and ExchangeStepAttempt.Key.exchangeStepAttemptId. I could just pass in ExchangeStepAttempt.Key and and derive them both or I could leave it as is explicit. I'm fine with either.


</blockquote></details>

v2alpha gets rid of all the `Key` messages -- all you should need to have here is `exchangeStepAttemptKey: String`.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 102 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqwsCJEsAB83eOq6OG:-Mbs-EKr4KG6HkTZk5qv:blh7r1z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L102)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Do you have a preference? I hate to build a mock *and* fake cryptor.
</blockquote></details>

I don't feel strongly. It's fine as is.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt, line 28 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqxqT65ucwWPV3W380:-Mbs-RZ28qpVW0PLVqYy:blvjr3n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I thought about that. Is that what we want? Wasn't sure.
</blockquote></details>

Seems simpler for now
___
*[src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt, line 30 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqyLrs2l6rqEWwwpMO:-Mbs-YpQ4uXlXjo_KmUr:bepkyj3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt#L30)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

The idea is that it should be a single coroutine (eg thread) performing a task. Is that a safe assumption?
</blockquote></details>

What if the coroutine spawns sub-coroutines to e.g. do some things concurrently -- do the child coroutines have different names?


<!-- Sent from Reviewable.io -->

2021-06-11 21:34 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 41 of 46 files reviewed, 17 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CryptorExchangeTask.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqjypL2z1g5wsABz2U:-MbwNJOa14J4sNX0cuRK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CryptorExchangeTask.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This can be in a companion object, I think. We also have a convention of only using UPPERCASE for constants.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqmUzt3sEfwU7GyqtD:-MbwrAYWApZYkF5ufg4j:b-o4k0in) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L63)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah - I meant to do pull that out into a separate task. Will do.
</blockquote></details>

Actually, this defies the interface which makes me think we need to do this a different way. Lets talk about it.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 81 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqpDYm-zOz6CpE-LYK:-Mbwha3vDRvFqfQdbI3i:b-o7grw9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L81)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe a friendlier interface would be for `batchRead` to take in a list of private input labels and a list of shared input labels instead of an enum? That way we can hide this async stuff.

Alternative (less preferable) -- just pull this code out to a helper function. It distracts from the basic flow of this method, which should basically read like:

```
val inputs = getInputs()
val outputs = runTask(inputs)
writeOutputs(outputs)
```
</blockquote></details>

I added these as helper functions to the Storage class. I think its more straightforward this way but feel free to disagree.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mbqur7j3NBXz3VTnpcP:-Mbwbnvt7xBDqfwccO4v:b-qnzxca) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L34)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you inject this as a constructor parameter?
</blockquote></details>

Done. Were you thinking this should be mocked up?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 74 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqvoPoAzdJ_U8DTL9K:-Mbwa8r96FA0cxp5yvqp:b-4odhjy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L74)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

In the spirit of [YAGNI](https://testing.googleblog.com/2017/08/code-health-eliminate-yagni-smells.html), let's remove it for now?
</blockquote></details>

I just deleted executeStep
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/JobLauncher.kt, line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mbqw1-F1z1gQaXvvElQ:-Mbw_Lct7vNfyAXVyBYg:b-n7lmg6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/launcher/JobLauncher.kt#L34)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

v2alpha gets rid of all the `Key` messages -- all you should need to have here is `exchangeStepAttemptKey: String`.
</blockquote></details>

we still are going to parse all they values of the `Key` messages, right? I removed it for now as input parameters and instead derive it in the function.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt, line 21 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mbqy14z6d5h8DCfFanX:-Mbwzi5j7lbvZmN5PlfM:b-72qok2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt#L21)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is `MutableMap` thread-safe? Do we need `ConcurrentHashMap` instead?
</blockquote></details>

done but I need to fix the list to be thread-safe too
___
*[src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt, line 24 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqxC9i9HswlRMIwshF:-MbwV-pR3dtIKSONyfxJ:bh2caf6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt#L24)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Capital L please
</blockquote></details>

Deleted this class
___
*[src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt, line 28 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqxqT65ucwWPV3W380:-MbwV3ha8NdmqlyiDIFg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Seems simpler for now
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqxLInBvbdcEKl6xCD:-Mbwzg321CjvEu6ArFWV:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is a double-lookup -- how about:

```
taskLogs.putIfAbsent(coroutineContextName, mutableListOf<String>())
```

or more efficient:

```
taskLogs.computeIfAbsent(coroutineContextName) { mutableListOf<String>() }
```
</blockquote></details>

done
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt, line 64 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mbr2CZl6QMJWq8JXv4J:-MbwVkDb1cEwxDcnj7-s:b-vuph64) ([raw file](https://github.com/world-federation-of-advertisers/pan [...]

2021-06-11 21:35 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 41 of 46 files reviewed, 17 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt, line 30 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqyLrs2l6rqEWwwpMO:-Mbx-6LXC6Be8liPXQo7:blciprm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt#L30)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What if the coroutine spawns sub-coroutines to e.g. do some things concurrently -- do the child coroutines have different names?
</blockquote></details>

i'm going to write some tests around this to be explicit.


<!-- Sent from Reviewable.io -->

2021-06-11 21:49 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 41 of 46 files reviewed, 17 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt, line 21 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mbqy14z6d5h8DCfFanX:-Mbx2Bkp-yVTaKe3iqJR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt#L21)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

done but I need to fix the list to be thread-safe too
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-15 16:28 UTC, efoxepstein requested changes
> Reviewed 2 of 45 files at r3, 20 of 20 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: all files reviewed, 19 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqmUzt3sEfwU7GyqtD:-McFV4d57DYR8MoiDTK-:b-joxpfa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L63)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Actually, this defies the interface which makes me think we need to do this a different way. Lets talk about it.
</blockquote></details>

Agreed -- let's discuss over Slack or Zoom
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 38 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFQetUBZ6LMb4B8wxb:-McFQetUBZ6LMb4B8wxc:bwenvrw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L38)):*
> ```Kotlin
> class ExchangeTaskMapper(
>   private val deterministicCommutativeCryptor: Cryptor = JniDeterministicCommutativeCryptor(),
>   private val timeoutMillis: Long = 24 * 60 * 60 * 1000, // 1 Day SLA By Default
> ```

Consider using `java.time.Duration` to eliminate the possibility of unit errors.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 41 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFQcPK6_X5tddFC8kn:-McFQcPK6_X5tddFC8ko:b-vlrgaa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L41)):*
> ```Kotlin
>   private val retryMillis: Long = 60 * 1000 // 1 minute. Only for retryable tasks. eg InputTask
> ) {
>   companion object {
> ```

Nit: companion object goes at bottom of class
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 65 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFQwO80t1zJse22ukC:-McFQwO80t1zJse22ukD:bgtyyo5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L65)):*
> ```Kotlin
>             step = step,
>             timeoutMillis = timeoutMillis,
>             retryMillis = retryMillis
> ```

Rather than injecting `timeoutMillis` and `retryMillis`, I think it would be cleaner to inject an factory for InputTask: `(exchangeKey: String, step: ExchangeWorkflow.Step) -> InputTask`.

In fact, you can generalize this and inject a factory for ALL ExchangeTask types. This would decouple `ExchangeTaskMapper` from the non-generic parts of it.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 47 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFS1NhAuauvjAkIl2u:-McFS1NhAuauvjAkIl2v:b1bxzvn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L47)):*
> ```Kotlin
>         val sharedOutputLabels = step.getSharedOutputLabelsMap()
>         coroutineScope {
>           val readDeferreds: List<Deferred<Map<String, ByteString>>> =
> ```

This is one of many possible strategies for InputTask, right? Or were you imagining that they would all work like this, but the `Storage` abstraction providing `batchRead` would take care of other strategies for making sure the inputs get produced?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 70 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFSFPf62KaB7Uddn7D:-McFSFPg2ksej0Qj3v8Z:b-a3j5al) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L70)):*
> ```Kotlin
>         readStatus = true
>       } catch (e: IllegalArgumentException) {
>         println("FAILED\n")
> ```

`println`?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 73 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFRg1iAw1Xff-640M7:-McFRg1iAw1Xff-640M8:b-mm6nal) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L73)):*
> ```Kotlin
>         delay(retryMillis)
>       }
>     } while (!readStatus)
> ```

Consider using a `Throttler` instead of a manual retry loop. https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/common/throttler/Throttler.kt
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mbqur7j3NBXz3VTnpcP:-McFSN4UBYwt3o6Kqc3s:b-9h3n0i) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L34)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Done. Were you thinking this should be mocked up?
</blockquote></details>

No, it's just a typical Kotlin pattern because we can't really be sure here that we want to run on `Dispatchers.Default`.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 36 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFSUYoCaApgxL1MZRL:-McFSUYoCaApgxL1MZRM:b-9ld5f3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L36)):*
> ```Kotlin
>   private val scope: CoroutineScope = CoroutineScope(Dispatchers.Default)
> ) : JobLauncher {
>   companion object {
> ```

Please move to bottom of class.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 47 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFT62cE2ai7xOtpXcq:-McFT62cE2ai7xOtpXcr:b797jby) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L47)):*
> ```Kotlin
>     val exchangeKey: String = attemptKey.exchangeId
>     val exchangeStepAttemptKey: String = attemptKey.exchangeStepAttemptId
>     val job: Job =
> ```

Unused variable?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 57 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFSg6s5ccSmo8p7M1C:-McFSg6s5ccSmo8p7M1D:bd5vcni) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/launcher/Corouti [...]

2021-06-15 18:42 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: all files reviewed, 19 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqmUzt3sEfwU7GyqtD:-McFxtzsEdYlCL9XB5n7:b-5jluhj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L63)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Agreed -- let's discuss over Slack or Zoom
</blockquote></details>

I went ahead and put up a commit earlier today that adds a separate inputTask but it still uses this somewhat messy if to implement
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 47 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFS1NhAuauvjAkIl2u:-McFyCiS8wCk18smFFpH:bbvqygz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is one of many possible strategies for InputTask, right? Or were you imagining that they would all work like this, but the `Storage` abstraction providing `batchRead` would take care of other strategies for making sure the inputs get produced?
</blockquote></details>

For now I was thinking batchRead would take care of the various storage possibilities. What other use cases do you think we should cover?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 47 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFT62cE2ai7xOtpXcq:-McFyRP84PoCObrFpcKa:b-89a4jy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Unused variable?
</blockquote></details>

yeah - its unused. Its still a return of scope.launch though. What do you suggest?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 57 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFSg6s5ccSmo8p7M1C:-McFyaKs17c69rUrokY6:b-6s1ndd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

We should probably discuss this but I think that the `finishExchangeStepAttempt` call should probably be in `ExchangeTaskMapper` instead. Otherwise, for a different `Launcher` that runs things on different machines or enqueues things in a job queue, it may be hard for the `Launcher` to be aware of when the work is completed?

Maybe for now just add a TODO to re-evaluate?
</blockquote></details>

yeah - i can see that perspective. It does mean passing apiClient on though which feels a little messy.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt, line 64 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mbr2CZl6QMJWq8JXv4J:-McFyt2q-9XKL-bglvHp:b-1nba9i) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt#L64)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ugh the formatter really mangles this! I regret my original comment here.
</blockquote></details>

yeah. kind of a pity.


<!-- Sent from Reviewable.io -->

2021-06-15 19:51 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: all files reviewed, 17 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqmUzt3sEfwU7GyqtD:-McGDXs9Dy-pPJhaoKvU:b3tsgti) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L63)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I went ahead and put up a commit earlier today that adds a separate inputTask but it still uses this somewhat messy if to implement
</blockquote></details>

Resolving this for now but let's be sure to discuss.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 47 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFS1NhAuauvjAkIl2u:-McGCqXcB936fLUlCfXv:b-xbwhkv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L47)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

For now I was thinking batchRead would take care of the various storage possibilities. What other use cases do you think we should cover?
</blockquote></details>

Let's say that the thing that needs doing is calling some internal service to enqueue some work in a job queue. Is the idea that `batchRead` would actually call the internal service?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 47 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFT62cE2ai7xOtpXcq:-McGD3Sy8SpiWjKtKTM_:bg62qxk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L47)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah - its unused. Its still a return of scope.launch though. What do you suggest?
</blockquote></details>

My recommendation is to delete the substring `val job: Job =`.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 57 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFSg6s5ccSmo8p7M1C:-McGDDd10XiHPWNb4gNo:b-tcm26x) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L57)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah - i can see that perspective. It does mean passing apiClient on though which feels a little messy.
</blockquote></details>

I'm not quite sure why that's messy, can you elaborate?


<!-- Sent from Reviewable.io -->

2021-06-16 22:12 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: all files reviewed, 16 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 52 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqkF5yBR_5lxeypt7n:-McKjKx7DbjNKK_2evu2:bb3plhz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L52)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Very optional: consider pulling out a map to make it easier to see the correspondence:

```
val stepFactoriesOrSomeGoodName = mapOf(
  ENCRYPT_STEP to CryptorExchangeTask::forEncryption,
  REENCRYPT_STEP to CryptorExchangeTask::forReEncryption,
  DECRYPT_STEP to CryptorExchangeTask::forDecryption,
)

...

private suspend fun getExchangeTaskForStep(step: ExchangeWorkflow.Step): ExchangeTask {
  val factory = stepFactoriesOrSomeGoodName[step.getStepCase()] ?: error("Unsupported step type")
  return factory(deterministicCommutatorCryptor)
}
```
</blockquote></details>

yeah - I want to think about this more. not every factory needs deterministicCommativeCryptor passed to it. Its not that generic.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 38 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFQetUBZ6LMb4B8wxb:-McKjAa-9xEa1EFyxWYh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Consider using `java.time.Duration` to eliminate the possibility of unit errors.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 47 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFS1NhAuauvjAkIl2u:-McJoA1610OJncIFz6Ej:b-224xtj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Let's say that the thing that needs doing is calling some internal service to enqueue some work in a job queue. Is the idea that `batchRead` would actually call the internal service?
</blockquote></details>

I think the idea was that batch read determines from the step details, exchangeKey, storageType, and inputLabels where to get the data from and how to do it. The next step, execute, can't proceed until batchRead is done. To that point, batchRead could enqueue work to get done and then wait on status until it's done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 70 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFSFPf62KaB7Uddn7D:-McG-Kp52ZYXf67HHTf4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L70)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`println`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 73 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFRg1iAw1Xff-640M7:-McKu8498yG5tYbCJZX9:bsdi3o1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L73)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Consider using a `Throttler` instead of a manual retry loop. https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/common/throttler/Throttler.kt
</blockquote></details>

What do you think about using debounce instead? I converted this to a flow with debounce. lmk what you think.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 36 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFSUYoCaApgxL1MZRL:-McG-DzqE6dMS6byKXCE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L36)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please move to bottom of class.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 47 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFT62cE2ai7xOtpXcq:-McLa7rf4nPIViJpSoa0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

My recommendation is to delete the substring `val job: Job =`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 57 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFSg6s5ccSmo8p7M1C:-McLayaa6lukMNGhvL8Y:b-frpvu0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm not quite sure why that's messy, can you elaborate?
</blockquote></details>

I moved exchangeTaskMapper over to the launcher package to avoid circular dependencies based on this one.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 71 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFTBJW5kFFq3IYLCwl:-McLBuVB04tUlJ95vP8u:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L71)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is this `return` actually necessary?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt, line 39 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFTh-e6mjgGR22zV1m:-McG-5Ae7m0R0mimUQRC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/logger/Logger.kt#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`return listCopy ?: emptyList()` would be more Kotlinic
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/logger/LoggerTest.kt, line 28 at r4](https://review [...]

2021-06-16 23:07 UTC, efoxepstein requested changes
> Reviewed 18 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: all files reviewed, 7 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 52 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-MbqkF5yBR_5lxeypt7n:-McM2-lI5UXw7m4ZU7cP:b-cidfw8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c913b785eeeb2e5763559d7fd757662900c9b3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L52)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah - I want to think about this more. not every factory needs deterministicCommativeCryptor passed to it. Its not that generic.
</blockquote></details>

I think I prefer my other suggestion of just injecting a factory for all ExchangeTasks. That way, `ExchangeTaskMapper` does not need to even know about the `Cryptor`. Resolving this so there's one place to discuss.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 65 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFQwO80t1zJse22ukC:-McM2LQe1e-hdCS-vnlK:b-qxhtal) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L65)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Rather than injecting `timeoutMillis` and `retryMillis`, I think it would be cleaner to inject an factory for InputTask: `(exchangeKey: String, step: ExchangeWorkflow.Step) -> InputTask`.

In fact, you can generalize this and inject a factory for ALL ExchangeTask types. This would decouple `ExchangeTaskMapper` from the non-generic parts of it.
</blockquote></details>

Moving this to the new file.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 47 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFS1NhAuauvjAkIl2u:-McM3nGxEi2HrdmsV_M2:brxp9sq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L47)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I think the idea was that batch read determines from the step details, exchangeKey, storageType, and inputLabels where to get the data from and how to do it. The next step, execute, can't proceed until batchRead is done. To that point, batchRead could enqueue work to get done and then wait on status until it's done.
</blockquote></details>

Sounds good.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 73 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFRg1iAw1Xff-640M7:-McM3a0WAGPTH_kRcrab:b-76kdoc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L73)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

What do you think about using debounce instead? I converted this to a flow with debounce. lmk what you think.
</blockquote></details>

I think it's less parallel this way. It won't start the second batchRead until the first is done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskMapper.kt, line 44 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McM2S9D2mYA65AN2_i3:-McM2S9D2mYA65AN2_i4:b-ljk8oe) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd513f4547396892b124038c5a97880fb6dd23d0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskMapper.kt#L44)):*
> ```Kotlin
>  */
> class ExchangeTaskMapper(
>   private val deterministicCommutativeCryptor: Cryptor = JniDeterministicCommutativeCryptor(),
> ```

Here's my recommendation from other comments restated: instead of any of these parameters, just inject a `(ExchangeWorkflow.Step) -> ExchangeTask` factory.

I think this will really simplify the code in this class and make things more testable.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt, line 39 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McM3MTCDtMATgekvcgD:-McM3MTCDtMATgekvcgE:biel420) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd513f4547396892b124038c5a97880fb6dd23d0/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt#L39)):*
> ```Kotlin
> @RunWith(JUnit4::class)
> class InputTaskTest {
>   val apiClient: ApiClient = mock()
> ```

`private val`?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/storage/StorageTest.kt, line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McM1Phz9uzxHwNISy9v:-McM1Phz9uzxHwNISy9w:b-lkhiz1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd513f4547396892b124038c5a97880fb6dd23d0/src/test/kotlin/org/wfanet/panelmatch/client/storage/StorageTest.kt#L28)):*
> ```Kotlin
>     val valueToStore = ByteString.copyFromUtf8("random-edp-string-0")
>     val key = java.util.UUID.randomUUID().toString()
>     val storage = FileSystemStorage(storageType = Storage.STORAGE_TYPE.PRIVATE, label = key)
> ```

This should really be using `System.getenv("TEST_TMPDIR")` as a base directory (this is a unique scratch dir provided by Bazel).
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/FileSystemStorage.kt, line 39 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McM-uc4E_BB_qQWgbX3:-McM-uc4E_BB_qQWgbX4:b-8c4l1u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd513f4547396892b124038c5a97880fb6dd23d0/src/main/kotlin/org/wfanet/panelmatch/client/storage/FileSystemStorage.kt#L39)):*
> ```Kotlin
>     val baseFolder =
>       when (storageType) {
>         Storage.STORAGE_TYPE.SHARED -> File("/tmp/panel-match/private-storage")
> ```

Hardcoding a path seems a little sketchy, I'd prefer keeping the `baseDir` as a parameter and then adding on a `private-storage` or `shared-storage` suffix.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 61 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McM0YyIASr7CMUXGtqn:-McM0GFE-nU7tGOvqEFr:b-6f8h9r) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd513f4547396892b124038c5a97880fb6dd23d0/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L61)):*
> ```Kotlin
>   step: ExchangeWorkflow.Step
> ): Pair<Storage, String> {
>   val storage = FileSystemStorage(storageType = storageType, label = label)
> ```

If we're hardcoding something here for now, can it be something InMemory? Bazel tests might complain if this tries to write to somewhere that's not bazel's scratch path for the test.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskMapperTest.kt, line 71 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McM16na42WKedYX9CS4:-McM16na42WKedYX9CS5:b3axjpj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd513f4547396892b124038c5a97880fb6dd23d0/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTas [...]

2021-06-17 22:09 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: all files reviewed, 7 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 73 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFRg1iAw1Xff-640M7:-McQzM1S9Zl90tqx9XzS:brjwjid) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L73)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think it's less parallel this way. It won't start the second batchRead until the first is done.
</blockquote></details>

reverted this using a helper function
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt, line 39 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McM3MTCDtMATgekvcgD:-McQxmL9A7ct3FvdE8X0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd513f4547396892b124038c5a97880fb6dd23d0/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`private val`?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/storage/StorageTest.kt, line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McM1Phz9uzxHwNISy9v:-McQoOGo70P96C-VlHix:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd513f4547396892b124038c5a97880fb6dd23d0/src/test/kotlin/org/wfanet/panelmatch/client/storage/StorageTest.kt#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This should really be using `System.getenv("TEST_TMPDIR")` as a base directory (this is a unique scratch dir provided by Bazel).
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/FileSystemStorage.kt, line 39 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McM-uc4E_BB_qQWgbX3:-McQ7mzN1V-6g-4n9wCO:bhufqrv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd513f4547396892b124038c5a97880fb6dd23d0/src/main/kotlin/org/wfanet/panelmatch/client/storage/FileSystemStorage.kt#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Hardcoding a path seems a little sketchy, I'd prefer keeping the `baseDir` as a parameter and then adding on a `private-storage` or `shared-storage` suffix.
</blockquote></details>

See other comments about using system variables for this for now. lmk if that works for the time being.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 61 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McM0YyIASr7CMUXGtqn:-McQxniQ6-0IKPjAqbAq:b-guk2ki) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd513f4547396892b124038c5a97880fb6dd23d0/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L61)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

If we're hardcoding something here for now, can it be something InMemory? Bazel tests might complain if this tries to write to somewhere that's not bazel's scratch path for the test.
</blockquote></details>

Changed this to read from system variables. lmk if you think it works for now. I have tests using both in memory and filesystem this way.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskMapperTest.kt, line 71 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McM16na42WKedYX9CS4:-McQ8X5JBPdjxhwwpx08:ba2e29r) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd513f4547396892b124038c5a97880fb6dd23d0/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskMapperTest.kt#L71)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What are these for? I hope it's not for filesystem flushes (another reason to use in-memory storage for the test)
</blockquote></details>

I wasn't actually sure. Change this file to use InMemory. The coroutine one still uses FileSystem since it by definition has to delay.


<!-- Sent from Reviewable.io -->

2021-06-17 23:01 UTC, efoxepstein requested changes
> Reviewed 11 of 12 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 53 of 54 files reviewed, 6 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 73 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McFRg1iAw1Xff-640M7:-McR8QPLBXck4bipjwz0:b-6cyjv4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e65d35c2ec3efe86ad7cc1e286f29d0651a365a2/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L73)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

reverted this using a helper function
</blockquote></details>

I think I prefer just using an injected throttler for retries but I won't block you here.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/storage/FileSystemStorageTest.kt, line 20 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McRASvdE9rv1bZ6c-Mt:-McRASvdE9rv1bZ6c-Mu:b-bta0l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f9b29be856b252241f59321b3cd0429ecb3713da/src/test/kotlin/org/wfanet/panelmatch/client/storage/FileSystemStorageTest.kt#L20)):*
> ```Kotlin
> 
> class FileSystemStorageTest : AbstractStorageTest() {
>   private val BASE_DIR = System.getenv("TEST_TMPDIR")
> ```

Please use `CONSTANT_CASE` only for constants. I'd just write `private val baseDir = ...`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 61 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McM0YyIASr7CMUXGtqn:-McR9_sSDD-RlosfAiqe:br0zswe) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd513f4547396892b124038c5a97880fb6dd23d0/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L61)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Changed this to read from system variables. lmk if you think it works for now. I have tests using both in memory and filesystem this way.
</blockquote></details>

I think I prefer just using normal dependency injection with batchRead/batchWrite as methods or extension functions on Storage instances. This is effectively using globals configured by magic -- and I definitely prefer my magic kept to normal flags or confined to `main` or tests when necessary.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 29 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McRAypG7yUWel-F5ibd:-McRAypHDArFgCkjRvfa:b-fkwwwk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f9b29be856b252241f59321b3cd0429ecb3713da/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L29)):*
> ```Kotlin
> /** Interface for Storage adapter. */
> interface Storage {
>   enum class STORAGE_CLASS {
> ```

Please name enum classes like classes (PascalCase). The values of the enum are correctly ANGRY_SNAKE_CASE, though.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 73 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McRBm1J6AcCURZLqnHZ:-McRBm1J6AcCURZLqnH_:b5ybcg8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f9b29be856b252241f59321b3cd0429ecb3713da/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L73)):*
> ```Kotlin
>       Storage.STORAGE_TYPE.FILESYSTEM ->
>         FileSystemStorage(
>           baseDir = requireNotNull(System.getProperty("${storageClass.toString()}_FILESYSTEM_PATH"))
> ```

Redundant toString call (but my other suggestions would end up just deleting this).
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 170 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McRA5n97wd3MoPRSpMI:-McRA5n97wd3MoPRSpMJ:b4r32xi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f9b29be856b252241f59321b3cd0429ecb3713da/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L170)):*
> ```Kotlin
>       }
>     )
>   readDeferreds.awaitAll()
> ```

https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/await-all.html

```
awaitAll(
  async { ... },
  async { ... }
)

```


<!-- Sent from Reviewable.io -->

2021-06-18 17:46 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 53 of 54 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 61 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McM0YyIASr7CMUXGtqn:-McV7yM50ja1bPOVjeQ8:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd513f4547396892b124038c5a97880fb6dd23d0/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L61)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think I prefer just using normal dependency injection with batchRead/batchWrite as methods or extension functions on Storage instances. This is effectively using globals configured by magic -- and I definitely prefer my magic kept to normal flags or confined to `main` or tests when necessary.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 29 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McRAypG7yUWel-F5ibd:-McV7z_sBoRbtzJYCdJo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f9b29be856b252241f59321b3cd0429ecb3713da/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please name enum classes like classes (PascalCase). The values of the enum are correctly ANGRY_SNAKE_CASE, though.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 73 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McRBm1J6AcCURZLqnHZ:-McV7s6U0iBt_hGcqIQl:b-9unw5o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f9b29be856b252241f59321b3cd0429ecb3713da/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L73)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Redundant toString call (but my other suggestions would end up just deleting this).
</blockquote></details>

deleted
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 170 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McRA5n97wd3MoPRSpMI:-McUxaT4-XbamdMgb2ww:b-x5m7gy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f9b29be856b252241f59321b3cd0429ecb3713da/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L170)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/await-all.html

```
awaitAll(
  async { ... },
  async { ... }
)

```
</blockquote></details>

do you think this way is more readable? not sure why you prefer this way.


<!-- Sent from Reviewable.io -->

2021-06-18 17:48 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 53 of 54 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/storage/FileSystemStorageTest.kt, line 20 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McRASvdE9rv1bZ6c-Mt:-McVE965-u-Mra9IPyJm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f9b29be856b252241f59321b3cd0429ecb3713da/src/test/kotlin/org/wfanet/panelmatch/client/storage/FileSystemStorageTest.kt#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use `CONSTANT_CASE` only for constants. I'd just write `private val baseDir = ...`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-18 18:23 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 44 of 54 files reviewed, 7 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 170 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McRA5n97wd3MoPRSpMI:-McVLubnCRJrYkf7SnRJ:bps6tro) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f9b29be856b252241f59321b3cd0429ecb3713da/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L170)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do you think this way is more readable? not sure why you prefer this way.
</blockquote></details>

I agree that the way Eli suggested is more readable (more specifically, it's more idiomatic for Kotlin). Building the temporary list is unnecessary.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McVK2DMDm99XGCqISlP:-McVK2DMDm99XGCqISlQ:b53nrka) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/472845170fb777a7bff6f0b65f0b733dceb109fe/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L33)):*
> ```
> StorageType
> ```
I'm a bit confused at how this would be used. The storage type is determined by which implementation of the storage client you pass in to the constructor of the class that uses it. The only thing that would know the storage type is the code that instantiates the specific impl. Multiple storage impls shouldn't even exist in the same JAR to avoid having unused library dependencies.


<!-- Sent from Reviewable.io -->

2021-06-18 19:33 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 44 of 54 files reviewed, 7 unresolved discussions (waiting on @efoxepstein, @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 170 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McRA5n97wd3MoPRSpMI:-McVYOoLEJOw2mPcSLcu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f9b29be856b252241f59321b3cd0429ecb3713da/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L170)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I agree that the way Eli suggested is more readable (more specifically, it's more idiomatic for Kotlin). Building the temporary list is unnecessary.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McVK2DMDm99XGCqISlP:-McVYhV08iV0ThrVWdyW:bjbr91) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/472845170fb777a7bff6f0b65f0b733dceb109fe/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> StorageType
> ```
I'm a bit confused at how this would be used. The storage type is determined by which implementation of the storage client you pass in to the constructor of the class that uses it. The only thing that would know the storage type is the code that instantiates the specific impl. Multiple storage impls shouldn't even exist in the same JAR to avoid having unused library dependencies.
</blockquote></details>

You're right. Its code I forgot to delete after a refactor. Deleted.


<!-- Sent from Reviewable.io -->

2021-06-18 20:08 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 39 of 54 files reviewed, 7 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskMapper.kt, line 44 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McM2S9D2mYA65AN2_i3:-McVhi2UBv34KxSLxbh8:b-aetav0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd513f4547396892b124038c5a97880fb6dd23d0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskMapper.kt#L44)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Here's my recommendation from other comments restated: instead of any of these parameters, just inject a `(ExchangeWorkflow.Step) -> ExchangeTask` factory.

I think this will really simplify the code in this class and make things more testable.
</blockquote></details>

To give more detail, the goal is effectively to have flexibility in how steps are mapped to tasks. The simplest way to do this is to have the mapper be a dependency, which follows a standard pattern of having a mapper interface with multiple possible implementations. Since Kotlin supports high-order functions, you can use a function type instead of defining a whole interface for one function.

The way this is implemented now is less flexible and gives this class responsibility over both doing the mapping and executing tasks.


<!-- Sent from Reviewable.io -->

2021-06-19 17:55 UTC, efoxepstein requested changes
> Reviewed 4 of 9 files at r7, 10 of 10 files at r8, 6 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 53 of 54 files reviewed, 11 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 39 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_Js-u5MEJwKGmfDj_:-Mc_Js-u5MEJwKGmfDja:b-djozzd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/75aca977abbdeab135ed6a3e7ba83172b2c708c6/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L39)):*
> ```Kotlin
>   val step: ExchangeWorkflow.Step,
>   val retryDuration: Duration,
>   val preferredSharedStorage: Storage,
> ```

Out of curiosity, why "preferred"? Is there an alternative? (Basically, what does "preferred" convey that just "sharedStorage" wouldn't?)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 48 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_K2NUBPf8BCdjjdHk:-Mc_K2NUBPf8BCdjjdHl:b-ld138z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/75aca977abbdeab135ed6a3e7ba83172b2c708c6/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L48)):*
> ```Kotlin
>    */
>   suspend fun waitForOutputsToBeReady(
>     preferredSharedStorage: Storage,
> ```

Will this always use the data members with the same names? (Also, can it be private?)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 51 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_KTZv3hR6WvDPmKrB:-Mc_KTZv3hR6WvDPmKrC:b15gc66) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/75aca977abbdeab135ed6a3e7ba83172b2c708c6/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L51)):*
> ```Kotlin
>     preferredPrivateStorage: Storage,
>     step: ExchangeWorkflow.Step
>   ) = coroutineScope {
> ```

It looks like the return type isn't unit, so please specify the return type explicitly.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 33 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_MXV43AtmqYb6dPCe:-Mc_MXV43AtmqYb6dPCf:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/75aca977abbdeab135ed6a3e7ba83172b2c708c6/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L33)):*
> ```Kotlin
>   private val deterministicCommutativeCryptor: Cryptor = JniDeterministicCommutativeCryptor(),
>   private val scope: CoroutineScope = CoroutineScope(Dispatchers.Default),
>   private val preferredSharedStorage: Storage,
> ```

Ditto
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 40 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_O359EG8N7OMUlyvz:-Mc_O359EG8N7OMUlyw-:b-alovlr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac945f50f36f4f789170e03a418bc331594715f0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L40)):*
> ```Kotlin
>     val exchangeStepAttemptKey: String = attemptKey.exchangeStepAttemptId
>     scope.launch(CoroutineName(exchangeStepAttemptKey) + Dispatchers.Default) {
>       ExchangeTaskMapper(
> ```

Can we build a single `ExchangeTaskMapper` on construction and just call execute on it each time? In fact, what about just injecting an `ExchangeTaskMapper` in the constructor instead of all of the parameters necessary to build it?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskMapper.kt, line 97 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_OLwiEgyeS7gDzeEP:-Mc_OLwiEgyeS7gDzeEQ:b-gi0m3a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac945f50f36f4f789170e03a418bc331594715f0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskMapper.kt#L97)):*
> ```Kotlin
>       val exchangeTask: ExchangeTask = getExchangeTaskForStep(step)
>       withTimeout(timeoutDuration.toMillis()) {
>         if (step.getStepCase() == ExchangeWorkflow.Step.StepCase.INPUT_STEP) {
> ```

I think we can stop special casing this now? `getAllInputForStep` will be an empty map so no need to handle it separately.

I guess there's still the handling of the outputs -- but it seems fine to me to just write them. We can optimize at a later time if this causes problems. But what I'm imagining at this point is for large private payloads that we don't want to copy, what we write to Storage is just a pointer to the real data.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 95 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_Ozvm-N3oDoYW5iAH:-Mc_Ozvm-N3oDoYW5iAI:b-54egmn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac945f50f36f4f789170e03a418bc331594715f0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L95)):*
> ```Kotlin
>       .build()
> ) {
>   init {}
> ```

Delete this?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 175 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_P2gN2erUyI4ZZgsm:-Mc_P2gN2erUyI4ZZgsn:bevnyry) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac945f50f36f4f789170e03a418bc331594715f0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L175)):*
> ```Kotlin
>         preferredSharedStorage = preferredSharedStorage,
>         preferredPrivateStorage = preferredPrivateStorage,
>         getExchangeTaskForStep = this::getExchangeTaskForStep
> ```

Please be consistent about prefixing `::getExchangeTaskForStep` with `this` (it's different in `buildAndExecute`) 
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt, line 45 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_NlTg-sG5Xdt53wah:-Mc_NlTg-sG5Xdt53wai:b-p93cj7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac945f50f36f4f789170e03a418bc331594715f0/src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt#L45)):*
> ```Kotlin
>     FileSystemStorage(baseDir = "${System.getenv("TEST_TMPDIR")}/private")
>   private val preferredSharedStorage =
>     FileSystemStorage(baseDir = "${System.getenv("TEST_TMPDIR")}/shared")
> ```

Can we please use `InMemoryStorage` unless we're specifically testing `FileSystemStorage`? Or even a mock Storage? That way we won't need delays.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/storage/FileSystemStorageTest.kt, line 20 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McRASvdE9rv1bZ6c-Mt:-Mc_NFsh4oIo8ybNKQtR:b-gnjovh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f9b29be856b252241f59321b3cd0429ecb3713da/src/test/kotlin/org/wfanet/panelmatch/client/storage/FileSystemStorageTest.kt#L20)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please lowercase the B so it's camelCase instead of PascalCase.


<!-- Sent from Reviewable.io -->

2021-06-22 14:42 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 53 of 54 files reviewed, 11 unresolved discussions (waiting on @corbantek, @efoxepstein, @SanjayVas, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 39 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_Js-u5MEJwKGmfDj_:-MckQvLa4caFaqV-LQd8:b-4121ov) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/75aca977abbdeab135ed6a3e7ba83172b2c708c6/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Out of curiosity, why "preferred"? Is there an alternative? (Basically, what does "preferred" convey that just "sharedStorage" wouldn't?)
</blockquote></details>

Got rid of the `preferred`. I was thinking more from the cli pov but its not really helpful now that I think about it.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 48 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_K2NUBPf8BCdjjdHk:-MckO1vIBLzUXyU1HTxY:bbmcx7t) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/75aca977abbdeab135ed6a3e7ba83172b2c708c6/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Will this always use the data members with the same names? (Also, can it be private?)
</blockquote></details>

Changed it to private. I'm assuming we'll have two types of storage. Not sure if I'm answering your question or not. Any storage type can be passed in with arbitrary storage location specified by Coordinator.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt, line 51 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_KTZv3hR6WvDPmKrB:-MckOFbF9ePnKR6cDQrl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/75aca977abbdeab135ed6a3e7ba83172b2c708c6/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTask.kt#L51)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It looks like the return type isn't unit, so please specify the return type explicitly.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 33 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_MXV43AtmqYb6dPCe:-MckOVQVAsRSYA-2AVGc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/75aca977abbdeab135ed6a3e7ba83172b2c708c6/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, line 40 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_O359EG8N7OMUlyvz:-MckaQdy2iDvySTHItQx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac945f50f36f4f789170e03a418bc331594715f0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can we build a single `ExchangeTaskMapper` on construction and just call execute on it each time? In fact, what about just injecting an `ExchangeTaskMapper` in the constructor instead of all of the parameters necessary to build it?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskMapper.kt, line 44 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McM2S9D2mYA65AN2_i3:-McW0n6r7HBaGV9Wt0bV:bwuohik) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd513f4547396892b124038c5a97880fb6dd23d0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskMapper.kt#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

To give more detail, the goal is effectively to have flexibility in how steps are mapped to tasks. The simplest way to do this is to have the mapper be a dependency, which follows a standard pattern of having a mapper interface with multiple possible implementations. Since Kotlin supports high-order functions, you can use a function type instead of defining a whole interface for one function.

The way this is implemented now is less flexible and gives this class responsibility over both doing the mapping and executing tasks.
</blockquote></details>

I updated it. Let me know if thats what you had in mind.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskMapper.kt, line 97 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_OLwiEgyeS7gDzeEP:-Mco6M5u0YCFMcjgwHhI:b8bp7vd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac945f50f36f4f789170e03a418bc331594715f0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskMapper.kt#L97)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think we can stop special casing this now? `getAllInputForStep` will be an empty map so no need to handle it separately.

I guess there's still the handling of the outputs -- but it seems fine to me to just write them. We can optimize at a later time if this causes problems. But what I'm imagining at this point is for large private payloads that we don't want to copy, what we write to Storage is just a pointer to the real data.
</blockquote></details>

I don't like that for a couple reasons.
1. Its messy and will be confusing to future people that look at this.
2. The storage in outputs could very well be read-only. It only needs to be read-only. So, we can't guarantee we can even write there.

I agree with you it would be nice to get rid of this if. Maybe we should change the schema to allow for this?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 95 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_Ozvm-N3oDoYW5iAH:-Mck9lx25D5Rxt8DN0ju:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac945f50f36f4f789170e03a418bc331594715f0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L95)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Delete this?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 175 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_P2gN2erUyI4ZZgsm:-Mck9oJ8ANZIX7YeFAxM:buxcuwq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac945f50f36f4f789170e03a418bc331594715f0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L175)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please be consistent about prefixing `::getExchangeTaskForStep` with `this` (it's different in `buildAndExecute`) 
</blockquote></details>

They are scoped differently so that won't work. I started to qualify them instead, but decided to just pull them out to their own class.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt, line 45 at r [...]

2021-06-22 18:59 UTC, efoxepstein approved these changes
> Reviewed 16 of 16 files at r10.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 55 of 56 files reviewed, 3 unresolved discussions (waiting on @corbantek, @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt, line 50 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mcp4LWe9ZqNAFaVeeae:-Mcp4LWe9ZqNAFaVeeaf:b-dr1vhz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ebd16deec738aac9ca183f9a24df384bca29cca4/src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt#L50)):*
> ```Kotlin
>   @Test
>   fun `test input task`() {
>     val EXCHANGE_KEY = java.util.UUID.randomUUID().toString()
> ```

camelCase please
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt, line 91 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mcp4Nyi0eqNVW-Wj5T7:-Mcp4Nyi0eqNVW-Wj5T8:b-igic7y) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ebd16deec738aac9ca183f9a24df384bca29cca4/src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt#L91)):*
> ```Kotlin
>           requireNotNull(
>             privateStorage.batchRead(inputLabels = mapOf("input" to "$EXCHANGE_KEY-mp-crypto-key"))[
>               "input"]
> ```

Bizarre formatting -- can you break this up by using an intermediate variable or something to make it nicer?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskMapper.kt, line 44 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McM2S9D2mYA65AN2_i3:-Mcp35pO2YxIXCMezu8z:b-qn5lbb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd513f4547396892b124038c5a97880fb6dd23d0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskMapper.kt#L44)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I updated it. Let me know if thats what you had in mind.
</blockquote></details>

Perfect!
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskMapper.kt, line 97 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mc_OLwiEgyeS7gDzeEP:-Mcp3F418gse_AMvOC_V:b2d59tf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac945f50f36f4f789170e03a418bc331594715f0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskMapper.kt#L97)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I don't like that for a couple reasons.
1. Its messy and will be confusing to future people that look at this.
2. The storage in outputs could very well be read-only. It only needs to be read-only. So, we can't guarantee we can even write there.

I agree with you it would be nice to get rid of this if. Maybe we should change the schema to allow for this?
</blockquote></details>

Can you file a bug or add a TODO and let's revisit this later?


<!-- Sent from Reviewable.io -->

2021-06-22 20:44 UTC, efoxepstein approved these changes
> Reviewed 15 of 15 files at r11.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 55 of 56 files reviewed, 1 unresolved discussion (waiting on @corbantek, @SanjayVas, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt, line 92 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-McpSj4jERzBVPCiqgUW:-McpSj4jERzBVPCiqgUX:b-vjfmj9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da16d7f8c15dae6dfbc378376290b3783c6b8e4c/src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt#L92)):*
> ```Kotlin
>     val readValues =
>       privateStorage.batchRead(inputLabels = mapOf("input" to "$exchangeKey-mp-crypto-key"))
>     val readInput = requireNotNull(readValues["input"])
> ```

You can probably remove the `requireNotNull` if you want -- assertThat *should* work on nullable things too.


<!-- Sent from Reviewable.io -->

2021-06-22 20:45 UTC, yunyeng approved these changes
> Reviewed 9 of 46 files at r3, 2 of 20 files at r4, 1 of 18 files at r5, 3 of 12 files at r6, 1 of 10 files at r8, 2 of 6 files at r9, 6 of 16 files at r10, 15 of 15 files at r11.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 55 of 56 files reviewed, 1 unresolved discussion (waiting on @corbantek and @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-06-22 20:58 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 54 of 56 files reviewed, 1 unresolved discussion (waiting on @corbantek, @efoxepstein, @SanjayVas, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt, line 50 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mcp4LWe9ZqNAFaVeeae:-Mcp9IF_79fw5mMLzWmK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ebd16deec738aac9ca183f9a24df384bca29cca4/src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt#L50)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

camelCase please
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt, line 91 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mcp4Nyi0eqNVW-Wj5T7:-Mcp8GBj8gZ_WYsxof6t:bl4urv6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ebd16deec738aac9ca183f9a24df384bca29cca4/src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt#L91)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Bizarre formatting -- can you break this up by using an intermediate variable or something to make it nicer?
</blockquote></details>

Weird. Done.


<!-- Sent from Reviewable.io -->

2021-06-22 21:01 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 55 of 56 files reviewed, 1 unresolved discussion (waiting on @corbantek and @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-06-22 23:41 UTC, efoxepstein approved these changes
> Reviewed 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 55 of 56 files reviewed, 2 unresolved discussions (waiting on @corbantek, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 92 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mcq51i316WP1LvHYBEj:-Mcq51i316WP1LvHYBEk:b-25lkom) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0ac4ef1b796643cab09aee81e5ae5b7d2aee9797/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L92)):*
> ```Kotlin
>   val deterministicCommutativeCryptor: Cryptor = buildMockCryptor(),
>   // If you are running a high number of runs_per_test in bazel, you need a longer timeout
>   val timeoutDuration: Duration = Duration.ofMillis(10000),
> ```

This is why I prefer injecting a throttler instead of a duration. You can just use a fake throttler in tests that retries when you want it to.


<!-- Sent from Reviewable.io -->

2021-06-23 01:16 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 55 of 56 files reviewed, 2 unresolved discussions (waiting on @corbantek, @efoxepstein, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 92 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mcq51i316WP1LvHYBEj:-McqN4uJDassHDRi1mm4:b-vdlp76) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0ac4ef1b796643cab09aee81e5ae5b7d2aee9797/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L92)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is why I prefer injecting a throttler instead of a duration. You can just use a fake throttler in tests that retries when you want it to.
</blockquote></details>

I'm not sure how that would fix things. The main problem is that we launch a coroutine and return without it completing. We can't really guarantee when it will complete the coroutine that we launched asynchronously.

I see that mockito supports a verify with a timeout. That feels like a better solution to me. Switched it to that.


<!-- Sent from Reviewable.io -->

2021-06-23 13:33 UTC, efoxepstein requested changes
> Reviewed 2 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20)* status: 55 of 56 files reviewed, 2 unresolved discussions (waiting on @corbantek, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 92 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-Mcq51i316WP1LvHYBEj:-Mct3UumAtDhB1lbr1RM:bton4wr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0ac4ef1b796643cab09aee81e5ae5b7d2aee9797/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L92)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm not sure how that would fix things. The main problem is that we launch a coroutine and return without it completing. We can't really guarantee when it will complete the coroutine that we launched asynchronously.

I see that mockito supports a verify with a timeout. That feels like a better solution to me. Switched it to that.
</blockquote></details>

This comment was supposed to be a line lower on the `retryDuration` comment -- but anyway, injecting a mock throttler would make it easier to test that it properly does retries.


<!-- Sent from Reviewable.io -->

2021-06-23 13:33 UTC, efoxepstein approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/20#-:-Mct3or-67u9G36-vAEy:bnfp4nl)* status: 55 of 56 files reviewed, 2 unresolved discussions (waiting on @corbantek, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-06-23 17:36 UTC, merged