add intersect and validate task
world-federation-of-advertisers/panel-exchange-client pull request #21
Opened 2021-06-14 21:25 UTC by stevenwarejones

2021-06-15 12:00 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McEXQWv4Ta0D7nR_fgL:-McEXQWv4Ta0D7nR_fgM:b-pus2yb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8c38345451c33cd68dba3ef8560c65f98af2b32a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt#L25)):*
> ```Kotlin
>     val currentData: List<ByteString> =
>       parseSerializedSharedInputs(requireNotNull(input["current-data"]))
>     val currentDataSize: Int = currentData.size
> ```

@efoxepstein `.size` is an `Int` which makes me wonder if if `maxSize` should also be an `Int`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McEXicK9l0tcGkkRbp5:-McEXicK9l0tcGkkRbp6:b-jq3qdf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8c38345451c33cd68dba3ef8560c65f98af2b32a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt#L37)):*
> ```Kotlin
>       "Overlap of ${currentOverlap} is less than $minimumOverlap"
>     }
>     return mapOf("current-data" to requireNotNull(input["current-data"]))
> ```

copy of


<!-- Sent from Reviewable.io -->

2021-06-15 17:47 UTC, efoxepstein requested changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McFjejm1Ck3lsv126pB:-McFjejm1Ck3lsv126pC:b-hccvqo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8c38345451c33cd68dba3ef8560c65f98af2b32a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt#L20)):*
> ```Kotlin
> import org.wfanet.panelmatch.protocol.common.parseSerializedSharedInputs
> 
> class IntersectValidateTask(val maxSize: Long, val minimumOverlap: Float) : ExchangeTask {
> ```

KDoc plz
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McEXQWv4Ta0D7nR_fgL:-McFjawVAL0X1z61V8mD:b-qcvib4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8c38345451c33cd68dba3ef8560c65f98af2b32a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@efoxepstein `.size` is an `Int` which makes me wonder if if `maxSize` should also be an `Int`
</blockquote></details>

Agreed, it should be an Int
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McFk8qg0WGvPNxfWm7P:-McFk8qg0WGvPNxfWm7Q:b-g600s1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8c38345451c33cd68dba3ef8560c65f98af2b32a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt#L30)):*
> ```Kotlin
>     }
>     val (match, rest) =
>       currentData.partition {
> ```

Re-thinking this, I kind of prefer this formula:

```
val oldData = parseSerializedSharedInputs(requireNotNull(input["previous-data"])).toSet()
val newItems = currentData.count { it in oldData }
require(count < maxSize * minimumOverlap)
```

I think this is probably a little more straightforward to reason about because maxSize * minimumOverlap is a constant (maybe we should remove `minimumOverlap` and add `maximumNewElements` instead?).

Anyway, either way, please use `count` instead of `partition`, and please don't re-parse the `previous-data` each time, and please ensure it's a set.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McFk3Sw9n5h89FbptSD:-McFk3Sw9n5h89FbptSE:b-b666rb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8c38345451c33cd68dba3ef8560c65f98af2b32a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt#L33)):*
> ```Kotlin
>         parseSerializedSharedInputs(requireNotNull(input["previous-data"])).contains(it)
>       }
>     val currentOverlap: Float = match.size.toFloat() / currentDataSize
> ```

`require(currentDataSize > 0)` if you do this division


<!-- Sent from Reviewable.io -->

2021-06-18 20:04 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McFjejm1Ck3lsv126pB:-McVcED18g1jChnRzYBV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8c38345451c33cd68dba3ef8560c65f98af2b32a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

KDoc plz
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McFk8qg0WGvPNxfWm7P:-McVgyp13v3O3EBTQr68:b-d8hvdx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8c38345451c33cd68dba3ef8560c65f98af2b32a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt#L30)):*
> val newItems = currentData.count { it in oldData }
Thanks for catching this. I kept the math in the same format as before but implemented your other good catches.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McFk3Sw9n5h89FbptSD:-McVcQ1B1EY87SS7RZ3F:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8c38345451c33cd68dba3ef8560c65f98af2b32a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`require(currentDataSize > 0)` if you do this division
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-18 21:52 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[WORKSPACE, line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McW63la-nKxnQMgYFC5:-McW63la-nKxnQMgYFC6:bqi8duk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a7582748a2ae5457c23fa1a5f991bb9ce1b4aed0/WORKSPACE#L72)):*
> ```Starlark
> http_archive(
>     name = "wfa_measurement_proto",
>     sha256 = "78dcfa75575c285fced66bfcea6116e868ca66647cf7ed6236153d03dcf8c655",
> ```

had to update this to reflect changing the api from Long to Int for maxSize


<!-- Sent from Reviewable.io -->

2021-06-19 18:00 UTC, efoxepstein reviewed
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 100 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-Mc_Q8UUEikdzQVvmcUL:-Mc_Q8UUEikdzQVvmcUM:bg51757) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a7582748a2ae5457c23fa1a5f991bb9ce1b4aed0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L100)):*
> ```Kotlin
>   init {}
> 
>   fun getExchangeTaskForStep(step: ExchangeWorkflow.Step): ExchangeTask {
> ```

This looks like it'll be pretty much the same in prod too. Should we pull this out to a non-testing library?


<!-- Sent from Reviewable.io -->

2021-06-22 14:45 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek, @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 100 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-Mc_Q8UUEikdzQVvmcUL:-McoAWBzB4-FtTW_lvbZ:b-7dzxdc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a7582748a2ae5457c23fa1a5f991bb9ce1b4aed0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L100)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This looks like it'll be pretty much the same in prod too. Should we pull this out to a non-testing library?
</blockquote></details>

done as part of coroutine branch -- https://github.com/world-federation-of-advertisers/panel-exchange-client/pull/20/files#diff-fc80882d80e22ba444f17b80aba6f4fa48143ffdd0b9d96ad1ff1ccce46a8299R30


<!-- Sent from Reviewable.io -->

2021-06-22 21:01 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @stevenwarejones, and @yunyeng)



<!-- Sent from Reviewable.io -->

2021-06-23 18:45 UTC, efoxepstein requested changes
> Reviewed 7 of 7 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek, @stevenwarejones, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McuAyiF62MlW81PguhS:-McuAyiF62MlW81PguhT:b4h9mqi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bae18df2e85243cd42474f6da350952bc694ed79/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L83)):*
> ```Kotlin
>   @Test
>   fun `test intersect and validate exchange step`() = runBlocking {
>     val exchangeKey = java.util.UUID.randomUUID().toString()
> ```

Please pull these out to constants with meaningful names at the top of the file.

```
private const val EXCHANGE_KEY = "some-arbitrary-exchange-key"
```


<!-- Sent from Reviewable.io -->

2021-06-23 19:02 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @efoxepstein, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McuAyiF62MlW81PguhS:-McuE_Cm3J1bKP4-_f59:bqinlck) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bae18df2e85243cd42474f6da350952bc694ed79/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L83)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please pull these out to constants with meaningful names at the top of the file.

```
private const val EXCHANGE_KEY = "some-arbitrary-exchange-key"
```
</blockquote></details>

they actually need to be generated in each test the way it is with common storage across all the tests. I can redeclare each storage each time for each test as an option but that doesn't feel any better than the way it is


<!-- Sent from Reviewable.io -->

2021-06-23 19:03 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @efoxepstein, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McuAyiF62MlW81PguhS:-McuF9vw1fVuVbQ32PcN:bnwqz62) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bae18df2e85243cd42474f6da350952bc694ed79/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L83)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

they actually need to be generated in each test the way it is with common storage across all the tests. I can redeclare each storage each time for each test as an option but that doesn't feel any better than the way it is
</blockquote></details>

i also think the way it is now is its own test in a way... that all these tests don't interfere with each other. 


<!-- Sent from Reviewable.io -->

2021-06-23 19:13 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @corbantek, @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McuAyiF62MlW81PguhS:-McuH7-G7dafCLl0qvWy:b-njlpjm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bae18df2e85243cd42474f6da350952bc694ed79/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L83)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i also think the way it is now is its own test in a way... that all these tests don't interfere with each other. 
</blockquote></details>

Each test case should be isolated, fully clean up after itself, and ideally deterministic unless you're deliberately trying to test random things.

Please see my https://github.com/world-federation-of-advertisers/panel-exchange-client/pull/29 which makes the InMemoryStorage and FileSystemStorage tests more hermetic.

If you want to test that things don't interfere, do that in a single testcase please.


<!-- Sent from Reviewable.io -->

2021-06-23 19:36 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @corbantek, @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 158 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McuMj1t0DHoYUSyKkRV:-McuMj1t0DHoYUSyKkRW:b-4f5ms) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/919a8e1ee671d5963043ee51203cc278c9bbc2c7/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L158)):*
> ```Kotlin
>       assertFailsWith(IllegalArgumentException::class) { testStep.buildAndExecuteTask() }
>     // Copy is not available if validate fails
>     val argumentException1 =
> ```

The unused variable warnings are pretty annoying when building/testing in bazel -- do you mind just removing all unused variables like this and `argumentException0`?


<!-- Sent from Reviewable.io -->

2021-06-23 19:44 UTC, efoxepstein reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek, @stevenwarejones, and @yunyeng)



<!-- Sent from Reviewable.io -->

2021-06-23 19:58 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek, @efoxepstein, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McuAyiF62MlW81PguhS:-McuPNQU6tR1VyoOlX5l:byweftc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bae18df2e85243cd42474f6da350952bc694ed79/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L83)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Each test case should be isolated, fully clean up after itself, and ideally deterministic unless you're deliberately trying to test random things.

Please see my https://github.com/world-federation-of-advertisers/panel-exchange-client/pull/29 which makes the InMemoryStorage and FileSystemStorage tests more hermetic.

If you want to test that things don't interfere, do that in a single testcase please.
</blockquote></details>

Done. I'm not really sure how to make the loggerTest completely hermetic though unless I make a fake loggerFor function. thoughts?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 158 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McuMj1t0DHoYUSyKkRV:-McuPO-31wq_ntiNgKbK:b-46djwv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/919a8e1ee671d5963043ee51203cc278c9bbc2c7/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L158)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The unused variable warnings are pretty annoying when building/testing in bazel -- do you mind just removing all unused variables like this and `argumentException0`?
</blockquote></details>

I think I got most of them.


<!-- Sent from Reviewable.io -->

2021-06-23 23:37 UTC, efoxepstein requested changes
> Reviewed 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: all files reviewed, 6 unresolved discussions (waiting on @corbantek, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt, line 25 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McvCuDxD-mveNeNrIyX:-McvCuDxD-mveNeNrIyY:b-cer3yl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3fad7ba274cf8d1e7a6d92abcac78d7aec1c0bcd/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt#L25)):*
> ```Kotlin
>  */
> class InMemoryStorage(keyPrefix: String) : Storage {
>   private val keyPrefix = keyPrefix
> ```

You can delete this line and instead write:

```
class InMemoryStorage(private val keyPrefix: String) : Storage {
```
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt, line 36 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McvD0MZ42KeQG1yswUy:-McvD0MZ42KeQG1yswUz:b2igokp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3fad7ba274cf8d1e7a6d92abcac78d7aec1c0bcd/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt#L36)):*
> ```Kotlin
> import org.wfanet.panelmatch.protocol.common.makeSerializedSharedInputs
> 
> const val exchangeKey = "some-exchange-key-00"
> ```

constants should be SCREAMING_SNAKE_CASE please
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt, line 128 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McvD8Hk6-4DEaRtrHSH:-McvD8Hk6-4DEaRtrHSI:b3niwo3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3fad7ba274cf8d1e7a6d92abcac78d7aec1c0bcd/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt#L128)):*
> ```Kotlin
>       val apiClient: ApiClient = mock()
>       val privateStorage = InMemoryStorage(keyPrefix = "private")
>       val sharedStorage = InMemoryStorage(keyPrefix = "shared")
> ```

Do all tests make these 3 things (apiClient, privateStorage, sharedStorage)? If so, promote to instance variables?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt, line 55 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McvDMsD7pZzezgZCxVn:-McvDMsE1YGs9xWQBotL:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3fad7ba274cf8d1e7a6d92abcac78d7aec1c0bcd/src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt#L55)):*
> ```Kotlin
>     val apiClient: ApiClient = mock()
>     val privateStorage = InMemoryStorage(keyPrefix = "private")
>     val sharedStorage = InMemoryStorage(keyPrefix = "shared")
> ```

Ditto
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McuAyiF62MlW81PguhS:-McvDtCw4qr8byUQTPfK:bonhek9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bae18df2e85243cd42474f6da350952bc694ed79/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L83)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Done. I'm not really sure how to make the loggerTest completely hermetic though unless I make a fake loggerFor function. thoughts?
</blockquote></details>

Add to Logger.kt:

```
/** Some good comment about how this is for testing only. */
internal fun clearLogs() {
  taskLogs.clear()
}
```

and then to test:

```
@Before
fun clearLogs() {
  clearLogsForTesting()
}
```
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 49 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McvDWjZ3Ou4mhTO3hct:-McvDWjZ3Ou4mhTO3hcu:bhkcq8g) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3fad7ba274cf8d1e7a6d92abcac78d7aec1c0bcd/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L49)):*
> ```Kotlin
>   @Test
>   fun `test encrypt exchange step`() = runBlocking {
>     val apiClient: ApiClient = mock()
> ```

It's fine to have these as private instance variables (since between each test case, a new instance of the class is made)


<!-- Sent from Reviewable.io -->

2021-06-24 14:45 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: all files reviewed, 6 unresolved discussions (waiting on @corbantek, @efoxepstein, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt, line 25 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McvCuDxD-mveNeNrIyX:-McyO35mEcGZlOtFHo4E:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3fad7ba274cf8d1e7a6d92abcac78d7aec1c0bcd/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

You can delete this line and instead write:

```
class InMemoryStorage(private val keyPrefix: String) : Storage {
```
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt, line 36 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McvD0MZ42KeQG1yswUy:-McyNf5HD8jaJIH1uv7c:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3fad7ba274cf8d1e7a6d92abcac78d7aec1c0bcd/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt#L36)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

constants should be SCREAMING_SNAKE_CASE please
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt, line 128 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McvD8Hk6-4DEaRtrHSH:-McyNemtBl0tcOwnARMo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3fad7ba274cf8d1e7a6d92abcac78d7aec1c0bcd/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt#L128)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Do all tests make these 3 things (apiClient, privateStorage, sharedStorage)? If so, promote to instance variables?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt, line 55 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McvDMsD7pZzezgZCxVn:-McyKlH94X0vEtzAuGlV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3fad7ba274cf8d1e7a6d92abcac78d7aec1c0bcd/src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McuAyiF62MlW81PguhS:-McyNynhAxZbEpTH4S6f:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bae18df2e85243cd42474f6da350952bc694ed79/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L83)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Add to Logger.kt:

```
/** Some good comment about how this is for testing only. */
internal fun clearLogs() {
  taskLogs.clear()
}
```

and then to test:

```
@Before
fun clearLogs() {
  clearLogsForTesting()
}
```
</blockquote></details>

Done
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 49 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McvDWjZ3Ou4mhTO3hct:-McyNgijAQheFW8Enu8B:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3fad7ba274cf8d1e7a6d92abcac78d7aec1c0bcd/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L49)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's fine to have these as private instance variables (since between each test case, a new instance of the class is made)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-24 16:52 UTC, efoxepstein approved these changes
> Reviewed 8 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: all files reviewed, 3 unresolved discussions (waiting on @corbantek, @stevenwarejones, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt, line 36 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McyvMLx19-ECqo7npX5:-McyvMLzALeiPn-qUeXH:blx9dci) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/19d0a37c02b0ff77893c9bf1dfb7ef34384e9c51/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt#L36)):*
> ```Kotlin
> import org.wfanet.panelmatch.protocol.common.makeSerializedSharedInputs
> 
> const val EXCHANGE_KEY = "some-exchange-key-00"
> ```

`private` please
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt, line 45 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McyvSXS-CmqP67EyZiK:-McyvSXS-CmqP67EyZiL:b-t4mlwq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/19d0a37c02b0ff77893c9bf1dfb7ef34384e9c51/src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt#L45)):*
> ```Kotlin
> import org.wfanet.panelmatch.protocol.common.parseSerializedSharedInputs
> 
> const val EXCHANGE_KEY = "some-exchange-key-00"
> ```

`private const val` please
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 41 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McyvYZc1ovtUmCVEYYU:-McyvYZc1ovtUmCVEYYV:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/19d0a37c02b0ff77893c9bf1dfb7ef34384e9c51/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L41)):*
> ```Kotlin
> import org.wfanet.panelmatch.protocol.common.parseSerializedSharedInputs
> 
> const val EXCHANGE_KEY = "some-exchange-key-00"
> ```

Ditto


<!-- Sent from Reviewable.io -->

2021-06-24 17:53 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21)* status: all files reviewed, 3 unresolved discussions (waiting on @corbantek, @efoxepstein, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt, line 36 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McyvMLx19-ECqo7npX5:-Mcz5zJ9AY3Gq_wzXF9p:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/19d0a37c02b0ff77893c9bf1dfb7ef34384e9c51/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt#L36)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`private` please
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt, line 45 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McyvSXS-CmqP67EyZiK:-Mcz5wXYBSG0aVNitp9_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/19d0a37c02b0ff77893c9bf1dfb7ef34384e9c51/src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`private const val` please
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 41 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/21#-McyvYZc1ovtUmCVEYYU:-Mcz5xKF8hGyeu7HqG5i:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/19d0a37c02b0ff77893c9bf1dfb7ef34384e9c51/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-24 17:57 UTC, merged