add event preprocessing step
world-federation-of-advertisers/panel-exchange-client pull request #212
Opened 2021-11-18 19:00 UTC by stevenwarejones

2021-11-18 20:27 UTC, efoxepstein requested changes
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-Mooc_Uv3tuZk-e6ehLp:-Mooc_Uv3tuZk-e6ehLq:byrut8d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8fd79be8c1f60d2be457b99fdd216a97e5c07927/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt#L42)):*
> ```Kotlin
>   override val getQueryResultsEvaluator = ::JniQueryEvaluator
>   override val queryResultsDecryptor by lazy { JniQueryResultsDecryptor() }
>   override val deterministicCommutativeCipherKeyProvider =
> ```

In general, not every production use case of this will use these things. Can you pull the changes from this file into a subclass or something?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MoocoKp-Cf-hApvtWLT:-MoocoKp-Cf-hApvtWLU:bgwtjo9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8fd79be8c1f60d2be457b99fdd216a97e5c07927/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L34)):*
> ```Kotlin
> ) : DoFn<T, MutableList<T>>() {
>   private var buffer = mutableListOf<T>()
>   var size: Long = 0L
> ```

`private var` please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-Mooit0vCHB8EMzDdAf0:-Mooit0vCHB8EMzDdAf1:b-quqcg7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8fd79be8c1f60d2be457b99fdd216a97e5c07927/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L45)):*
> ```Kotlin
>   abstract val certificateManager: CertificateManager
>   abstract val inputTaskThrottler: Throttler
>   abstract val deterministicCommutativeCipherKeyProvider:
> ```

Can we bundle all of these new parameters into a data class? Like `PreprocessingContext` maybe?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/PreprocessEventsTask.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MooiLGY4U4t0xYx_fNa:-MooiLGY4U4t0xYx_fNb:b-ll3758) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8fd79be8c1f60d2be457b99fdd216a97e5c07927/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/PreprocessEventsTask.kt#L41)):*
> ```Kotlin
>   override val storageFactory: StorageFactory,
>   private val deterministicCommutativeCipherKeyProvider:
>     (ByteString) -> DeterministicCommutativeCipherKeyProvider,
> ```

Does this need to be serializable? I'm wondering if this will work


<!-- Sent from Reviewable.io -->

2021-12-14 02:17 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-Mooc_Uv3tuZk-e6ehLp:-Mqqi6YPD-S3n6FZNiJ_:b202414) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8fd79be8c1f60d2be457b99fdd216a97e5c07927/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt#L42)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

In general, not every production use case of this will use these things. Can you pull the changes from this file into a subclass or something?
</blockquote></details>

i was thinking about this some more. No one's use case includes all these cases. No one requires both a queryResultsEvalulator and a queryResultsDecryptor, for example. You could argue that EventPreprocessingStep is more needed by model providers as it makes it easier to test end to end. Wdyt?


<!-- Sent from Reviewable.io -->

2021-12-14 18:03 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-Mooc_Uv3tuZk-e6ehLp:-MqqmZ1x7fb8GJSeRrNU:b-n3dbo3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8fd79be8c1f60d2be457b99fdd216a97e5c07927/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt#L42)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i was thinking about this some more. No one's use case includes all these cases. No one requires both a queryResultsEvalulator and a queryResultsDecryptor, for example. You could argue that EventPreprocessingStep is more needed by model providers as it makes it easier to test end to end. Wdyt?
</blockquote></details>

Can we get #235 and #242 merged first, rebase this, and then see what to do about this?


<!-- Sent from Reviewable.io -->

2021-12-17 21:44 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: 8 of 65 files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MoocoKp-Cf-hApvtWLT:-MquYuN-CfSJOGJ4wJPz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8fd79be8c1f60d2be457b99fdd216a97e5c07927/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L34)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`private var` please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-Mooit0vCHB8EMzDdAf0:-Mr8BBYi0CH1lD10MoYn:b-3ctsd0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8fd79be8c1f60d2be457b99fdd216a97e5c07927/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can we bundle all of these new parameters into a data class? Like `PreprocessingContext` maybe?
</blockquote></details>

I added in stepContexts. lmk what you think
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/PreprocessEventsTask.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MooiLGY4U4t0xYx_fNa:-Mr39-b-57XRE-PJKfvt:b90p7yh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8fd79be8c1f60d2be457b99fdd216a97e5c07927/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/PreprocessEventsTask.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Does this need to be serializable? I'm wondering if this will work
</blockquote></details>

the fn is not passed into the workflow ... just the constructed class. Why wouldn't it work?


<!-- Sent from Reviewable.io -->

2021-12-17 21:44 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: 8 of 65 files reviewed, 4 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-Mooc_Uv3tuZk-e6ehLp:-Mr9LfHNAohKgyzYDOmD:bs7meqb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8fd79be8c1f60d2be457b99fdd216a97e5c07927/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt#L42)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can we get #235 and #242 merged first, rebase this, and then see what to do about this?
</blockquote></details>

take another look at this.


<!-- Sent from Reviewable.io -->

2021-12-17 21:57 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: 8 of 65 files reviewed, 5 unresolved discussions (waiting on @efoxepstein)

___
*[src/test/kotlin/org/wfanet/panelmatch/integration/FullWithPreprocessingTest.kt, line 104 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-Mr9N36V0T0mqv_aX23C:-Mr9N36V0T0mqv_aX23D:bggi1kx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/64e961517690045da84e78e42b4c92ee750192ff/src/test/kotlin/org/wfanet/panelmatch/integration/FullWithPreprocessingTest.kt#L104)):*
> ```Kotlin
>         // TODO: Figure out where this extra carriage return is coming from
>         requireNotNull(it.plaintextJoinKeyAndId.joinKey).key.toStringUtf8() to
>           payload.replace("\n", "")
> ```

@efoxepstein - something weird is going on here. I'll think about it but lmk if anything comes to mind. Here is the current test output
```
expected: [(join-key-1, payload-for-join-key-1), (join-key-2, payload-for-join-key-2)]
but was : [(join-key-1, payload-for-join-key-1), (join-key-2, payload-for-join-key-2)]
```


<!-- Sent from Reviewable.io -->

2021-12-18 03:21 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: 8 of 65 files reviewed, 5 unresolved discussions (waiting on @efoxepstein)

___
*[src/test/kotlin/org/wfanet/panelmatch/integration/FullWithPreprocessingTest.kt, line 104 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-Mr9N36V0T0mqv_aX23C:-MrAYdWL6WDTcRyWMmLO:b-j2umjo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/64e961517690045da84e78e42b4c92ee750192ff/src/test/kotlin/org/wfanet/panelmatch/integration/FullWithPreprocessingTest.kt#L104)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@efoxepstein - something weird is going on here. I'll think about it but lmk if anything comes to mind. Here is the current test output
```
expected: [(join-key-1, payload-for-join-key-1), (join-key-2, payload-for-join-key-2)]
but was : [(join-key-1, payload-for-join-key-1), (join-key-2, payload-for-join-key-2)]
```
</blockquote></details>

it looks like the extra characters are getting inserted by the delimited writer


<!-- Sent from Reviewable.io -->

2022-01-03 18:37 UTC, efoxepstein requested changes
> Reviewed 7 of 57 files at r2, 1 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: 16 of 65 files reviewed, 6 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/common/ExchangeContext.kt, line 28 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsWCofhCeI78yVT3pVH:-MsWCofhCeI78yVT3pVI:b-gve00a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1aa8a7f10c6cafa0fe55fabaeedbecfe112e218a/src/main/kotlin/org/wfanet/panelmatch/client/common/ExchangeContext.kt#L28)):*
> ```Kotlin
>   val workflow: ExchangeWorkflow,
>   val step: ExchangeWorkflow.Step,
>   val stepContext: StepContext?,
> ```

I think this is a misnomer: in practice, the StepContext seems to apply to a particular task type, not a particular step, and certainly not a particular Exchange, since it's made before the daemon even starts running.

Can we discuss the design here? I think I'd prefer just adding additional constructor parameters to `ProductionExchangeTaskMapper`, for example rename `PreprocessStepContext` to `PreprocessEventsParameters` and pass it as a constructor argument to `ProductionExchangeTaskMapper`. Am I missing something here?


<!-- Sent from Reviewable.io -->

2022-01-03 18:39 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: 16 of 65 files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsWE3EtC9bKNegMmTBD:-MoocQus-rDw4ideWtvQ:bcvuxth) (no related file):*
Are there parts of this PR that we can split off into a smaller PR so we can make progress while we discuss some of the other design decisions?

---


<!-- Sent from Reviewable.io -->

2022-01-04 18:31 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: 16 of 65 files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/PreprocessEventsTask.kt, line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsaLMQNC6nx2I7HPIjF:-MsaLMQNC6nx2I7HPIjG:b-bdycpd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1aa8a7f10c6cafa0fe55fabaeedbecfe112e218a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/PreprocessEventsTask.kt#L31)):*
> ```Kotlin
> import org.wfanet.panelmatch.common.compression.CompressionParameters
> 
> suspend fun ApacheBeamContext.preprocessEventsTask(
> ```

This isn't consistent with how `executePrivateMembershipQueries` and `decryptPrivateMembershipResults` are named -- please remove `Task` 
___
*[src/test/kotlin/org/wfanet/panelmatch/integration/FullWithPreprocessingTest.kt, line 104 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-Mr9N36V0T0mqv_aX23C:-MsaLjVw72TNf0qZCJJR:bdr5l2j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/64e961517690045da84e78e42b4c92ee750192ff/src/test/kotlin/org/wfanet/panelmatch/integration/FullWithPreprocessingTest.kt#L104)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

it looks like the extra characters are getting inserted by the delimited writer
</blockquote></details>

Did you figure out what was happening?


<!-- Sent from Reviewable.io -->

2022-01-05 14:25 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: 13 of 68 files reviewed, 4 unresolved discussions (waiting on @efoxepstein)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsWE3EtC9bKNegMmTBD:-MsebIjGDtthNEUHb5ui:bmcm0pl) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Are there parts of this PR that we can split off into a smaller PR so we can make progress while we discuss some of the other design decisions?
</blockquote></details>

refactored per our discussion

---
___
*[src/test/kotlin/org/wfanet/panelmatch/integration/FullWithPreprocessingTest.kt, line 104 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-Mr9N36V0T0mqv_aX23C:-MseaqCh1C7g-2J5uGiE:b-r5b7qa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/64e961517690045da84e78e42b4c92ee750192ff/src/test/kotlin/org/wfanet/panelmatch/integration/FullWithPreprocessingTest.kt#L104)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Did you figure out what was happening?
</blockquote></details>

As far as I can tell, the delimiter is inserting characters at the beginning that never get removed in the end. That makes me think its a delimiter issue. Its marked as a TODO. I will look into it now but I'd also like to get this PR merged. I can't imagine how its not an existing bug.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/common/ExchangeContext.kt, line 28 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsWCofhCeI78yVT3pVH:-MsebE-73pPNvQcqu4HX:bkuo077) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1aa8a7f10c6cafa0fe55fabaeedbecfe112e218a/src/main/kotlin/org/wfanet/panelmatch/client/common/ExchangeContext.kt#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think this is a misnomer: in practice, the StepContext seems to apply to a particular task type, not a particular step, and certainly not a particular Exchange, since it's made before the daemon even starts running.

Can we discuss the design here? I think I'd prefer just adding additional constructor parameters to `ProductionExchangeTaskMapper`, for example rename `PreprocessStepContext` to `PreprocessEventsParameters` and pass it as a constructor argument to `ProductionExchangeTaskMapper`. Am I missing something here?
</blockquote></details>

redone. per our discussion.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/PreprocessEventsTask.kt, line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsaLMQNC6nx2I7HPIjF:-MseaouZA7dH6MttTv4e:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1aa8a7f10c6cafa0fe55fabaeedbecfe112e218a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/PreprocessEventsTask.kt#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This isn't consistent with how `executePrivateMembershipQueries` and `decryptPrivateMembershipResults` are named -- please remove `Task` 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-05 17:55 UTC, efoxepstein requested changes
> Reviewed 25 of 57 files at r2, 2 of 5 files at r3, 25 of 27 files at r4, 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: 65 of 68 files reviewed, 6 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/common/TaskParameters.kt, line 20 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfLb_i4CiGi3Cj4Md9:-MsfLb_i4CiGi3Cj4MdA:b-t33zuq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/939dadbd8b68e9d4174509173400c9469159f45e/src/main/kotlin/org/wfanet/panelmatch/client/common/TaskParameters.kt#L20)):*
> ```Kotlin
> 
> /** Provides a map to access a task-specific context. */
> class TaskParameters {
> ```

Do we want an immutable version of this? Or maybe a builder?

```
class TaskParameters private constructor(private val underlyingMap: Map<KClass<*>, Any>) {
  class Builder {
    private val map = mutableMapOf<KClass<*>, Any>()
    fun put(value: T): Builder { ... ; return this }
    fun build(): TaskParameters {
      return TaskParameters(map)
    }
  }

 companion object { fun newBuilder(): TaskParameters.Builder { return Builder() } }
}
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/common/TaskParameters.kt, line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfLHx5DYdVJD_r3y4b:-MsfLHx5DYdVJD_r3y4c:b82fd7n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/939dadbd8b68e9d4174509173400c9469159f45e/src/main/kotlin/org/wfanet/panelmatch/client/common/TaskParameters.kt#L31)):*
> ```Kotlin
>   fun <T : Any> get(key: KClass<T>): T? {
>     require(key.isData) { "Task Parameters only store data classes" }
>     val value = underlyingMap[key]
> ```

Can you just do `return underlyingMap[key] as T?`? Or `val value = underlyingMap[key] ?: return null ; return value as T`
___
*[src/main/kotlin/org/wfanet/panelmatch/integration/ExchangeWorkflowDaemonForTest.kt, line 104 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfJrQeEWKo0c_XfIZA:-MsfJrQf7gpbkXZCW4UH:b-gjx86z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/939dadbd8b68e9d4174509173400c9469159f45e/src/main/kotlin/org/wfanet/panelmatch/integration/ExchangeWorkflowDaemonForTest.kt#L104)):*
> ```Kotlin
>     )
> 
>   private val taskContext = TaskParameters().apply { put(preprocessingParameters) }
> ```

Maybe TaskParameters should be immutable and just take in all of its things as constructor parameters?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/common/TaskContextTest.kt, line 30 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfK86a7hyJSpD54ctl:-MsfK86a7hyJSpD54ctm:bkt7u22) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/939dadbd8b68e9d4174509173400c9469159f45e/src/test/kotlin/org/wfanet/panelmatch/client/common/TaskContextTest.kt#L30)):*
> ```Kotlin
> 
> @RunWith(JUnit4::class)
> class TaskContextTest {
> ```

Can you add some test cases that use inheritance? For example:

* Make a dataclass Foo that's a subclass of normal class Bar
* Put a Foo
* Call `get(Bar::class)`
___
*[src/test/kotlin/org/wfanet/panelmatch/client/common/TaskContextTest.kt, line 48 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfKV8Y6L2Ig3ysu9Ih:-MsfKV8Y6L2Ig3ysu9Ii:b-x6zc9w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/939dadbd8b68e9d4174509173400c9469159f45e/src/test/kotlin/org/wfanet/panelmatch/client/common/TaskContextTest.kt#L48)):*
> ```Kotlin
>     val parameters = TaskParameters()
>     parameters.put(TestDataClass1(1))
>     assertThat(parameters.get(TestDataClass2::class)).isEqualTo(null)
> ```

I think `assertThat(foo).isNull()` is clearer


<!-- Sent from Reviewable.io -->

2022-01-05 18:01 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: 65 of 68 files reviewed, 6 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/integration/FullWithPreprocessingTest.kt, line 104 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-Mr9N36V0T0mqv_aX23C:-MsfOiujEzXTjsdia9vT:b-hhr3qd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/64e961517690045da84e78e42b4c92ee750192ff/src/test/kotlin/org/wfanet/panelmatch/integration/FullWithPreprocessingTest.kt#L104)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

As far as I can tell, the delimiter is inserting characters at the beginning that never get removed in the end. That makes me think its a delimiter issue. Its marked as a TODO. I will look into it now but I'd also like to get this PR merged. I can't imagine how its not an existing bug.
</blockquote></details>

this is fixed


<!-- Sent from Reviewable.io -->

2022-01-05 18:20 UTC, efoxepstein requested changes
> Reviewed 1 of 5 files at r3, 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: all files reviewed, 7 unresolved discussions (waiting on @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/integration/FullWithPreprocessingTest.kt, line 95 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfRShl67Uui_Ve6h8e:-MsfRShm0DZCawU5XLkd:b-67aybk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0e9e4df0e841ba5cfa724b756ae47e8e16988ac8/src/test/kotlin/org/wfanet/panelmatch/integration/FullWithPreprocessingTest.kt#L95)):*
> ```Kotlin
>         val payload =
>           it.decryptedEventDataList.flatMap { plaintext ->
>             CombinedEvents.parseFrom(plaintext.payload).serializedEventsList.map { serializedEvent
> ```

It's a little hard for me to follow what's happening here -- maybe add a helper function like:

```
fun parsePayloads(plaintexts: Iterable<DecryptedEventDataOrWhatever>): List<String> {
   ...
}
```


<!-- Sent from Reviewable.io -->

2022-01-05 20:11 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: all files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/common/TaskParameters.kt, line 20 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfLb_i4CiGi3Cj4Md9:-MsfcqfEAIxM3ddd1uMA:brdu6or) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/939dadbd8b68e9d4174509173400c9469159f45e/src/main/kotlin/org/wfanet/panelmatch/client/common/TaskParameters.kt#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Do we want an immutable version of this? Or maybe a builder?

```
class TaskParameters private constructor(private val underlyingMap: Map<KClass<*>, Any>) {
  class Builder {
    private val map = mutableMapOf<KClass<*>, Any>()
    fun put(value: T): Builder { ... ; return this }
    fun build(): TaskParameters {
      return TaskParameters(map)
    }
  }

 companion object { fun newBuilder(): TaskParameters.Builder { return Builder() } }
}
```
</blockquote></details>

I think I prefer an immutable version. lmk what you think.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/common/TaskParameters.kt, line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfLHx5DYdVJD_r3y4b:-MsffRlyBJh5mH5XNkVe:b-1byg9v) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/939dadbd8b68e9d4174509173400c9469159f45e/src/main/kotlin/org/wfanet/panelmatch/client/common/TaskParameters.kt#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you just do `return underlyingMap[key] as T?`? Or `val value = underlyingMap[key] ?: return null ; return value as T`
</blockquote></details>

the former wouldn't work since it can't cast null as T. went with the latter.
___
*[src/main/kotlin/org/wfanet/panelmatch/integration/ExchangeWorkflowDaemonForTest.kt, line 104 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfJrQeEWKo0c_XfIZA:-Msfftta7CwMNR-ajms0:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/939dadbd8b68e9d4174509173400c9469159f45e/src/main/kotlin/org/wfanet/panelmatch/integration/ExchangeWorkflowDaemonForTest.kt#L104)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe TaskParameters should be immutable and just take in all of its things as constructor parameters?
</blockquote></details>

done
___
*[src/test/kotlin/org/wfanet/panelmatch/client/common/TaskContextTest.kt, line 30 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfK86a7hyJSpD54ctl:-MsfidTKBNVBGYS4Td7l:b-iryg4z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/939dadbd8b68e9d4174509173400c9469159f45e/src/test/kotlin/org/wfanet/panelmatch/client/common/TaskContextTest.kt#L30)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you add some test cases that use inheritance? For example:

* Make a dataclass Foo that's a subclass of normal class Bar
* Put a Foo
* Call `get(Bar::class)`
</blockquote></details>

done. It fails trying to access the parent but succeeds accessing the child. do you think I should try to disallow this behavior?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/common/TaskContextTest.kt, line 48 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfKV8Y6L2Ig3ysu9Ih:-MsfaHek7jbCj-6Fels_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/939dadbd8b68e9d4174509173400c9469159f45e/src/test/kotlin/org/wfanet/panelmatch/client/common/TaskContextTest.kt#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think `assertThat(foo).isNull()` is clearer
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/integration/FullWithPreprocessingTest.kt, line 95 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfRShl67Uui_Ve6h8e:-MsfqCKp2GdhcMyBbkM3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0e9e4df0e841ba5cfa724b756ae47e8e16988ac8/src/test/kotlin/org/wfanet/panelmatch/integration/FullWithPreprocessingTest.kt#L95)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's a little hard for me to follow what's happening here -- maybe add a helper function like:

```
fun parsePayloads(plaintexts: Iterable<DecryptedEventDataOrWhatever>): List<String> {
   ...
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-05 20:21 UTC, efoxepstein requested changes
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: all files reviewed, 6 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/common/TaskParameters.kt, line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfLHx5DYdVJD_r3y4b:-MsfshmFCmZwW6RxP25z:b6qpro3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/939dadbd8b68e9d4174509173400c9469159f45e/src/main/kotlin/org/wfanet/panelmatch/client/common/TaskParameters.kt#L31)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

the former wouldn't work since it can't cast null as T. went with the latter.
</blockquote></details>

Why can't you cast `null` as `T?`? https://pl.kotl.in/iYWwaVncK
___
*[src/main/kotlin/org/wfanet/panelmatch/client/common/TaskParameters.kt, line 23 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfrqPBCg0gaSFu-a6J:-MsfrqPBCg0gaSFu-a6K:b5l7dwx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b47c265de60042c5b2faf0482823135a1e3470c9/src/main/kotlin/org/wfanet/panelmatch/client/common/TaskParameters.kt#L23)):*
> ```Kotlin
>   private val underlyingMap: Map<KClass<*>, Any> =
>     parameters
>       .map {
> ```

Cleaner: `parameters.associateBy { it::class to it }`
___
*[src/main/kotlin/org/wfanet/panelmatch/integration/testing/WorkflowTestHelper.kt, line 26 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-Msft6aE2f1Cfdm6Bv7f:-Msft6aE2f1Cfdm6Bv7g:b-ajxu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b47c265de60042c5b2faf0482823135a1e3470c9/src/main/kotlin/org/wfanet/panelmatch/integration/testing/WorkflowTestHelper.kt#L26)):*
> ```Kotlin
> fun parsePlaintextResults(
>   plaintexts: Iterable<KeyedDecryptedEventDataSet>
> ): List<Pair<String, List<String>>> {
> ```

Do you mind making a data class for the Pair return type?
___
*[src/main/kotlin/org/wfanet/panelmatch/integration/testing/WorkflowTestHelper.kt, line 34 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfsvCnBpWa7HoPDHZ8:-MsfsvCnBpWa7HoPDHZ9:b9f69cb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b47c265de60042c5b2faf0482823135a1e3470c9/src/main/kotlin/org/wfanet/panelmatch/integration/testing/WorkflowTestHelper.kt#L34)):*
> ```Kotlin
>         }
>       }
>     requireNotNull(it.plaintextJoinKeyAndId.joinKey).key.toStringUtf8() to payload
> ```

Can you split this line into 2?

```
val joinKey = requireNotNull(it.plaintextJoinKeyAndId.joinKey)
joinKey.key.toStringUtf8() to payload
```
___
*[src/test/kotlin/org/wfanet/panelmatch/client/common/TaskContextTest.kt, line 30 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfK86a7hyJSpD54ctl:-MsftdQx8rrPmwbBj34k:bmr9pqr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/939dadbd8b68e9d4174509173400c9469159f45e/src/test/kotlin/org/wfanet/panelmatch/client/common/TaskContextTest.kt#L30)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

done. It fails trying to access the parent but succeeds accessing the child. do you think I should try to disallow this behavior?
</blockquote></details>

This seems fine to me.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/common/TaskParametersTest.kt, line 52 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsftS873M2GfCVbhTgs:-MsftS873M2GfCVbhTgt:b-h468u7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b47c265de60042c5b2faf0482823135a1e3470c9/src/test/kotlin/org/wfanet/panelmatch/client/common/TaskParametersTest.kt#L52)):*
> ```Kotlin
>   @Test
>   fun readInvalidKey() {
>     assertFails { TaskParameters(setOf(TestDataClass1(1))).get(InvalidClass1::class) }
> ```

Can you move the constructor call out of the `assertFails` so it's clear what's set-up and what's under test?


<!-- Sent from Reviewable.io -->

2022-01-05 21:03 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/common/TaskParameters.kt, line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfLHx5DYdVJD_r3y4b:-MsfxUHf4hRvedxwSKxK:byf8hcr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/939dadbd8b68e9d4174509173400c9469159f45e/src/main/kotlin/org/wfanet/panelmatch/client/common/TaskParameters.kt#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why can't you cast `null` as `T?`? https://pl.kotl.in/iYWwaVncK
</blockquote></details>

I wasn't thinking of a nullable template variable. that is much better. done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/common/TaskParameters.kt, line 23 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfrqPBCg0gaSFu-a6J:-Msg2PFR3syno7AOAJMl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b47c265de60042c5b2faf0482823135a1e3470c9/src/main/kotlin/org/wfanet/panelmatch/client/common/TaskParameters.kt#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Cleaner: `parameters.associateBy { it::class to it }`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/integration/testing/WorkflowTestHelper.kt, line 34 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfsvCnBpWa7HoPDHZ8:-Msfx06qCln7V6Vpd_fo:b-hsw3d5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b47c265de60042c5b2faf0482823135a1e3470c9/src/main/kotlin/org/wfanet/panelmatch/integration/testing/WorkflowTestHelper.kt#L34)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you split this line into 2?

```
val joinKey = requireNotNull(it.plaintextJoinKeyAndId.joinKey)
joinKey.key.toStringUtf8() to payload
```
</blockquote></details>

do you think this is still needed now that its a data class?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/common/TaskParametersTest.kt, line 52 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsftS873M2GfCVbhTgs:-MsfvizG7f1Z6YiWX2es:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b47c265de60042c5b2faf0482823135a1e3470c9/src/test/kotlin/org/wfanet/panelmatch/client/common/TaskParametersTest.kt#L52)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you move the constructor call out of the `assertFails` so it's clear what's set-up and what's under test?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-05 21:37 UTC, efoxepstein approved these changes
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/integration/testing/WorkflowTestHelper.kt, line 34 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/212#-MsfsvCnBpWa7HoPDHZ8:-Msg9uYm4rMOP-WTb48A:bb710yj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b47c265de60042c5b2faf0482823135a1e3470c9/src/main/kotlin/org/wfanet/panelmatch/integration/testing/WorkflowTestHelper.kt#L34)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do you think this is still needed now that its a data class?
</blockquote></details>

Nope


<!-- Sent from Reviewable.io -->

2022-01-05 22:59 UTC, merged