E2E Test passes full workflow
world-federation-of-advertisers/panel-exchange-client pull request #223
Opened 2021-11-24 21:38 UTC by yunyeng

2021-11-24 22:35 UTC, efoxepstein reviewed
> Reviewed 7 of 10 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: all files reviewed, 5 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt, line 132 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpJ3Qt2-Gxj1QrIZmZH:-MpJ3Qt36Md3xaAJZH0U:bd11jpx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7364a2d00617bc11c381c530db8e9dca5a3f56e0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt#L132)):*
> ```Kotlin
>     try {
>       privateStorage.createBlob("$DONE_TASKS_PATH/${step.stepId}", ByteString.EMPTY)
>     } catch (e: Exception) {}
> ```

Why is this necessary?
It feels dangerous to blindly suppress exceptions.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteShardedData.kt, line 102 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpJ3ZxN4ipBhxoD0bnf:-MpJ3ZxO1ov57UEsyaMC:bk651u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7364a2d00617bc11c381c530db8e9dca5a3f56e0/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteShardedData.kt#L102)):*
> ```Kotlin
>         storageClient.getBlob(blobKey)?.delete()
>         storageClient.createBlob(blobKey, messageFlow)
>       } catch (e: Exception) {}
> ```

This seems super dangerous. It could silently fail to write a blob. What is the reason this is needed?
___
*[src/main/kotlin/org/wfanet/panelmatch/common/ShardedFileName.kt, line 38 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpJ3yUy6fEtA_XL6Ace:-MpJ3yUy6fEtA_XL6Acf:bj8zik2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7364a2d00617bc11c381c530db8e9dca5a3f56e0/src/main/kotlin/org/wfanet/panelmatch/common/ShardedFileName.kt#L38)):*
> ```Kotlin
> 
>   init {
>     if (spec.isEmpty()) {
> ```

Maybe just `require(!spec.isEmpty())` instead, it seems like a bug if it's empty.
___
*[src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt, line 167 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpJ4BE24NypjBLOWiw0:-MpJ4BE24NypjBLOWiw1:bceksv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7364a2d00617bc11c381c530db8e9dca5a3f56e0/src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt#L167)):*
> ```Kotlin
> 
>       val steps = getSteps()
>       logStepStates(steps.filter { step -> step.state != ExchangeStep.State.SUCCEEDED })
> ```

Can you do the filtering inside of `logStepStates`? Thanks
___
*[src/test/kotlin/org/wfanet/panelmatch/integration/FullWorkflowTest.kt, line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpJ4JJm66guotNUw4wx:-MpJ4JJm66guotNUw4wy:b-nbee55) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7364a2d00617bc11c381c530db8e9dca5a3f56e0/src/test/kotlin/org/wfanet/panelmatch/integration/FullWorkflowTest.kt#L54)):*
> ```Kotlin
>     mapOf(
>       "mp-plaintext-join-keys" to PLAINTEXT_JOIN_KEYS.toByteString(),
>       "decrypted-event-data" to ByteString.EMPTY,
> ```

Wait, `decrypted-event-data` should be an output I think, not an input


<!-- Sent from Reviewable.io -->

2021-11-24 23:35 UTC, efoxepstein reviewed
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: all files reviewed, 5 unresolved discussions (waiting on @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/integration/FullWorkflowTest.kt, line 49 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpJIQqw7R3VnQZFWEr4:-MpJIQqw7R3VnQZFWEr5:b-azxfab) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/442ea949fb6e78e11ae392982a5bd3124efdf8ab/src/test/kotlin/org/wfanet/panelmatch/integration/FullWorkflowTest.kt#L49)):*
> ```Kotlin
>       "edp-identifier-hash-pepper" to EDP_IDENTIFIER_HASH_PEPPER,
>       "edp-commutative-deterministic-key" to EDP_COMMUTATIVE_DETERMINISTIC_KEY,
>       "edp-encrypted-event-data" to ByteString.EMPTY, // TODO(@efoxepstein): populate this
> ```

We might need to put something here for the test to actually pass.


<!-- Sent from Reviewable.io -->

2021-11-28 23:42 UTC, efoxepstein reviewed
> Reviewed 1 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: 7 of 10 files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt, line 135 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-Mpcuz7k6ZyyNK3h3cfq:-Mpcuz7mETE_QoFRaoEY:b-6afgwv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90cacbd91f2782a3bcaf7c155af7dfaa7200ea39/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt#L135)):*
> ```Kotlin
>     //   This will prevent re-execution of tasks that failed.
>     privateStorage.createBlob(
>       "$DONE_TASKS_PATH/${step.stepId}/${attemptKey.exchangeStepAttemptId}",
> ```

Ah, it's important that this is keyed by just step id, not attempt number, so that of a step finishes, the Kingdom can't accidentally make the client re-execute it.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt, line 148 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpcvCkO9sHvgQiGI-_Q:-MpcvCkO9sHvgQiGI-_R:bfcky2o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90cacbd91f2782a3bcaf7c155af7dfaa7200ea39/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt#L148)):*
> ```Kotlin
>   var blob = getBlob(blobKey)
>   while (blob != null) {
>     blob.delete()
> ```

What is the use case for trying to delete multiple times?


<!-- Sent from Reviewable.io -->

2021-11-28 23:43 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: 7 of 10 files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt, line 132 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpJ3Qt2-Gxj1QrIZmZH:-Mpct03X-F4dVVxmJpiM:brwgd3w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7364a2d00617bc11c381c530db8e9dca5a3f56e0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt#L132)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why is this necessary?
It feels dangerous to blindly suppress exceptions.
</blockquote></details>

I believe if step is succeeded by multiple attempts, it complains.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteShardedData.kt, line 102 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpJ3ZxN4ipBhxoD0bnf:-MpctAqj1RaI4BiuDfdx:blcvluw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7364a2d00617bc11c381c530db8e9dca5a3f56e0/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteShardedData.kt#L102)):*
> ```
> storageClient.getBlob(blobKey)?.delete()
> ```
I think storageClient.getBlob(blobKey)?.delete() doesn't delete successfully.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/ShardedFileName.kt, line 38 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpJ3yUy6fEtA_XL6Ace:-MpctFqj8xQJPTLBhE_F:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7364a2d00617bc11c381c530db8e9dca5a3f56e0/src/main/kotlin/org/wfanet/panelmatch/common/ShardedFileName.kt#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe just `require(!spec.isEmpty())` instead, it seems like a bug if it's empty.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/integration/FullWorkflowTest.kt, line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpJ4JJm66guotNUw4wx:-Mpcu_b9-OVm_YT5qi7U:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7364a2d00617bc11c381c530db8e9dca5a3f56e0/src/test/kotlin/org/wfanet/panelmatch/integration/FullWorkflowTest.kt#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Wait, `decrypted-event-data` should be an output I think, not an input
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/integration/FullWorkflowTest.kt, line 49 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpJIQqw7R3VnQZFWEr4:-MpcubXC6RU3RArtfG1c:bpcku0o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/442ea949fb6e78e11ae392982a5bd3124efdf8ab/src/test/kotlin/org/wfanet/panelmatch/integration/FullWorkflowTest.kt#L49)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

We might need to put something here for the test to actually pass.
</blockquote></details>

I think it requires something that will fit the regex on ShardedFileName.kt file.

baseName-*-of-X

I assume something like; mp-query-to-join-keys-map-0-of-1


<!-- Sent from Reviewable.io -->

2021-11-28 23:56 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: 7 of 10 files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt, line 132 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpJ3Qt2-Gxj1QrIZmZH:-MpcyM951TxRGo85vwr1:b2wky7z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7364a2d00617bc11c381c530db8e9dca5a3f56e0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt#L132)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

I believe if step is succeeded by multiple attempts, it complains.
</blockquote></details>

Only one attempt for a step should succeed. If multiple are, something is wrong.


<!-- Sent from Reviewable.io -->

2021-11-29 01:32 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: 7 of 10 files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteShardedData.kt, line 102 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpJ3ZxN4ipBhxoD0bnf:-MpdJOc_3mrulQJPb7Ub:b-irbfd3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7364a2d00617bc11c381c530db8e9dca5a3f56e0/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteShardedData.kt#L102)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

> ```
> storageClient.getBlob(blobKey)?.delete()
> ```
I think storageClient.getBlob(blobKey)?.delete() doesn't delete successfully.
</blockquote></details>

That sounds like a bug we should figure out
___
*[src/test/kotlin/org/wfanet/panelmatch/integration/FullWorkflowTest.kt, line 49 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpJIQqw7R3VnQZFWEr4:-MpdItaI4SgJ220t7z75:bqog80t) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/442ea949fb6e78e11ae392982a5bd3124efdf8ab/src/test/kotlin/org/wfanet/panelmatch/integration/FullWorkflowTest.kt#L49)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

I think it requires something that will fit the regex on ShardedFileName.kt file.

baseName-*-of-X

I assume something like; mp-query-to-join-keys-map-0-of-1
</blockquote></details>

Agreed


<!-- Sent from Reviewable.io -->

2021-11-29 17:57 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: 7 of 10 files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteShardedData.kt, line 101 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-Mpgnm-y8zFqyto7eTli:-Mpgnm-y8zFqyto7eTlj:bwk7tk1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90cacbd91f2782a3bcaf7c155af7dfaa7200ea39/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteShardedData.kt#L101)):*
> ```Kotlin
>     runBlocking(Dispatchers.IO) {
>       storageClient.deleteBlob(blobKey)
>       storageClient.createBlob(blobKey, messageFlow)
> ```

We should make helper functions:

```
suspend fun StorageClient.createOrReplaceBlob(blobKey: String, contents: Flow<ByteString>): Blob {
  getBlob(blobKey)?.delete()
  createBlob(blobKey, contents)
}

suspend fun StorageClient.createOrReplaceBlob(blobKey: String, contents: ByteString): Blob {
  getBlob(blobKey)?.delete()
  createBlob(blobKey, contents)
}
```
___
*[src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt, line 143 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpgoMwE9ApBHx75s4QC:-MpgoMwE9ApBHx75s4QD:b-cwrxux) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90cacbd91f2782a3bcaf7c155af7dfaa7200ea39/src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt#L143)):*
> ```Kotlin
>     val stepsList = exchangeWorkflow.stepsList
>     logger.info(
>       steps.filter { step -> step.state != ExchangeStep.State.SUCCEEDED }.joinToString("\n") {
> ```

How about:

```
val stepsByState = steps.groupBy { it.state }
val message = StringBuilder("ExchangeStep states:")
for ((state, stepsForState) in steps.groupBy { it.state }) {
  val stepsString =
    stepsForState
      .sortedBy { it.stepIndex }
      .joinToString(", ") { "${stepsList[it.stepIndex].stepId}#${it.stepIndex}" }
  message.appendLine("  $state: ${stepsString}")
}
logger.info(message)
```


<!-- Sent from Reviewable.io -->

2021-11-29 18:34 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: 4 of 11 files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteShardedData.kt, line 101 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-Mpgnm-y8zFqyto7eTli:-MpgyUrU-9589PPGtS_P:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90cacbd91f2782a3bcaf7c155af7dfaa7200ea39/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteShardedData.kt#L101)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

We should make helper functions:

```
suspend fun StorageClient.createOrReplaceBlob(blobKey: String, contents: Flow<ByteString>): Blob {
  getBlob(blobKey)?.delete()
  createBlob(blobKey, contents)
}

suspend fun StorageClient.createOrReplaceBlob(blobKey: String, contents: ByteString): Blob {
  getBlob(blobKey)?.delete()
  createBlob(blobKey, contents)
}
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt, line 143 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpgoMwE9ApBHx75s4QC:-MpgyTsU3ltzW7xWYEdl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90cacbd91f2782a3bcaf7c155af7dfaa7200ea39/src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt#L143)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How about:

```
val stepsByState = steps.groupBy { it.state }
val message = StringBuilder("ExchangeStep states:")
for ((state, stepsForState) in steps.groupBy { it.state }) {
  val stepsString =
    stepsForState
      .sortedBy { it.stepIndex }
      .joinToString(", ") { "${stepsList[it.stepIndex].stepId}#${it.stepIndex}" }
  message.appendLine("  $state: ${stepsString}")
}
logger.info(message)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-29 18:55 UTC, efoxepstein requested changes
> Reviewed 2 of 4 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: all files reviewed, 4 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/CreateOrReplaceBlob.kt, line 23 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-Mph1z2a27Cp0EDDfIRb:-Mph1z2a27Cp0EDDfIRc:b-rltfbc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bd16608fe4c4f05094fae9cd130476aeb2a066ca/src/main/kotlin/org/wfanet/panelmatch/client/storage/CreateOrReplaceBlob.kt#L23)):*
> ```Kotlin
> import org.wfanet.measurement.storage.StorageClient.Blob
> 
> suspend fun StorageClient.createOrReplaceBlob(blobKey: String, contents: Flow<ByteString>): Blob {
> ```

Kdoc please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/CreateOrReplaceBlob.kt, line 23 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-Mph21T9DfOphTvAJvC0:-Mph21T9DfOphTvAJvC1:b1c3rac) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bd16608fe4c4f05094fae9cd130476aeb2a066ca/src/main/kotlin/org/wfanet/panelmatch/client/storage/CreateOrReplaceBlob.kt#L23)):*
> ```Kotlin
> import org.wfanet.measurement.storage.StorageClient.Blob
> 
> suspend fun StorageClient.createOrReplaceBlob(blobKey: String, contents: Flow<ByteString>): Blob {
> ```

Unit test please: can you make an abstract base test class in src/main/kotlin/org/wfanet/panelmatch/client/storage/testing/ and then make a FileSystemCreateOrReplaceBlobTest to see if the issue reproduces?
___
*[src/test/kotlin/org/wfanet/panelmatch/integration/FullWorkflowTest.kt, line 49 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpJIQqw7R3VnQZFWEr4:-Mph1q5-6X8yWSFLqb26:b-i76ljn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/442ea949fb6e78e11ae392982a5bd3124efdf8ab/src/test/kotlin/org/wfanet/panelmatch/integration/FullWorkflowTest.kt#L49)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Agreed
</blockquote></details>

Done in #224 


<!-- Sent from Reviewable.io -->

2021-11-29 19:40 UTC, efoxepstein reviewed
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: all files reviewed, 2 unresolved discussions (waiting on @yunyeng)



<!-- Sent from Reviewable.io -->

2021-11-30 00:25 UTC, efoxepstein approved these changes
> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt, line 132 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpJ3Qt2-Gxj1QrIZmZH:-MpiDt5y-E_-LX3YfBCR:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7364a2d00617bc11c381c530db8e9dca5a3f56e0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt#L132)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Only one attempt for a step should succeed. If multiple are, something is wrong.
</blockquote></details>

Done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt, line 135 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-Mpcuz7k6ZyyNK3h3cfq:-MpiDsILDbcyXhDvTRgw:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90cacbd91f2782a3bcaf7c155af7dfaa7200ea39/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt#L135)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ah, it's important that this is keyed by just step id, not attempt number, so that of a step finishes, the Kingdom can't accidentally make the client re-execute it.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-11-30 00:26 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt, line 132 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MpJ3Qt2-Gxj1QrIZmZH:-MpiDbyDDCm-NME4h3kN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7364a2d00617bc11c381c530db8e9dca5a3f56e0/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt#L132)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Only one attempt for a step should succeed. If multiple are, something is wrong.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt, line 135 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-Mpcuz7k6ZyyNK3h3cfq:-MpiDcbR3gl6HNei71ix:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90cacbd91f2782a3bcaf7c155af7dfaa7200ea39/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt#L135)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ah, it's important that this is keyed by just step id, not attempt number, so that of a step finishes, the Kingdom can't accidentally make the client re-execute it.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/CreateOrReplaceBlob.kt, line 23 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-Mph1z2a27Cp0EDDfIRb:-MpiDtaw9ht7mnori6eJ:bhephqc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bd16608fe4c4f05094fae9cd130476aeb2a066ca/src/main/kotlin/org/wfanet/panelmatch/client/storage/CreateOrReplaceBlob.kt#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Kdoc please
</blockquote></details>

Taken care in #225 
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/CreateOrReplaceBlob.kt, line 23 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-Mph21T9DfOphTvAJvC0:-MpiDv7e71p2DjteNNQf:bhephqc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bd16608fe4c4f05094fae9cd130476aeb2a066ca/src/main/kotlin/org/wfanet/panelmatch/client/storage/CreateOrReplaceBlob.kt#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Unit test please: can you make an abstract base test class in src/main/kotlin/org/wfanet/panelmatch/client/storage/testing/ and then make a FileSystemCreateOrReplaceBlobTest to see if the issue reproduces?
</blockquote></details>

Taken care in #225 


<!-- Sent from Reviewable.io -->

2021-11-30 00:27 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-11-30 00:30 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-11-30 03:30 UTC, efoxepstein approved these changes
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-11-30 15:13 UTC, stevenwarejones requested changes
> Reviewed 1 of 10 files at r1, 1 of 2 files at r2, 1 of 4 files at r5, 4 of 7 files at r8, 1 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/integration/config/full_exchange_workflow.textproto, line 355 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MplOswmBfut9B3dst_u:-MplOswmBfut9B3dst_v:b-ibf0k5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4b3c88469d37f8734697884f0ddf3c9daf1e034c/src/test/kotlin/org/wfanet/panelmatch/integration/config/full_exchange_workflow.textproto#L355)):*
> ```
> 
>   execute_private_membership_queries_step {
>     serialized_parameters: "\n\006\b\001\020\n\030\001\022#\n\020\201\300\270\377\377\377\377\377\377\001\377\377\377\377\377\003\022\003\201\300}\030\f \001(\b0\0028\004@\n"
> ```

feels a little weird to put this serialized data here. Any other way we can do this?
___
*[src/test/kotlin/org/wfanet/panelmatch/integration/config/full_exchange_workflow.textproto, line 397 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MplP-vf1Sblpz5fxTRZ:-MplP-vf1Sblpz5fxTR_:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4b3c88469d37f8734697884f0ddf3c9daf1e034c/src/test/kotlin/org/wfanet/panelmatch/integration/config/full_exchange_workflow.textproto#L397)):*
> ```
> 
>   decrypt_private_membership_query_results_step {
>     serialized_parameters: "\n\006\b\001\020\n\030\001\022#\n\020\201\300\270\377\377\377\377\377\377\001\377\377\377\377\377\003\022\003\201\300}\030\f \001(\b0\0028\004@\n"
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-11-30 15:19 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @stevenwarejones, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/integration/config/full_exchange_workflow.textproto, line 355 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MplOswmBfut9B3dst_u:-MplPr0sDS_5dUNQCxjk:b-4voykz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4b3c88469d37f8734697884f0ddf3c9daf1e034c/src/test/kotlin/org/wfanet/panelmatch/integration/config/full_exchange_workflow.textproto#L355)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

feels a little weird to put this serialized data here. Any other way we can do this?
</blockquote></details>

Do you have any ideas for alternatives? We can inject it at runtime but that gets a little awkward too


<!-- Sent from Reviewable.io -->

2021-11-30 16:48 UTC, stevenwarejones requested changes
> Reviewed 1 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/integration/config/full_exchange_workflow.textproto, line 355 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MplOswmBfut9B3dst_u:-MpljoSfBEVP8fkvG5a7:brfugaz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4b3c88469d37f8734697884f0ddf3c9daf1e034c/src/test/kotlin/org/wfanet/panelmatch/integration/config/full_exchange_workflow.textproto#L355)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Do you have any ideas for alternatives? We can inject it at runtime but that gets a little awkward too
</blockquote></details>

can you put a comment in with what the unserialized values are?


<!-- Sent from Reviewable.io -->

2021-11-30 17:28 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/integration/config/full_exchange_workflow.textproto, line 355 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MplOswmBfut9B3dst_u:-MplsqhT3RT62s3qF9YM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4b3c88469d37f8734697884f0ddf3c9daf1e034c/src/test/kotlin/org/wfanet/panelmatch/integration/config/full_exchange_workflow.textproto#L355)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you put a comment in with what the unserialized values are?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/integration/config/full_exchange_workflow.textproto, line 397 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223#-MplP-vf1Sblpz5fxTRZ:-Mplsr8i7EEIAFEBFrFD:bjs7dm0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4b3c88469d37f8734697884f0ddf3c9daf1e034c/src/test/kotlin/org/wfanet/panelmatch/integration/config/full_exchange_workflow.textproto#L397)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Currently, all the serialized_parameters are same. Let me know if necessary to duplicate same comment on all of them.


<!-- Sent from Reviewable.io -->

2021-11-30 18:45 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-11-30 20:37 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/223)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @duliomatos1)



<!-- Sent from Reviewable.io -->

2021-11-30 20:42 UTC, merged