Group related Exchange Tasks
world-federation-of-advertisers/panel-exchange-client pull request #235
Opened 2021-12-07 07:51 UTC by yunyeng

2021-12-07 15:19 UTC, efoxepstein reviewed
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 21 unresolved discussions (waiting on @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKT_Wd8ejAlBdhwZix:-MqKT_We-UJMU8gYpPFq:b4etlc1) (no related file):*
This is great! Almost there, just a few minor comments

---
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt, line 88 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKQvzM25C0Qn-mGmLf:-MqKQvzM25C0Qn-mGmLg:b-uuaadw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt#L88)):*
> ```Kotlin
>   }
> 
>   override val exchangeTaskMapper: ExchangeTaskMapper = ProductionExchangeTaskMapperTaskMapper(
> ```

`by lazy` please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTasks.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKR61D4_xTPg6TF7J-:-MqKR61E9nXguYrsGkVx:benrjbg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTasks.kt#L23)):*
> ```Kotlin
> 
>   override suspend fun ExchangeContext.getBuildPrivateMembershipQueriesTask(
>     getPrivateMembershipCryptor: (ByteString) -> PrivateMembershipCryptor
> ```

Can you move this to the constructor of `ApacheBeamTasks` please?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTasks.kt, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKRIqO7OgLC_QFlnZD:-MqKRIqO7OgLC_QFlnZE:b-qjt19k) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTasks.kt#L49)):*
> ```Kotlin
> 
>   override suspend fun ExchangeContext.getExecutePrivateMembershipQueriesTask(
>     getQueryResultsEvaluator: (ByteString) -> QueryEvaluator
> ```

Ditto, please move to the constructor
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTasks.kt, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKRLW14_XwcE26wXWf:-MqKRLW14_XwcE26wXWg:b-qjt19k) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTasks.kt#L71)):*
> ```Kotlin
> 
>   override suspend fun ExchangeContext.getDecryptMembershipResultsTask(
>     queryResultsDecryptor: QueryResultsDecryptor
> ```

Ditto, please move to the constructor
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/BasicTasks.kt, line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKRS-QDgRNw0wldXnh:-MqKRS-QDgRNw0wldXni:byhc13l) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/BasicTasks.kt#L5)):*
> ```Kotlin
> import org.wfanet.panelmatch.client.common.ExchangeContext
> 
> interface BasicTasks {
> ```

Maybe `ValidationTasks`?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKReV8BsrI4vVRhqSV:-MqKReV8BsrI4vVRhqSW:bx4ksqg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L40)):*
> ```Kotlin
>   private val sharedStorageTasks: SharedStorageTasks
> ) :
>   BasicTasks by basicTasks,
> ```

I think it will be simpler to remove all of this inheritance. Instead, we can just rely on composition. But you'll need to replace `fun ExchangeContext.foo()` with `fun foo(context: ExchangeContext)` in all the interfaces....
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKSOoc-h4HeIOEFlvR:-MqKSOoc-h4HeIOEFlvS:b-mmu9vi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L47)):*
> ```Kotlin
>   GenerateKeysTasks by generateKeysTasks {
> 
>   abstract val deterministicCommutativeCryptor: DeterministicCommutativeCipher
> ```

We should be able to delete ALL of these abstract vals
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKS6P74vwpsAUfZxeJ:-MqKS6P74vwpsAUfZxeK:b-egf0xk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L60)):*
> ```Kotlin
>   }
> 
>   private suspend fun ExchangeContext.getExchangeTask(): ExchangeTask {
> ```

I think you can now combine this function with the one above:

```
suspend fun getExchangeTaskForStep(context: ExchangeContext): ExchangeTask {
  return when (step.stepCase) {
    StepCase.ENCRYPT_STEP -> commutativeEncryptionTasks.buildEncryptTask(context)
    ...
}

```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 63 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKRu7h2ytc92fjUa0S:-MqKRu7h2ytc92fjUa0T:bx5iduy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L63)):*
> ```Kotlin
>     @Suppress("WHEN_ENUM_CAN_BE_NULL_IN_JAVA")
>     return when (step.stepCase) {
>       StepCase.ENCRYPT_STEP -> CryptorExchangeTask.forEncryption(deterministicCommutativeCryptor)
> ```

This should be `commutativeEncryptionExchangeTasks.buildEncryptTask(this)` (ditto below)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasks.kt, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKSYJX9Zdn4G7qSgWM:-MqKSYJX9Zdn4G7qSgWN:b-w4aw6s) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasks.kt#L12)):*
> ```Kotlin
> 
>   fun getGenerateSymmetricKeyTask(
>     deterministicCommutativeCryptor: DeterministicCommutativeCipher
> ```

Remove this parameter please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasks.kt, line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKS_a25ifk7Jx-MEYZ:-MqKS_a25ifk7Jx-MEY_:b-tta9ru) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasks.kt#L18)):*
> ```Kotlin
> 
>   fun ExchangeContext.getGenerateSerializedRlweKeysStepTask(
>     getPrivateMembershipCryptor: (ByteString) -> PrivateMembershipCryptor
> ```

Remove this parameter please (and [...]

2021-12-07 19:32 UTC, efoxepstein reviewed
> Reviewed 4 of 19 files at r2, 17 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: 22 of 27 files reviewed, 22 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt, line 121 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqLMp0b5g2mEDjyr8h4:-MqLMp0b5g2mEDjyr8h5:bs0de8l) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8f8225b7a43a8c9d39ceebca1554829d501a8926/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt#L121)):*
> ```Kotlin
>   }
> 
>   override val throttler: Throttler by lazy {
> ```

Revert this please


<!-- Sent from Reviewable.io -->

2021-12-07 19:37 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: 22 of 27 files reviewed, 23 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperTest.kt, line 60 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqLN_zLE5WoPw22t69m:-MqLN_zMABL2J2Kaggx4:bf16dpj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1500f9bb2ddda233aa5f84a6d5a78b2ecde9b9aa/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperTest.kt#L60)):*
> ```Kotlin
>   private val testPrivateStorageSelector = TestPrivateStorageSelector()
>   private val exchangeTaskMapper =
>     ExchangeTaskMapper(
> ```

We can simplify this with fakes:

```
class FakeExchangeTask(val name: String): ExchangeTask { ... }

class FakeMapReduceTasks : MapReduceTasks {
  override fun foo(): ExchangeTask = FakeExchangeTask("foo")
}

...
```


<!-- Sent from Reviewable.io -->

2021-12-07 19:38 UTC, efoxepstein reviewed
> Reviewed 2 of 19 files at r2, 1 of 18 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 24 unresolved discussions (waiting on @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 102 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqLOpytCZns8XRCe-Iw:-MqLOpytCZns8XRCe-Ix:bjob39l) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1500f9bb2ddda233aa5f84a6d5a78b2ecde9b9aa/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L102)):*
> ```Kotlin
> 
>   private val exchangeTaskMapper =
>     ExchangeTaskMapper(
> ```

This also could benefit from the fake ExchangeTaskMapper I mentioned above, so maybe put it into a test helper library?


<!-- Sent from Reviewable.io -->

2021-12-07 19:42 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 24 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt, line 88 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKQvzM25C0Qn-mGmLf:-MqLPSql2EDzcRV6pOXL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt#L88)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`by lazy` please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt, line 121 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqLMp0b5g2mEDjyr8h4:-MqLPTWp9Ii9YEKrV0hK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8f8225b7a43a8c9d39ceebca1554829d501a8926/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt#L121)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Revert this please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTasks.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKR61D4_xTPg6TF7J-:-MqLPUd82DJuz3ZTYjmS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTasks.kt#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you move this to the constructor of `ApacheBeamTasks` please?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTasks.kt, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKRIqO7OgLC_QFlnZD:-MqLPV2h0oNn8CeAYxqe:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTasks.kt#L49)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto, please move to the constructor
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTasks.kt, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKRLW14_XwcE26wXWf:-MqLPVUZ4U10N1ZLiw2a:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamTasks.kt#L71)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto, please move to the constructor
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKSOoc-h4HeIOEFlvR:-MqLPW_tEtoYNE_eHCRd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

We should be able to delete ALL of these abstract vals
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKS6P74vwpsAUfZxeJ:-MqLPXN83Zy7tGeqnLg-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L60)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think you can now combine this function with the one above:

```
suspend fun getExchangeTaskForStep(context: ExchangeContext): ExchangeTask {
  return when (step.stepCase) {
    StepCase.ENCRYPT_STEP -> commutativeEncryptionTasks.buildEncryptTask(context)
    ...
}

```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 63 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKRu7h2ytc92fjUa0S:-MqLPXvL3RKX-rQCwxjL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L63)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This should be `commutativeEncryptionExchangeTasks.buildEncryptTask(this)` (ditto below)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasks.kt, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKSYJX9Zdn4G7qSgWM:-MqLPYpwDzo7QXaLV_QP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasks.kt#L12)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Remove this parameter please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasks.kt, line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKS_a25ifk7Jx-MEYZ:-MqLPZR_3__4DdiT_ZoG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasks.kt#L18)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Remove this parameter please (and put into constructor in impl)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasks.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKSatAAM2-Fvy73UmC:-MqLPZl78jPtmRU3veB7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasks.kt#L22)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Remove this parameter please (and put into constructor in impl)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasksImpl.kt, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKScnwE2C7eChjzI-x:-MqLP_P21_ol1qkSOLX7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasksImpl.kt#L16)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></s [...]

2021-12-08 01:17 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: 12 of 36 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqKReV8BsrI4vVRhqSV:-MqMbQRs2KrqMvwW_4FP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/865c5d8d7600407bc3f2e4981fec9504e6471244/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think it will be simpler to remove all of this inheritance. Instead, we can just rely on composition. But you'll need to replace `fun ExchangeContext.foo()` with `fun foo(context: ExchangeContext)` in all the interfaces....
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 102 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqLOpytCZns8XRCe-Iw:-MqMbTYH-ZN0boEHpUwO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1500f9bb2ddda233aa5f84a6d5a78b2ecde9b9aa/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L102)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This also could benefit from the fake ExchangeTaskMapper I mentioned above, so maybe put it into a test helper library?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperTest.kt, line 60 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqLN_zLE5WoPw22t69m:-MqMbSi88hBcGBjVrcKq:bkiq237) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1500f9bb2ddda233aa5f84a6d5a78b2ecde9b9aa/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperTest.kt#L60)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

We can simplify this with fakes:

```
class FakeExchangeTask(val name: String): ExchangeTask { ... }

class FakeMapReduceTasks : MapReduceTasks {
  override fun foo(): ExchangeTask = FakeExchangeTask("foo")
}

...
```
</blockquote></details>

Don't we want the real mapper here though?


<!-- Sent from Reviewable.io -->

2021-12-08 01:36 UTC, efoxepstein requested changes
> Reviewed 15 of 24 files at r5, 1 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: 28 of 36 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/PrivateStorageTasksImpl.kt, line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqMeiW711IytgyOzoAV:-MqMeiW87Xe0BBq6fZlh:b-aycdsk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c10031849a9487f4d972ebcd9be18be244d82cef/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/PrivateStorageTasksImpl.kt#L27)):*
> ```Kotlin
>   private val inputTaskThrottler: Throttler
> ) : PrivateStorageTasks {
>   override suspend fun getInput(context: ExchangeContext): ExchangeTask {
> ```

Maybe just input?


<!-- Sent from Reviewable.io -->

2021-12-08 02:20 UTC, efoxepstein requested changes
> Reviewed 2 of 24 files at r5, 6 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 102 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqLOpytCZns8XRCe-Iw:-MqMolLA6DpVKJ5rvKyC:b-9tqmxu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1500f9bb2ddda233aa5f84a6d5a78b2ecde9b9aa/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L102)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe add a helper function to make this ExchangeTaskMapper too?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperTest.kt, line 60 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqLN_zLE5WoPw22t69m:-MqMpYIM3pyXb1rNFe52:b-lxitz6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1500f9bb2ddda233aa5f84a6d5a78b2ecde9b9aa/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperTest.kt#L60)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Don't we want the real mapper here though?
</blockquote></details>

I think we just want to make sure the switch statement calls the right function. So the fake should work fine.


<!-- Sent from Reviewable.io -->

2021-12-08 17:56 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: 26 of 39 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/PrivateStorageTasksImpl.kt, line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqMeiW711IytgyOzoAV:-MqQB24U5re2UBqq-3Lh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c10031849a9487f4d972ebcd9be18be244d82cef/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/PrivateStorageTasksImpl.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe just input?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 102 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqLOpytCZns8XRCe-Iw:-MqQB7V58WJrcNrMUHoV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1500f9bb2ddda233aa5f84a6d5a78b2ecde9b9aa/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L102)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe add a helper function to make this ExchangeTaskMapper too?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperTest.kt, line 60 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqLN_zLE5WoPw22t69m:-MqQB4y6DkgM3i1jTQNq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1500f9bb2ddda233aa5f84a6d5a78b2ecde9b9aa/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperTest.kt#L60)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think we just want to make sure the switch statement calls the right function. So the fake should work fine.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-08 18:08 UTC, efoxepstein requested changes
> Reviewed 13 of 13 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCryptorExchangeTask.kt, line 25 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqQDBxZ8wvx_lSFgeXq:-MqQDBxZ8wvx_lSFgeXr:brfwil9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d91c199f60d26adaae9e56de1b97316b81d6e66f/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCryptorExchangeTask.kt#L25)):*
> ```Kotlin
> import org.wfanet.panelmatch.common.storage.toStringUtf8
> 
> class FakeCryptorExchangeTask(val task: String) : ExchangeTask {
> ```

Why do we need this? Can we just use `FakeExchangeTask` for everything? In the test you can just `assertThat(task.task).isEqualTo("decrypt-task")` or something. (Also, maybe rename `val task` to `val taskName`)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeInputTask.kt, line 25 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqQDSWS7y1orL9-kAYd:-MqQDSWS7y1orL9-kAYe:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d91c199f60d26adaae9e56de1b97316b81d6e66f/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeInputTask.kt#L25)):*
> ```Kotlin
> import org.wfanet.panelmatch.common.storage.toStringUtf8
> 
> class FakeInputTask(val task: String) : ExchangeTask {
> ```

Ditto
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 69 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqQDoxL3AikcyMA5yFY:-MqQDoxL3AikcyMA5yFZ:b-qswuux) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d91c199f60d26adaae9e56de1b97316b81d6e66f/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L69)):*
> ```Kotlin
>   }
> 
>   private val exchangeTaskMapper = makeExchangeTaskMapper()
> ```

`makeFakeExchangeTaskMapper()`?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperTest.kt, line 69 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqQDXGf7nk7M6gv2U-r:-MqQDXGf7nk7M6gv2U-s:b-klwx0y) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d91c199f60d26adaae9e56de1b97316b81d6e66f/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperTest.kt#L69)):*
> ```Kotlin
>     val context = ExchangeContext(ATTEMPT_KEY, DATE, WORKFLOW, WORKFLOW.getSteps(0))
>     val exchangeTask = exchangeTaskMapper.getExchangeTaskForStep(context)
>     assertThat(exchangeTask).isInstanceOf(FakeInputTask::class.java)
> ```

You can `assertThat(exchangeTask).isInstanceOf(FakeExchangeTask::class.java)` and then `assertThat((exchangeTask as FakeExchangeTask).taskName).isEqualTo("input")`


<!-- Sent from Reviewable.io -->

2021-12-08 18:16 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: 29 of 39 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt, line 69 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqQDoxL3AikcyMA5yFY:-MqQFeLg1625nUrbyNY-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d91c199f60d26adaae9e56de1b97316b81d6e66f/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorTest.kt#L69)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`makeFakeExchangeTaskMapper()`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCryptorExchangeTask.kt, line 25 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqQDBxZ8wvx_lSFgeXq:-MqQFfMD3XQ-m587-g4d:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d91c199f60d26adaae9e56de1b97316b81d6e66f/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCryptorExchangeTask.kt#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why do we need this? Can we just use `FakeExchangeTask` for everything? In the test you can just `assertThat(task.task).isEqualTo("decrypt-task")` or something. (Also, maybe rename `val task` to `val taskName`)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeInputTask.kt, line 25 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqQDSWS7y1orL9-kAYd:-MqQFg3S--kiV0NQ7bMk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d91c199f60d26adaae9e56de1b97316b81d6e66f/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeInputTask.kt#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperTest.kt, line 69 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqQDXGf7nk7M6gv2U-r:-MqQFdKe0kBxLSPC6yNS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d91c199f60d26adaae9e56de1b97316b81d6e66f/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperTest.kt#L69)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

You can `assertThat(exchangeTask).isInstanceOf(FakeExchangeTask::class.java)` and then `assertThat((exchangeTask as FakeExchangeTask).taskName).isEqualTo("input")`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-08 18:18 UTC, efoxepstein approved these changes
> Reviewed 10 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)



<!-- Sent from Reviewable.io -->

2021-12-08 23:22 UTC, efoxepstein approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 1 unresolved discussion (waiting on @mpatel24, @stevenwarejones, and @yunyeng)



<!-- Sent from Reviewable.io -->

2021-12-09 22:15 UTC, stevenwarejones requested changes
> Reviewed 1 of 19 files at r2, 1 of 2 files at r4, 1 of 24 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 4 unresolved discussions (waiting on @mpatel24 and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt, line 40 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqWFIOY9l4RcDfavpq-:-MqWFIOY9l4RcDfavpq0:bowdc17) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a09c8ae1ed69190148f97753b04cb3cd3a0abed1/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt#L40)):*
> ```Kotlin
>   certificateManager: CertificateManager,
>   pipelineOptions: PipelineOptions
> ): ExchangeTaskMapper {
> ```

why not just extend the base class?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt, line 43 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqWFWAs4vfEQqE4RQNz:-MqWFWAs4vfEQqE4RQO-:b-xs7pxj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a09c8ae1ed69190148f97753b04cb3cd3a0abed1/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt#L43)):*
> ```Kotlin
>   return ExchangeTaskMapper(
>     validationTasks = ValidationTasksImpl(),
>     commutativeEncryptionTasks = JniCommutativeEncryptionTasks(JniDeterministicCommutativeCipher()),
> ```

this should just be called `commutativeEncryptionTasks`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 21 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqWFmos8gUR8fWWbyHg:-MqWFmos8gUR8fWWbyHh:bfxori2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a09c8ae1ed69190148f97753b04cb3cd3a0abed1/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L21)):*
> ```Kotlin
> 
> /** Maps join key exchange steps to exchange tasks */
> class ExchangeTaskMapper(
> ```

@efoxepstein - since companies are writing their own mappers and daemons, can we try to get those two interfaces pretty stable?


<!-- Sent from Reviewable.io -->

2021-12-09 22:17 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 4 unresolved discussions (waiting on @mpatel24, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt, line 40 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqWFIOY9l4RcDfavpq-:-MqWGOGl9FXmB2Wgh5Se:bze2a8d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a09c8ae1ed69190148f97753b04cb3cd3a0abed1/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt#L40)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why not just extend the base class?
</blockquote></details>

Composition > Inheritance


<!-- Sent from Reviewable.io -->

2021-12-10 18:05 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 4 unresolved discussions (waiting on @mpatel24, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt, line 43 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqWFWAs4vfEQqE4RQNz:-Mq_W9mA1Don9vsq9Jh6:bmzck6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a09c8ae1ed69190148f97753b04cb3cd3a0abed1/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt#L43)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this should just be called `commutativeEncryptionTasks`
</blockquote></details>

Do you mean class name CommutativeEncryptionTasksImpl instead of JniCommutativeEncryptionTasks ?


<!-- Sent from Reviewable.io -->

2021-12-10 19:51 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 4 unresolved discussions (waiting on @mpatel24, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt, line 43 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqWFWAs4vfEQqE4RQNz:-Mq_tPtY5E41IzpIUaT6:batib7q) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a09c8ae1ed69190148f97753b04cb3cd3a0abed1/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt#L43)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Do you mean class name CommutativeEncryptionTasksImpl instead of JniCommutativeEncryptionTasks ?
</blockquote></details>

That makes sense to me because it can work with any DeterminsiticCommutativeCipher, not just the JNI one. +1


<!-- Sent from Reviewable.io -->

2021-12-10 20:29 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: 36 of 39 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @mpatel24, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt, line 43 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqWFWAs4vfEQqE4RQNz:-Mqa1GVJ57t_yZyEmI6_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a09c8ae1ed69190148f97753b04cb3cd3a0abed1/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

That makes sense to me because it can work with any DeterminsiticCommutativeCipher, not just the JNI one. +1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-10 20:31 UTC, efoxepstein approved these changes
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 4 unresolved discussions (waiting on @mpatel24, @stevenwarejones, and @yunyeng)



<!-- Sent from Reviewable.io -->

2021-12-10 20:31 UTC, stevenwarejones requested changes
> Reviewed 2 of 24 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 5 unresolved discussions (waiting on @mpatel24, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/MapReduceTasks.kt, line 24 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa1ZBPDZZDqdEd66vL:-Mqa1ZBQ6XOXvmOYR1-V:b-vj0j0k) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a09c8ae1ed69190148f97753b04cb3cd3a0abed1/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/MapReduceTasks.kt#L24)):*
> ```Kotlin
>   suspend fun executePrivateMembershipQueries(context: ExchangeContext): ExchangeTask
> 
>   suspend fun decryptMembershipResults(context: ExchangeContext): ExchangeTask
> ```

what if a company only wants to implement some of these in a custom mapreduce way?


<!-- Sent from Reviewable.io -->

2021-12-10 20:44 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 5 unresolved discussions (waiting on @mpatel24, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/MapReduceTasks.kt, line 24 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa1ZBPDZZDqdEd66vL:-Mqa3wxn3ALXiRh40G40:b6dsg34) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a09c8ae1ed69190148f97753b04cb3cd3a0abed1/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/MapReduceTasks.kt#L24)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what if a company only wants to implement some of these in a custom mapreduce way?
</blockquote></details>

If an Exchange Step is map reduce related, don't they need all three tasks? Maybe we can introduce a very simple top interface like;

interface ExchangeTasks {
    fun build(): ExchangeTask
}

WDYT?


<!-- Sent from Reviewable.io -->

2021-12-10 20:51 UTC, stevenwarejones requested changes
> Reviewed 1 of 21 files at r1, 3 of 18 files at r3, 5 of 24 files at r5, 4 of 7 files at r6, 5 of 13 files at r7, 7 of 10 files at r8, 1 of 2 files at r9, 2 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 8 unresolved discussions (waiting on @mpatel24, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasksImpl.kt, line 29 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa5M5H6TAZ2g3Sqp0c:-Mqa5M5H6TAZ2g3Sqp0d:bdxmebu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f28b6599ba38312256255f4d30bb887bc398fb37/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasksImpl.kt#L29)):*
> ```Kotlin
>   private val certificateManager: CertificateManager
> ) : GenerateKeysTasks {
>   override fun generateLookupKeys(): ExchangeTask {
> ```

This isn't' really a key. Its more akin to a joinkeyOperation. I'd prefer to call them JoinKeyTasks
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/MapReduceTasks.kt, line 24 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa1ZBPDZZDqdEd66vL:-Mqa5fbx6c52-rL4K49h:b-dn527y) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a09c8ae1ed69190148f97753b04cb3cd3a0abed1/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/MapReduceTasks.kt#L24)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

If an Exchange Step is map reduce related, don't they need all three tasks? Maybe we can introduce a very simple top interface like;

interface ExchangeTasks {
    fun build(): ExchangeTask
}

WDYT?
</blockquote></details>

I'm not sure. I guess we can keep it as is for now and just throw unimplemented errors.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCommutativeEncryptionTasks.kt, line 19 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa5z6-DP7mRcw9UZba:-Mqa5z6-DP7mRcw9UZbb:b-52i63j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f28b6599ba38312256255f4d30bb887bc398fb37/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCommutativeEncryptionTasks.kt#L19)):*
> ```Kotlin
> import org.wfanet.panelmatch.client.exchangetasks.CommutativeEncryptionTasks
> 
> class FakeCommutativeEncryptionTasks : CommutativeEncryptionTasks {
> ```

JoinKeyTasks?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCommutativeEncryptionTasks.kt, line 23 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa60319zqqaeW3xXHD:-Mqa60319zqqaeW3xXHE:boe7jx8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f28b6599ba38312256255f4d30bb887bc398fb37/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCommutativeEncryptionTasks.kt#L23)):*
> ```Kotlin
>   override fun reEncrypt() = FakeExchangeTask("re-encrypt")
>   override fun decrypt() = FakeExchangeTask("decrypt")
>   override fun generateEncryptionKey() = FakeExchangeTask("generate-encryption-key")
> ```

move this to KeyTasks
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ValidationTasks.kt, line 20 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa5sWUEKNkZBWLRyPC:-Mqa5sWUEKNkZBWLRyPD:b-68rrcu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f28b6599ba38312256255f4d30bb887bc398fb37/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ValidationTasks.kt#L20)):*
> ```Kotlin
> 
> interface ValidationTasks {
>   fun intersectAndValidate(context: ExchangeContext): ExchangeTask
> ```

this feels like a funny grouping. Maybe just put it in with JoinKeyTasks ?


<!-- Sent from Reviewable.io -->

2021-12-10 21:35 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 7 unresolved discussions (waiting on @mpatel24, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasksImpl.kt, line 29 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa5M5H6TAZ2g3Sqp0c:-MqaG3SdDm1QuNq-_j_P:bh0khmt) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f28b6599ba38312256255f4d30bb887bc398fb37/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasksImpl.kt#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

This isn't' really a key. Its more akin to a joinkeyOperation. I'd prefer to call them JoinKeyTasks
</blockquote></details>

+1, rename class and interface to JoinKeyTasks/JoinKeyTasksImpl please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/MapReduceTasks.kt, line 24 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa1ZBPDZZDqdEd66vL:-MqaGApvEOHg8K6CN4Xo:b-9zt6bq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a09c8ae1ed69190148f97753b04cb3cd3a0abed1/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/MapReduceTasks.kt#L24)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm not sure. I guess we can keep it as is for now and just throw unimplemented errors.
</blockquote></details>

Let's keep as is for now
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCommutativeEncryptionTasks.kt, line 19 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa5z6-DP7mRcw9UZba:-MqaGLhi7jRT10Xny1Ep:bwpxfos) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f28b6599ba38312256255f4d30bb887bc398fb37/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCommutativeEncryptionTasks.kt#L19)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

JoinKeyTasks?
</blockquote></details>

We have uses for these that do not include join keys
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCommutativeEncryptionTasks.kt, line 23 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa60319zqqaeW3xXHD:-MqaGNokBDeoGrnmDmrB:bwpxfos) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f28b6599ba38312256255f4d30bb887bc398fb37/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCommutativeEncryptionTasks.kt#L23)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

move this to KeyTasks
</blockquote></details>

We have uses for these that do not include join keys
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ValidationTasks.kt, line 20 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa5sWUEKNkZBWLRyPC:-MqaGGrE6VoMYo_SY0C2:bjr7y3a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f28b6599ba38312256255f4d30bb887bc398fb37/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ValidationTasks.kt#L20)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this feels like a funny grouping. Maybe just put it in with JoinKeyTasks ?
</blockquote></details>

+1, I agree


<!-- Sent from Reviewable.io -->

2021-12-10 21:42 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: 29 of 39 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @mpatel24, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCommutativeEncryptionTasks.kt, line 19 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa5z6-DP7mRcw9UZba:-MqaHmv_1OsbLefr8pqF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f28b6599ba38312256255f4d30bb887bc398fb37/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCommutativeEncryptionTasks.kt#L19)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

We have uses for these that do not include join keys
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCommutativeEncryptionTasks.kt, line 23 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa60319zqqaeW3xXHD:-MqaHnnI483oo-R0i5RD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f28b6599ba38312256255f4d30bb887bc398fb37/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCommutativeEncryptionTasks.kt#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

We have uses for these that do not include join keys
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasksImpl.kt, line 29 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa5M5H6TAZ2g3Sqp0c:-MqaHkgy02bK4Ku1DLjV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f28b6599ba38312256255f4d30bb887bc398fb37/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasksImpl.kt#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

+1, rename class and interface to JoinKeyTasks/JoinKeyTasksImpl please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ValidationTasks.kt, line 20 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa5sWUEKNkZBWLRyPC:-MqaHr7J4EK4AFJp77a-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f28b6599ba38312256255f4d30bb887bc398fb37/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ValidationTasks.kt#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

+1, I agree
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-10 21:46 UTC, efoxepstein requested changes
> Reviewed 10 of 10 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 6 unresolved discussions (waiting on @mpatel24, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/JoinKeyTasks.kt, line 19 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqaIGuO9wmSzwEnjtF2:-MqaIGuO9wmSzwEnjtF3:b-m0l9np) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8712efaf0bc3bc223e71203266d02215eddb2dee/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/JoinKeyTasks.kt#L19)):*
> ```Kotlin
> import org.wfanet.panelmatch.client.common.ExchangeContext
> 
> interface JoinKeyTasks {
> ```

Can you add some KDoc to all the interfaces and functions? For interfaces, just briefly describe the theme. For functions, just a very brief description of which ExchangeStep type each corresponds to.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/JoinKeyTasks.kt, line 21 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqaI8xRBL79Ea7Ires0:-MqaI8xRBL79Ea7Ires1:b9qiuee) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8712efaf0bc3bc223e71203266d02215eddb2dee/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/JoinKeyTasks.kt#L21)):*
> ```Kotlin
> interface JoinKeyTasks {
> 
>   fun generateSymmetricKey(): ExchangeTask
> ```

Do you mind passing ExchangeContext to these too? (All of the functions in all of these interfaces) 


<!-- Sent from Reviewable.io -->

2021-12-10 22:22 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: 29 of 39 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @mpatel24, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasksImpl.kt, line 29 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa5M5H6TAZ2g3Sqp0c:-MqaR9iA36wAgb1LhrJN:b5aihxd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f28b6599ba38312256255f4d30bb887bc398fb37/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasksImpl.kt#L29)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no - I meant move this one to a new joinKeyTasks -- the rest of these are generating keys and should stay here


<!-- Sent from Reviewable.io -->

2021-12-10 22:39 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: 26 of 42 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @mpatel24, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasksImpl.kt, line 29 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa5M5H6TAZ2g3Sqp0c:-MqaV9Dn5S9Qyr83TME9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f28b6599ba38312256255f4d30bb887bc398fb37/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateKeysTasksImpl.kt#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

no - I meant move this one to a new joinKeyTasks -- the rest of these are generating keys and should stay here
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/JoinKeyTasks.kt, line 19 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqaIGuO9wmSzwEnjtF2:-MqaV0cn32yaS-SJzNxS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8712efaf0bc3bc223e71203266d02215eddb2dee/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/JoinKeyTasks.kt#L19)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you add some KDoc to all the interfaces and functions? For interfaces, just briefly describe the theme. For functions, just a very brief description of which ExchangeStep type each corresponds to.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/JoinKeyTasks.kt, line 21 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqaI8xRBL79Ea7Ires0:-MqaV0JH5ezy7Ro2RKjz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8712efaf0bc3bc223e71203266d02215eddb2dee/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/JoinKeyTasks.kt#L21)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Do you mind passing ExchangeContext to these too? (All of the functions in all of these interfaces) 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-10 22:50 UTC, efoxepstein approved these changes
> Reviewed 7 of 10 files at r12, 11 of 14 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 4 unresolved discussions (waiting on @mpatel24 and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-12-13 14:07 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 4 unresolved discussions (waiting on @mpatel24 and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCommutativeEncryptionTasks.kt, line 19 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa5z6-DP7mRcw9UZba:-Mqo61uxA__HXJrAQ-pq:bk0ae1v) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f28b6599ba38312256255f4d30bb887bc398fb37/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCommutativeEncryptionTasks.kt#L19)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm thinking the joinkey uses go inside JoinKeyTasks -- not non-joinkey uses go under some other task.
</blockquote></details>

I don't understand what you're asking for here, can you elaborate? Are you saying you want two functions that return an ExchangeTask for applying commutative deterministic encryption under two interfaces?

Ultimately the step type needs to be mapped to one of these... Unless you're proposing two step types too?


<!-- Sent from Reviewable.io -->

2021-12-14 00:28 UTC, efoxepstein requested changes
> Reviewed 32 of 32 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 7 unresolved discussions (waiting on @mpatel24, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 25 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqqJm7LEHZGFOvr7okD:-MqqJm7LEHZGFOvr7okE:bi7swp6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8295d8087d25c020a42c793c65809e7a03c34f06/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L25)):*
> ```Kotlin
>   suspend fun getExchangeTaskForStep(context: ExchangeContext): ExchangeTask {
>     @Suppress("WHEN_ENUM_CAN_BE_NULL_IN_JAVA")
>     return when (context.step.stepCase) {
> ```

Wrap all of this with `with(context)`:

```
return with(context) {
  when (step.stepCase) {
    StepCase.FOO -> foo()  // no need to write context.foo now
  }
}
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 79 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqqJxXd186tePpW8i0K:-MqqJxXd186tePpW8i0L:bf5lfy7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8295d8087d25c020a42c793c65809e7a03c34f06/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L79)):*
> ```Kotlin
> 
>   /** Returns the task that validates the step. */
>   abstract fun ExchangeContext.intersectAndValidate(): ExchangeTask
> ```

Can you make them all suspend? Thanks
___
*[src/main/kotlin/org/wfanet/panelmatch/integration/InProcessExchangeTaskMapper.kt, line 51 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqqKWArAuhGUwhhoM87:-MqqKWArAuhGUwhhoM88:b-jkrdyk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8295d8087d25c020a42c793c65809e7a03c34f06/src/main/kotlin/org/wfanet/panelmatch/integration/InProcessExchangeTaskMapper.kt#L51)):*
This is exactly identical to ProductionExchangeTaskMapper. Can you just use that instead of InProcessExchangeTaskMapper?

```
$ diff src/main/kotlin/org/wfanet/panelmatch/integration/InProcessExchangeTaskMapper.kt src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt
15c15
< package org.wfanet.panelmatch.integration
---
> package org.wfanet.panelmatch.client.deploy
51c51
< class InProcessExchangeTaskMapper(
---
> class ProductionExchangeTaskMapper(
58d57
< 
```


<!-- Sent from Reviewable.io -->

2021-12-14 00:43 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: 40 of 45 files reviewed, 7 unresolved discussions (waiting on @efoxepstein, @mpatel24, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 25 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqqJm7LEHZGFOvr7okD:-MqqOFuJ3GCTFqlsv2-8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8295d8087d25c020a42c793c65809e7a03c34f06/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Wrap all of this with `with(context)`:

```
return with(context) {
  when (step.stepCase) {
    StepCase.FOO -> foo()  // no need to write context.foo now
  }
}
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 79 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqqJxXd186tePpW8i0K:-MqqOGnS8AvopjlzwsYg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8295d8087d25c020a42c793c65809e7a03c34f06/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L79)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you make them all suspend? Thanks
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCommutativeEncryptionTasks.kt, line 19 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-Mqa5z6-DP7mRcw9UZba:-MqqODFmBHE4VQBb3nq-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f28b6599ba38312256255f4d30bb887bc398fb37/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/testing/FakeCommutativeEncryptionTasks.kt#L19)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't understand what you're asking for here, can you elaborate? Are you saying you want two functions that return an ExchangeTask for applying commutative deterministic encryption under two interfaces?

Ultimately the step type needs to be mapped to one of these... Unless you're proposing two step types too?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/integration/InProcessExchangeTaskMapper.kt, line 51 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235#-MqqKWArAuhGUwhhoM87:-MqqOBrQ4-6kTtXv4YE3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8295d8087d25c020a42c793c65809e7a03c34f06/src/main/kotlin/org/wfanet/panelmatch/integration/InProcessExchangeTaskMapper.kt#L51)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is exactly identical to ProductionExchangeTaskMapper. Can you just use that instead of InProcessExchangeTaskMapper?

```
$ diff src/main/kotlin/org/wfanet/panelmatch/integration/InProcessExchangeTaskMapper.kt src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt
15c15
< package org.wfanet.panelmatch.integration
---
> package org.wfanet.panelmatch.client.deploy
51c51
< class InProcessExchangeTaskMapper(
---
> class ProductionExchangeTaskMapper(
58d57
< 
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-14 18:04 UTC, efoxepstein approved these changes
> Reviewed 5 of 5 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 4 unresolved discussions (waiting on @mpatel24 and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-12-14 21:12 UTC, stevenwarejones approved these changes
> Reviewed 2 of 32 files at r15, 2 of 5 files at r16.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 4 unresolved discussions (waiting on @mpatel24 and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-12-14 22:05 UTC, efoxepstein approved these changes
> Reviewed 4 of 4 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/235)* status: all files reviewed, 4 unresolved discussions (waiting on @mpatel24 and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-12-14 22:08 UTC, merged