Make Build Queries and Decrypt Queries Input/Outputs more explicit
world-federation-of-advertisers/panel-exchange-client pull request #242
Opened 2021-12-10 16:36 UTC by stevenwarejones

- Replaces QueryId to JoinKeys with separate QueryIdToId and JoinKeysToId
- Fixes a bug in the decryption pipeline

2021-12-10 19:22 UTC, efoxepstein requested changes
> Reviewed 1 of 77 files at r5, 25 of 119 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242)* status: 26 of 122 files reviewed, 14 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc, line 42 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_Ubwp5cHzm2y0g7Zc:-Mq_Ubwp5cHzm2y0g7Zd:b2lb66t) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/778150249fa9d55180b434415955b2893e20f619/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc#L42)):*
> ```cpp
>   const Fingerprinter& fingerprinter = GetSha256Fingerprinter();
>   std::unique_ptr<Fingerprinter> peppered_fingerprinter =
>       wfa::panelmatch::common::crypto::GetPepperedFingerprinter(
> ```

While you're editing this can you add a using-decl for this?
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc, line 54 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_UP-zDXIdY0-aG-hk:-Mq_UP0-EnAvnsEKzEQW:b-9ujb6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/778150249fa9d55180b434415955b2893e20f619/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc#L54)):*
> ```cpp
>     lookup_key_and_id.mutable_join_key_identifier()->CopyFrom(
>         decrypted_join_key_and_id.join_key_identifier());
>     *prepared_query.add_lookup_key_and_ids() = lookup_key_and_id;
> ```

std::move RHS please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/JoinKeyHashingExchangeTask.kt, line 45 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_jEdn82zN0h0oRCHz:-Mq_jEdn82zN0h0oRCI-:bnx1ahx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/JoinKeyHashingExchangeTask.kt#L45)):*
> ```Kotlin
> 
>     val serializedOutput = lookupKeyAndIdCollection { lookupKeyAndIds += results }.toByteString()
>     return mapOf(outputDataLabel to serializedOutput.asBufferedFlow(1024))
> ```

I think we should prefer `flowOf(serializedOutput)` and let the consumer rebuffer it as appropriate to avoid unnecessary copies here.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt, line 60 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_jVU72d1_MUAVPDAR:-Mq_jVU72d1_MUAVPDAS:b-way09f) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L60)):*
> ```Kotlin
> ): CreateQueriesOutputs {
>   val tuple =
>     PCollectionTuple.of(CreateQueries.lookupKeyAndIdsTag, lookupKeyAndIds)
> ```

No need to use a PCollectionTuple now. Please convert `CreateQueries` to a `PTransform<PCollection<LookupKeyAndId>, PCollectionTuple>`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 105 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_lv9D4KBvSGwwnLnd:-Mq_lv9D4KBvSGwwnLne:b-ciy4c4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L105)):*
> ```Kotlin
> ) : PTransform<PCollectionTuple, PCollection<KeyedDecryptedEventDataSet>>() {
> 
>   override fun expand(input: PCollectionTuple): PCollection<KeyedDecryptedEventDataSet> {
> ```

We don't need to fix it now, but this function has become a LOT less efficient. Every `groupByKey` and `join` adds a shuffle stage, which is slow. Maybe add a TODO to optimize if necessary?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 109 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_kN0V5e1gUzwuBbCD:-Mq_kN0V5e1gUzwuBbCE:b-sjj0rm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L109)):*
> ```Kotlin
>       KvCoder.of(
>         ProtoCoder.of(JoinKeyIdentifier::class.java),
>         ListCoder.of(SerializableCoder.of(Plaintext::class.java))
> ```

Plaintext is a `data class`? Or is it a proto? If the latter, can you use `ProtoCoder`?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 146 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_lA9S2Kay3yMWJQO4:-Mq_kjE33IY3i4ev4JuS:brd76uf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L146)):*
> ```Kotlin
>         .setCoder(plaintextListCoder)
>         .groupByKey()
>         .map { kvOf(it.key, it.value.flatten()) }
> ```

I'm getting a little lost with the types around here. Can you introduce an intermediate variable with a type annotation? Maybe right before the `groupByKey`?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 177 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_mDAG7Y7n-3NZkmNk:-Mq_mDAG7Y7n-3NZkmNl:b-fgieoh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L177)):*
> ```Kotlin
>   private val metricsNamespace = "DecryptQueryResults"
>   private val noResults = Metrics.counter(metricsNamespace, "no-results")
>   private val discardedResult = Metrics.counter(metricsNamespace, "skipped-queries")
> ```

Can you add a blank line after between this and `@ProcessElement`?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 184 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_mNO5ApxXXyl1DC7L:-Mq_mNO5ApxXXyl1DC7M:bvqkyb5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L184)):*
> ```Kotlin
>     if (encryptedQueryResultsList.isEmpty()) {
>       noResults.inc()
>     } else if (decryptedJoinKeyAndId == null) {
> ```

Is it worthwhile checking that both this and the previous condition are not true?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 186 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_mU5W4olt7YxLFMQD:-Mq_mU5W4olt7YxLFMQE:b-l014g7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L186)):*
> ```Kotlin
>     } else if (decryptedJoinKeyAndId == null) {
>       discardedResult.inc()
>     } else {
> ```

If you add `return`s in the previous if-cases then you can unindent all of the remaining code, which aids in readability.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 189 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_m_L68fY9oglAs9Cz:-M [...]

2021-12-10 19:39 UTC, efoxepstein requested changes
> Reviewed 2 of 77 files at r5, 39 of 119 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242)* status: 67 of 122 files reviewed, 34 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt, line 107 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_n9yN7bFdzeKV6RPC:-Mq_n9yRAk_WOehUc94g:b-onty6p) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt#L107)):*
> ```Kotlin
>     assertThat(panelistQueries.values())
>       .containsInAnyOrder(
>         PanelistQuery(1, 1, "abc"),
> ```

It's a little hard to know what the 3 parameters mean, can you add keyword arguments please?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt, line 134 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_nEyD-Aw4SQH458PN:-Mq_nEyD-Aw4SQH458PO:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt#L134)):*
> ```Kotlin
>     val panelistQueries = getPanelistQueries(decodedQueries, queryIdAndJoinKeys)
>     assertThat(panelistQueries.values())
>       .containsInAnyOrder(
> ```

Ditto
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt, line 190 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_nIeG9LVLut87Kjo3:-Mq_nIeG9LVLut87Kjo4:bz5ukdp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt#L190)):*
> ```Kotlin
> 
>   private fun getLookupKeyAndIds(vararg entries: Pair<Long, String>): PCollection<LookupKeyAndId> {
>     return pcollectionOf(
> ```

Do we have a `pcollectionOf` helper that takes in an iterable instead of a varargs? If not maybe we should add that
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt, line 236 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_nXH9-B6A3_ivqpsM:-Mq_nXHA-vTyKX1D2xWS:bydg69m) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt#L236)):*
> ```Kotlin
>       queryIdAndIdsIterable: Iterable<QueryIdAndId>,
>       shardedQueries: Iterable<ShardedQuery> ->
>       if (queryIdAndIdsIterable.count() > 0) {
> ```

Negate this with early return please: https://testing.googleblog.com/2017/06/code-health-reduce-nesting-reduce.html
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt, line 238 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_nrl3DgWn_XDgI0XB:-Mq_nrl3DgWn_XDgI0XC:b-bykyfd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt#L238)):*
> ```Kotlin
>       if (queryIdAndIdsIterable.count() > 0) {
>         val queriesList = shardedQueries.toList()
>         val queryIdAndIdsList = queryIdAndIdsIterable.toList()
> ```

Can you quickly audit all usages of `.join` and see if all of them immediately turn the arguments into a list? If so, let's just change `.join` to use lists instead of iterables.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractQueryPreparerTest.kt, line 29 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_oBJyCk0DP4OrpH1p:-Mq_oBJyCk0DP4OrpH1q:b-b69c4l) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractQueryPreparerTest.kt#L29)):*
> ```Kotlin
>   listOf(
>     joinKeyAndIdOf(
>       "some decrypted join key 0".toByteStringUtf8(),
> ```

supernit: I like to avoid spaces in test constants because it makes it easier to mentally tokenize things when looking at error messages
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractQueryPreparerTest.kt, line 57 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_oHeA4LphNmkwNFXs:-Mq_oHeBCBBRGxgMitVp:b-kl6kps) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractQueryPreparerTest.kt#L57)):*
> ```Kotlin
>   @Test
>   fun testCryptor() {
> ```

nit: weirdly blank line
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractQueryPreparerTest.kt, line 65 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_oMQVAVpqwlEeo8_a:-Mq_oMQVAVpqwlEeo8_b:b-kl6kps) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractQueryPreparerTest.kt#L65)):*
> ```Kotlin
>   @Test
>   fun hashesAreEqual() {
> ```

nit: weirdly blank line
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractQueryPreparerTest.kt, line 75 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_oN3HB3iueKPewlUA:-Mq_oN3HB3iueKPewlUB:b-kl6kps) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractQueryPreparerTest.kt#L75)):*
> ```Kotlin
>   @Test
>   fun hashesAreNotEqual() {
> ```

nit: weirdly blank line
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractQueryPreparerTest.kt, line 83 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_oWTd8zsxQDM2huQo:-Mq_oWTd8zsxQDM2huQp:b-yi73hp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractQueryPreparerTest.kt#L83)):*
> ```Kotlin
>         DECRYPTED_JOIN_KEYS
>       )
>     assertThat(joinKeyAndIds1).isNotEqualTo(joinKeyAndIds2)
> ```

Do you want to go further and make sure that they share no elements in common?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractQueryPreparerTest.kt, line 88 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_o_q75aEE-FvPhYyk:-Mq_o_q75aEE-FvPhYyl:b-kl6kps) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractQueryPreparerTest.kt#L88)):*
> ```Kotlin
>   @Test
>   fun joinKeyIdentifiersAreEqual() {
> ```

nit: weirdly blank line
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextQueryPreparer.kt, line 37 [...]

2021-12-10 19:41 UTC, efoxepstein reviewed
> Reviewed 55 of 119 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242)* status: all files reviewed, 34 unresolved discussions (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-12-13 23:00 UTC, efoxepstein reviewed
> Reviewed 13 of 13 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-12-13 23:03 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt, line 238 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_nrl3DgWn_XDgI0XB:-Mqq18lR9NGVaETmTmHD:b-8m32e7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt#L238)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you quickly audit all usages of `.join` and see if all of them immediately turn the arguments into a list? If so, let's just change `.join` to use lists instead of iterables.
</blockquote></details>

(Or add a TODO for this?)


<!-- Sent from Reviewable.io -->

2021-12-13 23:04 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242)* status: all files reviewed, 28 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc, line 42 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_Ubwp5cHzm2y0g7Zc:-Mqo-NEo7ShgalFkGMm6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/778150249fa9d55180b434415955b2893e20f619/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc#L42)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

While you're editing this can you add a using-decl for this?
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc, line 54 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_UP-zDXIdY0-aG-hk:-Mqo-SnUC3WlqFCnhpPg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/778150249fa9d55180b434415955b2893e20f619/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

std::move RHS please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/JoinKeyHashingExchangeTask.kt, line 45 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_jEdn82zN0h0oRCHz:-Mqo-pwZ0vKxj7b42xMM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/JoinKeyHashingExchangeTask.kt#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think we should prefer `flowOf(serializedOutput)` and let the consumer rebuffer it as appropriate to avoid unnecessary copies here.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt, line 60 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_jVU72d1_MUAVPDAR:-Mqo0RfDCHTDH3hXUY_q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L60)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

No need to use a PCollectionTuple now. Please convert `CreateQueries` to a `PTransform<PCollection<LookupKeyAndId>, PCollectionTuple>`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 105 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_lv9D4KBvSGwwnLnd:-Mqo1j7H-RS-JexAJlrg:b-a3d2c4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L105)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

We don't need to fix it now, but this function has become a LOT less efficient. Every `groupByKey` and `join` adds a shuffle stage, which is slow. Maybe add a TODO to optimize if necessary?
</blockquote></details>

Yeah - I thought about that as I refactored it. The key space should be relatively small by this point. We're not talking millions of keys. Just the number of valid join keys.

I could easily combine the to join statements. I could even join plaintextJoinKeys and decryptedJoinKeys before I even turn them into Pcollections. wdyt?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 146 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_lA9S2Kay3yMWJQO4:-MqpkGWC8djRPO5nrwKc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L146)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm getting a little lost with the types around here. Can you introduce an intermediate variable with a type annotation? Maybe right before the `groupByKey`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 177 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_mDAG7Y7n-3NZkmNk:-Mqo2QqM27vbRxaySb0X:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L177)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you add a blank line after between this and `@ProcessElement`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 184 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_mNO5ApxXXyl1DC7L:-MqpkXfmCYXDxECSWRTf:b5ovbqb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L184)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is it worthwhile checking that both this and the previous condition are not true?
</blockquote></details>

Hmmmm..... How could both be empty and null? Wouldn't it just have not returned then?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 186 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_mU5W4olt7YxLFMQD:-Mqo3fCt4jGaZd3zO0v9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L186)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

If you add `return`s in the previous if-cases then you can unindent all of the remaining code, which aids in readability.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 189 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_m_L68fY9oglAs9Cz:-Mqo3v7x7gUqJi2KWYTl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L189)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use a traditional for-loop.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 199 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_mglq-ceBGs_gsQ_1:-Mqo46Ps5EH3bta7IR0r:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQu [...]

2021-12-13 23:11 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 105 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_lv9D4KBvSGwwnLnd:-Mqq2XOt4EgJdTQOtBFu:bjjgujk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L105)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Yeah - I thought about that as I refactored it. The key space should be relatively small by this point. We're not talking millions of keys. Just the number of valid join keys.

I could easily combine the to join statements. I could even join plaintextJoinKeys and decryptedJoinKeys before I even turn them into Pcollections. wdyt?
</blockquote></details>

Sounds good to me. Feel free to do this in a separate PR if you want.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 184 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_mNO5ApxXXyl1DC7L:-Mqq2e4q0cGVFW_dPHxP:b9y720x) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L184)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Hmmmm..... How could both be empty and null? Wouldn't it just have not returned then?
</blockquote></details>

It would require incorrect usage of this class. It's an optional defensive check, not necessary but maybe useful to the reader to demonstrated what's expected
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 222 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_mkyr9t3OEjH7HSQJ:-Mqq2yWD3GgNPF371HsE:bsrtbpx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L222)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

done
</blockquote></details>

Doesn't seem done but that's fine, this is very optional
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt, line 236 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mq_nXH9-B6A3_ivqpsM:-Mqq1s5l71MKOK38Ahzo:bntol0c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6ec1aa3452bb820e8a8cdf20e0034ca9b47c1d19/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt#L236)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Whats the right way to yield nothing here?
</blockquote></details>

I'd do this:

```
val queryIdAndIdsList = queryIdAndIdsIterable.toList()
if (queryIdAndIdsList.empty()) {
  return@join
}
...
```

https://kotlinlang.org/docs/returns.html#return-to-labels


<!-- Sent from Reviewable.io -->

2021-12-13 23:20 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 115 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mqq4m5i0_Lur2Hlq8a8:-Mqq4m5i0_Lur2Hlq8a9:b5mbhok) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/beb5995bf366ff05a1da88f702a33ca00939c6e7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L115)):*
> ```Kotlin
>     val plaintextJoinKeyAndIds = input[plaintextJoinKeyAndIdsTag]
> 
>     val keyedQueryIdAndIds = queryIdAndIds.keyBy { it.joinKeyIdentifier }
> ```

Nit: add names to the unnamed transforms in this file like `keyBy("Key QueryIdAndIds by Id")`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 118 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242#-Mqq4y0A4wQL4t9pVXey:-Mqq4y0A4wQL4t9pVXez:b-b20mrs) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/beb5995bf366ff05a1da88f702a33ca00939c6e7/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L118)):*
> ```Kotlin
>     val keyedDecryptedJoinKeyAndIds = decryptedJoinKeyAndIds.keyBy { it.joinKeyIdentifier }
>     val decryptedJoinKeyKeyedByQueryId =
>       keyedQueryIdAndIds.strictOneToOneJoin(keyedDecryptedJoinKeyAndIds).map {
> ```

Nit: `mapKeys { it.queryId }` 


<!-- Sent from Reviewable.io -->

2021-12-14 21:01 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/242)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-12-14 21:12 UTC, merged