Adds all the interfaces for encrypting user data
world-federation-of-advertisers/panel-exchange-client pull request #28
Opened 2021-06-23 16:42 UTC by enfreck

Adds the interfaces aes, encrypt_identifier, encrypt_payload,
fingerprinter, generate_hashkey, hkdf, and encrypt_original_data to be
used for the encrypting user data.

2021-06-23 16:55 UTC, efoxepstein requested changes
> Reviewed 10 of 10 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28)* status: all files reviewed, 6 unresolved discussions (waiting on @enfreck)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.h, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Mctl-QpBg172j5rS14m:-Mctl-QqDhkqtpEIXoVj:b-3fpjwk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/98d8f59766df8439e45a20d9de661bb1b7069a56/src/main/cc/wfanet/panelmatch/common/crypto/aes.h#L25)):*
> ```objc
> #include "absl/strings/string_view.h"
> 
> class Aes {
> ```

Add a class-level comment please. See https://google.github.io/styleguide/cppguide.html#Class_Comments
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.h, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Mctl5eqDJM-rYTiB-l7:-Mctl5eqDJM-rYTiB-l8:b2ikg4b) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/98d8f59766df8439e45a20d9de661bb1b7069a56/src/main/cc/wfanet/panelmatch/common/crypto/aes.h#L28)):*
> ```objc
>  public:
>   virtual ~Aes() = default;
>   virtual absl::StatusOr < std::string >>
> ```

Add a function-level comment please to this and all other functions in header files. See https://google.github.io/styleguide/cppguide.html#Function_Comments
___
*[src/main/cc/wfanet/panelmatch/common/crypto/encrypt_identifier.h, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Mctlaxu8u-GohBYPyta:-Mctlaxu8u-GohBYPytb:b-tkodoe) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/98d8f59766df8439e45a20d9de661bb1b7069a56/src/main/cc/wfanet/panelmatch/common/crypto/encrypt_identifier.h#L28)):*
> ```objc
>   virtual ~EncryptIdentifier() = default;
>   virtual std::string Encrypt(absl::string_view identifier,
>                               absl::string_view cryptokey) = 0;
> ```

Is there any possibility that this would fail? For example, what if the cryptokey is invalid? If there is such a possibility, this should return `absl::StatusOr<std::string>` instead.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/encrypt_payload.h, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-MctllYt2wNjJipzpFjk:-MctllYt2wNjJipzpFjl:bo3pqa8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/98d8f59766df8439e45a20d9de661bb1b7069a56/src/main/cc/wfanet/panelmatch/common/crypto/encrypt_payload.h#L22)):*
> ```objc
> namespace wfanet::panelmatch::common::crypto {
> 
> #include "absl/strings/string_view.h"
> ```

`#include` for StatusOr please.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/encrypt_payload.h, line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Mctmy0w2xAnSbEwu69R:-Mctmy0w2xAnSbEwu69S:bhb3807) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/47b27c16bc87536fca7e6d77c7676d011e8e99aa/src/main/cc/wfanet/panelmatch/common/crypto/encrypt_payload.h#L24)):*
> ```objc
> #include "absl/strings/string_view.h"
> 
> class EncryptPayload {
> ```

I think we'll want to rename this too probably, but let's wait until after you add a good comment to it before thinking of a better name.
___
*[src/main/cc/wfanet/panelmatch/protocol/crypto/encrypt_original_data.h, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-MctmCJ436QxpHvc9duT:-MctmCJ436QxpHvc9duU:bsh9pgl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/98d8f59766df8439e45a20d9de661bb1b7069a56/src/main/cc/wfanet/panelmatch/protocol/crypto/encrypt_original_data.h#L30)):*
> ```objc
> };
> 
> class EncryptOriginalData {
> ```

I think we should rename this to something with the word "Event" in it. How about `EventEncrypter`?


<!-- Sent from Reviewable.io -->

2021-06-23 17:57 UTC, enfreck commented
___
*[src/main/cc/wfanet/panelmatch/common/crypto/encrypt_payload.h, line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Mctmy0w2xAnSbEwu69R:-MctztnT27GAQ4QL-fGN:bkrahle) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/47b27c16bc87536fca7e6d77c7676d011e8e99aa/src/main/cc/wfanet/panelmatch/common/crypto/encrypt_payload.h#L24)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think we'll want to rename this too probably, but let's wait until after you add a good comment to it before thinking of a better name.
</blockquote></details>

Since this is kind of the "mirror" class of EncryptIdentifier, would it make sense to name it EncryptEvent?  Would that get too confusing if the other class is named EventEncryptor? 


<!-- Sent from Reviewable.io -->

2021-06-23 18:03 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28)* status: all files reviewed, 6 unresolved discussions (waiting on @enfreck)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/encrypt_payload.h, line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Mctmy0w2xAnSbEwu69R:-Mcu0uFb9xu6pftmSGL_:bb5vmeh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/47b27c16bc87536fca7e6d77c7676d011e8e99aa/src/main/cc/wfanet/panelmatch/common/crypto/encrypt_payload.h#L24)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Since this is kind of the "mirror" class of EncryptIdentifier, would it make sense to name it EncryptEvent?  Would that get too confusing if the other class is named EventEncryptor? 
</blockquote></details>

Yes, that would be confusing! Maybe EventEncryptor is a bad name then? We kind of want a name the encapsulates both parts: encrypting the event and hashing the encrypted identifier.

Could you make a tiny doc with a table of options where we can iterate quickly on better names?


<!-- Sent from Reviewable.io -->

2021-06-24 18:26 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28)* status: all files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @enfreck)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/BUILD.bazel, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-MczF76b0SYMrAg11iI0:-MczF76b0SYMrAg11iI1:bouaass) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/47b27c16bc87536fca7e6d77c7676d011e8e99aa/src/main/cc/wfanet/panelmatch/common/crypto/BUILD.bazel#L33)):*
> ```Starlark
>     name = "cryptor",
>     srcs = [
>         "cryptor.cc",
> ```

can we name all the files with similar patterns? eg if you're going to add in aes.h, then maybe change the other to pohlig_hellman
___
*[src/main/cc/wfanet/panelmatch/common/crypto/encrypt_identifier.h, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Mctlaxu8u-GohBYPyta:-MczFGrHE5EkJ8crwMtJ:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/98d8f59766df8439e45a20d9de661bb1b7069a56/src/main/cc/wfanet/panelmatch/common/crypto/encrypt_identifier.h#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is there any possibility that this would fail? For example, what if the cryptokey is invalid? If there is such a possibility, this should return `absl::StatusOr<std::string>` instead.
</blockquote></details>

+1
___
*[src/main/cc/wfanet/panelmatch/common/crypto/encrypt_payload.h, line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Mctmy0w2xAnSbEwu69R:-MczFc_K5Fpg3JSWK6Lt:b-hsjdqy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/47b27c16bc87536fca7e6d77c7676d011e8e99aa/src/main/cc/wfanet/panelmatch/common/crypto/encrypt_payload.h#L24)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Yes, that would be confusing! Maybe EventEncryptor is a bad name then? We kind of want a name the encapsulates both parts: encrypting the event and hashing the encrypted identifier.

Could you make a tiny doc with a table of options where we can iterate quickly on better names?
</blockquote></details>

I'm not sure why there are different files in common for encryptPayload, encryptIdentifier, encryptOriginalData. Should these be in the protocol?


<!-- Sent from Reviewable.io -->

2021-06-24 20:34 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28)* status: all files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @enfreck)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/BUILD.bazel, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-MczF76b0SYMrAg11iI0:-McziYQM60BUXASCmhQo:b-a9tk4u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/47b27c16bc87536fca7e6d77c7676d011e8e99aa/src/main/cc/wfanet/panelmatch/common/crypto/BUILD.bazel#L33)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can we name all the files with similar patterns? eg if you're going to add in aes.h, then maybe change the other to pohlig_hellman
</blockquote></details>

@enfreck I discussed this with Steven and we agreed it's fine to rename `cryptor.{h,cc}` in a follow-up PR. For now, let's just add your new interfaces (with the names we discussed).


<!-- Sent from Reviewable.io -->

2021-06-24 20:36 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28)* status: all files reviewed, 7 unresolved discussions (waiting on @enfreck and @stevenwarejones)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/encrypt_payload.h, line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Mctmy0w2xAnSbEwu69R:-Mczj6367dUZpxZfOWtG:biohytu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/47b27c16bc87536fca7e6d77c7676d011e8e99aa/src/main/cc/wfanet/panelmatch/common/crypto/encrypt_payload.h#L24)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm not sure why there are different files in common for encryptPayload, encryptIdentifier, encryptOriginalData. Should these be in the protocol?
</blockquote></details>

Discussed with Steven, let's first do the rename/commenting and then we can move them to `protocol` at a later time if it seems right.


<!-- Sent from Reviewable.io -->

2021-06-25 15:06 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28)* status: 1 of 10 files reviewed, 7 unresolved discussions (waiting on @efoxepstein, @enfreck, and @stevenwarejones)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/fingerprinter.h, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md2h-p31Tz8Z1LMmB8F:-Md2h-p31Tz8Z1LMmB8G:b8t8kr0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/47b27c16bc87536fca7e6d77c7676d011e8e99aa/src/main/cc/wfanet/panelmatch/common/crypto/fingerprinter.h#L27)):*
> ```objc
>  public:
>   virtual ~Fingerprinter() = default;
>   virtual uint64_t Fingerprint(absl::string_view item) = 0;
> ```

`virtual absl::StatusOr<uint64_t>`


<!-- Sent from Reviewable.io -->

2021-06-25 15:10 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28)* status: 1 of 10 files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @enfreck)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.h, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Mctl-QpBg172j5rS14m:-Md2heJW3gDmKESERgum:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/98d8f59766df8439e45a20d9de661bb1b7069a56/src/main/cc/wfanet/panelmatch/common/crypto/aes.h#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Add a class-level comment please. See https://google.github.io/styleguide/cppguide.html#Class_Comments
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.h, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Mctl5eqDJM-rYTiB-l7:-Md2hnujBRw_ctUnNtMC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/98d8f59766df8439e45a20d9de661bb1b7069a56/src/main/cc/wfanet/panelmatch/common/crypto/aes.h#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Add a function-level comment please to this and all other functions in header files. See https://google.github.io/styleguide/cppguide.html#Function_Comments
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/encrypt_payload.h, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-MctllYt2wNjJipzpFjk:-Md2hreE1jM86Yr3HRcC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/98d8f59766df8439e45a20d9de661bb1b7069a56/src/main/cc/wfanet/panelmatch/common/crypto/encrypt_payload.h#L22)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`#include` for StatusOr please.
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/encrypt_payload.h, line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Mctmy0w2xAnSbEwu69R:-Md2hsotAXznG_gIrv0c:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/47b27c16bc87536fca7e6d77c7676d011e8e99aa/src/main/cc/wfanet/panelmatch/common/crypto/encrypt_payload.h#L24)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Discussed with Steven, let's first do the rename/commenting and then we can move them to `protocol` at a later time if it seems right.
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/protocol/crypto/encrypt_original_data.h, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-MctmCJ436QxpHvc9duT:-Md2i50--qjngsyYFrtT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/98d8f59766df8439e45a20d9de661bb1b7069a56/src/main/cc/wfanet/panelmatch/protocol/crypto/encrypt_original_data.h#L30)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think we should rename this to something with the word "Event" in it. How about `EventEncrypter`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-25 15:10 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28)* status: 1 of 10 files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @enfreck)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/encrypt_identifier.h, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Mctlaxu8u-GohBYPyta:-Md2i9Pz4d8EqNgvj4u5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/98d8f59766df8439e45a20d9de661bb1b7069a56/src/main/cc/wfanet/panelmatch/common/crypto/encrypt_identifier.h#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-25 15:28 UTC, efoxepstein requested changes
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28)* status: all files reviewed, 7 unresolved discussions (waiting on @enfreck and @stevenwarejones)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.h, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md2j_ua4U6WnN7Bm9TJ:-Md2j_ua4U6WnN7Bm9TK:bqq2dxe) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41f2998ec1ba7544f9be451988a12d83a8996bd3/src/main/cc/wfanet/panelmatch/common/crypto/aes.h#L32)):*
> ```objc
>  public:
>   virtual ~Aes() = default;
>   // An encryption method that uses an AES Key to encrypt an input
> ```

Could you switch the part of speech to read more like "Encrypts `input` using AES key `key`"? (Here and elsewhere too. Maybe note that this will return an error status if the key is the wrong size for the given AES implementation.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.h, line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md2jzZQEazxbNToeGjd:-Md2jzZQEazxbNToeGje:b-qq7xpa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41f2998ec1ba7544f9be451988a12d83a8996bd3/src/main/cc/wfanet/panelmatch/common/crypto/aes.h#L34)):*
> ```objc
>   // An encryption method that uses an AES Key to encrypt an input
>   virtual absl::StatusOr<std::string> Encrypt(absl::string_view input,
>                                               absl::string_view key) = 0;
> ```

I think we might want to use Tink's `SecretData` class to hold the key instead of `absl::string_view` (here and elsewhere). This is the recommended way to hold key material since it's good at deleting it.

So the type of that parameter should be `const crypto::tink::util::SecretData& key` I think.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/fingerprinter.h, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md2h-p31Tz8Z1LMmB8F:-Md2k_D4DCQigXMWG0rM:b-qx0dy1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/47b27c16bc87536fca7e6d77c7676d011e8e99aa/src/main/cc/wfanet/panelmatch/common/crypto/fingerprinter.h#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`virtual absl::StatusOr<uint64_t>`
</blockquote></details>

Actually, I'm not sure that a fingerprinter should be able to fail. Any `string_view` should be fingerprintable!
___
*[src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h, line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md2kr_g8YiFveTTVII6:-Md2kr_g8YiFveTTVII7:b-xlw6mv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41f2998ec1ba7544f9be451988a12d83a8996bd3/src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h#L25)):*
Maybe just steal Tink's class-level comment: https://google.github.io/tink/javadoc/tink/1.0.0/index.html?com/google/crypto/tink/subtle/Hkdf.html

> This class implements HMAC-based Extract-and-Expand Key Derivation Function (HKDF) https://tools.ietf.org/html/rfc5869.

Personally, I'd phrase it as:

> Implements HMAC-based Extract-and-Expand Key Derivation Function (HKDF) from RFC5869 (https://tools.ietf.org/html/rfc5869)

(Also, please update other class comments to be similar. They don't need to describe the methods within, they should just describe what they're used for.)
___
*[src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md2kjIuAtUEcxbQ1-xJ:-Md2kjIuAtUEcxbQ1-xK:bxsj64i) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41f2998ec1ba7544f9be451988a12d83a8996bd3/src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h#L32)):*
> ```objc
>   // Generates an encryption key from a SecretData input
>   virtual absl::StatusOr<util::SecretData> ComputeHkdf(
>       const util::SecretData& ikm) = 0;
> ```

I think you'll need to write `crypto::tink::util::SecretData` (with the `crypto::tink` prefix). This really shouldn't compile.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/join_key_hash.h, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md2lTss7-tAsWBHK3nO:-Md2lTss7-tAsWBHK3nP:bnidl6l) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41f2998ec1ba7544f9be451988a12d83a8996bd3/src/main/cc/wfanet/panelmatch/common/crypto/join_key_hash.h#L26)):*
> ```objc
> 
> // An interface that uses a sha256 hash on an identifier
> class JoinKeyHash {
> ```

How do you feel about just dropping this interface and making an implementation of Fingerprinter called `PepperedFingerprinter` as something like:

```
class PepperedFingerprinter : public Fingerprinter {
 public:
  PepperedFingerprinter(const Fingerprinter* delegate, absl::string_view pepper):
    delegate_(delegate), pepper_(pepper) {}
  int64_t Fingerprint(absl::string_view item) const override { return delegate_->Fingerprint(absl::StrCat(item, pepper)); }
  private:
    ...
};
```
___
*[src/main/cc/wfanet/panelmatch/protocol/crypto/event_data_processor.h, line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md2m7zT6czkNj70trsq:-Md2m7zT6czkNj70trsr:bdpmyx2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41f2998ec1ba7544f9be451988a12d83a8996bd3/src/main/cc/wfanet/panelmatch/protocol/crypto/event_data_processor.h#L31)):*
> ```objc
> 
> // An interface which encrypts an identifier and event data
> class EventDataProcessor {
> ```

For some reason I thought we decided on "Preprocessor"? Let's chat about it


<!-- Sent from Reviewable.io -->

2021-06-25 15:39 UTC, efoxepstein reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28)* status: all files reviewed, 7 unresolved discussions (waiting on @enfreck and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-06-25 16:51 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28)* status: 2 of 10 files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.h, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md2j_ua4U6WnN7Bm9TJ:-Md34FfA1AU3798ON0Z1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41f2998ec1ba7544f9be451988a12d83a8996bd3/src/main/cc/wfanet/panelmatch/common/crypto/aes.h#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Could you switch the part of speech to read more like "Encrypts `input` using AES key `key`"? (Here and elsewhere too. Maybe note that this will return an error status if the key is the wrong size for the given AES implementation.
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.h, line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md2jzZQEazxbNToeGjd:-Md34FSZ621aYV-q7hS0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41f2998ec1ba7544f9be451988a12d83a8996bd3/src/main/cc/wfanet/panelmatch/common/crypto/aes.h#L34)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think we might want to use Tink's `SecretData` class to hold the key instead of `absl::string_view` (here and elsewhere). This is the recommended way to hold key material since it's good at deleting it.

So the type of that parameter should be `const crypto::tink::util::SecretData& key` I think.
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h, line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md2kr_g8YiFveTTVII6:-Md34DyuC8MbaZ13C0XY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41f2998ec1ba7544f9be451988a12d83a8996bd3/src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe just steal Tink's class-level comment: https://google.github.io/tink/javadoc/tink/1.0.0/index.html?com/google/crypto/tink/subtle/Hkdf.html

> This class implements HMAC-based Extract-and-Expand Key Derivation Function (HKDF) https://tools.ietf.org/html/rfc5869.

Personally, I'd phrase it as:

> Implements HMAC-based Extract-and-Expand Key Derivation Function (HKDF) from RFC5869 (https://tools.ietf.org/html/rfc5869)

(Also, please update other class comments to be similar. They don't need to describe the methods within, they should just describe what they're used for.)
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md2kjIuAtUEcxbQ1-xJ:-Md34BPQ6ZS2CXWTrl2A:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41f2998ec1ba7544f9be451988a12d83a8996bd3/src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think you'll need to write `crypto::tink::util::SecretData` (with the `crypto::tink` prefix). This really shouldn't compile.
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/join_key_hash.h, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md2lTss7-tAsWBHK3nO:-Md34Ad75GiDrcxG3SCX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41f2998ec1ba7544f9be451988a12d83a8996bd3/src/main/cc/wfanet/panelmatch/common/crypto/join_key_hash.h#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How do you feel about just dropping this interface and making an implementation of Fingerprinter called `PepperedFingerprinter` as something like:

```
class PepperedFingerprinter : public Fingerprinter {
 public:
  PepperedFingerprinter(const Fingerprinter* delegate, absl::string_view pepper):
    delegate_(delegate), pepper_(pepper) {}
  int64_t Fingerprint(absl::string_view item) const override { return delegate_->Fingerprint(absl::StrCat(item, pepper)); }
  private:
    ...
};
```
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/protocol/crypto/event_data_processor.h, line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md2m7zT6czkNj70trsq:-Md3491v6Tsd5PC7FvZC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41f2998ec1ba7544f9be451988a12d83a8996bd3/src/main/cc/wfanet/panelmatch/protocol/crypto/event_data_processor.h#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

For some reason I thought we decided on "Preprocessor"? Let's chat about it
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-25 16:55 UTC, efoxepstein requested changes
> Reviewed 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28)* status: all files reviewed, 5 unresolved discussions (waiting on @enfreck and @stevenwarejones)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.h, line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md34g9d1kW37FXQrIXE:-Md34g9d1kW37FXQrIXF:b-4rlyos) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e486db570011255965c5e0ef376f43f291416de4/src/main/cc/wfanet/panelmatch/common/crypto/aes.h#L28)):*
> ```objc
> #include "tink/util/secret_data.h"
> 
> // Implements AesSivBoringSsl from AES-SIV-CMAC as defined in
> ```

Ah, we want to be a little more generic here because this is an interface. It just implements Aes, not necessarily AesSivBoringSsl (basically, this is a perfect comment for a concrete subclass of this).
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.h, line 38 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md34TYF2gnz9hiH_Y2F:-Md34TYF2gnz9hiH_Y2G:b-pwxew9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e486db570011255965c5e0ef376f43f291416de4/src/main/cc/wfanet/panelmatch/common/crypto/aes.h#L38)):*
> ```objc
>   virtual absl::StatusOr<std::string> Encrypt(
>       absl::string_view input, const crypto::tink::util::SecretData key) = 0;
>   // Decrypts input using AES key key
> ```

Please use backticks around a variable in comments like `\`key\`` to indicate it.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 29 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md34qyWEU8Mg_olglYF:-Md34qyWEU8Mg_olglYG:bwimwd4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e486db570011255965c5e0ef376f43f291416de4/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L29)):*
> ```objc
> 
> // Implements HMAC-based Extract-and-Expand Key Derivation Function (HKDF)
> // from RFC5869 and AesSivBoringSsl from AES-SIV-CMAC
> ```

Again, make the AES part more generic.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/join_key_hash.h, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md2lTss7-tAsWBHK3nO:-Md34zwZ1aQ6krdsbZeU:bbq0yq0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41f2998ec1ba7544f9be451988a12d83a8996bd3/src/main/cc/wfanet/panelmatch/common/crypto/join_key_hash.h#L26)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh sorry, I think my suggestion wasn't clear. It was to just delete this interface. Eventually you can add the `PepperedFingerprinter` class in another PR.


<!-- Sent from Reviewable.io -->

2021-06-25 19:21 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28)* status: 6 of 10 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @enfreck, and @stevenwarejones)

___
*[src/main/cc/wfanet/panelmatch/protocol/crypto/BUILD.bazel, line 43 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md3bh2MCrNSxzTwafa0:-Md3bh2MCrNSxzTwafa1:b70fcla) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f560313081e686c6619223e1a4a61c0c2c51f8d2/src/main/cc/wfanet/panelmatch/protocol/crypto/BUILD.bazel#L43)):*
> ```Starlark
>     name = "event_data_preprocessor",
>     hdrs = [
>         "event_data_preprocessor.h",
> ```

can we just call it `preprocessor.h`?
___
*[src/main/cc/wfanet/panelmatch/protocol/crypto/event_data_processor.h, line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md2m7zT6czkNj70trsq:-Md3-GB9CEj4UMAog5Ls:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41f2998ec1ba7544f9be451988a12d83a8996bd3/src/main/cc/wfanet/panelmatch/protocol/crypto/event_data_processor.h#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

For some reason I thought we decided on "Preprocessor"? Let's chat about it
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-06-25 19:26 UTC, efoxepstein reviewed
> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28)* status: all files reviewed, 5 unresolved discussions (waiting on @enfreck and @stevenwarejones)

___
*[src/main/cc/wfanet/panelmatch/protocol/crypto/BUILD.bazel, line 43 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md3bh2MCrNSxzTwafa0:-Md3cW3277X9UTtptckI:b2gonfr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f560313081e686c6619223e1a4a61c0c2c51f8d2/src/main/cc/wfanet/panelmatch/protocol/crypto/BUILD.bazel#L43)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can we just call it `preprocessor.h`?
</blockquote></details>

I prefer the current name. It adds a little context to the reader for what this actually does. There are very likely to be other forms of preprocessing for other data so I want to make sure we don't have a collision.

Can we get this PR in and then reevaluate the names when we have a little more code to put this in context?


<!-- Sent from Reviewable.io -->

2021-06-25 19:28 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.h, line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md34g9d1kW37FXQrIXE:-Md3cw3z7VDnT30oVjUu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e486db570011255965c5e0ef376f43f291416de4/src/main/cc/wfanet/panelmatch/common/crypto/aes.h#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ah, we want to be a little more generic here because this is an interface. It just implements Aes, not necessarily AesSivBoringSsl (basically, this is a perfect comment for a concrete subclass of this).
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.h, line 38 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md34TYF2gnz9hiH_Y2F:-Md3cx4k4FiI14hALcp1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e486db570011255965c5e0ef376f43f291416de4/src/main/cc/wfanet/panelmatch/common/crypto/aes.h#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use backticks around a variable in comments like `\`key\`` to indicate it.
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/fingerprinter.h, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md2h-p31Tz8Z1LMmB8F:-Md3d4Lj-70ttsc1Ul49:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/47b27c16bc87536fca7e6d77c7676d011e8e99aa/src/main/cc/wfanet/panelmatch/common/crypto/fingerprinter.h#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Actually, I'm not sure that a fingerprinter should be able to fail. Any `string_view` should be fingerprintable!
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 29 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-Md34qyWEU8Mg_olglYF:-Md3cxsz1hzTwNriMOvO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e486db570011255965c5e0ef376f43f291416de4/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Again, make the AES part more generic.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-25 19:29 UTC, efoxepstein approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28#-:-Md3cxC35dpSnOePr0Q2:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-06-28 16:18 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-06-28 16:39 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-06-28 16:48 UTC, merged