Ensure WriteShardedData always writes to all shards
world-federation-of-advertisers/panel-exchange-client pull request #299
Opened 2022-04-07 13:41 UTC by efoxepstein

2022-04-07 13:48 UTC, robinsons approved these changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/299)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @yunyeng)



<!-- Sent from Reviewable.io -->

2022-04-07 16:38 UTC, stevenwarejones requested changes
I would argue that if writeShardedData is not writing to certain shards, it should, instead, throw an error since this signals an inefficient protocol.

> Reviewed 1 of 5 files at r1, 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/299#-:-N-3spdd2vPI3bkzoU8G:b4em9pn)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt, line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/299#-N-3scMPCPj1H0FnutRP:-N-3scMPCPj1H0FnutRQ:b38fsbl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/baf7f2317007af3cf2e1177acc805c58e22cb597/src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt#L77)):*
> ```Kotlin
>     val presentKeys = groupedData.keys("Present Keys").toListView("Present Keys View")
> 
>     val missingFiles: PCollection<KV<Int, Iterable<T>>> =
> ```

why do you need SideInput here? Its just a single input of presentKeys mapped to missingFiles


<!-- Sent from Reviewable.io -->

2022-04-07 17:03 UTC, efoxepstein reviewed
Not necessarily -- more files will mean more parallelism for Apache Beam to exploit.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/299#-:-N-3y5pf3wXE43pFKZpB:b-dqajsm)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt, line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/299#-N-3scMPCPj1H0FnutRP:-N-3xube91h97YPNpelu:b-f0y9g2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/baf7f2317007af3cf2e1177acc805c58e22cb597/src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt#L77)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why do you need SideInput here? Its just a single input of presentKeys mapped to missingFiles
</blockquote></details>

Can you explain exactly what you'd do to the `presentKeys` PCollection to get `missingFiles`?


<!-- Sent from Reviewable.io -->

2022-04-08 16:30 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/299)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt, line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/299#-N-3scMPCPj1H0FnutRP:-N-9-Gej3oLXtcS3tt4B:b-fxe60u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/96924094fcbacedb7c60d6271a20c320bca8882b/src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt#L77)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you explain exactly what you'd do to the `presentKeys` PCollection to get `missingFiles`?
</blockquote></details>

flatten them to a list, pardo look for gaps, and yield those gaps. Also, what do you think about pulling this into a separate function with its own test?


<!-- Sent from Reviewable.io -->

2022-04-08 18:00 UTC, stevenwarejones reviewed
Hmmmm.... it would need to be a use case where having 2 items in a shard is worse than having zero.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/299#-:-N-9KFBO6z4ccncvDx32:bzcerid)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @robinsons, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt, line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/299#-N-3scMPCPj1H0FnutRP:-N-9KCDk72qRYMKLcCzn:bbjq4ta) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/96924094fcbacedb7c60d6271a20c320bca8882b/src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt#L77)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Clever, thanks, done. I don't think it needs its own test, it's pretty well covered by the test added in this PR. We want to try to test interfaces, not implementation details, and I don't know if this functionality needs to be reusable.
</blockquote></details>

did you push?


<!-- Sent from Reviewable.io -->

2022-04-08 18:28 UTC, efoxepstein reviewed
We're using this code for the ComScore pilot. They've patched it and we have it implemented internally. There's no time to change that. Our situation is that each EncryptedQueryBundle is pretty large, so we can't have too many per file. This means we need a lot of files. But since they're randomly assigned to files, there's a pretty good chance one is empty.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/299#-:-N-9QN2Y3ZdVjFfVBK_Y:b-9854vn)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @robinsons, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt, line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/299#-N-3scMPCPj1H0FnutRP:-N-9QqqpDbww1i_3rkB6:bp0q0uo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/96924094fcbacedb7c60d6271a20c320bca8882b/src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt#L77)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

did you push?
</blockquote></details>

Yes. This uses `combineIntoList` instead of a side input now.


<!-- Sent from Reviewable.io -->

2022-04-11 19:02 UTC, stevenwarejones approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/299)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @robinsons, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt, line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/299#-N-3scMPCPj1H0FnutRP:-N-P-E_22NN0s-mtFrdJ:b6iiqs1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/96924094fcbacedb7c60d6271a20c320bca8882b/src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt#L77)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Yes. This uses `combineIntoList` instead of a side input now.
</blockquote></details>

somehow, mine didn't update earlier. lgtm


<!-- Sent from Reviewable.io -->

2022-04-11 20:15 UTC, merged