juliamorrissey C++ for SWIG
world-federation-of-advertisers/panel-exchange-client pull request #30
Opened 2021-06-24 21:39 UTC by jmorrrr

Creating header file for translation into protocol buffers and c++ and header file for serialization

2021-06-25 11:02 UTC, efoxepstein requested changes
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: all files reviewed, 16 unresolved discussions (waiting on @jmorrrr)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1mIwdAOBF_YM6MwdM:-Md1mIwdAOBF_YM6MwdN:b-pluj62) (no related file):*
Please update the Pull Request message on GitHub so the title has imperative mood. In other words, something like "Adds event preparation SWIG-compatible C++ wrapper library"

---
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1p5zy1MZ6mQrd7BZJ:-Md1p5zy1MZ6mQrd7BZK:bulnwmm) (no related file):*
We'll need to define the `EncryptRequest` and `EncryptResponse` protocol buffers as part of this PR too (see your doc and the C++ Philosophy doc for more on this). I'm thinking maybe we should also consider renaming them to `PreprocessEventsRequest` and `PreprocessEventsResponse` to be a little more specific, too.

---
___
*[bazel-bin, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1mug7CEAPbAh-mDVx:-Md1mug8CSCg1Ws1fUZJ:b-vn1hs9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/bazel-bin#L1)):*
> ```
> /usr/local/google/home/juliamorrissey/.cache/bazel/_bazel_juliamorrissey/d23000c5a219f05f9bb048e9e38da167/execroot/panel_exchange_client/bazel-out/k8-fastbuild/bin
> ```

Please remove this file from the commit. You should use `git rm --cached bazel-bin` to make sure you remove it from git but not your computer.
___
*[bazel-out, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1n5y50GpTRoxVG0Fn:-Md1n5y50GpTRoxVG0Fo:b-vn1hs9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/bazel-out#L1)):*
> ```
> /usr/local/google/home/juliamorrissey/.cache/bazel/_bazel_juliamorrissey/d23000c5a219f05f9bb048e9e38da167/execroot/panel_exchange_client/bazel-out
> ```

Please remove this file from the commit. You should use `git rm --cached bazel-bin` to make sure you remove it from git but not your computer.
___
*[bazel-panel-exchange-client, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1n6gK5ArRD67MHKzZ:-Md1n6gK5ArRD67MHKz_:b-vn1hs9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/bazel-panel-exchange-client#L1)):*
> ```
> /usr/local/google/home/juliamorrissey/.cache/bazel/_bazel_juliamorrissey/d23000c5a219f05f9bb048e9e38da167/execroot/panel_exchange_client
> ```

Please remove this file from the commit. You should use `git rm --cached bazel-bin` to make sure you remove it from git but not your computer.
___
*[bazel-testlogs, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1n7Go3Ua76yY8kW66:-Md1n7Go3Ua76yY8kW67:b-vn1hs9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/bazel-testlogs#L1)):*
> ```
> /usr/local/google/home/juliamorrissey/.cache/bazel/_bazel_juliamorrissey/d23000c5a219f05f9bb048e9e38da167/execroot/panel_exchange_client/bazel-out/k8-fastbuild/testlogs
> ```

Please remove this file from the commit. You should use `git rm --cached bazel-bin` to make sure you remove it from git but not your computer.
___
*[.clwb/.bazelproject, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1n89t3NdRb70XVyiY:-Md1n89t3NdRb70XVyiZ:b-vn1hs9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/.clwb/.bazelproject#L1)):*
> ```
> directories:
> ```

Please remove this file from the commit. You should use `git rm --cached bazel-bin` to make sure you remove it from git but not your computer.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 0 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1nAdN2dh-LP8yrwpo:-Md1nAdN2dh-LP8yrwpp:b-y7jkp3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/58e93bbb965151d70efbaea87f208e2a3831ef55/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L0)):*
In this file, you should add two `cc_library` build rules. Something like:

```
cc_library(
  name = "encrypt_original_data",
  hdrs = ["encrypt_original_data.h"],
  deps = [
    # Needs a dep on the protocol buffers
    # Needs a dep on Erin's code
  ]
)

cc_library(
  name = "encrypt_original_data_wrapper",
  hdrs = ["encrypt_original_data_wrapper.h"],
  srcs = ["encrypt_original_data_wrapper.cc"],
  deps = [
    ":encrypt_original_data", 
    # Will also need a dep on the protocol buffers
  ]
)
```
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data.h, line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1o0vzCrlU1FhGp-xS:-Md1o0vzCrlU1FhGp-xT:b-imt480) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data.h#L18)):*
> ```objc
> 
> //
> // Created by juliamorrissey on 6/24/21.
> ```

Please delete this comment block.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data.h, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1nfoa8tX6syKMPBWA:-Md1nfoa8tX6syKMPBWB:b9gc9d2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data.h#L25)):*
> ```objc
> 
> namespace wfanet::panelmatch::client::eventprocessing {
> absl::StatusOr<EncryptedData> Convert(struct EncryptedData& data);
> ```

These should use the `Request` and `Response` protos we discussed. I believe in your doc you called them `EncryptRequest` and `EncryptResponse`:

```
absl::StatusOr<EncryptResponse> Convert(const EncryptRequest& request);
```
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.h, line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1o3PM9YobUoqljhI6:-Md1o3PM9YobUoqljhI7:b-imt480) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.h#L18)):*
> ```objc
> 
> //
> // Created by juliamorrissey on 6/24/21.
> ```

Please delete this comment block.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.cc, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1oh63DIjBkBLuztsg:-Md1oh63DIjBkBLuztsh:b-9oq9yj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.cc#L16)):*
> ```cpp
> 
> //
> // Created by juliamorrissey on 6/24/21.
> ```

Please remove this comment block
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.cc, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1og7_EFmvY1NmZOeL:-Md1og7_EFmvY1NmZOeM:bv3ko2u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a5 [...]

2021-06-25 15:10 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: all files reviewed, 16 unresolved discussions (waiting on @efoxepstein and @jmorrrr)

___
*[bazel-bin, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1mug7CEAPbAh-mDVx:-Md2hVdC2nhqsV1Dp7Dx:b-3ujpy0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/bazel-bin#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please remove this file from the commit. You should use `git rm --cached bazel-bin` to make sure you remove it from git but not your computer.
</blockquote></details>

Is your git not respecting `.gitignore`?
___
*[.clwb/.bazelproject, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1n89t3NdRb70XVyiY:-Md2hiIe3nlmKdTvLScm:b-efiy0a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/.clwb/.bazelproject#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please remove this file from the commit. You should use `git rm --cached bazel-bin` to make sure you remove it from git but not your computer.
</blockquote></details>

also, maybe add `.clwb` to `.gitignore`


<!-- Sent from Reviewable.io -->

2021-06-26 01:39 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: 4 of 16 files reviewed, 16 unresolved discussions (waiting on @efoxepstein)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1mIwdAOBF_YM6MwdM:-Md2aoe16-_JtKB1jQ_q:b-896fix) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please update the Pull Request message on GitHub so the title has imperative mood. In other words, something like "Adds event preparation SWIG-compatible C++ wrapper library"
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1p5zy1MZ6mQrd7BZJ:-Md4y1v_E7NHZ9ABiswI:b-896fix) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

We'll need to define the `EncryptRequest` and `EncryptResponse` protocol buffers as part of this PR too (see your doc and the C++ Philosophy doc for more on this). I'm thinking maybe we should also consider renaming them to `PreprocessEventsRequest` and `PreprocessEventsResponse` to be a little more specific, too.
</blockquote></details>

Done.

---
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1nAdN2dh-LP8yrwpo:-Md4y4gO-KCaV4jogcFR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/58e93bbb965151d70efbaea87f208e2a3831ef55/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

In this file, you should add two `cc_library` build rules. Something like:

```
cc_library(
  name = "encrypt_original_data",
  hdrs = ["encrypt_original_data.h"],
  deps = [
    # Needs a dep on the protocol buffers
    # Needs a dep on Erin's code
  ]
)

cc_library(
  name = "encrypt_original_data_wrapper",
  hdrs = ["encrypt_original_data_wrapper.h"],
  srcs = ["encrypt_original_data_wrapper.cc"],
  deps = [
    ":encrypt_original_data", 
    # Will also need a dep on the protocol buffers
  ]
)
```
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data.h, line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1o0vzCrlU1FhGp-xS:-Md2az2b3W1HrHKWTG1-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data.h#L18)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please delete this comment block.
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data.h, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1nfoa8tX6syKMPBWA:-Md2ix8XB_iOU7pIMto3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data.h#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

These should use the `Request` and `Response` protos we discussed. I believe in your doc you called them `EncryptRequest` and `EncryptResponse`:

```
absl::StatusOr<EncryptResponse> Convert(const EncryptRequest& request);
```
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.h, line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1o3PM9YobUoqljhI6:-Md2ajstCp8dIhsA4oD0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.h#L18)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please delete this comment block.
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.cc, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1oh63DIjBkBLuztsg:-Md2b0m05DlzvpkKaLHQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.cc#L16)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please remove this comment block
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.cc, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1og7_EFmvY1NmZOeL:-Md2gYT7CjKWV6Kn5dlR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.cc#L22)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please update this type to `EncryptRequest` as discussed in your doc
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.cc, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1omTS08Rh7FGxinB2:-Md2g87t5lK1dbSebuF2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.cc#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please update this type to `EncryptResponse` as discussed in your doc
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.cc, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1opdk5RZvEJ-TW1r6:-Md2fDff3VOYnxon_vkk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.cc#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This should call Erin's library instead of `CompleteSetupPhase`.
</blockquote></details>

Done.
___
*[bazel-bin, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1mug7CEAPbAh-mDVx:-Md2asbA3rdyE8R3wuDm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/bazel-bin#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please remove this file from the commit. You should use `git rm --cached bazel-bin` to make sure you remove it from git but not your computer.
</blockquote></details>

Done.
___
*[bazel-out, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1n5y50GpTRoxVG0Fn:-Md2at-v2Aj1SN6q3lmk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/bazel-out#L [...]

2021-06-26 01:40 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: 4 of 16 files reviewed, 16 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1nAdN2dh-LP8yrwpo:-Md4yLBH49_EOQyUhYiW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/58e93bbb965151d70efbaea87f208e2a3831ef55/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-26 01:40 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: 4 of 16 files reviewed, 16 unresolved discussions (waiting on @efoxepstein)

___
*[bazel-bin, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1mug7CEAPbAh-mDVx:-Md4yNdO7DkqsTD0RTpg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/bazel-bin#L1)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-26 01:40 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: 4 of 16 files reviewed, 16 unresolved discussions (waiting on @efoxepstein)

___
*[.clwb/.bazelproject, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1n89t3NdRb70XVyiY:-Md4yPuK46Y1bYutV6rl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/.clwb/.bazelproject#L1)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-26 11:30 UTC, efoxepstein requested changes
> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: all files reviewed, 8 unresolved discussions (waiting on @jmorrrr)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md73HSG8g6sgiDgEWay:-Md73HSH7LZLO_xYKyCJ:b-83bq3q) (no related file):*
Could you please add `encrypt_original_data.cc` modeled after https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/cc/wfanet/panelmatch/protocol/crypto/deterministic_commutative_encryption_utility.cc?

This is the file that will call Erin's library. Since Erin's library isn't checked in yet, you can just have it do nothing for now:

```
absl::StatusOr<PreprocessEventsResponse> Convert(const PreprocessEventsRequest& request) {
  // TODO: call Erin's library
}
```

(Note: I'm also making a comment elsewhere that proposing renaming this function to `PreprocessEvents`.)

---
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md748tDE3wGVfjzN4HY:-Md748tE2CpAFle3Q5b8:bg5be9k) (no related file):*
In the interest of velocity, since Erin's library is not merged yet, I'll be OK with merging this PR without unit tests. However, the next PR should link in Erin's library and add good test coverage of everything. @stevenwarejones , WDYT?

---
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md70yag4ZaFITGgXj4O:-Md70yag4ZaFITGgXj4P:b-d33qju) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L4)):*
> ```Starlark
>   name = "encrypt_original_data",
>   hdrs = ["encrypt_original_data.h"],
>   deps = [
> ```

Could you add the `strip_include_prefix` thing found in similar C++ build files in this repo? See for example https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/cc/wfanet/panelmatch/protocol/crypto/BUILD.bazel#L15.

Once you do this, for the `#include` statements referencing files in this repo, you'll chop of the beginning (e.g. `#include "wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data.h"`).
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.h, line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md70bex4iGfTNHfIgG_:-Md70bex4iGfTNHfIgGa:bupvyfb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.h#L20)):*
> ```objc
> #define SRC_MAIN_CC_WFANET_PANELMATCH_CLIENT_EVENTPREPROCESSING_ENCRYPT_ORIGINAL_DATA_WRAPPER_H_
> 
> #include "absl/status/statusor.h"
> ```

`#include <string>` too please
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.h, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md71i0V0iWmkDL0KLA6:-Md71i0V0iWmkDL0KLA7:b-gnexgn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.h#L23)):*
> ```objc
> 
> namespace wfanet::panelmatch::client::eventpreocessing {
> absl::StatusOr<std::string> Convert(const std::string& serialized_request);
> ```

Can you change the function name here to `PreprocessEvents`? (Notice the pattern: `PreprocessEventsRequest -> PreprocessEvents -> PreprocessEventsResponse`)

Same comment applies to `encrypt_original_data.h`.

This means you should also rename all the files to `preprocess_events.{h,cc}` or `preprocess_events_wrapper.{h,cc}` as appropriate.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.cc, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md71w5_-10_wGM_dFHI:-Md71w5_-10_wGM_dFHJ:bpy8yr1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.cc#L26)):*
> ```cpp
>   RETURN_IF_ERROR(ParseRequestFromString(request_proto, serialized_request));
>   ASSIGN_OR_RETURN(PreprocessEventsResponse result,
>                    EventDataPreprocessor(request_proto));
> ```

This should be calling the function you defined in `encrypt_original_data.h` (which another comment suggests renaming to just `PreprocessEvents`. That file should call Erin's code.
___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 12 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md72I-K5h5C_dolD2gz:-Md72I-K5h5C_dolD2h-:b-ul8yyi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L12)):*
> ```Starlark
>     name = "preprocess_events_proto",
>     srcs = ["preprocess_events.proto"],
>     strip_import_prefix = "/src/main/proto",
> ```

Since you have `strip_import_prefix` here, in your C++ files please use `#include "wfanet/panelmatch/client/eventpreprocessing/preprocess_events.pb.h"` (with the import prefix stripped).
___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md72bGc22z7bRa_axwu:-Md72bGc22z7bRa_axwv:bi22539) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto#L19)):*
> ```protobuf
> package wfanet.panelmatch.protocol.protobuf;
> 
> option java_package = "wfanet.panelmatch.protocol.protobuf";
> ```

It's possible the other proto files do this wrong but the `java_package` should be: `org.wfanet.panelmatch.protocol.protobuf` (with the leading `org.`)
___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md72phoC_jEaFV6SUF2:-Md72phoC_jEaFV6SUF3:bai5o2j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto#L38)):*
> ```protobuf
>   message IdAndPayload {
>     bytes id = 1;
>     bytes payload = 2;
> ```

How about `encrypted_id` and `encrypted_payload` to make it a little more obvious what the difference is between the request and the response? (And maybe rename this message to `EncryptedIdAndPayload`)


<!-- Sent from Reviewable.io -->

2021-06-28 16:07 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: all files reviewed, 8 unresolved discussions (waiting on @jmorrrr)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md748tDE3wGVfjzN4HY:-MdIMQQK81lVLiZx_wCI:b-gslkz9) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

In the interest of velocity, since Erin's library is not merged yet, I'll be OK with merging this PR without unit tests. However, the next PR should link in Erin's library and add good test coverage of everything. @stevenwarejones , WDYT?
</blockquote></details>

feels icky. I might be okay if there is one opened by next week.... don't want this to become a pattern though.

---
___
*[.clwb/.bazelproject, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1n89t3NdRb70XVyiY:-MdIMxVM4JMQZsoY9292:b-v0lc6c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/.clwb/.bazelproject#L1)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm not seeing the change to `.gitignore`


<!-- Sent from Reviewable.io -->

2021-06-28 16:23 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: all files reviewed, 9 unresolved discussions (waiting on @jmorrrr)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md748tDE3wGVfjzN4HY:-MdIQDYs5E03vnJNCOJM:b-1l947z) (no related file):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

feels icky. I might be okay if there is one opened by next week.... don't want this to become a pattern though.
</blockquote></details>

Agreed it's icky. @jmorrrr maybe let's add unit tests. To do this:

1. `encrypt_original_data.cc` should just `return absl::UnimplementedError("Not implemented");`
2. Then add tests: `src/test/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_test.cc` and `src/test/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper_test.cc`. They should except that error for now.

---


<!-- Sent from Reviewable.io -->

2021-06-28 16:41 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: all files reviewed, 10 unresolved discussions (waiting on @efoxepstein and @jmorrrr)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md748tDE3wGVfjzN4HY:-MdISkQD66XtS2QYYvn2:b-hpvobq) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Agreed it's icky. @jmorrrr maybe let's add unit tests. To do this:

1. `encrypt_original_data.cc` should just `return absl::UnimplementedError("Not implemented");`
2. Then add tests: `src/test/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_test.cc` and `src/test/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper_test.cc`. They should except that error for now.
</blockquote></details>

I approve once Eli approves.

---
___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdIUCsf2AHMseOBTlGe:-MdIUCsf2AHMseOBTlGf:b-haeqdz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto#L28)):*
> ```protobuf
>     bytes id = 1;
>     bytes payload = 2;
>   }
> ```

I'd prefer
```
message PreprocessEventsRequest {
  repeated UnprocessedEvent unprocessed_event = 1;
  message UnprocessedEvent {
    bytes id = 1;
    bytes data = 2;
  }

```
___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md72phoC_jEaFV6SUF2:-MdITQUi0LMNA9cbojbW:b-qbg0ms) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How about `encrypted_id` and `encrypted_payload` to make it a little more obvious what the difference is between the request and the response? (And maybe rename this message to `EncryptedIdAndPayload`)
</blockquote></details>

I'd actually prefer more like this
```
message PreprocessEventsResponse {
  repeated ProcessedEvent processed_event = 1;
  message ProcessedEvent {
    bytes encrypted_id = 1;
    bytes encrypted_data = 2;
```


<!-- Sent from Reviewable.io -->

2021-06-28 16:43 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: all files reviewed, 11 unresolved discussions (waiting on @jmorrrr and @stevenwarejones)

___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md72phoC_jEaFV6SUF2:-MdIV9voAka4-ZNtaVva:b-ozq9wj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto#L38)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'd actually prefer more like this
```
message PreprocessEventsResponse {
  repeated ProcessedEvent processed_event = 1;
  message ProcessedEvent {
    bytes encrypted_id = 1;
    bytes encrypted_data = 2;
```
</blockquote></details>

Agreed, that sounds good.


<!-- Sent from Reviewable.io -->

2021-06-28 17:40 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: all files reviewed, 11 unresolved discussions (waiting on @efoxepstein and @jmorrrr)

___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.h, line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md70bex4iGfTNHfIgG_:-MdIM8tA3mekMweQ5qY_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.h#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`#include <string>` too please
</blockquote></details>

Done.
___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 12 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md72I-K5h5C_dolD2gz:-MdILqql1VRIiLo8sWra:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L12)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since you have `strip_import_prefix` here, in your C++ files please use `#include "wfanet/panelmatch/client/eventpreprocessing/preprocess_events.pb.h"` (with the import prefix stripped).
</blockquote></details>

Done.
___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md72bGc22z7bRa_axwu:-MdIIGEvCZQAuSe2CArj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto#L19)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's possible the other proto files do this wrong but the `java_package` should be: `org.wfanet.panelmatch.protocol.protobuf` (with the leading `org.`)
</blockquote></details>

Done.
___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md72phoC_jEaFV6SUF2:-MdILJW_2EsVgsvQiyxa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How about `encrypted_id` and `encrypted_payload` to make it a little more obvious what the difference is between the request and the response? (And maybe rename this message to `EncryptedIdAndPayload`)
</blockquote></details>

Done.
___
*[.clwb/.bazelproject, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md1n89t3NdRb70XVyiY:-MdIhKOBEeNOuQdCUHHf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a71875f202c02c8e7ea134bb8f8a51b984531d5d/.clwb/.bazelproject#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm not seeing the change to `.gitignore`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-28 17:49 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: all files reviewed, 11 unresolved discussions (waiting on @efoxepstein and @jmorrrr)

___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md72phoC_jEaFV6SUF2:-MdIjKb66QM-N1WrFlWd:b-85wfd9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto#L38)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not seeing this change


<!-- Sent from Reviewable.io -->

2021-06-28 20:46 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: all files reviewed, 11 unresolved discussions (waiting on @efoxepstein, @jmorrrr, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md73HSG8g6sgiDgEWay:-MdIrPFU-5zBRxiWkaQk:b-896fix) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Could you please add `encrypt_original_data.cc` modeled after https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/cc/wfanet/panelmatch/protocol/crypto/deterministic_commutative_encryption_utility.cc?

This is the file that will call Erin's library. Since Erin's library isn't checked in yet, you can just have it do nothing for now:

```
absl::StatusOr<PreprocessEventsResponse> Convert(const PreprocessEventsRequest& request) {
  // TODO: call Erin's library
}
```

(Note: I'm also making a comment elsewhere that proposing renaming this function to `PreprocessEvents`.)
</blockquote></details>

Done.

---
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md70yag4ZaFITGgXj4O:-MdIqxbHEdUqywD3XV8k:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L4)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Could you add the `strip_include_prefix` thing found in similar C++ build files in this repo? See for example https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/cc/wfanet/panelmatch/protocol/crypto/BUILD.bazel#L15.

Once you do this, for the `#include` statements referencing files in this repo, you'll chop of the beginning (e.g. `#include "wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data.h"`).
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.h, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md71i0V0iWmkDL0KLA6:-MdIqZR7BPOpQCuyrB_g:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.h#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you change the function name here to `PreprocessEvents`? (Notice the pattern: `PreprocessEventsRequest -> PreprocessEvents -> PreprocessEventsResponse`)

Same comment applies to `encrypt_original_data.h`.

This means you should also rename all the files to `preprocess_events.{h,cc}` or `preprocess_events_wrapper.{h,cc}` as appropriate.
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.cc, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md71w5_-10_wGM_dFHI:-MdJ1U9K6GNhTsYJ73PL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.cc#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This should be calling the function you defined in `encrypt_original_data.h` (which another comment suggests renaming to just `PreprocessEvents`. That file should call Erin's code.
</blockquote></details>

Done.
___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdIUCsf2AHMseOBTlGe:-MdIlLCe4mpM4F30Vatp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'd prefer
```
message PreprocessEventsRequest {
  repeated UnprocessedEvent unprocessed_event = 1;
  message UnprocessedEvent {
    bytes id = 1;
    bytes data = 2;
  }

```
</blockquote></details>

Done.
___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md72phoC_jEaFV6SUF2:-MdIla3f3ChIy5Hy-M3H:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto#L38)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

not seeing this change
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-28 21:06 UTC, efoxepstein requested changes
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: all files reviewed, 11 unresolved discussions (waiting on @jmorrrr and @stevenwarejones)

___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 2 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdJQNxE0_VYlhFVM8td:-MdJQNxE0_VYlhFVM8te:b-66s0uw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50fb26247925f41b7bcdc8eff3eeee8dd779692d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L2)):*
> ```Starlark
> cc_library(
>   strip_include_prefix = "/src/main/cc",
> ```

autoformatting should re-sort these lines -- can you please autoformat?
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 10 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdJQM725CTJQJ6ANvxf:-MdJQM725CTJQJ6ANvxg:b8e15ze) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50fb26247925f41b7bcdc8eff3eeee8dd779692d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L10)):*
> ```Starlark
>     "@com_google_absl//absl/algorithm:container",
>     "//src/main/proto/wfanet/panelmatch/client/eventpreprocessing:preprocess_events_cc_proto",
>     #"//src/main/cc/wfanet/panelmatch/protocol/crypto/preprocess_events.h:PreprocessEvents",
> ```

Delete this line please.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdJQXckDSNCVGirXuoQ:-MdJQXckDSNCVGirXuoR:b-qhj0o9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50fb26247925f41b7bcdc8eff3eeee8dd779692d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc#L1)):*
> ```cpp
> #include <string>
> ```

Please add license headers
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 7 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdJQ_UaBmw2odgT2fzu:-MdJQ_UaBmw2odgT2fzv:b5837qt) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50fb26247925f41b7bcdc8eff3eeee8dd779692d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc#L7)):*
> ```cpp
> #inclue "src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.h"
> 
> namespace wfanet::panelmatch::client::PreprocessEvents {
> ```

Namespace should just be `wfanet::panelmatch::client` please
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 8 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdJQd7OA0-P14iCQ8JD:-MdJQd7OA0-P14iCQ8JE:b-ssvxw7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50fb26247925f41b7bcdc8eff3eeee8dd779692d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc#L8)):*
> ```cpp
> 
> namespace wfanet::panelmatch::client::PreprocessEvents {
>   absl::StatusOr<PreprocessEventsResponse> Convert(const PreprocessEventsRequest& request) {
> ```

Please rename this function to `PreprocessEvents`
___
*[src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdJR7nH5fLs3IaE0xLf:-MdJR7nIDG6lRm3bfgJG:b9nfoo1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50fb26247925f41b7bcdc8eff3eeee8dd779692d/src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L1)):*
> ```cpp
> //
> ```

Coming in a future commit, I presume?
___
*[src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper_test.cc, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdJRAAy14Xsf__fA0Jx:-MdJRAAy14Xsf__fA0Jy:b9nfoo1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50fb26247925f41b7bcdc8eff3eeee8dd779692d/src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper_test.cc#L1)):*
> ```cpp
> //
> ```

Coming in a future commit, I presume?
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.h, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md71i0V0iWmkDL0KLA6:-MdJQiPMAsCpD_bnPGPI:bfq07r7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.h#L23)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like you updated the namespace name instead of the function name. `Convert -> PreprocessEvents`.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc, line 30 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdJQstPBSX_2zpm9Y5v:-MdJQstPBSX_2zpm9Y5w:b-nj74xt) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50fb26247925f41b7bcdc8eff3eeee8dd779692d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc#L30)):*
> ```cpp
> }
> 
> }
> ```

Closing braces of namespaces should have a comment in the form of `// namespace wfanet::whatever::whatever`.


<!-- Sent from Reviewable.io -->

2021-06-28 22:12 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: 12 of 20 files reviewed, 10 unresolved discussions (waiting on @efoxepstein and @jmorrrr)



<!-- Sent from Reviewable.io -->

2021-06-29 10:40 UTC, efoxepstein requested changes
> Reviewed 1 of 8 files at r4, 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: all files reviewed, 6 unresolved discussions (waiting on @jmorrrr)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdMLgSYC3qAjUG5GObl:-MdMLgSYC3qAjUG5GObm:bvgd2c4) (no related file):*
The linter has a few complaints:

```
src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc:21:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
Done processing src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc
src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc:26:  Missing username in TODO; it should look like "// TODO(my_username): Stuff."  [readability/todo] [2]
src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc:15:  src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc should include its header file src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.h  [build/include] [5]
src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc:29:  Could not find a newline character at the end of the file.  [whitespace/ending_newline] [5]
src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.h:30:  #endif line should be "#endif  // SRC_MAIN_CC_WFANET_PANELMATCH_CLIENT_EVENTPREPROCESSING_PREPROCESS_EVENTS_H_"  [build/header_guard] [5]
src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.h:29:  #endif line should be "#endif  // SRC_MAIN_CC_WFANET_PANELMATCH_CLIENT_EVENTPREPROCESSING_PREPROCESS_EVENTS_WRAPPER_H_"  [build/header_guard] [5]
```

---
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 20 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdMKfGl9qID7fCD5h4C:-MdMKfGm-jPciAJKlcCg:bqdq5rw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2f5285ef9db41e0a6ea83aa8a8ecec2811bbcd1d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc#L20)):*
> ```cpp
> #include "wfanet/panelmatch/client/eventpreprocessing/preprocess_events.pb.h"
> #include "wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.h"
> #inclue \
> ```

Typo: "inclue" -> "include"
___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 33 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdMLJ6v0Pj15V0otMJN:-MdMLJ6v0Pj15V0otMJO:bqyfs6g) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2f5285ef9db41e0a6ea83aa8a8ecec2811bbcd1d/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto#L33)):*
> ```protobuf
> }
> 
> // Response of the PreprocessEventsRequest method
> ```

`// Response of the PreprocessEvents method` please
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.h, line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdMKwoL2UbQ_5EeZx3N:-MdMKwoL2UbQ_5EeZx3O:b-jcwjqf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2f5285ef9db41e0a6ea83aa8a8ecec2811bbcd1d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.h#L28)):*
> ```objc
> absl::StatusOr<std::string> PreprocessEvents(
>     const std::string& serialized_request);
> }
> ```

Namespace-closing braces should have a comment with the name of the namespace: https://google.github.io/styleguide/cppguide.html#Namespaces


<!-- Sent from Reviewable.io -->

2021-06-29 15:28 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein and @jmorrrr)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdMLgSYC3qAjUG5GObl:-MdN-eiPBVJVouK-kkW1:b-896fix) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The linter has a few complaints:

```
src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc:21:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
Done processing src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc
src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc:26:  Missing username in TODO; it should look like "// TODO(my_username): Stuff."  [readability/todo] [2]
src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc:15:  src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc should include its header file src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.h  [build/include] [5]
src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc:29:  Could not find a newline character at the end of the file.  [whitespace/ending_newline] [5]
src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.h:30:  #endif line should be "#endif  // SRC_MAIN_CC_WFANET_PANELMATCH_CLIENT_EVENTPREPROCESSING_PREPROCESS_EVENTS_H_"  [build/header_guard] [5]
src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.h:29:  #endif line should be "#endif  // SRC_MAIN_CC_WFANET_PANELMATCH_CLIENT_EVENTPREPROCESSING_PREPROCESS_EVENTS_WRAPPER_H_"  [build/header_guard] [5]
```
</blockquote></details>

Done.

---
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 2 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdJQNxE0_VYlhFVM8td:-MdJYSldACb695hN_A7G:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50fb26247925f41b7bcdc8eff3eeee8dd779692d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L2)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

autoformatting should re-sort these lines -- can you please autoformat?
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 10 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdJQM725CTJQJ6ANvxf:-MdJYTTWB14Xz_32vfSM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50fb26247925f41b7bcdc8eff3eeee8dd779692d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L10)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Delete this line please.
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdJQXckDSNCVGirXuoQ:-MdJXT_zBl88QQcXcFHJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50fb26247925f41b7bcdc8eff3eeee8dd779692d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please add license headers
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 7 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdJQ_UaBmw2odgT2fzu:-MdJYhG6CZ_xM3wFlM4Q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50fb26247925f41b7bcdc8eff3eeee8dd779692d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc#L7)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Namespace should just be `wfanet::panelmatch::client` please
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 8 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdJQd7OA0-P14iCQ8JD:-MdJYpGN0TdPpCwkh_YO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50fb26247925f41b7bcdc8eff3eeee8dd779692d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc#L8)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please rename this function to `PreprocessEvents`
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 20 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdMKfGl9qID7fCD5h4C:-MdMxXjM-8nL85ZPXad-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2f5285ef9db41e0a6ea83aa8a8ecec2811bbcd1d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Typo: "inclue" -> "include"
</blockquote></details>

Done.
___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 33 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdMLJ6v0Pj15V0otMJN:-MdMwFL18OB0rNINqhFu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2f5285ef9db41e0a6ea83aa8a8ecec2811bbcd1d/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`// Response of the PreprocessEvents method` please
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdJR7nH5fLs3IaE0xLf:-MdJXkpS-pJQ2O3M_KGJ:b2nhswy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50fb26247925f41b7bcdc8eff3eeee8dd779692d/src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Coming in a future commit, I presume?
</blockquote></details>

Yes
___
*[src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper_test.cc, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdJRAAy14Xsf__fA0Jx:-MdJRq2k8g4lPejBivAb:b8ap73b) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50fb26247925f41b7bcdc8eff3eeee8dd779692d/src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper_test.cc#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Coming in a future commit, I presume?
</blockquote></details>

Yes but I actually deleted this file because I am not doing unit testing for wrapper class
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/encrypt_original_data_wrapper.h, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md71i0V0iWmkDL0KLA6:-MdJaWFuBFQyAru0qRUG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c28684da95e06dc2e4d515bf2246f205da86f30/src/main/cc/wfanet/pa [...]

2021-06-29 15:32 UTC, efoxepstein requested changes
> Reviewed 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: all files reviewed, 3 unresolved discussions (waiting on @jmorrrr)

___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 29 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdNOVbN9WQtnWad1zCE:-MdNOVbN9WQtnWad1zCF:b-6kn611) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2e51a21edd635f84a3cb2a5f8be60d1c000a5ea5/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc#L29)):*
> ```cpp
>   return absl::UnimplementedError("Not implemented");
> }
> }  // namespace wfanet::panelmatch::client
> ```

This file should end in a newline (the autoformatter should do this?) But if it doesn't, please manually do it.
___
*[src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdJR7nH5fLs3IaE0xLf:-MdNOO1j8KCfvBHO2q-1:b6gm6lp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50fb26247925f41b7bcdc8eff3eeee8dd779692d/src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L1)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

Yes
</blockquote></details>

OK, leaving this comment open until you have your test ready.


<!-- Sent from Reviewable.io -->

2021-06-30 17:12 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-Md748tDE3wGVfjzN4HY:-MdSr93m94isgDW3n28x:b-896fix) (no related file):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I approve once Eli approves.
</blockquote></details>

Done.

---
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 29 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdNOVbN9WQtnWad1zCE:-MdN_vIm3QTcC2_47Q-V:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2e51a21edd635f84a3cb2a5f8be60d1c000a5ea5/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This file should end in a newline (the autoformatter should do this?) But if it doesn't, please manually do it.
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdJR7nH5fLs3IaE0xLf:-MdSrAfR7S2hooKEeB5r:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50fb26247925f41b7bcdc8eff3eeee8dd779692d/src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

OK, leaving this comment open until you have your test ready.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-30 17:50 UTC, efoxepstein requested changes
> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: all files reviewed, 3 unresolved discussions (waiting on @jmorrrr)

___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 24 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdT1Xtc9cNVECFWcvxS:-MdT1Xtc9cNVECFWcvxT:berjh3z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/259119b095c70892abd98508044fba06ab1ca42a/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto#L24)):*
> ```protobuf
> // Request to preprocess event data
> message PreprocessEventsRequest {
>   repeated UnprocessedEvent unprocessed_event = 1;
> ```

Please pluralize this
___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 35 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdT1ZT6A2G8z78WiqfZ:-MdT1ZT6A2G8z78Wiqf_:berjh3z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/259119b095c70892abd98508044fba06ab1ca42a/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto#L35)):*
> ```protobuf
> // Response of the PreprocessEvents method
> message PreprocessEventsResponse {
>   repeated ProcessedEvent processed_event = 1;
> ```

Please pluralize this
___
*[src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 55 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdT1Hux7nsx2HY1L1cq:-MdT1Hux7nsx2HY1L1cr:buheeuj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/259119b095c70892abd98508044fba06ab1ca42a/src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L55)):*
> ```cpp
>   PreprocessEventsRequest test_request;
> 
>   PreprocessEventsRequest_UnprocessedEvent test_unprocessed;
> ```

Is this unused?

I think what you want is:

```
PreprocessEventsRequest test_request;
PreprocessEventsRequest::UnprocessedEvent* unprocessed_event = test_request.add_unprocessed_events();  // Note that this is assuming you do my comments on the proto first.
unprocessed_event->set_id(test_id);
unprocessed_event->set_data(test_data);

test_request.set_crypto_key(...);
test_request.set_pepper(...);
```


<!-- Sent from Reviewable.io -->

2021-06-30 18:22 UTC, efoxepstein approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-:-MdT8zEi7vU4DYhzRxNq:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @enfreck and @jmorrrr)



<!-- Sent from Reviewable.io -->

2021-06-30 18:23 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @enfreck)

___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 24 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdT1Xtc9cNVECFWcvxS:-MdT2Q1I7f2xyJ8BGy99:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/259119b095c70892abd98508044fba06ab1ca42a/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto#L24)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please pluralize this
</blockquote></details>

Done.
___
*[src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 35 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdT1ZT6A2G8z78WiqfZ:-MdT2QPHB_HydPmT_Wiz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/259119b095c70892abd98508044fba06ab1ca42a/src/main/proto/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.proto#L35)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please pluralize this
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 55 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30#-MdT1Hux7nsx2HY1L1cq:-MdT9EyY1LYN84klQjuV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/259119b095c70892abd98508044fba06ab1ca42a/src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is this unused?

I think what you want is:

```
PreprocessEventsRequest test_request;
PreprocessEventsRequest::UnprocessedEvent* unprocessed_event = test_request.add_unprocessed_events();  // Note that this is assuming you do my comments on the proto first.
unprocessed_event->set_id(test_id);
unprocessed_event->set_data(test_data);

test_request.set_crypto_key(...);
test_request.set_pepper(...);
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-30 18:26 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck, @kunyuchen, and @oliver-amzn)



<!-- Sent from Reviewable.io -->

2021-06-30 18:34 UTC, enfreck approved these changes
> Reviewed 3 of 14 files at r1, 1 of 12 files at r2, 1 of 9 files at r3, 3 of 6 files at r6, 3 of 4 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kunyuchen and @oliver-amzn)



<!-- Sent from Reviewable.io -->

2021-06-30 19:23 UTC, matthewclegg approved these changes
Looks good!

2021-06-30 19:30 UTC, merged