add initial support for passing aws creds to Dataflow
world-federation-of-advertisers/panel-exchange-client pull request #350
Opened 2022-07-20 16:47 UTC by stevenwarejones

Tested using a custom local Daemon

2022-07-20 23:13 UTC, robinsons requested changes
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/350)* status: all files reviewed, 2 unresolved discussions (waiting on @jonmolle and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageBeamTask.kt` line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/350#-N7SrlFG2tO5qMgvC6WN:-N7SrlFG2tO5qMgvC6WO:bhz3tw6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b1c70d12ce37875e0fb74c1e47f514c534dde5c8/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageBeamTask.kt#L57)):*
> ```Kotlin
>     pipeline.apply("Generate Shard Names", Create.of(shardedFileName.fileNames.asIterable()))
>   val writeFilesDoFn =
>     object : DoFn<String, String>() {
> ```

Could we make a dedicated class for this instead of an anonymous object?
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyToSharedStorageBeamTask.kt` line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/350#-N7Srvtj4AxKFY4K1gVj:-N7Srvtj4AxKFY4K1gVk:brhumzt) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b1c70d12ce37875e0fb74c1e47f514c534dde5c8/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyToSharedStorageBeamTask.kt#L51)):*
> ```Kotlin
>   }
>   val readFilesDoFn =
>     object : DoFn<String, String>() {
> ```

Same here.


<!-- Sent from Reviewable.io -->

2022-07-21 17:57 UTC, jonmolle requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/350)* status: 11 of 15 files reviewed, 3 unresolved discussions (waiting on @jonmolle, @robinsons, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GoogleCloudExampleDaemon.kt` line 170 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/350#-N7WtnmWDmQzBvUzbMuW:-N7WtnmWDmQzBvUzbMuX:b-qo1xnj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b1c70d12ce37875e0fb74c1e47f514c534dde5c8/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GoogleCloudExampleDaemon.kt#L170)):*
> ```Kotlin
>       // aws-sdk-java-v2 casts responses to AwsSessionCredentials if its assumed you need a
>       // sessionToken
>       val awsCredentials =
> ```

Does this assume you're going to be using the same AWS Credentials for all S3 connections across all exchanges?



_Code quote:_
```Kotlin
        DefaultCredentialsProvider.create().resolveCredentials() as AwsSessionCredentials
```


<!-- Sent from Reviewable.io -->

2022-07-21 18:31 UTC, jonmolle requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/350)* status: 11 of 19 files reviewed, 3 unresolved discussions (waiting on @jonmolle, @robinsons, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GoogleCloudExampleDaemon.kt` line 170 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/350#-N7WtnmWDmQzBvUzbMuW:-N7X-06LEQetoulVYgpf:bfv7xqk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b1c70d12ce37875e0fb74c1e47f514c534dde5c8/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GoogleCloudExampleDaemon.kt#L170)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

Does this assume you're going to be using the same AWS Credentials for all S3 connections across all exchanges?
</blockquote></details>

Sorry, to follow this up, I think the paradigm is to keep all factory options within the storage details of the appropriate storageclient. I realize that we can't just have a session token hard-coded somewhere. I ask about how the credentials here are generated in part because if possible it would be cleaner to move this into the s3 storage details if possible. From what I can gather from this PR, that would involve some sort of check (either implicitly through checking existence of aws credentials or explicitly stating) whether we expect to get AWS credentials from the environment or the details object. That seems like it would allow us to support multiple different credentials per-partner, though, which I'm not sure this does. Am I off-base here? I'm also not against making this change is a downstream PR if that TODO on the line below this is referring to this change.  


<!-- Sent from Reviewable.io -->

2022-07-22 18:02 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/350)* status: 10 of 19 files reviewed, 3 unresolved discussions (waiting on @jonmolle and @robinsons)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GoogleCloudExampleDaemon.kt` line 170 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/350#-N7WtnmWDmQzBvUzbMuW:-N7b-G3M3JuxgV-QbEej:b-iht1qv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b1c70d12ce37875e0fb74c1e47f514c534dde5c8/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GoogleCloudExampleDaemon.kt#L170)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

Sorry, to follow this up, I think the paradigm is to keep all factory options within the storage details of the appropriate storageclient. I realize that we can't just have a session token hard-coded somewhere. I ask about how the credentials here are generated in part because if possible it would be cleaner to move this into the s3 storage details if possible. From what I can gather from this PR, that would involve some sort of check (either implicitly through checking existence of aws credentials or explicitly stating) whether we expect to get AWS credentials from the environment or the details object. That seems like it would allow us to support multiple different credentials per-partner, though, which I'm not sure this does. Am I off-base here? I'm also not against making this change is a downstream PR if that TODO on the line below this is referring to this change.  
</blockquote></details>

A couple clarifying points:
1. These are short-lived credentials that typically only last one hour
2. They are generated in the ExchangeTaskMapper when the task is generated on the client side
3. I'm not sure about the best way to pull this into the storageFactory config. The storageFactory config is set one time and used over and over again. These creds change all the time.

I've added a TODO to think about this a little more
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageBeamTask.kt` line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/350#-N7SrlFG2tO5qMgvC6WN:-N7b3oN_4Abu1D3S6UMV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b1c70d12ce37875e0fb74c1e47f514c534dde5c8/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageBeamTask.kt#L57)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Could we make a dedicated class for this instead of an anonymous object?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyToSharedStorageBeamTask.kt` line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/350#-N7Srvtj4AxKFY4K1gVj:-N7b3olZC4KQ49v-JUyT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b1c70d12ce37875e0fb74c1e47f514c534dde5c8/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyToSharedStorageBeamTask.kt#L51)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-22 18:14 UTC, jonmolle approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/350)* status: 10 of 19 files reviewed, 2 unresolved discussions (waiting on @robinsons)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GoogleCloudExampleDaemon.kt` line 170 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/350#-N7WtnmWDmQzBvUzbMuW:-N7b4vBODiZt_weWQaPi:b-2n0hdb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b1c70d12ce37875e0fb74c1e47f514c534dde5c8/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GoogleCloudExampleDaemon.kt#L170)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

A couple clarifying points:
1. These are short-lived credentials that typically only last one hour
2. They are generated in the ExchangeTaskMapper when the task is generated on the client side
3. I'm not sure about the best way to pull this into the storageFactory config. The storageFactory config is set one time and used over and over again. These creds change all the time.

I've added a TODO to think about this a little more
</blockquote></details>

That's good enough for me at least for now (IE: for a PoC). I think some of this may be a non-issue; specifically since you can grant a single service account access to multiple buckets, having a single aws account associated with the daemon is probably okay. I was more thinking about if it might be doable to actually generate these session credentials within the factory (moving the long-lived keys that are pulled here to storageDetails fields). If that's infeasible this seems okay, though.


<!-- Sent from Reviewable.io -->

2022-07-22 19:45 UTC, robinsons approved these changes
> Reviewed 2 of 4 files at r2, 4 of 4 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/350)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-07-22 21:27 UTC, merged