[WIP] initial terraform setup
world-federation-of-advertisers/panel-exchange-client pull request #351
Opened 2022-07-27 18:38 UTC by bdomen-ggl

2022-08-16 19:01 UTC, bdomen-ggl reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351)* status: 0 of 18 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @jonmolle, @SanjayVas, and @stevenwarejones)

___
*[`src/main/docker/images.bzl` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-N9brbJI4qt8d9mqbHqS:-N9c0_Gw5wbal0acLWIm:b-pwpq2a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/05473b219d4039b15d6a64b5770ce0fdbedefeeb/src/main/docker/images.bzl#L19)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

Can you clean up this test code?
</blockquote></details>

Yes, I'm in the process of this. I was saving this one for last as I was worried earlier that I might accidentally publish an image to the GCS Container Registry. Since I'm all hooked up to AWS now, there's no worry for that and I can do this now.
___
*[`src/main/docker/images.bzl` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-N9bro7S9O-5tcvB1yvV:-N9c-ztX2UVjWaMy9rIs:b-leqck) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/05473b219d4039b15d6a64b5770ce0fdbedefeeb/src/main/docker/images.bzl#L27)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Yes, this one will be named more like the original version.


<!-- Sent from Reviewable.io -->

2022-08-16 19:38 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351)* status: 0 of 18 files reviewed, all discussions resolved (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/docker/images.bzl` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-N9brbJI4qt8d9mqbHqS:-N9c9ZDA6qF3r55SkNuS:blyphgc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/05473b219d4039b15d6a64b5770ce0fdbedefeeb/src/main/docker/images.bzl#L19)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Yes, I'm in the process of this. I was saving this one for last as I was worried earlier that I might accidentally publish an image to the GCS Container Registry. Since I'm all hooked up to AWS now, there's no worry for that and I can do this now.
</blockquote></details>

No problem!


<!-- Sent from Reviewable.io -->

2022-08-17 13:33 UTC, stevenwarejones requested changes
> Reviewed 7 of 18 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351)* status: 9 of 18 files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl, @duliomatos1, and @SanjayVas)

___
*[`src/main/k8s/dev/example_edp_daemon_aws.cue` line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-N9fzo0O8x05HZkbFhMY:-N9fzo0PAQ9s40JL0ZnM:bea68fb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8551d4f5a02641975f988599a7b3835f4276f527/src/main/k8s/dev/example_edp_daemon_aws.cue#L27)):*
> ```CUE
> 		keyFile:  "/var/run/secrets/files/edp1_tls.key"
> 	}
> 	tinkKeyUri: "gcp-kms://projects/halo-cmm-dev/locations/us-central1/keyRings/edp-test-key-ring/cryptoKeys/edp-test-key"
> ```

using gcp kms on aws?


<!-- Sent from Reviewable.io -->

2022-08-17 17:32 UTC, stevenwarejones reviewed
> Reviewed 1 of 2 files at r6, 5 of 19 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351)* status: 6 of 28 files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl, @duliomatos1, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-08-18 21:00 UTC, stevenwarejones requested changes
> Reviewed 2 of 2 files at r5, 7 of 19 files at r7, 4 of 7 files at r8, 1 of 3 files at r9, 1 of 4 files at r10, 3 of 4 files at r12, 8 of 10 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351)* status: 29 of 31 files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/k8s/dev/example_daemon_gke.cue` line 64 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-N9mjS7B412gAtF7L3KN:-N9mjS7B412gAtF7L3KO:b7ssk7u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1225b377edfab6d8e2115759024d11413465c687/src/main/k8s/dev/example_daemon_gke.cue#L64)):*
> ```CUE
> 		workerMachineType:                  *"n1-standard-1" | string
> 		diskSize:                           *"30" | string
> 		dataflowWorkerLoggingOptionsLevel:  *"INFO" | string
> ```

are we thinking the default values shouldn't be explicitly set here? Its kind of nice to enumerate all the possible options
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 192 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-N9mkGib0fEzz7KQgCS1:-N9mkGib0fEzz7KQgCS2:boed9yf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c40a622a46053b408e99218a7ffc0070f5446fe6/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L192)):*
> ```Kotlin
>   }
> 
>   override val rootStorageClient: StorageClient by lazy { S3StorageClient(S3Client.builder().region(Region.of(s3Region)).build(), s3Bucket) }
> ```

maybe we should rename s3Region to `rootStorageS3Region` wdyt?
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GoogleCloudExampleDaemon.kt` line 162 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-N9mjpEN3Wsj2gysLnP4:-N9mjpEN3Wsj2gysLnP5:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c957037c32e1a3a963d90d583a547d1ac4d76be9/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GoogleCloudExampleDaemon.kt#L162)):*
> ```Kotlin
>         maxNumWorkers = dataflowMaxNumWorkers
>         diskSizeGb = dataflowDiskSize
>         defaultWorkerLogLevel = DataflowWorkerLoggingOptions.Level.DEBUG
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-08-18 21:24 UTC, bdomen-ggl reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351)* status: 28 of 31 files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/docker/images.bzl` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-N9brbJI4qt8d9mqbHqS:-N9mopw21qYRS6W9YqGS:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/05473b219d4039b15d6a64b5770ce0fdbedefeeb/src/main/docker/images.bzl#L19)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

No problem!
</blockquote></details>

Done
___
*[`src/main/k8s/dev/example_edp_daemon_aws.cue` line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-N9fzo0O8x05HZkbFhMY:-N9mmKYzD8Cm0HSl5OlD:b-otc3b8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8551d4f5a02641975f988599a7b3835f4276f527/src/main/k8s/dev/example_edp_daemon_aws.cue#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

using gcp kms on aws?
</blockquote></details>

Nope, I didn't update the key at that time.

It's removed now as a script will populate the uri. KMS key ids are dynamically generated. There are some operations that allow the usage of the alias instead of the id and there are some operations that do not allow the usage of an alias. To be safe, I'm updating with the id instead of the alias.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 192 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-N9mkGib0fEzz7KQgCS1:-N9mnFgh1soPu_61j60e:b-wb3lma) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c40a622a46053b408e99218a7ffc0070f5446fe6/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L192)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

maybe we should rename s3Region to `rootStorageS3Region` wdyt?
</blockquote></details>

I'm pretty bad with naming so I'm open to suggestions. I like keeping s3Region as the region is most often the same to all the AWS API calls and not specific to root storage. If exceptions are needed, I think we can create specific variables for those cases.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GoogleCloudExampleDaemon.kt` line 162 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-N9mjpEN3Wsj2gysLnP4:-N9mokGZ3Y3HVHUzUa4R:b-i8g0ss) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c957037c32e1a3a963d90d583a547d1ac4d76be9/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GoogleCloudExampleDaemon.kt#L162)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

I'm fine with the name as is, but also open to suggestions here.


<!-- Sent from Reviewable.io -->

2022-09-06 13:08 UTC, stevenwarejones requested changes
> Reviewed 19 of 29 files at r18, 9 of 14 files at r19, 4 of 6 files at r20, 8 of 8 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351)* status: 48 of 49 files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 169 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-NBHtf_pByEUoGFUUKvk:-NBHtf_pByEUoGFUUKvl:bxmgz0y) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1421aa2fe51090e4804648d9351329ad832e7e10/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L169)):*
> ```Kotlin
>         tempLocation = dataflowTempLocation
>         serviceAccount = dataflowServiceAccount
>         workerMachineType = dataflowWorkerMachineType
> ```

we should still be passing in machine type preferences
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 87 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-NBHt_ui6dr6mSi54AhK:-NBHt_ui6dr6mSi54AhL:b-5qkywg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e9b2f5e18e9d29eaffaa8ff15ff46358b8b6258/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L87)):*
> ```Kotlin
>     val baseOptions =
>       PipelineOptionsFactory.`as`(BeamOptions::class.java).apply {
>         runner = DirectRunner::class.java
> ```

we shouldn't be using the DirectRunner in production
___
*[`src/main/terraform/modules/panel-exchange-client/ca_root.tf` line 17 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-NBHuHv39pFx9uyLwn8d:-NBHuHv39pFx9uyLwn8e:b-x57f7a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e9b2f5e18e9d29eaffaa8ff15ff46358b8b6258/src/main/terraform/modules/panel-exchange-client/ca_root.tf#L17)):*
> ```HCL
>   validity {
>     type  = "DAYS"
>     value = 365
> ```

@sanjayvas - what default are we preferring for root certs? 5 years?
___
*[`src/main/terraform/modules/panel-exchange-client/ca_sub.tf` line 17 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-NBHuUlACXz8wDigG-Us:-NBHuUlACXz8wDigG-Ut:bcagzjk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e9b2f5e18e9d29eaffaa8ff15ff46358b8b6258/src/main/terraform/modules/panel-exchange-client/ca_sub.tf#L17)):*
> ```HCL
>   validity {
>     type  = "DAYS"
>     value = 364
> ```

maybe just 365? esp if you increase root length


<!-- Sent from Reviewable.io -->

2022-09-06 15:21 UTC, bdomen-ggl reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351)* status: 48 of 49 files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/k8s/dev/example_daemon_gke.cue` line 64 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-N9mjS7B412gAtF7L3KN:-NBIKN28DtvqodC1K3af:b-gwg8c9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1225b377edfab6d8e2115759024d11413465c687/src/main/k8s/dev/example_daemon_gke.cue#L64)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

are we thinking the default values shouldn't be explicitly set here? Its kind of nice to enumerate all the possible options
</blockquote></details>

We could? I'm not familiar with the possible options. I added the example_daemon_aws.cue, which I mostly copied from the example_daemon_gke.cue.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 87 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-NBHt_ui6dr6mSi54AhK:-NBIHJo5B-6hNZ7lpnsu:bukbg72) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e9b2f5e18e9d29eaffaa8ff15ff46358b8b6258/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L87)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

we shouldn't be using the DirectRunner in production
</blockquote></details>

This file comes from another branch. I'll see if there was a merge problem or whatnot.
___
*[`src/main/terraform/modules/panel-exchange-client/ca_root.tf` line 17 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-NBHuHv39pFx9uyLwn8d:-NBIJsVT4D0TKrytUl1r:b-62egxd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e9b2f5e18e9d29eaffaa8ff15ff46358b8b6258/src/main/terraform/modules/panel-exchange-client/ca_root.tf#L17)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@sanjayvas - what default are we preferring for root certs? 5 years?
</blockquote></details>

I think I had a problem with 5 years being too long. I'll double check this. I found other documentation that indicates 13 months, but it didn't seem to be specifically for creating a private ACM.
___
*[`src/main/terraform/modules/panel-exchange-client/ca_sub.tf` line 17 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-NBHuUlACXz8wDigG-Us:-NBIHYdk0ByI9Xs8vRcH:b-utyg73) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e9b2f5e18e9d29eaffaa8ff15ff46358b8b6258/src/main/terraform/modules/panel-exchange-client/ca_sub.tf#L17)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

maybe just 365? esp if you increase root length
</blockquote></details>

I ran into a problem that the certs get created too fast despite the subroot is dependent on the root being created first. AWS thinks the subroot doesn't expire soon enough and I was getting an error creating the resources.


<!-- Sent from Reviewable.io -->

2022-09-06 16:34 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351)* status: 48 of 49 files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/k8s/dev/example_daemon_gke.cue` line 62 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-NBIYXIa69DnCym81P5V:-NBIYXIa69DnCym81P5W:bxuur1z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2a8a27cdfcb79708e99f43a6832f137d2851856e/src/main/k8s/dev/example_daemon_gke.cue#L62)):*
> ```CUE
> 		serviceAccount:                     string
> 		tempLocation:                       *"gs://\(cloudStorageBucket)/dataflow-temp/" | string
> 		workerMachineType:                  *"n1-standard-1" | string
> ```

is this worker type available on aws?


<!-- Sent from Reviewable.io -->

2022-09-06 17:00 UTC, bdomen-ggl reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351)* status: 48 of 49 files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/k8s/dev/example_daemon_gke.cue` line 62 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-NBIYXIa69DnCym81P5V:-NBIjGWp-Nz375rADEeC:blvtedb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2a8a27cdfcb79708e99f43a6832f137d2851856e/src/main/k8s/dev/example_daemon_gke.cue#L62)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is this worker type available on aws?
</blockquote></details>

Not sure, but this is the GKE config file. The AWS config file doesn't support dataflow.


<!-- Sent from Reviewable.io -->

2022-09-06 20:14 UTC, stevenwarejones requested changes
> Reviewed 1 of 14 files at r19, 7 of 7 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351)* status: all files reviewed, 2 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/terraform/modules/panel-exchange-client/ca_sub.tf` line 17 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-NBHuUlACXz8wDigG-Us:-NBJR8Ap5IUtUCaoVPGK:b-iffn5g) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e9b2f5e18e9d29eaffaa8ff15ff46358b8b6258/src/main/terraform/modules/panel-exchange-client/ca_sub.tf#L17)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

I ran into a problem that the certs get created too fast despite the subroot is dependent on the root being created first. AWS thinks the subroot doesn't expire soon enough and I was getting an error creating the resources.
</blockquote></details>

the subroots should have a shorter lifespan, right? 1 year?


<!-- Sent from Reviewable.io -->

2022-09-07 15:41 UTC, bdomen-ggl reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351)* status: 43 of 49 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/terraform/modules/panel-exchange-client/ca_sub.tf` line 17 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351#-NBHuUlACXz8wDigG-Us:-NBNaMYX2b6XnR7abuMs:be8tjm0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e9b2f5e18e9d29eaffaa8ff15ff46358b8b6258/src/main/terraform/modules/panel-exchange-client/ca_sub.tf#L17)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

the subroots should have a shorter lifespan, right? 1 year?
</blockquote></details>

Thanks, was trying to copy an example as best as I could. Updated to be one year for the subroot and 5 years for the root certs.


<!-- Sent from Reviewable.io -->

2022-09-07 17:30 UTC, stevenwarejones approved these changes
> Reviewed 6 of 6 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-09-27 18:36 UTC, stevenwarejones approved these changes
> Reviewed 7 of 7 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-10-17 19:08 UTC, jonmolle approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/351)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-10-17 19:18 UTC, merged