Fix issues with certificate authority
world-federation-of-advertisers/panel-exchange-client pull request #358
Opened 2022-10-14 03:58 UTC by jonmolle

Fixes a common transient error in PrivateCAClient

Also adds clarity in storage selector errors to make IDing issues easier.

2022-10-25 16:27 UTC, duliomatos1 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/358)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl, @jonmolle, and @sandip80)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt` line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/358#-NFEuGDeCzutItOi_yQ7:-NFEuGDeCzutItOi_yQ8:b-3h9plp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0cb391089ec085bcb5177e4ecad5057476c38159/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt#L52)):*
> ```Kotlin
>   private val certificateAuthorityArn: String,
>   private val client: CreateCertificateClient,
>   private val generateKeyPair: () -> KeyPair = { generateKeyPair("RSA") }
> ```

Any reason to prefer RSA over ECDSA for AWS?  


<!-- Sent from Reviewable.io -->

2022-10-31 21:35 UTC, stevenwarejones requested changes
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/358)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @bdomen-ggl, @jonmolle, and @sandip80)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageDetailsProvider.kt` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/358#-NFjxTOXBZlGQ66oI4rs:-NFjxTOXBZlGQ66oI4rt:bilz4hy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0cb391089ec085bcb5177e4ecad5057476c38159/src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageDetailsProvider.kt#L28)):*
> ```Kotlin
> class StorageDetailsProvider(
>   private val secretMap: MutableSecretMap,
>   private val detailsType: String = "Private"
> ```

I'm not sure I like just passing around debug details esp with its already contained in the storage client  in the prefix. What about adding a getNonNullableBlog function to StorageClient that throws the debug info you are looking for?


<!-- Sent from Reviewable.io -->

2022-11-01 21:02 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/358)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, @sandip80, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageDetailsProvider.kt` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/358#-NFjxTOXBZlGQ66oI4rs:-NFouGDd8Yf5TU8M-Lth:box8zwb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0cb391089ec085bcb5177e4ecad5057476c38159/src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageDetailsProvider.kt#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm not sure I like just passing around debug details esp with its already contained in the storage client  in the prefix. What about adding a getNonNullableBlog function to StorageClient that throws the debug info you are looking for?
</blockquote></details>

I looked at doing this and I think it is a bit overkill. But my own changes are unnecessary and awkward. The stack trace shows which storage selector had the error, so this can be easily inferred without issue. The problem before was it was always calling it "private storage" even in the shared storage selector.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt` line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/358#-NFEuGDeCzutItOi_yQ7:-NFouLYJDdHjO96S8DBN:b8lhe3k) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0cb391089ec085bcb5177e4ecad5057476c38159/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt#L52)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Any reason to prefer RSA over ECDSA for AWS?  
</blockquote></details>

It isn't supported! Well, it is, but you can't generate certificates from a private EC CA in the same way, so it is effectively useless for our needs. You can reproduce this by making a ECDSA CA and then trying to issue a certificate in the web UI or CLI.


<!-- Sent from Reviewable.io -->

2022-11-02 21:18 UTC, stevenwarejones approved these changes
> Reviewed 1 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/358)* status: all files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl, @duliomatos1, and @sandip80)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageDetailsProvider.kt` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/358#-NFjxTOXBZlGQ66oI4rs:-NFuCJD60hoARC9yFam-:b-joddjj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0cb391089ec085bcb5177e4ecad5057476c38159/src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageDetailsProvider.kt#L28)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

I looked at doing this and I think it is a bit overkill. But my own changes are unnecessary and awkward. The stack trace shows which storage selector had the error, so this can be easily inferred without issue. The problem before was it was always calling it "private storage" even in the shared storage selector.
</blockquote></details>

sounds good to me


<!-- Sent from Reviewable.io -->

2022-11-03 17:09 UTC, duliomatos1 approved these changes
> Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/358)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bdomen-ggl and @sandip80)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt` line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/358#-NFEuGDeCzutItOi_yQ7:-NFySvVW-fhH4ERe6P_X:b-f3gain) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0cb391089ec085bcb5177e4ecad5057476c38159/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt#L52)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

It isn't supported! Well, it is, but you can't generate certificates from a private EC CA in the same way, so it is effectively useless for our needs. You can reproduce this by making a ECDSA CA and then trying to issue a certificate in the web UI or CLI.
</blockquote></details>

got it, thanks


<!-- Sent from Reviewable.io -->

2022-11-03 18:46 UTC, merged

2022-11-04 16:31 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/358)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageDetailsProvider.kt` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/358#-NFjxTOXBZlGQ66oI4rs:-NG2Tqi88nY8ktPCnB9W:b5gfty1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0cb391089ec085bcb5177e4ecad5057476c38159/src/main/kotlin/org/wfanet/panelmatch/client/storage/StorageDetailsProvider.kt#L28)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

Great! Anything other changes you'd like to see?
</blockquote></details>

no - I approved it already. are you wanting comments on anything specific?


<!-- Sent from Reviewable.io -->

2022-11-04 16:32 UTC, stevenwarejones reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/358#-:-NG2U9RcCY3dL9he8l7p:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->