Adds Kotlin Interface and Implementation
world-federation-of-advertisers/panel-exchange-client pull request #37
Opened 2021-07-01 20:57 UTC by jmorrrr

Creates SWIG-compatible Kotlin interface as well as an implementation of the interface using the JNI library.

2021-07-02 14:12 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @jmorrrr)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-MdbYIEO8pZc0f517SXs:-MdbYIEO8pZc0f517SXt:b-y8ge9s) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L23)):*
> ```Kotlin
> import wfanet.panelmatch.client.PreprocessEventsResponse
> 
> /** A [PreprocessEvents] implementation using the JNI [PreprocessEvents]. */
> ```

I'm not sure about style for Kotlin, but I think the preference is to use // instead of /**
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-MdbYhZt5lN_vwizf7FO:-MdbYhZt5lN_vwizf7FP:b-928heh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L36)):*
> ```Kotlin
>   }
> 
>   override fun PreprocessEvents(request: PreprocessEventsRequest): PreprocessEventsResponse {
> ```

Would it be a good idea to set up tests for this now, or will it just be handled later?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-MdbYUpa9HYapnym5x9-:-MdbYUpa9HYapnym5x90:bhmil10) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt#L21)):*
> ```Kotlin
> 
> interface PreprocessEvents {
>   /** Runs Erin's Encryption Code */
> ```

Eventually, this comment will need to be changed to reflect what the method will do


<!-- Sent from Reviewable.io -->

2021-07-02 14:36 UTC, efoxepstein requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37)* status: all files reviewed, 6 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-MdbYIEO8pZc0f517SXs:-MdbcR668X2IiF6Q6gTy:b-vqrskm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L23)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

I'm not sure about style for Kotlin, but I think the preference is to use // instead of /**
</blockquote></details>

For KDoc (the Kotlin version of JavaDoc) we use `/** ... */`. In other words, what's here is fine.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Mdbcb2f9GmUlwDyRRsV:-Mdbcb2f9GmUlwDyRRsW:bekfozc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L25)):*
> ```Kotlin
> /** A [PreprocessEvents] implementation using the JNI [PreprocessEvents]. */
> class JniPreprocessEvents : PreprocessEvents {
>   /** Indicates something went wrong in C++. */
> ```

Please pull JniException out to file `JniException.kt`.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-MdbcfoB64XEq0TMZnCW:-MdbcfoC4AFXkSSHoy5T:blqlz17) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L28)):*
> ```Kotlin
>   class JniException(cause: Throwable) : RuntimeException(cause)
> 
>   private fun <T> wrapJniException(block: () -> T): T {
> ```

Please pull this function out into `JniException.kt` (and it won't need to be private anymore)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-MdbYhZt5lN_vwizf7FO:-MdbclCE41CxmefGZEHo:bt4j37v) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L36)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Would it be a good idea to set up tests for this now, or will it just be handled later?
</blockquote></details>

+1, please add tests
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Mdbd8gf0z8dQxLdxSUw:-Mdbd8gf0z8dQxLdxSUx:byyo9kj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt#L20)):*
> ```Kotlin
> import wfanet.panelmatch.client.PreprocessEventsResponse
> 
> interface PreprocessEvents {
> ```

Please add a comment for the interface. This should be the more detailed comment (the comment on `PreprocessEvents` can be shorter and less detailed).

It should roughly match whatever comment is on Erin's interface.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-MdbYUpa9HYapnym5x9-:-MdbcqfY-pRzEbY-xFWD:b-e1kgus) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt#L21)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Eventually, this comment will need to be changed to reflect what the method will do
</blockquote></details>

Agreed -- can you update it now to give a more detailed description of what it does?


<!-- Sent from Reviewable.io -->

2021-07-02 15:48 UTC, matthewclegg requested changes

2021-07-02 15:48 UTC, matthewclegg commented on src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt
> +            "panel_exchange_client/src/main/swig/wfanet/panelmatch/client/eventpreprocessing"
Define this path as a constant?

2021-07-02 21:08 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37)* status: all files reviewed, 7 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-MdbYIEO8pZc0f517SXs:-MdbduwT130FQP7rKrYI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

For KDoc (the Kotlin version of JavaDoc) we use `/** ... */`. In other words, what's here is fine.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Mdbcb2f9GmUlwDyRRsV:-MdcCWW77CzYe1Mps5rG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please pull JniException out to file `JniException.kt`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-MdbcfoB64XEq0TMZnCW:-MdcCVpzC-po9WaVgQTK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please pull this function out into `JniException.kt` (and it won't need to be private anymore)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-MdbYhZt5lN_vwizf7FO:-Mdd2Mcq9LqiwKgnGAYK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L36)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

+1, please add tests
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-MdYrxQYBUNwbgw3vbdx-r1-46:-MdcEusCENcsZjRXYc1B:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L46)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Define this path as a constant?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Mdbd8gf0z8dQxLdxSUw:-MdcB_siA_WfT7BbBOCn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please add a comment for the interface. This should be the more detailed comment (the comment on `PreprocessEvents` can be shorter and less detailed).

It should roughly match whatever comment is on Erin's interface.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-MdbYUpa9HYapnym5x9-:-MdcB_jIEcTSctCgblvV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt#L21)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Agreed -- can you update it now to give a more detailed description of what it does?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-07 11:37 UTC, efoxepstein requested changes
> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37)* status: all files reviewed, 12 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-MdbYUpa9HYapnym5x9-:-Me-ipCM8fv3A9lG6JjD:bgd5vni) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt#L21)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's not quite right now -- since it does more than just deterministic, commutative encryption. How about something like `Preprocesses each of the events in [request] as described above`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me-idvZ8vJMUOkS7Spu:-Me-idv_E4d14u6dj8XF:b862ek5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt#L22)):*
> ```Kotlin
> /**
>  * Implements several encryption schemes to encrypt event data and an identifier. // A deterministic
>  * commutative encryption scheme is used to encrypt the identifier, // which is hashed using a
> ```

Can you edit this comment to remove the `//`s?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me-jGuD716w3yz0IpTX:-Me-jGuD716w3yz0IpTY:b-8xzfrb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt#L27)):*
> ```Kotlin
> /** Abstract base class for testing implementations of [PreprocessEvents]. */
> abstract class AbstractPreprocessEventsTest {
>   abstract val PreprocessEvents: PreprocessEvents
> ```

lowercase please -- this is a variable (`preprocessEvents`)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt, line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me-jLEeByFVw2TV20FQ:-Me-jLEeByFVw2TV20FR:bdzeco7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt#L31)):*
> ```Kotlin
>   @Test
>   fun testPreprocessEvents() {
>     val randomID: ByteString = ByteString.copyFromUtf8("random-id")
> ```

`randomId` (lowercase "d")
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me-jNWw0V8v-37IhVlA:-Me-jNWx9xFi3C6snOpL:b-4qvewr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt#L33)):*
> ```Kotlin
>     val randomID: ByteString = ByteString.copyFromUtf8("random-id")
>     val randomData: ByteString = ByteString.copyFromUtf8("random-data")
>     val randomCryptoKey: ByteString = ByteString.copyFromUtf8("random-crypto-key")
> ```

There's a difference between "random" and "arbitrary". I think you want "arbitrary" here -- because these values are not at all random. (In fact, they're completely set in stone, which is the opposite of random.)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me-jhwx0zirdpZsEMMa:-Me-jhwx0zirdpZsEMMb:bhyd0ab) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt#L38)):*
> ```Kotlin
>     val unImplementedException =
>       assertFailsWith(RuntimeException::class) {
>         val request = PreprocessEventsRequest.newBuilder().setCryptoKey(randomCryptoKey)
> ```

The Kotlinic way to do this is:

```
val request = PreprocessEventsRequest.newBuilder()
  .apply {
    cryptoKey = randomCryptoKey
    pepper = randomPepper
    addUnprocessedEventsBuilder().apply {
      id = randomId
      data = randomData
    }
  }
  .build()
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt, line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me-k2PX4CYk-VYQfya2:-Me-k2PX4CYk-VYQfya3:b-7ayuzx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt#L43)):*
> ```Kotlin
>         unprocessedEvent.setId(randomID)
>         unprocessedEvent.setData(randomData)
>         PreprocessEvents.preprocess(request.build())
> ```

Can you remove all code from the `assertFailsWith` block except for this line? (In other words, we want to be sure that it's this line that throws the exception, not one of the above lines.)
___
*[src/main/kotlin/org/wfanet/panelmatch/common/JniException.kt, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me-kCVX5suNmDE3iJx2:-Me-kCVX5suNmDE3iJx3:b-3gelv9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/common/JniException.kt#L22)):*
> ```Kotlin
> class JniException(cause: Throwable) : RuntimeException(cause)
> 
> public fun <T> wrapJniException(block: () -> T): T {
> ```

No need to write `public` (it's the default)
___
*[src/main/kotlin/org/wfanet/panelmatch/common/JniException.kt, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me-kLXY8DNXDTBcvXCp:-Me-kLXY8DNXDTBcvXCq:b-ujq4v0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/common/JniException.kt#L22)):*
> ```Kotlin
> class JniException(cause: Throwable) : RuntimeException(cause)
> 
> public fun <T> wrapJniException(block: () -> T): T {
> ```

Add a KDoc comment to this function please


<!-- Sent from Reviewable.io -->

2021-07-07 13:01 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37)* status: all files reviewed, 14 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-MdbYUpa9HYapnym5x9-:-Me-wLziEnu0m4tBk1xE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac778cf8a6693d1c08e899b8a69778b69d51c06f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt#L21)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's not quite right now -- since it does more than just deterministic, commutative encryption. How about something like `Preprocesses each of the events in [request] as described above`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me-idvZ8vJMUOkS7Spu:-Me-wEr2-C3qr-6Pl-Vf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt#L22)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you edit this comment to remove the `//`s?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me-jGuD716w3yz0IpTX:-Me-wg009LAlPWkVy9XT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

lowercase please -- this is a variable (`preprocessEvents`)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt, line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me-jLEeByFVw2TV20FQ:-Me-wk2F0WYP5ZuG4ItP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`randomId` (lowercase "d")
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me-jNWw0V8v-37IhVlA:-Me-xF3k1Wl2XkXhKfGx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

There's a difference between "random" and "arbitrary". I think you want "arbitrary" here -- because these values are not at all random. (In fact, they're completely set in stone, which is the opposite of random.)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me-jhwx0zirdpZsEMMa:-Me-xQXxAJtTfFCwQXqG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The Kotlinic way to do this is:

```
val request = PreprocessEventsRequest.newBuilder()
  .apply {
    cryptoKey = randomCryptoKey
    pepper = randomPepper
    addUnprocessedEventsBuilder().apply {
      id = randomId
      data = randomData
    }
  }
  .build()
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt, line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me-k2PX4CYk-VYQfya2:-Me-yHzP6seaiA6Tufwz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you remove all code from the `assertFailsWith` block except for this line? (In other words, we want to be sure that it's this line that throws the exception, not one of the above lines.)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt, line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me0-4xr8Ln8QWq5A5Z9:-Me0-4xr8Ln8QWq5A5ZA:b-egqq22) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt#L43)):*
> an you remove all code from the assertFailsWith block except for this line? (In other words, we want to be sure that it's this line that throws the exception, not one of the above lines.)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt, line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me0-OVt1IMjhPy0cXTV:-Me0-OVt1IMjhPy0cXTW:b93brv9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/AbstractPreprocessEventsTest.kt#L43)):*
> ```
> s(request.build())
> ```
___
*[src/main/kotlin/org/wfanet/panelmatch/common/JniException.kt, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me-kCVX5suNmDE3iJx2:-Me-ynSR63hnQxneigkY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/common/JniException.kt#L22)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

No need to write `public` (it's the default)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/JniException.kt, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me-kLXY8DNXDTBcvXCp:-Me-z8GIAtzP9dsyZEYT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/01c0d60efb85e8389d3c725be4d7d41b6de7c594/src/main/kotlin/org/wfanet/panelmatch/common/JniException.kt#L22)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Add a KDoc comment to this function please
</blockquote></details>

 [...]

2021-07-07 13:35 UTC, efoxepstein requested changes
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37)* status: all files reviewed, 5 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me0A52b5tr3BfaOKosV:-Me0A52b5tr3BfaOKosW:biy50dd) (no related file):*
Could you please update the title of this PR to be a little more specific (and in the imperative mood)? Something like "Add Kotlin JNI event preprocessing library".

---


<!-- Sent from Reviewable.io -->

2021-07-07 13:40 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @enfreck, @matthewclegg, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me0A52b5tr3BfaOKosV:-Me0Ba8_-Ysxq4gx4_5F:b-896fix) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Could you please update the title of this PR to be a little more specific (and in the imperative mood)? Something like "Add Kotlin JNI event preprocessing library".
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-07-07 13:45 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37)* status: all files reviewed, 4 unresolved discussions (waiting on @enfreck, @matthewclegg, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-07 13:50 UTC, enfreck reviewed
> Reviewed 2 of 4 files at r1, 7 of 11 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37)* status: all files reviewed, 4 unresolved discussions (waiting on @enfreck, @matthewclegg, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-07 13:53 UTC, enfreck approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37)* status: all files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-07 15:08 UTC, stevenwarejones approved these changes
lgtm

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-:-Me0V1gd52jKrWyKy33z:bb7k0qh)* status: all files reviewed, 1 unresolved discussion (waiting on @matthewclegg)



<!-- Sent from Reviewable.io -->

2021-07-07 15:11 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37)* status: all files reviewed, 2 unresolved discussions (waiting on @jmorrrr and @matthewclegg)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt, line 33 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me0WCrL3Gpij2ozA5jU:-Me0WCrL3Gpij2ozA5jV:bnkili5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0d5dfaa862b3cde71ebeaea7de284693dddd879b/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt#L33)):*
> ```Kotlin
>   fun `Status kUnimplemented`() {
>     val unImplemented =
>       assertFailsWith(JniException::class) {
> ```

optional: you could combine this test with the abstract test and pass in the type of exception you expect to get back. At the moment, the tests look a little duplicative.


<!-- Sent from Reviewable.io -->

2021-07-07 15:38 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37)* status: all files reviewed, 2 unresolved discussions (waiting on @jmorrrr and @matthewclegg)



<!-- Sent from Reviewable.io -->

2021-07-07 16:16 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37)* status: all files reviewed, 2 unresolved discussions (waiting on @matthewclegg and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt, line 33 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-Me0WCrL3Gpij2ozA5jU:-Me0kBHK6nW5FpEnSVrQ:b-rm2uru) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0d5dfaa862b3cde71ebeaea7de284693dddd879b/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt#L33)):*
> optional: you could combine this test with the abstract test and pass in the type of exception you expect to get back. At the moment, the tests look a little duplicative.
The abstract tests will get more complicated once more components are done and there will be more things to test there


<!-- Sent from Reviewable.io -->

2021-07-07 17:22 UTC, matthewclegg approved these changes

2021-07-07 17:22 UTC, matthewclegg commented on src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt
> +      val swigPath =
I'm afraid I don't know Kotlin, so my comments may not be accurate, but the following stackoverflow discussion seems to suggest that this is not the optimal way to create a constant. 

https://stackoverflow.com/questions/44038721/constants-in-kotlin-whats-a-recommended-way-to-create-them

2021-07-07 17:27 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37)* status: all files reviewed, 3 unresolved discussions (waiting on @matthewclegg and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 37 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-MdYrxQYBUNwbgw3vbdx-r3-37:-Me0zur39o4odYN0sszI:bo09cwh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0d5dfaa862b3cde71ebeaea7de284693dddd879b/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L37)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

I'm afraid I don't know Kotlin, so my comments may not be accurate, but the following stackoverflow discussion seems to suggest that this is not the optimal way to create a constant. 

https://stackoverflow.com/questions/44038721/constants-in-kotlin-whats-a-recommended-way-to-create-them
</blockquote></details>

`private const val SWIG_PATH = ` would probably be consistent with our other code.


<!-- Sent from Reviewable.io -->

2021-07-07 17:42 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37)* status: all files reviewed, 3 unresolved discussions (waiting on @matthewclegg and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 37 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/37#-MdYrxQYBUNwbgw3vbdx-r3-37:-Me130Du-TNFULlzr9h_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0d5dfaa862b3cde71ebeaea7de284693dddd879b/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`private const val SWIG_PATH = ` would probably be consistent with our other code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-07 17:51 UTC, merged