Prepare encryption_utility_helper for common-cpp migration.
world-federation-of-advertisers/panel-exchange-client pull request #38
Opened 2021-07-07 15:39 UTC by efoxepstein

This moves it into the //src/main/cc/wfanet/panelmatch/common Bazel
package, which can be migrated entirely to the common-cpp repo.

This also refactors some redundant code to use a helper library.

2021-07-07 21:04 UTC, jmorrrr requested changes
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/38)* status: 1 of 11 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @enfreck, and @stevenwarejones)

___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/38#-Me1llS5-XfN6r0_EKpR:-Me1llS5-XfN6r0_EKpS:bhlvsnj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/424409c3b4eccad77265e5089b81ea2a38e6b24d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc#L27)):*
> ```cpp
>     const std::string& serialized_request) {
>   return wfanet::panelmatch::common::JniWrap(serialized_request,
>                                              &PreprocessEvents);
> ```

I don't think there should be an ampersand here. Or JniWrap  needs to call the inner function without an ampersand and the call to JniWrap in Deterministic commutative utility wrapper should be changed as well.


<!-- Sent from Reviewable.io -->

2021-07-08 14:03 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/38)* status: 2 of 11 files reviewed, 3 unresolved discussions (waiting on @enfreck, @jmorrrr, and @stevenwarejones)

___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/38#-Me1llS5-XfN6r0_EKpR:-Me5Q98H9en9ben_QOOg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/424409c3b4eccad77265e5089b81ea2a38e6b24d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc#L27)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

I don't think there should be an ampersand here. Or JniWrap  needs to call the inner function without an ampersand and the call to JniWrap in Deterministic commutative utility wrapper should be changed as well.
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/protocol/crypto/deterministic_commutative_encryption_utility_wrapper.h, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/38#-Me2ldig5JApfERrGx-q:-Me5PmJd7epdfJYHXuWm:b-cmkgtr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/007428720b10dd9d78bde55e435490ed72d75114/src/main/cc/wfanet/panelmatch/protocol/crypto/deterministic_commutative_encryption_utility_wrapper.h#L22)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i thought it was necessary to refer to the generated `.pb.h` file?
</blockquote></details>

In this file, there are no references to symbols exported by the generated `.pb.h`.
___
*[src/main/cc/wfanet/panelmatch/protocol/crypto/deterministic_commutative_encryption_utility_wrapper.cc, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/38#-Me5K9367tk2hAYtyX34:-Me5PxqxEOI5EH7OdfsN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/424409c3b4eccad77265e5089b81ea2a38e6b24d/src/main/cc/wfanet/panelmatch/protocol/crypto/deterministic_commutative_encryption_utility_wrapper.cc#L24)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i don't think you need these anymore since they are moved to the helper
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-08 16:39 UTC, jmorrrr approved these changes
> Reviewed 8 of 11 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/38)* status: all files reviewed, 2 unresolved discussions (waiting on @enfreck and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-08 20:58 UTC, enfreck approved these changes
> Reviewed 8 of 11 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/38)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-09 14:43 UTC, stevenwarejones approved these changes
> Reviewed 7 of 11 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/38)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)



<!-- Sent from Reviewable.io -->

2021-07-09 16:11 UTC, merged