Add PepperedFingerprinter implementation
world-federation-of-advertisers/panel-exchange-client pull request #39
Opened 2021-07-08 16:32 UTC by enfreck

Add PepperedFingerprinter .h, .cc, and tests for hashing user data
identifiers.

2021-07-08 16:45 UTC, jmorrrr requested changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: all files reviewed, 4 unresolved discussions (waiting on @enfreck)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6-VqF-1UZdjlFJYl1:-Me6-VqF-1UZdjlFJYl2:bd8h651) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc#L56)):*
> ```cpp
> }  // namespace
> 
> std::unique_ptr<Fingerprinter> GetPepperedFingerprinter(
> ```

What is this doing? Comment?
___
*[src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6-E7w-pXwe5_6Gwxw:-Me6-E7w-pXwe5_6Gwxx:bv1snt6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc#L33)):*
> ```cpp
> // any-sketch/src/test/cc/any_sketch/fingerprinters/fingerprinters_test.cc
> TEST(FingerprintersTest, PepperedFingerprinterWithSha256) {
>   const Fingerprinter& sha = GetSha256Fingerprinter();
> ```

More specific  comments about what case this is testing for
___
*[src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6-2FR5k09GSDGkxBc:-Me6-2FR5k09GSDGkxBd:bki50s6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc#L48)):*
> ```cpp
> TEST(FingerprintersTest, PepperedFingerprinterWithFarm) {
>   const Fingerprinter& farm = GetFarmFingerprinter();
>   std::unique_ptr<Fingerprinter> fingerprinter =
> ```

Add comment that this is testing arbitrary finger[rinter
___
*[src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me5zweT3nuRG6pWbocC:-Me5zweU6x_Hn0wRvJBu:b2huvt2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc#L52)):*
> ```cpp
>   EXPECT_NE(fingerprinter->Fingerprint("not-an-empty"), 0x9ae16a3b2f90404f);
> 
>   std::unique_ptr<Fingerprinter> empty_fingerprinter =
> ```

add comment that this is testing empty fingerprinter


<!-- Sent from Reviewable.io -->

2021-07-08 17:08 UTC, efoxepstein requested changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: all files reviewed, 13 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[WORKSPACE, line 330 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me64okF2alV1GB0W8WS:-Me64okF2alV1GB0W8WT:bddwrs8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/WORKSPACE#L330)):*
> ```Starlark
> tink_cc_deps_init()
> 
> wfa_repo_archive(
> ```

Depending on when this lands, you might need to pull in `common_cpp` instead.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me62xVK-fVzKysLB6sy:-Me62xVK-fVzKysLB6sz:b-c36orr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d0662f2813e1e1d6b57ff030fd3a7d9437055309/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L26)):*
> ```objc
> #include "absl/status/statusor.h"
> #include "absl/strings/string_view.h"
> #include "tink/util/secret_data.h"
> ```

It looks like `SecretData` is referenced in this file so you probably want to keep the `#include`
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6325CD_M0RM-6C6im:-Me6325CD_M0RM-6C6in:bsgy9nu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L35)):*
> ```objc
>   // aes key and an aes method to encrypt the input with the aes key
>   virtual absl::StatusOr<std::string> Encrypt(
>       absl::string_view input, const crypto::tink::util::SecretData key) = 0;
> ```

`key` should be a const reference (instead of passing by value)
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me638Un81EmvwScpi1w:-Me638Un81EmvwScpi1x:bvmx1cf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L39)):*
> ```objc
>   // aes key and an aes method to decrypt the input with the aes key
>   virtual absl::StatusOr<std::string> Decrypt(
>       absl::string_view input, const crypto::tink::util::SecretData key) = 0;
> ```

Ditto for `key`
___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.h, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me63Byx9dXi8c2TAcMU:-Me63Byx9dXi8c2TAcMV:b-5mb52w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.h#L27)):*
> ```objc
> namespace wfanet::panelmatch::common::crypto {
> 
> using ::crypto::tink::util::SecretData;
> ```

Please don't put using-declarations in headers (https://abseil.io/tips/119)
___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.h, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me63KuGBuM5q8gIAMf8:-Me63KuGBuM5q8gIAMf9:b-rwfu0u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.h#L32)):*
> ```objc
> // Returns a Fingerprinter with a hashfunction 'delegate' and pepper 'pepper'
> std::unique_ptr<Fingerprinter> GetPepperedFingerprinter(
>     const Fingerprinter* delegate, SecretData pepper);
> ```

`pepper` should be a const reference
___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me63T2k998uVEWM95NJ:-Me63T2k998uVEWM95NK:b-kyfxf2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc#L27)):*
> ```cpp
> 
> using ::crypto::tink::util::SecretData;
> using wfa::any_sketch::Fingerprinter;
> ```

Please fully qualify using-declarations (start with `::`) and put them in the innermost namespace (the anonymous one)
___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me63caW1qQvM1WRs1YU:-Me63caW1qQvM1WRs1YV:b7jtn41) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc#L51)):*
> ```cpp
> 
>  private:
>   const SecretData& pepper_;
> ```

This should make a copy of `pepper` most likely (in other words, store just a `SecretData pepper_`). This is because (a) it's not very big and (b) this could crash:

```
auto fingerprinter = GetPepperedFingerprinter(some_other_fingerprinter, SecretDataFromStringView("abc"));
fingerprinter->Fingerprint(something);  // This could crash
```
___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6-VqF-1UZdjlFJYl1:-Me64Fmm6JJE8XUUvswb:busf6oi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc#L56)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

What is this doing? Comment?
</blockquote></details>

The comment is in the header file -- no need to duplicate it here.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me64Rq_16TMH5g6XKIf:-Me64Rq_16TMH5g6XKIg:b-kebz16) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc#L25)):*
> ```cpp
> 
> using ::crypto::tink::util::SecretDataFromStringView;
> using wfa::any_sketch::Fingerprinter;
> ```

Please fully qualify


<!-- Sent from Reviewable.io -->

2021-07-08 18:42 UTC, matthewclegg approved these changes

2021-07-08 19:54 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: 2 of 7 files reviewed, 13 unresolved discussions (waiting on @efoxepstein, @enfreck, and @jmorrrr)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me62xVK-fVzKysLB6sy:-Me6fo0z1lZ7uOqMX_2h:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d0662f2813e1e1d6b57ff030fd3a7d9437055309/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It looks like `SecretData` is referenced in this file so you probably want to keep the `#include`
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6325CD_M0RM-6C6im:-Me6fojC7W6wJmmYAUcT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L35)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`key` should be a const reference (instead of passing by value)
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me638Un81EmvwScpi1w:-Me6fp0Q4L8fGpqKDCoh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto for `key`
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.h, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me63Byx9dXi8c2TAcMU:-Me6fpYjDgnN2o08Fbak:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.h#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please don't put using-declarations in headers (https://abseil.io/tips/119)
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.h, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me63KuGBuM5q8gIAMf8:-Me6fq-_AW4AbN7De3W5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.h#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`pepper` should be a const reference
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me63T2k998uVEWM95NJ:-Me6fuPF9YbIhz4gHI6p:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please fully qualify using-declarations (start with `::`) and put them in the innermost namespace (the anonymous one)
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me63caW1qQvM1WRs1YU:-Me6fvH2CXs4ACLXO4cR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc#L51)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This should make a copy of `pepper` most likely (in other words, store just a `SecretData pepper_`). This is because (a) it's not very big and (b) this could crash:

```
auto fingerprinter = GetPepperedFingerprinter(some_other_fingerprinter, SecretDataFromStringView("abc"));
fingerprinter->Fingerprint(something);  // This could crash
```
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6-VqF-1UZdjlFJYl1:-Me6fvjBDVYu91wrIhhB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc#L56)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The comment is in the header file -- no need to duplicate it here.
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me64Rq_16TMH5g6XKIf:-Me6fwV-BkacRP_T0kta:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please fully qualify
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6-E7w-pXwe5_6Gwxw:-Me6fwwx-gU9WEwps_rg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc#L33)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

More specific  comments about what case this is testing for
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6-2FR5k09GSDGkxBc:-Me6fxCC5951h8bMypL0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc#L48)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

Add comment that this is testing arbitrary finger[rinter
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me5zweT3nuRG6pWbocC:-Me6fxY_1JxYAZeJcF_U:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc#L52)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

add comment that this is testing empty fingerprinter
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-08 20:12 UTC, jmorrrr approved these changes
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: all files reviewed, 9 unresolved discussions (waiting on @efoxepstein and @enfreck)



<!-- Sent from Reviewable.io -->

2021-07-08 20:16 UTC, efoxepstein requested changes
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: all files reviewed, 4 unresolved discussions (waiting on @enfreck)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6kIR25sqAZOYXgEBI:-Me6kIR25sqAZOYXgEBJ:btk7pbc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f787ecdb6c7aa7b8d6360d76ff0a8b6fd8aed143/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L36)):*
> ```objc
>   // aes key and an aes method to encrypt the input with the aes key
>   virtual absl::StatusOr<std::string> Encrypt(
>       absl::string_view input, const ::crypto::tink::util::SecretData& key) = 0;
> ```

This should not be fully qualified (https://abseil.io/tips/130). Basically: only fully qualify using decls.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6kZYp6rxcQ2VaRyv_:-Me6kZYp6rxcQ2VaRyva:bqpbv9s) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f787ecdb6c7aa7b8d6360d76ff0a8b6fd8aed143/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L40)):*
> ```objc
>   // aes key and an aes method to decrypt the input with the aes key
>   virtual absl::StatusOr<std::string> Decrypt(
>       absl::string_view input, const ::crypto::tink::util::SecretData& key) = 0;
> ```

Ditto for full qualification
___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.h, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6kcet1LvysMj4Hu3Y:-Me6kcet1LvysMj4Hu3Z:bsv9nef) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f787ecdb6c7aa7b8d6360d76ff0a8b6fd8aed143/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.h#L28)):*
> ```objc
> 
> // Returns a Fingerprinter with a hashfunction 'delegate' and pepper 'pepper'
> std::unique_ptr<::wfa::any_sketch::Fingerprinter> GetPepperedFingerprinter(
> ```

Ditto in this file for full qualification


<!-- Sent from Reviewable.io -->

2021-07-08 20:26 UTC, enfreck commented
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6kIR25sqAZOYXgEBI:-Me6mpzr2Ko6nusBzU0A:b-pdszm6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f787ecdb6c7aa7b8d6360d76ff0a8b6fd8aed143/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L36)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This should not be fully qualified (https://abseil.io/tips/130). Basically: only fully qualify using decls.
</blockquote></details>

If a lot of other files I have already merged have fully qualified paths for non using declarations, should I change those?  Specifically aes.h, hkdf.h, and hkdf.cc


<!-- Sent from Reviewable.io -->

2021-07-09 11:36 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: all files reviewed, 4 unresolved discussions (waiting on @enfreck)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6kIR25sqAZOYXgEBI:-MeA2S7R-_eeryea_wDw:b-lxuwya) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f787ecdb6c7aa7b8d6360d76ff0a8b6fd8aed143/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L36)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

If a lot of other files I have already merged have fully qualified paths for non using declarations, should I change those?  Specifically aes.h, hkdf.h, and hkdf.cc
</blockquote></details>

Yes (in a separate PR please)


<!-- Sent from Reviewable.io -->

2021-07-09 13:21 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @enfreck, and @stevenwarejones)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6kIR25sqAZOYXgEBI:-MeAQ7kZ3G1HusRgzyH3:b-373snn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f787ecdb6c7aa7b8d6360d76ff0a8b6fd8aed143/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L36)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Yes (in a separate PR please)
</blockquote></details>

Upon running tests, these need the :: in front of them.  I assume the same will be true for aes_with_hkdf when tests are written.  Messing around with the other files as well drew the same conclusion.


<!-- Sent from Reviewable.io -->

2021-07-09 14:40 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: 5 of 7 files reviewed, 7 unresolved discussions (waiting on @efoxepstein, @enfreck, and @jmorrrr)

___
*[WORKSPACE, line 330 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me64okF2alV1GB0W8WS:-MeAhfRr2UbfahUvwQpT:b-7tdf7d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/WORKSPACE#L330)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Depending on when this lands, you might need to pull in `common_cpp` instead.
</blockquote></details>

agree
___
*[src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc, line 40 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-MeAhENz-HsUegwTQP5S:-MeAhENz-HsUegwTQP5T:b4mhair) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/49d7c5f93dc1df16e7d7b5f5781777d124430c98/src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc#L40)):*
> ```cpp
>   std::unique_ptr<Fingerprinter> empty_fingerprinter =
>       GetPepperedFingerprinter(&sha, pepper);
>   EXPECT_EQ(empty_fingerprinter->Fingerprint(""), 0x141cfc9842c4b0e3);
> ```

can you make this reused value a constant?
___
*[src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc, line 51 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-MeAhNpu7z8XYoFCCTD4:-MeAhNpu7z8XYoFCCTD5:bwnljzq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/49d7c5f93dc1df16e7d7b5f5781777d124430c98/src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc#L51)):*
> ```cpp
> // Test PepperedFingerprinter with FarmHashFingerprinter delegate
> // Test values from
> // any-sketch/src/test/cc/any_sketch/fingerprinters/fingerprinters_test.cc
> ```

reference to common
___
*[src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc, line 59 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-MeAhbes5Vbr_ot7nOJf:-MeAhbes5Vbr_ot7nOJg:b-2guby3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/49d7c5f93dc1df16e7d7b5f5781777d124430c98/src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc#L59)):*
> ```cpp
>   std::unique_ptr<Fingerprinter> empty_fingerprinter =
>       GetPepperedFingerprinter(&farm, pepper);
>   EXPECT_EQ(empty_fingerprinter->Fingerprint(""), 0x9ae16a3b2f90404f);
> ```

same here


<!-- Sent from Reviewable.io -->

2021-07-09 16:45 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: 5 of 7 files reviewed, 7 unresolved discussions (waiting on @efoxepstein, @jmorrrr, and @stevenwarejones)

___
*[WORKSPACE, line 330 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me64okF2alV1GB0W8WS:-MeB92oW9ux30M7FxFlQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/WORKSPACE#L330)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

agree
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6kIR25sqAZOYXgEBI:-MeB94u986lVZTqY9ey-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f787ecdb6c7aa7b8d6360d76ff0a8b6fd8aed143/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L36)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Upon running tests, these need the :: in front of them.  I assume the same will be true for aes_with_hkdf when tests are written.  Messing around with the other files as well drew the same conclusion.
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6kZYp6rxcQ2VaRyv_:-MeB95GTDO3lMIB07qZU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f787ecdb6c7aa7b8d6360d76ff0a8b6fd8aed143/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto for full qualification
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.h, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me6kcet1LvysMj4Hu3Y:-MeB95fWCWdHeYICMw-c:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f787ecdb6c7aa7b8d6360d76ff0a8b6fd8aed143/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.h#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto in this file for full qualification
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc, line 40 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-MeAhENz-HsUegwTQP5S:-MeB96E55fMqR5raD4gM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/49d7c5f93dc1df16e7d7b5f5781777d124430c98/src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc#L40)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you make this reused value a constant?
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc, line 51 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-MeAhNpu7z8XYoFCCTD4:-MeB96gFBN65hWFWlBrk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/49d7c5f93dc1df16e7d7b5f5781777d124430c98/src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc#L51)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

reference to common
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc, line 59 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-MeAhbes5Vbr_ot7nOJf:-MeB96vAEEIvUci9mw5u:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/49d7c5f93dc1df16e7d7b5f5781777d124430c98/src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc#L59)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-09 17:01 UTC, efoxepstein approved these changes
> Reviewed 2 of 2 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: all files reviewed, 5 unresolved discussions (waiting on @enfreck and @stevenwarejones)

___
*[WORKSPACE, line 330 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me64okF2alV1GB0W8WS:-MeBBj9a4Js5SRTKJuci:bfbioks) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/WORKSPACE#L330)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you copy from https://github.com/world-federation-of-advertisers/any-sketch/blob/main/WORKSPACE#L79 ? Note that we can drop the dep on farmhash but need to add:

```
load("@wfa_common_cpp//build:deps.bzl", "common_cpp_deps")

common_cpp_deps()
```
___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc, line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-MeBC4B12X-3Z22vAKpO:-MeBC4B12X-3Z22vAKpP:b-14sg5f) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e5de1054372b43996c795e92f5ceda7a89c5f7e5/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc#L33)):*
> ```cpp
> // A hashfunction that concatenates a pepper to an input, then uses
> // a specified hashfunction.
> class PepperedFingerprinter : public wfa::Fingerprinter {
> ```

If you have `using ::wfa::Fingerprinter`, you don't need to `wfa::` here (so remove one or the other please)
___
*[src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc, line 40 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-MeAhENz-HsUegwTQP5S:-MeBCFcFAQirCxxfSlGF:b-6l20j3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/49d7c5f93dc1df16e7d7b5f5781777d124430c98/src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc#L40)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Note that this explicitly goes against Google's testing best practices (but I won't insist on changing it back).


<!-- Sent from Reviewable.io -->

2021-07-09 21:11 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[WORKSPACE, line 330 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-Me64okF2alV1GB0W8WS:-MeC6-1X1kjQQiFc_mZB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/50e2ef481793b9638c6352032e7d0bc623e7719a/WORKSPACE#L330)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you copy from https://github.com/world-federation-of-advertisers/any-sketch/blob/main/WORKSPACE#L79 ? Note that we can drop the dep on farmhash but need to add:

```
load("@wfa_common_cpp//build:deps.bzl", "common_cpp_deps")

common_cpp_deps()
```
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc, line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-MeBC4B12X-3Z22vAKpO:-MeC6-iO08NTC-DOHB4X:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e5de1054372b43996c795e92f5ceda7a89c5f7e5/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

If you have `using ::wfa::Fingerprinter`, you don't need to `wfa::` here (so remove one or the other please)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-11 20:55 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc, line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-MeBC4B12X-3Z22vAKpO:-MeMLM0z93QqXSHnmmuh:b-gh1utj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e5de1054372b43996c795e92f5ceda7a89c5f7e5/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc#L33)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not seeing this change. I'd prefer you just get rid of the `using` of the 2 options that Eli gave.


<!-- Sent from Reviewable.io -->

2021-07-12 14:56 UTC, jmorrrr approved these changes
> Reviewed 1 of 2 files at r3, 4 of 6 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-12 16:18 UTC, enfreck commented
___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc, line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-MeBC4B12X-3Z22vAKpO:-MeQVQHx2kRiIzZfsQt-:bwqnnrc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e5de1054372b43996c795e92f5ceda7a89c5f7e5/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc#L33)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

not seeing this change. I'd prefer you just get rid of the `using` of the 2 options that Eli gave.
</blockquote></details>

Interesting, it shows up for me that I got rid of the wfa:: in front of Fingerprinter.  Is there a reason it's better to get rid of the using instead?


<!-- Sent from Reviewable.io -->

2021-07-12 18:01 UTC, enfreck commented
___
*[src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc, line 40 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-MeAhENz-HsUegwTQP5S:-MeQsJSA9knNLNO6cpnH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/49d7c5f93dc1df16e7d7b5f5781777d124430c98/src/test/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter_test.cc#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Note that this explicitly goes against Google's testing best practices (but I won't insist on changing it back).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-13 15:31 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @jmorrrr, and @stevenwarejones)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc, line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-MeBC4B12X-3Z22vAKpO:-MeVUesnA0MPll6s0eyP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e5de1054372b43996c795e92f5ceda7a89c5f7e5/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc#L33)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Interesting, it shows up for me that I got rid of the wfa:: in front of Fingerprinter.  Is there a reason it's better to get rid of the using instead?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-13 16:57 UTC, efoxepstein approved these changes
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-14 19:51 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck)

___
*[WORKSPACE, line 4 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-MeaZ8jP53GGLITvBt9C:-MeaZ8jP53GGLITvBt9D:bo4z8d3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c0397eedf7ca14939567fdf23b0cb71a0c4628a2/WORKSPACE#L4)):*
> ```Starlark
> 
> load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")
> load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")
> ```

where is this being used?
___
*[src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc, line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-MeBC4B12X-3Z22vAKpO:-MeaZRdv1p6pf05JX_8I:boks7d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e5de1054372b43996c795e92f5ceda7a89c5f7e5/src/main/cc/wfanet/panelmatch/common/crypto/peppered_fingerprinter.cc#L33)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Fingerprinter feels common enough to pull in the namespace


<!-- Sent from Reviewable.io -->

2021-07-14 20:07 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck)



<!-- Sent from Reviewable.io -->

2021-07-14 20:21 UTC, jmorrrr approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck)



<!-- Sent from Reviewable.io -->

2021-07-14 21:06 UTC, enfreck commented
___
*[WORKSPACE, line 4 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39#-MeaZ8jP53GGLITvBt9C:-MeapoYcBQNWIFHNJ6zQ:bhofej8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c0397eedf7ca14939567fdf23b0cb71a0c4628a2/WORKSPACE#L4)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

where is this being used?
</blockquote></details>

Deleted


<!-- Sent from Reviewable.io -->

2021-07-14 21:15 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-15 16:02 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/39)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)



<!-- Sent from Reviewable.io -->

2021-07-15 17:49 UTC, merged