Add implementation to Aes
world-federation-of-advertisers/panel-exchange-client pull request #47
Opened 2021-07-16 15:54 UTC by enfreck

Add the Aes_Siv_BoringSsl implementation to Aes along with tests for Aes
and AesWithHkdf

2021-07-16 16:24 UTC, efoxepstein requested changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47)* status: all files reviewed, 11 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.h, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek41XsBlV7Hpj3n7P_:-Mek3qaQ8o0nPXGtsye7:b3xuxgw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/main/cc/wfanet/panelmatch/common/crypto/aes.h#L48)):*
> ```objc
>       const ::crypto::tink::util::SecretData& key) const = 0;
> 
>   // Returns byte size for Aes key
> ```

Maybe "Returns required byte size for Aes key" (add "required")
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.cc, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek49cD2Wv-IQfNC2JW:-Mek49cD2Wv-IQfNC2JX:b2wf2gl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/main/cc/wfanet/panelmatch/common/crypto/aes.cc#L16)):*
> ```cpp
> 
> #include "wfanet/panelmatch/common/crypto/aes.h"
> ```

`#include <string>`, `#include <memory>` too please
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek4YVoAWT4x5a3yDKg:-Mek4YVoAWT4x5a3yDKh:b-gxlran) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L38)):*
> ```cpp
>   std::unique_ptr<Aes> aes = GetAesSivCmac512();
>   SecretData key = SecretDataFromStringView(absl::HexStringToBytes(
>       "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
> ```

Pull this out for reuse?

```
// Test key used in `tink/cc/subtle/aes_siv_boringssl_test.cc`.
// The first 32 bytes come from RFC3394: https://datatracker.ietf.org/doc/html/rfc3394#section-4.3
// The last 32 bytes is an arbitrary byte pattern.
SecretData GetTestKey() {
  return SecretDataFromStringView(absl::HexStringToBytes("00..."));
}
```
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek5d186LlWx2ESWJxa:-Mek5d186LlWx2ESWJxb:bv96jdr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L40)):*
> ```cpp
>       "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
>       "00112233445566778899aabbccddeefff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff"));
>   std::string_view message = "Some data to encrypt.";
> ```

rename variable to `plaintext` please
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek5UM0EhEoNB5jAOm0:-Mek5UM0EhEoNB5jAOm1:b-8pp9ho) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L42)):*
> ```cpp
>   std::string_view message = "Some data to encrypt.";
>   auto encrypted = aes->Encrypt(message, key);
>   ASSERT_TRUE(encrypted.ok()) << encrypted.status();
> ```

You can combine these two lines with:

```
ASSERT_OK_AND_ASSIGN(std::string ciphertext, aes->Encrypt(message, key));
```
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek5mP58Q46GYlSQu28:-Mek5mP58Q46GYlSQu29:bkx2djl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L43)):*
> ```cpp
>   auto encrypted = aes->Encrypt(message, key);
>   ASSERT_TRUE(encrypted.ok()) << encrypted.status();
>   auto reverted = aes->Decrypt(*encrypted, key);
> ```

Maybe name this variable as `recovered_plaintext`
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek5phR82brkL8A8c55:-Mek5phR82brkL8A8c56:b-rnxzil) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L44)):*
> ```cpp
>   ASSERT_TRUE(encrypted.ok()) << encrypted.status();
>   auto reverted = aes->Decrypt(*encrypted, key);
>   ASSERT_TRUE(reverted.ok()) << reverted.status();
> ```

Ditto for ASSERT_OK_AND_ASSIGN
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 179 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek5yMu3fod9R8Wr75K:-Mek5yMv73qkwQ0Ab0mE:bm3sk83) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L179)):*
> ```cpp
> 
> // Tests that the same key with different strings return different values
> TEST(AesTest, sameKeyDiffernetStringDecrypt) {
> ```

Typo in `Different`
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek63XJ9VtP6_o7ommS:-Mek63XJ9VtP6_o7ommT:b5ufm10) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc#L36)):*
> ```cpp
>   AesWithHkdf aes_hkdf(std::move(hkdf), std::move(aes));
>   auto encrypted = aes_hkdf.Encrypt(message, key);
>   ASSERT_TRUE(encrypted.ok()) << encrypted.status();
> ```

ASSERT_OK_AND_ASSIGN please
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek6DaZ950nSnqQctOC:-Mek6DaZ950nSnqQctOD:b-p22feh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc#L45)):*
> ```cpp
> // of the functions called within it
> TEST(AesWithHkdfTest, compareEncrypt) {
>   std::unique_ptr<Hkdf> hkdf = GetSha256Hkdf();
> ```

Would these tests be easier if you use fake HKDF and AES implementations? Something like:

```
class FakeHkdf : public Hkdf {
 public:
  absl::StatusOr<SecretData> ComputeHkdf(...) override {
    return SecretDataFromStringView(absl::StrCat(SecretDataAsStringView(key), " with length ", size));
  }
};

class FakeAes: public Aes {
 public:
  ... {
    return absl::StrCat("message ", message, " with key ", key);
  }
};
```

Your call for whatever you think is simpler.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc, line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek7MXW91XjW1STu0A4:-Mek7MXW91XjW1STu0A5:bn72z2p) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc#L144)):*
> ```cpp
> 
> // Tests that the same key with different strings return different values
> TEST(AesTest, sameKeyDiffernetStringDecrypt) {
> ```

Typos in "different" in several places


<!-- Sent from Reviewable.io -->

2021-07-16 17:25 UTC, jmorrrr approved these changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47)* status: all files reviewed, 11 unresolved discussions (waiting on @enfreck and @matthewclegg)



<!-- Sent from Reviewable.io -->

2021-07-16 20:50 UTC, jmorrrr approved these changes
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47)* status: all files reviewed, 11 unresolved discussions (waiting on @enfreck and @matthewclegg)



<!-- Sent from Reviewable.io -->

2021-07-16 20:53 UTC, efoxepstein requested changes
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47)* status: all files reviewed, 23 unresolved discussions (waiting on @enfreck and @matthewclegg)

___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mel42ku4xFOjLZVu2sr:-Mel42ku4xFOjLZVu2ss:blht6zi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L49)):*
> ```cpp
>   std::unique_ptr<Aes> aes = GetAesSivCmac512();
>   SecretData key = GetTestKey();
>   std::string_view plaintext = "Some data to encrypt.";
> ```

Just use `std::string` here please. (It will automatically convert to `absl::string_view` as needed.) (Also note that we never want to use `std::string_view`.)
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mel4NRGDahsxdZ8s0p-:-Mel4NRGDahsxdZ8s0p0:b-54egmn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L62)):*
> ```cpp
>   SecretData key = GetTestKey();
>   // auto aes_other = AesSivBoringSsl::New(key);
>   // ASSERT_TRUE(aes_other.ok()) << aes_other.status();
> ```

Delete this?
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mel4OM5BknJQKfpGuWA:-Mel4OM5BknJQKfpGuWB:b-54egmn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L67)):*
> ```cpp
>       AesSivBoringSsl::New(key));
>   std::string plaintext = "Some data to encrypt.";
>   // auto result_this = aes_this->Encrypt(plaintext, key);
> ```

Delete this?
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 71 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mel4PHL1ttYR3DNv2we:-Mel4PHL1ttYR3DNv2wf:b-54egmn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L71)):*
> ```cpp
>                        aes_this->Encrypt(plaintext, key));
>   // auto result_other = (*aes_other)->EncryptDeterministically(plaintext, "");
>   // ASSERT_TRUE(result_other.ok()) << result_other.status();
> ```

Delete this?
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 74 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mel4Td90cyqk0jpLnr8:-Mel4Td90cyqk0jpLnr9:b-e1el4z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L74)):*
> ```cpp
>   ASSERT_OK_AND_ASSIGN(std::string result_other,
>                        (*aes_other).EncryptDeterministically(plaintext, ""));
>   EXPECT_THAT(result_this, result_other);
> ```

EXPECT_EQ please
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 83 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mel4avz0FwNERLyLwCF:-Mel4avz0FwNERLyLwCG:b-b4w9xs) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L83)):*
> ```cpp
>   SecretData key = GetTestKey();
>   auto aes_other = AesSivBoringSsl::New(key);
>   ASSERT_TRUE(aes_other.ok()) << aes_other.status();
> ```

ASSERT_OK_AND_ASSIGN for aes_other?
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 92 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mel4e0cAjJ1w6BE5M9Q:-Mel4e0cAjJ1w6BE5M9R:b-qtlqas) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L92)):*
> ```cpp
>   ASSERT_TRUE(result_other.ok()) << result_other.status();
>   // ASSERT_OK_AND_ASSIGN(auto result_other,
>   // (*aes_other)->DecryptDeterministically(cyphertext, ""));
> ```

Delete this please
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 110 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mel4gOV6yq4M1kL3dqF:-Mel4gOV6yq4M1kL3dqG:b-s82b3k) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L110)):*
> ```cpp
>   SecretData key = GetTestKey();
>   std::string plaintext = "Some data to encrypt.";
>   auto cyphertext = aes->Encrypt(plaintext, key);
> ```

cipher
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 131 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mel4lbPCR4YgeYUm4oE:-Mel4lbPCR4YgeYUm4oF:b-pvtwzq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L131)):*
> ```cpp
>   SecretData key = GetTestKey();
>   std::string plaintext = "Some data to encrypt.";
>   auto cyphertext = aes->Encrypt(plaintext, key);
> ```

ASSERT_OK_AND_ASSIGN on this?
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mel4tcaAjzRsLgDxVAp:-Mel4tcaAjzRsLgDxVAq:b-t9zhc3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc#L28)):*
> ```cpp
> using ::crypto::tink::util::SecretDataFromStringView;
> 
> // Tests that a value cyphertext then decrypted returns that original value
> ```

ciphertext
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc, line 35 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mel4vU26mUFNzMl_ndp:-Mel4vU26mUFNzMl_ndq:b-tukvl7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc#L35)):*
> ```cpp
>   std::string_view plaintext = "Some data to encrypt.";
>   AesWithHkdf aes_hkdf(std::move(hkdf), std::move(aes));
>   ASSERT_OK_AND_ASSIGN(std::string cyphertext,
> ```

ciphertext (probably just global find & replace)
___
*[src/test/cc/wfanet/panelmatch/common/crypto/BUILD.bazel, line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mel54S2EN-vZEPwdTkO:-Mel54S2EN-vZEPwdTkP:b-tvlik) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/BUILD.bazel#L21)):*
> ```Starlark
>         "//src/main/cc/wfanet/panelmatch/common/crypto:aes",
>         "//src/test/cc/testutil:matchers",
>         "//src/test/cc/testutil:status_macros",
> ```

Grab this and the above one from `@wfa_common_cpp` please


<!-- Sent from Reviewable.io -->

2021-07-16 22:25 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47)* status: all files reviewed, 24 unresolved discussions (waiting on @enfreck and @matthewclegg)

___
*[WORKSPACE, line 338 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-MelQ86RBiCiN0V2xEck:-MelQ86RBiCiN0V2xEcl:b-dawti6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/WORKSPACE#L338)):*
> ```Starlark
> 
> # Common-cpp
> http_archive(
> ```

```
http_archive(
    name = "wfa_common_cpp",
    sha256 = "e0e1f5eed832ef396109354a64c6c1306bf0fb5ea0b449ce6ee1e8edc6fe279d",
    strip_prefix = "common-cpp-43c75acc3394e19bcfd2cfe8e8e2454365d26d60",
    url = "https://github.com/world-federation-of-advertisers/common-cpp/archive/43c75acc3394e19bcfd2cfe8e8e2454365d26d60.tar.gz",
)
```


<!-- Sent from Reviewable.io -->

2021-07-16 22:59 UTC, matthewclegg requested changes

2021-07-16 22:59 UTC, matthewclegg commented on src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc
> +  // auto aes_other = AesSivBoringSsl::New(key);
Delete commented lines?

2021-07-16 22:59 UTC, matthewclegg commented on src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc
> +// Tests that the same key with different strings return different values
The comment for this unit test is the same as for the previous one.  What is this supposed to be testing?

2021-07-16 22:59 UTC, matthewclegg commented on src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc
> +// Tests that the same key with different strings return different values
Same as above -- comment describing the test is the same as for the previous test.

2021-07-19 15:03 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47)* status: all files reviewed, 27 unresolved discussions (waiting on @efoxepstein and @matthewclegg)

___
*[WORKSPACE, line 338 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-MelQ86RBiCiN0V2xEck:-MezH8B28_NwWgqDB6D5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/WORKSPACE#L338)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

```
http_archive(
    name = "wfa_common_cpp",
    sha256 = "e0e1f5eed832ef396109354a64c6c1306bf0fb5ea0b449ce6ee1e8edc6fe279d",
    strip_prefix = "common-cpp-43c75acc3394e19bcfd2cfe8e8e2454365d26d60",
    url = "https://github.com/world-federation-of-advertisers/common-cpp/archive/43c75acc3394e19bcfd2cfe8e8e2454365d26d60.tar.gz",
)
```
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.h, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek41XsBlV7Hpj3n7P_:-MezH93A5hMaD-XNoTkU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/main/cc/wfanet/panelmatch/common/crypto/aes.h#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe "Returns required byte size for Aes key" (add "required")
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.cc, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek49cD2Wv-IQfNC2JW:-MezH9kM1eNAYr7fka4y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/main/cc/wfanet/panelmatch/common/crypto/aes.cc#L16)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`#include <string>`, `#include <memory>` too please
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek4YVoAWT4x5a3yDKg:-MezHA_u8xB61LPPk_Hx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Pull this out for reuse?

```
// Test key used in `tink/cc/subtle/aes_siv_boringssl_test.cc`.
// The first 32 bytes come from RFC3394: https://datatracker.ietf.org/doc/html/rfc3394#section-4.3
// The last 32 bytes is an arbitrary byte pattern.
SecretData GetTestKey() {
  return SecretDataFromStringView(absl::HexStringToBytes("00..."));
}
```
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek5d186LlWx2ESWJxa:-MezHHem19dw9giCwToh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

rename variable to `plaintext` please
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek5UM0EhEoNB5jAOm0:-MezHHC995w54hXIRMS3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L42)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

You can combine these two lines with:

```
ASSERT_OK_AND_ASSIGN(std::string ciphertext, aes->Encrypt(message, key));
```
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek5mP58Q46GYlSQu28:-MezHHzPD-ryGTtYvzj0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe name this variable as `recovered_plaintext`
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek5phR82brkL8A8c55:-MezHIG49Em4k_GZxHjL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L44)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto for ASSERT_OK_AND_ASSIGN
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 179 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek5yMu3fod9R8Wr75K:-MezHWBm3M-B9X53dclq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L179)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Typo in `Different`
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mel42ku4xFOjLZVu2sr:-MezHB_S9_PIIMtCOIKl:bk3jg69) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L49)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Just use `std::string` here please. (It will automatically convert to `absl::string_view` as needed.) (Also note that we never want to use `std::string_view`.)
</blockquote></details>

Why would we not want to use string_view in test cases?
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek3fmyQqMrM3lUadSr-r2-61:-MezHIjf0b5uwJ9rS67z:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L61)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Delete commented lines?
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mel4NRGDahsxdZ8s0p-:-MezHJ2r2k9DnzLDFcHf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Delete this?
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 67 at r2](https://reviewable.io/reviews/world-fe [...]

2021-07-19 15:03 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47)* status: 3 of 7 files reviewed, 27 unresolved discussions (waiting on @efoxepstein, @jmorrrr, and @matthewclegg)

___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 180 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek3fmyQqMrM3lUadSr-r2-180:-MezHo8-D8qWjYirWCoO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L180)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

The comments are the same since they test the same thing, just one for encrypt and one for decrypt.  I updated the comments to reflect that.
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc, line 145 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek3fmyQqMrM3lUadSs-r2-145:-MezHlt3BIuHfyPxBL6A:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc#L145)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Same reason as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-19 16:36 UTC, efoxepstein requested changes
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47)* status: all files reviewed, 12 unresolved discussions (waiting on @enfreck and @matthewclegg)

___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek5UM0EhEoNB5jAOm0:-MezakFX2WJWWBfLPQH1:bd4hke6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L42)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Was this undone?
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mel42ku4xFOjLZVu2sr:-MezaKpX6muJu6ic_Lh9:b-qbxpo2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L49)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Why would we not want to use string_view in test cases?
</blockquote></details>

`string_view` is a view type -- basically, it needs to point to data owned by something else. It's not good at owning data. Think of it as a pointer -- you wouldn't write `int* x = &5;`, right?

(This has nothing to do with test cases, it's true anywhere where string_view might be used.)
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 21 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mezbvqi7Tc4HiPjVrxo:-Mezbvqi7Tc4HiPjVrxp:b-4srftb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fe099e4221aef4942f005c7b94f1eed0856e2acd/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L21)):*
> ```cpp
> #include "absl/strings/escaping.h"
> #include "gtest/gtest.h"
> #include "src/main/cc/common_cpp/testing/status_matchers.h"
> ```

It should strip the include prefix -- so please use `#include "common_cpp/testing/wahtever.h`
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 22 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mezbv3F93x-cecI-srB:-Mezbv3F93x-cecI-srC:b-ikaepy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fe099e4221aef4942f005c7b94f1eed0856e2acd/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L22)):*
> ```cpp
> #include "gtest/gtest.h"
> #include "src/main/cc/common_cpp/testing/status_matchers.h"
> //#include "src/test/cc/testutil/matchers.h"
> ```

Delete please
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-MezbuhD1DZMxIuFFtEj:-MezbuhD1DZMxIuFFtEk:b-4srftb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fe099e4221aef4942f005c7b94f1eed0856e2acd/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L23)):*
> ```cpp
> #include "src/main/cc/common_cpp/testing/status_matchers.h"
> //#include "src/test/cc/testutil/matchers.h"
> #include "src/main/cc/common_cpp/testing/status_macros.h"
> ```

It should strip the include prefix -- so please use `#include "common_cpp/testing/wahtever.h`
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 126 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-MezbMR8595IF0y1RvH7:-MezbMR8595IF0y1RvH8:b-fmkjaj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fe099e4221aef4942f005c7b94f1eed0856e2acd/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L126)):*
> ```cpp
>   std::string plaintext = "Some data to encrypt.";
>   ASSERT_OK_AND_ASSIGN(std::string ciphertext, aes->Encrypt(plaintext, key));
>   key = SecretDataFromStringView(absl::HexStringToBytes(""));
> ```

Can you just make a new variable here for the empty key? `SecretData empty_key = ...`? It'll be easier to follow what's happening.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 138 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-MezbVy39rtuPepmeRvp:-MezbVy39rtuPepmeRvq:b-ty1oyz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fe099e4221aef4942f005c7b94f1eed0856e2acd/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L138)):*
> ```cpp
>       "990102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
>       "99112233445566778899aabbccddeefff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff"));
>   SecretData key_2 = GetTestKey();
> ```

Maybe: `ASSERT_NE(key_1, key_2);` as a sanity check
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc, line 19 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mezbd_JCysqcuhzVlGP:-Mezbd_JCysqcuhzVlGQ:b-cllkcj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fe099e4221aef4942f005c7b94f1eed0856e2acd/src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc#L19)):*
> ```cpp
> #include "absl/strings/escaping.h"
> #include "gtest/gtest.h"
> //#include "src/test/cc/testutil/matchers.h"
> ```

Remove commented line please
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc, line 21 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mezbg5X3Ab3Bp3xGKW0:-Mezbg5X3Ab3Bp3xGKW1:b-4srftb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fe099e4221aef4942f005c7b94f1eed0856e2acd/src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc#L21)):*
> ```cpp
> //#include "src/test/cc/testutil/matchers.h"
> #include "src/main/cc/common_cpp/testing/status_macros.h"
> #include "src/main/cc/common_cpp/testing/status_matchers.h"
> ```

It should strip the include prefix -- so please use `#include "common_cpp/testing/wahtever.h`


<!-- Sent from Reviewable.io -->

2021-07-19 17:41 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47)* status: 5 of 7 files reviewed, 12 unresolved discussions (waiting on @efoxepstein and @matthewclegg)

___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mek5UM0EhEoNB5jAOm0:-MezqlZh4w0REKhY2HY4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa22c65377c76e231dcf25f4a3eecf749d105666/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L42)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Was this undone?
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mel42ku4xFOjLZVu2sr:-MezqkQ85RypyasUHn_e:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2047b50ef784fc8f5662a319a4e62acbbf14f8ea/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L49)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`string_view` is a view type -- basically, it needs to point to data owned by something else. It's not good at owning data. Think of it as a pointer -- you wouldn't write `int* x = &5;`, right?

(This has nothing to do with test cases, it's true anywhere where string_view might be used.)
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 21 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mezbvqi7Tc4HiPjVrxo:-MezqvCUCXOlAgYTLed2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fe099e4221aef4942f005c7b94f1eed0856e2acd/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L21)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It should strip the include prefix -- so please use `#include "common_cpp/testing/wahtever.h`
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 22 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mezbv3F93x-cecI-srB:-MezqjVW8O4GAWiyVh7f:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fe099e4221aef4942f005c7b94f1eed0856e2acd/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L22)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Delete please
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-MezbuhD1DZMxIuFFtEj:-MezqjBm6UXTmKBNFvKc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fe099e4221aef4942f005c7b94f1eed0856e2acd/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It should strip the include prefix -- so please use `#include "common_cpp/testing/wahtever.h`
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 126 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-MezbMR8595IF0y1RvH7:-MezqmVDChMcnBHxzQaX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fe099e4221aef4942f005c7b94f1eed0856e2acd/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L126)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you just make a new variable here for the empty key? `SecretData empty_key = ...`? It'll be easier to follow what's happening.
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc, line 138 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-MezbVy39rtuPepmeRvp:-MezqnDU61zItPjz8aoP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fe099e4221aef4942f005c7b94f1eed0856e2acd/src/test/cc/wfanet/panelmatch/common/crypto/aes_test.cc#L138)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe: `ASSERT_NE(key_1, key_2);` as a sanity check
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc, line 19 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mezbd_JCysqcuhzVlGP:-MezqoPU9jTuxFKMym7E:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fe099e4221aef4942f005c7b94f1eed0856e2acd/src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc#L19)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Remove commented line please
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc, line 21 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47#-Mezbg5X3Ab3Bp3xGKW0:-MezqoccDZUIvW34wmZL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fe099e4221aef4942f005c7b94f1eed0856e2acd/src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc#L21)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It should strip the include prefix -- so please use `#include "common_cpp/testing/wahtever.h`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-19 17:44 UTC, efoxepstein approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47)* status: all files reviewed, 3 unresolved discussions (waiting on @matthewclegg)



<!-- Sent from Reviewable.io -->

2021-07-19 18:51 UTC, jmorrrr approved these changes
> Reviewed 2 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47)* status: all files reviewed, 3 unresolved discussions (waiting on @matthewclegg and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-20 04:42 UTC, matthewclegg approved these changes

2021-07-20 17:45 UTC, stevenwarejones approved these changes
> Reviewed 1 of 7 files at r1, 2 of 6 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/47)* status: all files reviewed, 3 unresolved discussions (waiting on @matthewclegg)



<!-- Sent from Reviewable.io -->

2021-07-20 19:15 UTC, merged