Adds EncryptionDoFn
world-federation-of-advertisers/panel-exchange-client pull request #48
Opened 2021-07-16 20:21 UTC by jmorrrr

Adds function to encrypt event data

2021-07-19 18:16 UTC, enfreck requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mezx_lgDslmkeo5uTvW:-Mezx_lgDslmkeo5uTvX:b4uzj8s) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ecbafea54bb49f084f18eb9c25fd5796a50e70d7/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt#L24)):*
> ```Kotlin
> import org.wfanet.panelmatch.client.PreprocessEventsResponse
> 
> class EncryptionEventsDoFn(
> ```

Class or function level comment(s)?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-MezxJc8CwVS3rXNbeW1:-MezxJc9BBdX6DK31fys:b-n12m05) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ecbafea54bb49f084f18eb9c25fd5796a50e70d7/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt#L28)):*
> ```Kotlin
> ) : DoFn<MutableList<KV<ByteString, ByteString>>, KV<ByteString, ByteString>>() {
>   @ProcessElement
>   fun process(c: ProcessContext) {
> ```

Is there a better name than 'c' for this variable?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-MezyFqoCfhwulkdK-7w:-MezyFqoCfhwulkdK-7x:b-a17hh7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ecbafea54bb49f084f18eb9c25fd5796a50e70d7/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L53)):*
> ```Kotlin
> 
>   @Test
>   fun testEncrypt() {
> ```

Are there any cases in which Encrypt would fail?  Such as empty lists, nulls, etc?


<!-- Sent from Reviewable.io -->

2021-07-19 18:32 UTC, efoxepstein requested changes
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48)* status: all files reviewed, 9 unresolved discussions (waiting on @jmorrrr and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-0bktD59GjDdNH4FO:-Mf-0bkwANXANmSyffJ9:b892u2f) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4093c88e5ec48dff9e402c1e8a14e4db9f591483/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt#L33)):*
> ```Kotlin
>       PreprocessEventsRequest.newBuilder()
>         .apply {
>           for (pairs in list) {
> ```

`pairs` is just one pair at a time, so maybe rename to `pair`?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-0kPJ4PQixUkKllUj:-Mf-0kPJ4PQixUkKllUk:bhkgtmq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4093c88e5ec48dff9e402c1e8a14e4db9f591483/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L40)):*
> ```Kotlin
>   val arbitraryUnprocessedEvents: MutableList<KV<ByteString, ByteString>> =
>     mutableListOf(
>       KV.of(ByteString.copyFromUtf8("1"), ByteString.copyFromUtf8("1")),
> ```

Can you use different things for the keys and values to ensure that they don't get swapped at any point?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-10Rh6kYTK_YlTE1u:-Mf-10Rh6kYTK_YlTE1v:btf6vc8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4093c88e5ec48dff9e402c1e8a14e4db9f591483/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L59)):*
> ```Kotlin
>     assertThat(result)
>       .containsInAnyOrder(
>         KV.of(ByteString.copyFromUtf8("1abcdefg"), ByteString.copyFromUtf8("1hijklmnop")),
> ```

Please add a helper function like:

```
fun bytestringKvOf(key: String, value: String): KV<ByteString, ByteString> {
  return Kv.of(ByteString.copyFromUtf8(key), ...)
}
```
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-1IhN6MCsv2wj6IzW:-Mf-1IhN6MCsv2wj6IzX:brdzbbo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4093c88e5ec48dff9e402c1e8a14e4db9f591483/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L65)):*
> ```Kotlin
> }
> 
> private object encryptEvents :
> ```

This should be named as PascalCase (and please call it `FakeEncryptEvents`)
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 73 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-1Ner1_D0qDL7vy4j:-Mf-1Ner1_D0qDL7vy4k:b-dcj1cc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4093c88e5ec48dff9e402c1e8a14e4db9f591483/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L73)):*
> ```Kotlin
>           for (events in request.unprocessedEventsList) {
>             addProcessedEventsBuilder().apply {
>               this.setEncryptedId(events.id.concat(ByteString.copyFromUtf8("abcdefg")))
> ```

Please use `encryptedId = ` instead of `setEncryptedId`
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 74 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-1QYYB760H81ckxoz:-Mf-1QYYB760H81ckxp-:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4093c88e5ec48dff9e402c1e8a14e4db9f591483/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L74)):*
> ```Kotlin
>             addProcessedEventsBuilder().apply {
>               this.setEncryptedId(events.id.concat(ByteString.copyFromUtf8("abcdefg")))
>               this.setEncryptedData(events.data.concat(ByteString.copyFromUtf8("hijklmnop")))
> ```

Ditto


<!-- Sent from Reviewable.io -->

2021-07-19 18:50 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48)* status: all files reviewed, 9 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mezx_lgDslmkeo5uTvW:-Mf-4Yab6oQctwwPLDDZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ecbafea54bb49f084f18eb9c25fd5796a50e70d7/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt#L24)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Class or function level comment(s)?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-MezxJc8CwVS3rXNbeW1:-Mf--XpdBG6bsPtUjcOk:b-bku7h7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ecbafea54bb49f084f18eb9c25fd5796a50e70d7/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt#L28)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Is there a better name than 'c' for this variable?
</blockquote></details>

This is the typical naming for ProcessContext I'm pretty sure
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-0bktD59GjDdNH4FO:-Mf-1q30CH6YRNMXyrD0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4093c88e5ec48dff9e402c1e8a14e4db9f591483/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`pairs` is just one pair at a time, so maybe rename to `pair`?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-MezyFqoCfhwulkdK-7w:-Mf-2Wem7TvnYM--JSKv:b42rui) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ecbafea54bb49f084f18eb9c25fd5796a50e70d7/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L53)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Are there any cases in which Encrypt would fail?  Such as empty lists, nulls, etc?
</blockquote></details>

This is just a test to make sure that the DoFn effectively packs, calls a function on, and unpacks protos - no set operation will be tested until your library is done so as far as I understood in my discussions with Eli no further tests are necessary in this PR @efoxepstein is this right? Or should I add null test because I just think an empty list would return nothing
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-0kPJ4PQixUkKllUj:-Mf-24776wYbHgNpCjZp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4093c88e5ec48dff9e402c1e8a14e4db9f591483/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you use different things for the keys and values to ensure that they don't get swapped at any point?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-10Rh6kYTK_YlTE1u:-Mf-3lr35gPA0uLyrSwJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4093c88e5ec48dff9e402c1e8a14e4db9f591483/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L59)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please add a helper function like:

```
fun bytestringKvOf(key: String, value: String): KV<ByteString, ByteString> {
  return Kv.of(ByteString.copyFromUtf8(key), ...)
}
```
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-1IhN6MCsv2wj6IzW:-Mf-2GF24JXjL7bFEYv1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4093c88e5ec48dff9e402c1e8a14e4db9f591483/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L65)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This should be named as PascalCase (and please call it `FakeEncryptEvents`)
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 73 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-1Ner1_D0qDL7vy4j:-Mf-2UL77T_MgIJx7twY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4093c88e5ec48dff9e402c1e8a14e4db9f591483/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L73)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use `encryptedId = ` instead of `setEncryptedId`
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 74 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-1QYYB760H81ckxoz:-Mf-2Uft6f8dnxmyigHt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4093c88e5ec48dff9e402c1e8a14e4db9f591483/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L74)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-19 19:05 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48)* status: 3 of 5 files reviewed, 8 unresolved discussions (waiting on @efoxepstein and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-92Mx9GHxT_xsyzwi:-Mf-92My9AW_bE3IXKnl:bdy7fe9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/112b16ed77f3443b490f43f3a658579ebe54263a/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt#L26)):*
> ```Kotlin
> /**
>  * DoFn to pack, apply a specified encryption protocol, and unpack PreprocessEvents protocol
>  * bufffers
> ```

extra f


<!-- Sent from Reviewable.io -->

2021-07-19 20:17 UTC, efoxepstein requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48)* status: all files reviewed, 3 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-MezyFqoCfhwulkdK-7w:-Mf-PS2V5rldM6yZ5b1t:bjqu661) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ecbafea54bb49f084f18eb9c25fd5796a50e70d7/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L53)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

This is just a test to make sure that the DoFn effectively packs, calls a function on, and unpacks protos - no set operation will be tested until your library is done so as far as I understood in my discussions with Eli no further tests are necessary in this PR @efoxepstein is this right? Or should I add null test because I just think an empty list would return nothing
</blockquote></details>

Trying out an empty list sounds reasonable to me. Don't worry about null things.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 40 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-PZBiEaORhlZtEHVz:-Mf-PZBj2SmZ9cxxUkA-:b-aedpli) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/112b16ed77f3443b490f43f3a658579ebe54263a/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L40)):*
> ```Kotlin
>   val arbitraryUnprocessedEvents: MutableList<KV<ByteString, ByteString>> =
>     mutableListOf(
>       KV.of(ByteString.copyFromUtf8("1"), ByteString.copyFromUtf8("2")),
> ```

Use your helper function here?


<!-- Sent from Reviewable.io -->

2021-07-19 20:37 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-MezyFqoCfhwulkdK-7w:-Mf-Tf8lC3BhgziRU4xP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ecbafea54bb49f084f18eb9c25fd5796a50e70d7/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L53)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Trying out an empty list sounds reasonable to me. Don't worry about null things.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 40 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-PZBiEaORhlZtEHVz:-Mf-QmPYCOHt21vY-hJq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/112b16ed77f3443b490f43f3a658579ebe54263a/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Use your helper function here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-19 21:01 UTC, efoxepstein requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48)* status: all files reviewed, 6 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt, line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-W-c45jsFGxmcnUJb:-Mf-W-c45jsFGxmcnUJc:b-n6j0n1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c01078c57223dedb03cc3708d2e298af3d08b3/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt#L25)):*
> ```Kotlin
> 
> /**
>  * DoFn to pack, apply a specified encryption protocol, and unpack PreprocessEvents protocol buffers
> ```

Can you change the phrasing here so it's like "Peels the apricots, quarters them, and sautes them in rosemary, honey, and butter"?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 38 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-YLjFE7MX46LdRhga:-Mf-YLjFE7MX46LdRhgb:bix9utz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c01078c57223dedb03cc3708d2e298af3d08b3/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L38)):*
> ```Kotlin
> @RunWith(JUnit4::class)
> class EncryptionEventsDoFnTest : BeamTestBase() {
>   val arbitraryUnprocessedEvents: MutableList<KV<ByteString, ByteString>> =
> ```

`private val`
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 40 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-YNIZ4se0yT3oM1Bn:-Mf-YNIZ4se0yT3oM1Bo:bix9utz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c01078c57223dedb03cc3708d2e298af3d08b3/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L40)):*
> ```Kotlin
>   val arbitraryUnprocessedEvents: MutableList<KV<ByteString, ByteString>> =
>     mutableListOf(byteStringKvOf("1", "2"), byteStringKvOf("3", "4"))
>   val emptyUnprocessedEvents: MutableList<KV<ByteString, ByteString>> = mutableListOf()
> ```

`private val`
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 42 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-YYy67YT6eK7W8FvU:-Mf-YYy7CsShPLanh8vn:b-rhwslu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c01078c57223dedb03cc3708d2e298af3d08b3/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L42)):*
> ```Kotlin
>   val emptyUnprocessedEvents: MutableList<KV<ByteString, ByteString>> = mutableListOf()
> 
>   private val collection: PCollection<MutableList<KV<ByteString, ByteString>>> by lazy {
> ```

Since this and `emptyCollection` are only used in one test case each, they can just be local variables in the test cases where they're used
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-YPStEbuEQZhukKET:-Mf-YPStEbuEQZhukKEU:by5xx3p) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c01078c57223dedb03cc3708d2e298af3d08b3/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L46)):*
> ```Kotlin
>       "collection1",
>       arbitraryUnprocessedEvents,
>       coder = ListCoder.of(KvCoder.of(ByteStringCoder.of(), ByteStringCoder.of()))
> ```

pull out coder to a variable?

```
private val coder: Coder<List<KV<...>>> = ListCoder.of(...)
```


<!-- Sent from Reviewable.io -->

2021-07-19 21:52 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt, line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-W-c45jsFGxmcnUJb:-Mf-jrsM8nlYk0DCyWfm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c01078c57223dedb03cc3708d2e298af3d08b3/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you change the phrasing here so it's like "Peels the apricots, quarters them, and sautes them in rosemary, honey, and butter"?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 38 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-YLjFE7MX46LdRhga:-Mf-ampWEdDNxosU4vFm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c01078c57223dedb03cc3708d2e298af3d08b3/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`private val`
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 40 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-YNIZ4se0yT3oM1Bn:-Mf-anVe2IGjZ07pCw54:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c01078c57223dedb03cc3708d2e298af3d08b3/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`private val`
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 42 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-YYy67YT6eK7W8FvU:-Mf-bBl0A0KsrjCvgTKu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c01078c57223dedb03cc3708d2e298af3d08b3/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L42)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since this and `emptyCollection` are only used in one test case each, they can just be local variables in the test cases where they're used
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-YPStEbuEQZhukKET:-Mf-ihgn57MYkfZAZkD3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c01078c57223dedb03cc3708d2e298af3d08b3/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

pull out coder to a variable?

```
private val coder: Coder<List<KV<...>>> = ListCoder.of(...)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-19 22:05 UTC, efoxepstein requested changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48)* status: all files reviewed, 3 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt, line 27 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-mrtK3FO5AsVT7L7i:-Mf-mrtK3FO5AsVT7L7j:b93c7lw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5e5090ad308d8d10c52e9f20850d1c8a94546f4e/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt#L27)):*
> ```Kotlin
>  * Takes in a MutableList<KV<ByteString,ByteString>>, packs them into PreprocessedEventRequest
>  * protos, encrypts the identifier and event data using several encryption schemes, and unpacks them
>  * from PreprocessedEventResponse protos back into a PCollection<KV<ByteString,ByteString>>
> ```

Technically it doesn't create the PCollection -- it just emits `KV<ByteString, ByteString>` pairs
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 42 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-YYy67YT6eK7W8FvU:-Mf-n7uu-pKp-0jphXN8:b-izy0p1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c01078c57223dedb03cc3708d2e298af3d08b3/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L42)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This one doesn't look done?

What I mean is:

```
@Test
fun whatever() {
  val collection = pcollectionOf(...)
}
```


<!-- Sent from Reviewable.io -->

2021-07-19 22:25 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt, line 27 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-mrtK3FO5AsVT7L7i:-Mf-r4JQBptAam_UqRIR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5e5090ad308d8d10c52e9f20850d1c8a94546f4e/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Technically it doesn't create the PCollection -- it just emits `KV<ByteString, ByteString>` pairs
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 42 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-YYy67YT6eK7W8FvU:-Mf-rMOwBM2-sA4Bq3OX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c01078c57223dedb03cc3708d2e298af3d08b3/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L42)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This one doesn't look done?

What I mean is:

```
@Test
fun whatever() {
  val collection = pcollectionOf(...)
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-19 22:28 UTC, efoxepstein approved these changes
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48)* status: all files reviewed, 2 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 42 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-YYy67YT6eK7W8FvU:-Mf-s_1V8MHcw9AW7ttG:bnhnodi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c01078c57223dedb03cc3708d2e298af3d08b3/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L42)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you unpack it and remove the lazy?

```
val arbitraryUnprocessedEvents = ...
val collection = pcollectionOf(...)
```


<!-- Sent from Reviewable.io -->

2021-07-19 22:34 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt, line 42 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-Mf-YYy67YT6eK7W8FvU:-Mf-tVMjDBqERFV5O5g9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d5c01078c57223dedb03cc3708d2e298af3d08b3/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFnTest.kt#L42)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you unpack it and remove the lazy?

```
val arbitraryUnprocessedEvents = ...
val collection = pcollectionOf(...)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-19 22:36 UTC, efoxepstein approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48#-:-Mf-uMRM6LI2TuRb0UQ0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck, @matthewclegg, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-20 04:40 UTC, matthewclegg approved these changes

2021-07-20 13:04 UTC, enfreck approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-20 17:43 UTC, stevenwarejones approved these changes
> Reviewed 1 of 5 files at r1, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/48)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)



<!-- Sent from Reviewable.io -->

2021-07-20 17:49 UTC, merged