Add implementation to event_data_preprocessor
world-federation-of-advertisers/panel-exchange-client pull request #57
Opened 2021-07-22 14:21 UTC by enfreck

Add implementation to event_data_preprocessor to encrypt identifier and
event data.

2021-07-22 14:51 UTC, efoxepstein requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfDgdTn9_H1zt3HuGNU:-MfDgdTn9_H1zt3HuGNV:bcj3psx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/28ff6fd4f491498ee7d90b3798b810ae8840019c/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc#L69)):*
> ```cpp
> 
>   std::unique_ptr<wfa::Fingerprinter> fingerprinter =
>       GetPepperedFingerprinter(delegate_, pepper_);
> ```

Why make a new one each time?


<!-- Sent from Reviewable.io -->

2021-07-22 15:11 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @jmorrrr, and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfDgdTn9_H1zt3HuGNU:-MfDlHWhC5fKdymrYEg1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/28ff6fd4f491498ee7d90b3798b810ae8840019c/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc#L69)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why make a new one each time?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-22 15:19 UTC, jmorrrr approved these changes
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @matthewclegg)



<!-- Sent from Reviewable.io -->

2021-07-22 16:22 UTC, efoxepstein requested changes
> Reviewed 2 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57)* status: all files reviewed, 13 unresolved discussions (waiting on @enfreck and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 47 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfDz2hx03VS3NnPhjyB:-MfDz2hy2uOvm4aqg794:b-n2wulx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L47)):*
> ```objc
>       std::unique_ptr<common::crypto::Cryptor> cryptor,
>       const ::crypto::tink::util::SecretData& pepper,
>       const wfa::Fingerprinter* delegate,
> ```

Since we're within the `wfa` namespace here, you can just write `Fingerprinter*` (without the `wfa::` prefix)
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfDzCTqDiuv--OrX241:-MfDzCTqDiuv--OrX242:b-qbnekb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L48)):*
> ```objc
>       const ::crypto::tink::util::SecretData& pepper,
>       const wfa::Fingerprinter* delegate,
>       const wfa::panelmatch::common::crypto::AesWithHkdf& aes_hkdf);
> ```

Please pass in `aes_hkdf` by const pointer (it's fine for the private member variable to be a const reference). See https://abseil.io/tips/116
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfDz83ZBU02XBdtQp-y:-MfDz83ZBU02XBdtQp-z:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L57)):*
> ```objc
>  private:
>   std::unique_ptr<common::crypto::Cryptor> cryptor_;
>   std::unique_ptr<wfa::Fingerprinter> fingerprinter;
> ```

Ditto
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfDzh6f1Df8HbeWZ5vn:-MfDzh6f1Df8HbeWZ5vo:bgfu2fr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L57)):*
> ```objc
>  private:
>   std::unique_ptr<common::crypto::Cryptor> cryptor_;
>   std::unique_ptr<wfa::Fingerprinter> fingerprinter;
> ```

`fingerprinter_`
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfDzg9G4xkHwGt47hPK:-MfDzg9G4xkHwGt47hPL:b-n4a5uk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L58)):*
> ```objc
>   std::unique_ptr<common::crypto::Cryptor> cryptor_;
>   std::unique_ptr<wfa::Fingerprinter> fingerprinter;
>   const ::wfa::panelmatch::common::crypto::AesWithHkdf& aes_hkdf_;
> ```

Please be consistent with how you refer to things in this namespace. Here you fully qualify but above you write `common::crypto::Cryptor`
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc, line 47 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfE-1gsEnpz-UU11OzX:-MfE-1gsEnpz-UU11OzY:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc#L47)):*
> ```cpp
> EventDataPreprocessor::EventDataPreprocessor(std::unique_ptr<Cryptor> cryptor,
>                                              const SecretData& pepper,
>                                              const wfa::Fingerprinter* delegate,
> ```

Ditto
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfE-Mrp09kgHCzoO_xi:-MfE-Mrp09kgHCzoO_xj:b-3xzng9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc#L62)):*
> ```cpp
>     return absl::InternalError("Incorrect vector size");
> 
>   ProcessedData processed_data = ProcessedData();
> ```

Simpler: `ProcessedData processed_data;`
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfE-WT00WClQDEKm5nP:-MfE-WT00WClQDEKm5nQ:b-u5u36n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L29)):*
> ```cpp
> namespace {
> 
> using common::crypto::Aes;
> ```

Using-decls should be fully qualified (always start with `using ::`)
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 100 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfE00vM9uocE6imIGcN:-MfE00vM9uocE6imIGcO:b-42jnaq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L100)):*
> ```cpp
> };
> 
> std::unique_ptr<FakeCryptor> CreateFakeCryptor(void) {
> ```

Nit: remove `void`
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 106 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfE05bdCrqAFvh9f4jN:-MfE05bdCrqAFvh9f4jO:b-byja30) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L106)):*
> ```cpp
> // Test using fake classes to ensure proper return values
> TEST(EventDataPreprocessorTests, properImplementation) {
>   const FakeFingerprinter fingerprinter = FakeFingerprinter();
> ```

You can just write `const FakeFingerprinter fingerprinter;`
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 117 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfE0BBX5El0_ZsFHJIg:-MfE0BBX5El0_ZsFHJIh:b-p83gvf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L117)):*
> ```cpp
>   ASSERT_OK_AND_ASSIGN(ProcessedData processed,
>                        preprocessor.Process("identifier", "event"));
>   ASSERT_EQ(processed.encrypted_identifier, 1);
> ```

Prefer `EXPECT_EQ` unless you need `ASSERT_EQ`'s behavior. 
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 126 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfE0OzBCPfhz0P7Y789:-MfE0OzBCPfhz0P7Y78A:b-abgjcy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L126)):*
> ` [...]

2021-07-22 17:20 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57)* status: 2 of 5 files reviewed, 12 unresolved discussions (waiting on @efoxepstein, @jmorrrr, and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 47 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfDz2hx03VS3NnPhjyB:-MfEDhif2EhSa1ZIbBtd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since we're within the `wfa` namespace here, you can just write `Fingerprinter*` (without the `wfa::` prefix)
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfDzCTqDiuv--OrX241:-MfEDiDH9wuhtFxk_9tK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please pass in `aes_hkdf` by const pointer (it's fine for the private member variable to be a const reference). See https://abseil.io/tips/116
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfDz83ZBU02XBdtQp-y:-MfEDmq1-X4MxY2mIj9Y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfDzh6f1Df8HbeWZ5vn:-MfEDnYs-IO7bFrm62B7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`fingerprinter_`
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfDzg9G4xkHwGt47hPK:-MfEDpHv-uZTy6Q-dErG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L58)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please be consistent with how you refer to things in this namespace. Here you fully qualify but above you write `common::crypto::Cryptor`
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc, line 47 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfE-1gsEnpz-UU11OzX:-MfEDptMDO-p8laCkVA9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfE-Mrp09kgHCzoO_xi:-MfEDq4Q-S0eeH-e-IOU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Simpler: `ProcessedData processed_data;`
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfE-WT00WClQDEKm5nP:-MfEDqouAaWi2OtdY7TS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Using-decls should be fully qualified (always start with `using ::`)
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 106 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfE05bdCrqAFvh9f4jN:-MfEDtlEBnmh7P_5vAJi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L106)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

You can just write `const FakeFingerprinter fingerprinter;`
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 117 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfE0BBX5El0_ZsFHJIg:-MfEDvEQ6qSzbM_v7raS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L117)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Prefer `EXPECT_EQ` unless you need `ASSERT_EQ`'s behavior. 
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 126 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfE0OzBCPfhz0P7Y789:-MfEDvZH6iX3msKJ8DB4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L126)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`const Foo foo(arg1, arg2, arg3);`
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 139 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfE0Sdu0CmhzZz7jKVq:-MfEDvtnDsaEaTQtM17C:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e2b7f22c075296ac8286711d453970a675fef603/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L139)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-22 17:29 UTC, efoxepstein requested changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57)* status: all files reviewed, 2 unresolved discussions (waiting on @enfreck and @matthewclegg)

___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 43 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfEEcWH1-EyEOPe1kPx:-MfEEcWH1-EyEOPe1kPy:b-z0w97) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/de0f25fee7e010803b544a8cff256b18804a9b2b/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L43)):*
> ```cpp
>   absl::StatusOr<SecretData> ComputeHkdf(const SecretData& ikm,
>                                          int length) const override {
>     return SecretDataFromStringView("hkdf");
> ```

My concern about these fake things is that they ignore the inputs, so there could be bugs in `EventDataPreprocessor` with passing the wrong inputs to things.

Can you make the return values depend on the inputs somehow?
For example, the HKDF could be `SecretDataFromStringView(absl::StrCat("HKDF with length ", length, " of ", SecretDataAsStringView(ikm)))`.

Alternatively, use gMock so you can validate the inputs.

```
class MockHkdf {
 public:
  MOCK_METHOD(absl::StatusOr<SecretData>, ComputeHkdf, (const SecretData& irm, int length), (const, override));
};

TEST(..., ...) {
  MockHkdf mock_hkdf;
  ...
  EXPECT_CALL(mock_hkdf, ComputeHkdf(SecretDataAsStringView("what the input should be"), 64))
    .WillOnce(Return(absl::StatusOr<SecretData>(SecretDataFromStringView("hkdf"))));
```
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 88 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfEERC21dF6oYKMr9Bm:-MfEERC21dF6oYKMr9Bn:bnsvwnr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/de0f25fee7e010803b544a8cff256b18804a9b2b/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L88)):*
> ```cpp
>   absl::StatusOr<std::vector<std::string>> BatchProcess(
>       const std::vector<std::string>& plaintexts_or_ciphertexts,
>       wfa::panelmatch::common::crypto::Action action) override {
> ```

For consistency, also add a using-decl for Action please


<!-- Sent from Reviewable.io -->

2021-07-22 19:24 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @matthewclegg, and @stevenwarejones)

___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 43 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfEEcWH1-EyEOPe1kPx:-MfEey8p4WUzU8uvKf9r:b-62laue) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/de0f25fee7e010803b544a8cff256b18804a9b2b/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

My concern about these fake things is that they ignore the inputs, so there could be bugs in `EventDataPreprocessor` with passing the wrong inputs to things.

Can you make the return values depend on the inputs somehow?
For example, the HKDF could be `SecretDataFromStringView(absl::StrCat("HKDF with length ", length, " of ", SecretDataAsStringView(ikm)))`.

Alternatively, use gMock so you can validate the inputs.

```
class MockHkdf {
 public:
  MOCK_METHOD(absl::StatusOr<SecretData>, ComputeHkdf, (const SecretData& irm, int length), (const, override));
};

TEST(..., ...) {
  MockHkdf mock_hkdf;
  ...
  EXPECT_CALL(mock_hkdf, ComputeHkdf(SecretDataAsStringView("what the input should be"), 64))
    .WillOnce(Return(absl::StatusOr<SecretData>(SecretDataFromStringView("hkdf"))));
```
</blockquote></details>

I did the first option since that's mostly what I have currently, but if we think I should use gMock I can switch over to that too.
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 88 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfEERC21dF6oYKMr9Bm:-MfEevqe5ACwrX71Xy_4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/de0f25fee7e010803b544a8cff256b18804a9b2b/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L88)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

For consistency, also add a using-decl for Action please
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-22 19:26 UTC, efoxepstein requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57)* status: all files reviewed, 4 unresolved discussions (waiting on @enfreck, @matthewclegg, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc, line 57 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfEfIIm0f91VHpAfTlY:-MfEfIIm0f91VHpAfTlZ:bq3wshc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/33e5bed21f40a43c633ffb8e81f38c46a90a5167/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc#L57)):*
> ```cpp
>     absl::string_view identifier, absl::string_view event_data) const {
>   std::vector<std::string> input = {std::string(identifier)};
>   std::cout << "Input = " << input[0] << std::endl;
> ```

Delete debugging code?
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfEfLx05yO3KLP0D0CF:-MfEfLx05yO3KLP0D0CG:b905yu6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/33e5bed21f40a43c633ffb8e81f38c46a90a5167/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L46)):*
> ```cpp
>                                          int length) const override {
>     return SecretDataFromStringView(absl::StrCat(
>         "HKDF with length ", length, " of ", SecretDataAsStringView(ikm)));
> ```

Maybe put quotes around this (and others)? Like `..., " of '", SecretDataAsStringView(ikr), "'"));`
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 79 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfEfYTz3gBb_uxslDNx:-MfEfYU-AUtROcKrDYG5:bo419fa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/33e5bed21f40a43c633ffb8e81f38c46a90a5167/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L79)):*
> ```cpp
>     absl::string_view item_as_string_view(
>         reinterpret_cast<const char*>(item.data()), item.size());
>     return item_as_string_view.length();
> ```

This looks like the same as `return item.size()`
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 122 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfEfgKnE_14LZ2dJJt9:-MfEfgKnE_14LZ2dJJtA:b-grds9y) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/33e5bed21f40a43c633ffb8e81f38c46a90a5167/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L122)):*
> ```cpp
>                                      &fingerprinter, &aes_hkdf);
>   ASSERT_OK_AND_ASSIGN(ProcessedData processed,
>                        preprocessor.Process("identifier", "event"));
> ```

Can you change this to "some-identifier" and "some-event" so it's more recognizable as a test string? (Or "test-event")


<!-- Sent from Reviewable.io -->

2021-07-23 13:26 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @matthewclegg, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc, line 57 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfEfIIm0f91VHpAfTlY:-MfIXqqa4AGJ64qVI_ZF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/33e5bed21f40a43c633ffb8e81f38c46a90a5167/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Delete debugging code?
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfEfLx05yO3KLP0D0CF:-MfIXrhr97mnsvmvXVTw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/33e5bed21f40a43c633ffb8e81f38c46a90a5167/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe put quotes around this (and others)? Like `..., " of '", SecretDataAsStringView(ikr), "'"));`
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 79 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfEfYTz3gBb_uxslDNx:-MfIXs9x3tnhvfE8E9dR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/33e5bed21f40a43c633ffb8e81f38c46a90a5167/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L79)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This looks like the same as `return item.size()`
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 122 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfEfgKnE_14LZ2dJJt9:-MfIXsl715xbCPf4nQLH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/33e5bed21f40a43c633ffb8e81f38c46a90a5167/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L122)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you change this to "some-identifier" and "some-event" so it's more recognizable as a test string? (Or "test-event")
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-23 13:34 UTC, efoxepstein approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-:-MfIZjLEDcBV4_ydjHrw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck, @matthewclegg, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc, line 57 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfEfIIm0f91VHpAfTlY:-MfIZ_-R7BwrgRYjAM5y:bu19wx0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/33e5bed21f40a43c633ffb8e81f38c46a90a5167/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc#L57)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove #include <ostream> too?


<!-- Sent from Reviewable.io -->

2021-07-23 15:59 UTC, enfreck reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @matthewclegg, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc, line 57 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfEfIIm0f91VHpAfTlY:-MfJ4sNE2ShweIOXYp5t:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/33e5bed21f40a43c633ffb8e81f38c46a90a5167/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.cc#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Remove #include <ostream> too?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-23 16:13 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-23 17:10 UTC, matthewclegg approved these changes

2021-07-23 17:14 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck and @matthewclegg)

___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 39 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfJKq9A5t4m5OjPzMUZ:-MfJKq9A5t4m5OjPzMU_:bpp9x9d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3eca27ad4580f2db01419821e4a213a5b0407d10/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L39)):*
> ```cpp
> 
> // Fake Hkdf class for testing purposes only
> class FakeHkdf : public Hkdf {
> ```

@efoxepstein - shouldn't these fake classes go under `src/main/cc/wfa/panelmatch/protocol/crypto/testing`?


<!-- Sent from Reviewable.io -->

2021-07-23 17:47 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 39 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfJKq9A5t4m5OjPzMUZ:-MfJTTc48qvKZC78WFl6:bdu28ds) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3eca27ad4580f2db01419821e4a213a5b0407d10/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L39)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@efoxepstein - shouldn't these fake classes go under `src/main/cc/wfa/panelmatch/protocol/crypto/testing`?
</blockquote></details>

Only if there's a need to reuse them in other tests


<!-- Sent from Reviewable.io -->

2021-07-23 17:48 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc, line 39 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57#-MfJKq9A5t4m5OjPzMUZ:-MfJTnVrCB2wdWsh92DA:be55ni7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3eca27ad4580f2db01419821e4a213a5b0407d10/src/test/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor_test.cc#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Only if there's a need to reuse them in other tests
</blockquote></details>

(Or if their logic is sufficiently complicated that we'd want unit tests for the fakes)


<!-- Sent from Reviewable.io -->

2021-07-23 19:30 UTC, stevenwarejones approved these changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/57)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-23 21:02 UTC, merged