Adds calls to EventDataPreprocessor
world-federation-of-advertisers/panel-exchange-client pull request #63
Opened 2021-07-26 21:33 UTC by jmorrrr

Adds calls to EventDataPreprocessor and adjusts existing tests accordingly

2021-07-26 21:44 UTC, efoxepstein requested changes
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63)* status: all files reviewed, 10 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZjSVn0UyBoio_MX7t:-MfZjSVn0UyBoio_MX7u:bzhtwvw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc#L66)):*
> ```cpp
>       &fingerprinter, &aes_hkdf);
>   PreprocessEventsResponse processed;
>   for (PreprocessEventsRequest::UnprocessedEvent u :
> ```

This is making a copy of each `UnprocessedEvent` -- can you use a const reference instead of a value?
___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZjen4AqV_PErGw40p:-MfZjen4AqV_PErGw40q:bdhb1wa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc#L68)):*
> ```cpp
>   for (PreprocessEventsRequest::UnprocessedEvent u :
>        request.unprocessed_events()) {
>     preprocessor.Process(u.id(), u.data());
> ```

Should this line exist?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZjrPXDBM_kmFuso4N:-MfZjrPXDBM_kmFuso4O:bbnaahz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e1cd1d219b8bdece4620395787c83d702f4dfe9d/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L27)):*
> ```Kotlin
> 
>   override fun preprocess(request: PreprocessEventsRequest): PreprocessEventsResponse {
>     return wrapJniException {
> ```

Why did you remove the `wrapJniException`?
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZkPiSCeGRraO7IpzN:-MfZkPiSCeGRraO7IpzO:b9c1bvp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L17)):*
> ```cpp
> #include "wfa/panelmatch/client/eventpreprocessing/preprocess_events.h"
> 
> #include <wfa/panelmatch/protocol/crypto/event_data_preprocessor.h>
> ```

Use `#include "..."` instead of `#include <...>` for everything except stdlib things (like `<string>`, `<vector>`, etc.)
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZkZjm0D-czHviTseM:-MfZkZjm0D-czHviTseN:b-54egmn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L35)):*
> ```cpp
> #include "wfa/panelmatch/client/eventpreprocessing/preprocess_events.pb.h"
> 
> class EventDataPreprocessor;
> ```

Delete this?
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZkcbA3_umiAJPM917:-MfZkcbA3_umiAJPM918:b7pzum3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L46)):*
> ```cpp
> using ::wfa::panelmatch::protocol::crypto::ProcessedData;
> 
> PreprocessEventsRequest makeTestRequest(const char* id, const char* data,
> ```

C++ functions should be `PascalCase`
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZken6EViPXUix95Ul:-MfZken6EViPXUix95Um:b-hl8dua) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L47)):*
> ```cpp
> 
> PreprocessEventsRequest makeTestRequest(const char* id, const char* data,
>                                         const char* cryptokey,
> ```

Please use `absl::string_view` for string-type parameters
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZktj50ojH_uomlGF9:-MfZktj50ojH_uomlGFA:b-87b7ji) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L59)):*
> ```cpp
> }
> 
> // Test using actual implementations to ensure nothing crashes
> ```

Can you add test cases for things like:

* Missing pepper
* Missing crypto key
* zero unprocessed events
* multiple unprocessed events
* missing id in unprocessed event
* missing data in unprocessed event
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZkmeM4SypWJl7n0cZ:-MfZkmeNDmfaGw_UQutR:bhgtijm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L64)):*
> ```cpp
>       "some-identifier", "some-data", "test_crypto_key", "test_pepper");
> 
>   ASSERT_OK_AND_ASSIGN(PreprocessEventsResponse processed,
> ```

Probably a good idea to make sure the response has the right number of results in it
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZlVlB5aN_5WMiur31:-MfZlVlCAMYyvDIzUEl9:b-yrxkzk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt#L30)):*
> ```Kotlin
> 
>   @Test
>   fun `test`() {
> ```

I think you can just delete this test case. This should be covered by the case class.


<!-- Sent from Reviewable.io -->

2021-07-26 21:46 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63)* status: all files reviewed, 10 unresolved discussions (waiting on @efoxepstein, @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZlVlB5aN_5WMiur31:-MfZmCuaD7WFpKB-CHQy:b-bkbxos) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt#L30)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think you can just delete this test case. This should be covered by the case class.
</blockquote></details>

Should I just delete the file?


<!-- Sent from Reviewable.io -->

2021-07-26 22:04 UTC, jmorrrr commented
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZken6EViPXUix95Ul:-MfZq-9-0-vCD2UMxxB_:b-el477v) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use `absl::string_view` for string-type parameters
</blockquote></details>

It is saying that  set_id,set_data,set_crypto, and set_pepper need either char* or std::basic_string<char> types


<!-- Sent from Reviewable.io -->

2021-07-26 22:10 UTC, jmorrrr commented
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZken6EViPXUix95Ul:-MfZra5424R02jmmauS1:b1t12fp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L47)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

It is saying that  set_id,set_data,set_crypto, and set_pepper need either char* or std::basic_string<char> types
</blockquote></details>

I am getting rid of this function anyway so never mind


<!-- Sent from Reviewable.io -->

2021-07-26 22:12 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63)* status: all files reviewed, 10 unresolved discussions (waiting on @efoxepstein, @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZlVlB5aN_5WMiur31:-MfZrxv_6Nijro6WYL4p:b5k0qoa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt#L30)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Should I just delete the file?
</blockquote></details>

Then the tests in the base class wouldn't run....


<!-- Sent from Reviewable.io -->

2021-07-26 23:11 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63)* status: 4 of 8 files reviewed, 10 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZjSVn0UyBoio_MX7t:-MfZqdKI68MgK6-CosII:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc#L66)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is making a copy of each `UnprocessedEvent` -- can you use a const reference instead of a value?
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZjen4AqV_PErGw40p:-MfZoa5T6KKaDb0M2Xcc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc#L68)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Should this line exist?
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZkPiSCeGRraO7IpzN:-MfZqlkZEovPbbu6DHj6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L17)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Use `#include "..."` instead of `#include <...>` for everything except stdlib things (like `<string>`, `<vector>`, etc.)
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZkZjm0D-czHviTseM:-MfZogJT3jkVtMI34kna:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L35)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Delete this?
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZkcbA3_umiAJPM917:-MfZoldl8ti1FcIUlkY_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

C++ functions should be `PascalCase`
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZktj50ojH_uomlGF9:-Mf_3gT85QMFBxTOKZVZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L59)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you add test cases for things like:

* Missing pepper
* Missing crypto key
* zero unprocessed events
* multiple unprocessed events
* missing id in unprocessed event
* missing data in unprocessed event
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZkmeM4SypWJl7n0cZ:-MfZstCxAiWHv-n932nI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L64)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Probably a good idea to make sure the response has the right number of results in it
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZlVlB5aN_5WMiur31:-MfZss7mAKvmJdQ0fWyJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67191fb28f86a4db99ba12bd8d02e7d254b0e6e9/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt#L30)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Then the tests in the base class wouldn't run....
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfZjrPXDBM_kmFuso4N:-MfZo_DdD6aElXxpctSC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e1cd1d219b8bdece4620395787c83d702f4dfe9d/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why did you remove the `wrapJniException`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-26 23:22 UTC, efoxepstein requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63)* status: all files reviewed, 8 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 63 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-Mf_6wbY6UyamN4ZefYC:-Mf_6wbY6UyamN4ZefYD:b-qx3m7a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed2597e32083ee6ea71f15cebbd35c336255e86c/src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc#L63)):*
> ```cpp
>   const AesWithHkdf aes_hkdf = AesWithHkdf(std::move(hkdf), std::move(aes));
>   EventDataPreprocessor preprocessor = EventDataPreprocessor(
>       std::move(cryptor), SecretDataFromStringView(request.pepper()),
> ```

You might want to consider checking that `request.pepper().size() > 0` somewhere above here (see also the comment in the test file about this)
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-Mf_5Q8kCZRmcbV40G2v:-Mf_5Q8kCZRmcbV40G2w:b-by4bci) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed2597e32083ee6ea71f15cebbd35c336255e86c/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L44)):*
> ```cpp
> 
> // Test using actual implementations to ensure nothing crashes
> TEST(EventDataPreprocessorTests, actualValues) {
> ```

Nitpick: can you use `PascalCase` for `actualValues` too? I think that's the convention -- see examples here: https://google.github.io/googletest/primer.html#simple-tests
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-Mf_5d463isQdrjQiYiA:-Mf_5d463isQdrjQiYiB:bh4ig0q) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed2597e32083ee6ea71f15cebbd35c336255e86c/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L55)):*
> ```cpp
>   ASSERT_OK_AND_ASSIGN(PreprocessEventsResponse processed,
>                        PreprocessEvents(test_request));
>   ASSERT_EQ(processed.processed_events_size(), 1);
> ```

This one can be `EXPECT_EQ` -- you only want to use `ASSERT` when you specifically *need* the test case to stop executing if the statement fails.
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-Mf_5kmr2l3zK014Tmd1:-Mf_5kmr2l3zK014Tmd2:bf40efz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed2597e32083ee6ea71f15cebbd35c336255e86c/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L55)):*
> ```cpp
>   ASSERT_OK_AND_ASSIGN(PreprocessEventsResponse processed,
>                        PreprocessEvents(test_request));
>   ASSERT_EQ(processed.processed_events_size(), 1);
> ```

It might be worthwhile checking that the output value is *different* from the input too: `EXPECT_NE(processed.processed_events(0).whatever_the_field_is_called(), "some-data");`
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-Mf_63K9-R9U0hFmLnE2:-Mf_63K9-R9U0hFmLnE3:bgv34rw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed2597e32083ee6ea71f15cebbd35c336255e86c/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L65)):*
> ```cpp
>   unprocessed_event->set_data("some-data");
>   test_request.set_crypto_key("some-cryptokey");
>   ASSERT_OK_AND_ASSIGN(PreprocessEventsResponse processed,
> ```

Since you're not actually using `processed` here, you should probably do `EXPECT_THAT(PreprocessEvents(test_request), IsOk());`

But also: do we want this test case to be OK? I would expect that it should probably throw an error. What do you think? (An empty pepper is likely indicative of something weird happening.)
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 76 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-Mf_5yp1DYTdqlPQrZGp:-Mf_5yp22yKQBCkbu6nP:bw8ca10) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed2597e32083ee6ea71f15cebbd35c336255e86c/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L76)):*
> ```cpp
>   test_request.set_pepper("some-pepper");
>   ASSERT_THAT(PreprocessEvents(test_request).status(),
>               wfa::StatusIs(absl::StatusCode::kInvalidArgument, ""));
> ```

You can just write `StatusIs` without the `wfa` in front
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-Mf_6eBb3pIh6GLkbDMs:-Mf_6eBb3pIh6GLkbDMt:b-aupowp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed2597e32083ee6ea71f15cebbd35c336255e86c/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L93)):*
> ```cpp
>   test_request.set_pepper("some-pepper");
>   test_request.set_crypto_key("some-cryptokey");
>   ASSERT_OK_AND_ASSIGN(PreprocessEventsResponse processed,
> ```

Ditto for using `IsOk()`
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 103 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-Mf_6gVbDHX2pXTfDB6V:-Mf_6gVbDHX2pXTfDB6W:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed2597e32083ee6ea71f15cebbd35c336255e86c/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L103)):*
> ```cpp
>   test_request.set_pepper("some-pepper");
>   test_request.set_crypto_key("some-cryptokey");
>   ASSERT_OK_AND_ASSIGN(PreprocessEventsResponse processed,
> ```

Ditto


<!-- Sent from Reviewable.io -->

2021-07-26 23:53 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63)* status: all files reviewed, 8 unresolved discussions (waiting on @efoxepstein, @enfreck, @matthewclegg, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 63 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-Mf_6wbY6UyamN4ZefYC:-Mf_Cbw_BJE53-octdYD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed2597e32083ee6ea71f15cebbd35c336255e86c/src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc#L63)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

You might want to consider checking that `request.pepper().size() > 0` somewhere above here (see also the comment in the test file about this)
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-Mf_5Q8kCZRmcbV40G2v:-Mf_9WdV9vKHoLpEEvwW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed2597e32083ee6ea71f15cebbd35c336255e86c/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L44)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Nitpick: can you use `PascalCase` for `actualValues` too? I think that's the convention -- see examples here: https://google.github.io/googletest/primer.html#simple-tests
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-Mf_5d463isQdrjQiYiA:-Mf_9sv3C4n0D9iUpfeK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed2597e32083ee6ea71f15cebbd35c336255e86c/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This one can be `EXPECT_EQ` -- you only want to use `ASSERT` when you specifically *need* the test case to stop executing if the statement fails.
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-Mf_5kmr2l3zK014Tmd1:-Mf_CdHR9XYISXGM8J-m:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed2597e32083ee6ea71f15cebbd35c336255e86c/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It might be worthwhile checking that the output value is *different* from the input too: `EXPECT_NE(processed.processed_events(0).whatever_the_field_is_called(), "some-data");`
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-Mf_63K9-R9U0hFmLnE2:-Mf_AHhtEG52K_fZxKFs:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed2597e32083ee6ea71f15cebbd35c336255e86c/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L65)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since you're not actually using `processed` here, you should probably do `EXPECT_THAT(PreprocessEvents(test_request), IsOk());`

But also: do we want this test case to be OK? I would expect that it should probably throw an error. What do you think? (An empty pepper is likely indicative of something weird happening.)
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 76 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-Mf_5yp1DYTdqlPQrZGp:-Mf_AS3WBPG94fyO8zjH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed2597e32083ee6ea71f15cebbd35c336255e86c/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L76)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

You can just write `StatusIs` without the `wfa` in front
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-Mf_6eBb3pIh6GLkbDMs:-Mf_AIt82NZJaT0eKU5T:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed2597e32083ee6ea71f15cebbd35c336255e86c/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L93)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto for using `IsOk()`
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 103 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-Mf_6gVbDHX2pXTfDB6V:-Mf_AIge50F8xsDBqzTQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed2597e32083ee6ea71f15cebbd35c336255e86c/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L103)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-26 23:55 UTC, efoxepstein approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck, @matthewclegg, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-27 14:52 UTC, stevenwarejones requested changes
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt, line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfcRmmwEPvpD6a1hRuV:-MfcRmmwEPvpD6a1hRuW:b-po249n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ef7388b3abeb776ba18f678a6bc07e990d31ef8a/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt#L23)):*
> ```Kotlin
> @RunWith(JUnit4::class)
> class JniPreprocessEventsTest : AbstractPreprocessEventsTest() {
>   override val preprocessEvents: PreprocessEvents = JniPreprocessEvents()
> ```

can you add a test that makes sure JNIException is throw and caught by Kotlin?


<!-- Sent from Reviewable.io -->

2021-07-27 16:16 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck, @matthewclegg, and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt, line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63#-MfcRmmwEPvpD6a1hRuV:-MfckGrLANDROEGFBfVi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ef7388b3abeb776ba18f678a6bc07e990d31ef8a/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt#L23)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add a test that makes sure JNIException is throw and caught by Kotlin?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-27 16:22 UTC, stevenwarejones approved these changes
> Reviewed 3 of 8 files at r1, 1 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck, @matthewclegg, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-27 16:31 UTC, enfreck approved these changes
> Reviewed 4 of 8 files at r1, 1 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/63)* status: all files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-27 16:32 UTC, merged