Make Function to Run Event Preprocessing DoFns
world-federation-of-advertisers/panel-exchange-client pull request #64
Opened 2021-07-27 20:46 UTC by jmorrrr

Adds function and testing

2021-07-27 21:24 UTC, efoxepstein requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 6 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdoS_v2iCbk93ibfPz:-MfdoS_v2iCbk93ibfQ-:b4rieuk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt#L23)):*
> ```Kotlin
> 
> /** Runs preprocessing DoFns on input [PCollection] and outputs encrypted [PCollection] */
> fun eventPreprocessor(
> ```

The part of speech feels wrong here -- can you rename to `preprocessEvents`?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdoscR5r3vaMWG_prW:-MfdoscR5r3vaMWG_prX:bicczrb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt#L24)):*
> ```Kotlin
> /** Runs preprocessing DoFns on input [PCollection] and outputs encrypted [PCollection] */
> fun eventPreprocessor(
>   collection: PCollection<KV<ByteString, ByteString>>,
> ```

`collection` is a little bit generic of a name, can you rename to `events`?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdoYlaC7ai4fbIXOnl:-MfdoYlb9_URhME9FsX9:b-gnx43x) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt#L27)):*
> ```Kotlin
>   maxByteSize: Int,
>   pepper: ByteString,
>   cryptokey: ByteString
> ```

Can you provide two versions of this function? One as is and another one like:

```
fun preprocessEvents(events: PCollection<KV<ByteString, ByteString>>, maxByteSize: Int, pepperProvider: SerializableFunction<Void, ByteString>, cryptoKeyProvider: SerializableFunction<Void, ByteString>)
```

(And then one of them can call the other)
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessorTest.kt, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-Mfdp4Jk4oGZNZBt-dk1:-Mfdp3GN9Q5gsnqmHkV6:b-omjixb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessorTest.kt#L43)):*
> ```Kotlin
>   }
> 
>   fun kvOf(key: String, value: String): KV<ByteString, ByteString> {
> ```

It's a little confusing defining another version of `kvOf`. How about:

```
fun eventsOf(vararg pairs: Pair<String, String>): PCollection<KV<ByteString, ByteString>> {
  val coder = ...
  return pcollectionOf("Create Events", *pairs.map { kvOf(toByteString(it.first), toByteString(it.second)) }.toTypedArray(), coder = coder)
}
```

Then in your test case: `val events = eventsOf("A" to "B", "C" to "D", ...)`

For a similar example see https://github.com/world-federation-of-advertisers/panel-exchange-client/pull/49/files#diff-305256797a181e80e4959cdfda99a5b99209985a80088ff7c8b08c3354b767adR41
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessorTest.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdqPEGElIBKZZy1Lpy:-MfdqPEGElIBKZZy1Lpz:b-bbm7wz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessorTest.kt#L46)):*
> ```Kotlin
>     return kvOf(toByteString(key), toByteString(value))
>   }
>   fun toByteString(input: String): ByteString {
> ```

It would be a little more Kotlin-ish to name this `byteStringOf`. Or define `String.toByteString()` like this: https://github.com/world-federation-of-advertisers/panel-exchange-client/pull/49/files#diff-305256797a181e80e4959cdfda99a5b99209985a80088ff7c8b08c3354b767adR170 and then use it like `"some-string".toByteString()`
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdqfUMDN1Sz99UDIqG:-MfdqfUMDN1Sz99UDIqH:b-46pmaa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt#L51)):*
> ```Kotlin
>   fun testJniWrapExceptionCryptoKey() {
>     assertFailsWith(JniException::class) {
>       val request =
> ```

While you're touching this code, can you move `val request` out of the `assertFailsWith` please


<!-- Sent from Reviewable.io -->

2021-07-27 22:17 UTC, jmorrrr commented
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdoS_v2iCbk93ibfPz:-Mfe1k0F3JJitLmY2hnW:bdfeo70) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The part of speech feels wrong here -- can you rename to `preprocessEvents`?
</blockquote></details>

There is already something called process events.. maybe like Batch and? CombinedDoFns? Any Ideas?


<!-- Sent from Reviewable.io -->

2021-07-27 22:21 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 6 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdoS_v2iCbk93ibfPz:-Mfe2mRm7kQVRUXLZbeU:buvokxt) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt#L23)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

There is already something called process events.. maybe like Batch and? CombinedDoFns? Any Ideas?
</blockquote></details>

Where is the existing thing called `preprocessEvents`?


<!-- Sent from Reviewable.io -->

2021-07-27 22:23 UTC, jmorrrr commented
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdoS_v2iCbk93ibfPz:-Mfe32CR51ztXGSK1WYR:b-69mnum) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Where is the existing thing called `preprocessEvents`?
</blockquote></details>

an Interface in the kotlin eventpreprocessing folder


<!-- Sent from Reviewable.io -->

2021-07-27 22:24 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 6 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdoS_v2iCbk93ibfPz:-Mfe3CYS3ygGuS4Kq3ai:b3mrcmu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt#L23)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

an Interface in the kotlin eventpreprocessing folder
</blockquote></details>

Shouldn't be an issue -- they are capitalized differently. Does it complain?


<!-- Sent from Reviewable.io -->

2021-07-27 22:26 UTC, jmorrrr commented
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdoS_v2iCbk93ibfPz:-Mfe3fzBEjCUJk2ODGTl:b-h0c5uq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Shouldn't be an issue -- they are capitalized differently. Does it complain?
</blockquote></details>

Not for the function but do I just name the file with a lowercase p too?


<!-- Sent from Reviewable.io -->

2021-07-27 22:27 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 6 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdoS_v2iCbk93ibfPz:-Mfe3pZk6RAWmwtrwx6K:b-zerazy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt#L23)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Not for the function but do I just name the file with a lowercase p too?
</blockquote></details>

You can keep the file named `EventPreprocessor` if you want, or `EventPreprocessorPipeline` or whatever you want


<!-- Sent from Reviewable.io -->

2021-07-27 23:29 UTC, jmorrrr commented
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdoYlaC7ai4fbIXOnl:-MfeI5PUCmEOC9jNwD3f:b-8jb6ig) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you provide two versions of this function? One as is and another one like:

```
fun preprocessEvents(events: PCollection<KV<ByteString, ByteString>>, maxByteSize: Int, pepperProvider: SerializableFunction<Void, ByteString>, cryptoKeyProvider: SerializableFunction<Void, ByteString>)
```

(And then one of them can call the other)
</blockquote></details>

So then do I need to make new cryptokeyProvider and pepperProvider SerializableFunctions that call the other ones? I am confused what this means


<!-- Sent from Reviewable.io -->

2021-07-27 23:35 UTC, jmorrrr commented
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdoYlaC7ai4fbIXOnl:-MfeJf8d1_VZkhkCbWpR:bfrg3o0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt#L27)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

So then do I need to make new cryptokeyProvider and pepperProvider SerializableFunctions that call the other ones? I am confused what this means
</blockquote></details>

Nevermind I think I do understand


<!-- Sent from Reviewable.io -->

2021-07-27 23:39 UTC, stevenwarejones reviewed
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdoS_v2iCbk93ibfPz:-MfeHS14AKW0BBUKGAv5:bitq48) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

You can keep the file named `EventPreprocessor` if you want, or `EventPreprocessorPipeline` or whatever you want
</blockquote></details>

`preprocessEventsInPipeline` ?


<!-- Sent from Reviewable.io -->

2021-07-27 23:52 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdoS_v2iCbk93ibfPz:-MfeLyRI2A_Un5otOu9t:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt#L23)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`preprocessEventsInPipeline` ?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdoscR5r3vaMWG_prW:-MfeEYF839_StB_dk9Qn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt#L24)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`collection` is a little bit generic of a name, can you rename to `events`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdoYlaC7ai4fbIXOnl:-MfeJxO489vJMHR-Lxc9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessor.kt#L27)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Nevermind I think I do understand
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessorTest.kt, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-Mfdp4Jk4oGZNZBt-dk1:-MfeHFzeCHesk87UcEbo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessorTest.kt#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's a little confusing defining another version of `kvOf`. How about:

```
fun eventsOf(vararg pairs: Pair<String, String>): PCollection<KV<ByteString, ByteString>> {
  val coder = ...
  return pcollectionOf("Create Events", *pairs.map { kvOf(toByteString(it.first), toByteString(it.second)) }.toTypedArray(), coder = coder)
}
```

Then in your test case: `val events = eventsOf("A" to "B", "C" to "D", ...)`

For a similar example see https://github.com/world-federation-of-advertisers/panel-exchange-client/pull/49/files#diff-305256797a181e80e4959cdfda99a5b99209985a80088ff7c8b08c3354b767adR41
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessorTest.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdqPEGElIBKZZy1Lpy:-MfeH0kzAEoGRAj63Xtt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessorTest.kt#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It would be a little more Kotlin-ish to name this `byteStringOf`. Or define `String.toByteString()` like this: https://github.com/world-federation-of-advertisers/panel-exchange-client/pull/49/files#diff-305256797a181e80e4959cdfda99a5b99209985a80088ff7c8b08c3354b767adR170 and then use it like `"some-string".toByteString()`
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfdqfUMDN1Sz99UDIqG:-MfeF7yR3Mz5pH3I0b2M:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44319c3730d44538a691b4bcd2d7d100a8a4bec6/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEventsTest.kt#L51)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

While you're touching this code, can you move `val request` out of the `assertFailsWith` please
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-27 23:53 UTC, efoxepstein requested changes
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt, line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfeNcuQAKZ_1s3ETb7C:-MfeNcuQAKZ_1s3ETb7D:bdfu4m2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4eed8ee6f090b1cf826269735e20b1cdbff2c5d0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt#L49)):*
> ```Kotlin
>   cryptoKeyProvider: SerializableFunction<Void, ByteString>
> ) {
>   return preprocessEventsInPipeline(events, maxByteSize, pepperProvider, cryptoKeyProvider)
> ```

This is infinite recursion I think. You want *this* version to do the `events.apply` stuff and the other version to build the HardCoded stuff and call this one


<!-- Sent from Reviewable.io -->

2021-07-27 23:58 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt, line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfeNcuQAKZ_1s3ETb7C:-MfeO9ji5K6Y6wO5JZfF:b-kb7882) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4eed8ee6f090b1cf826269735e20b1cdbff2c5d0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt#L49)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is infinite recursion I think. You want *this* version to do the `events.apply` stuff and the other version to build the HardCoded stuff and call this one
</blockquote></details>

Should I just make the other function completely independent and just have it the same except it calls EncryptionEventsDoFn with the other Serializable Function calls? I do not think it is infinite recursion now because you suggested passing in types SerializableFunction<Void,ByteString> so if I pass that into HardCodedPepperProvider it should just return whatever pepper and cryptokey the SerializableFunction<Void,ByteString> returns


<!-- Sent from Reviewable.io -->

2021-07-28 00:05 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt, line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfeNcuQAKZ_1s3ETb7C:-MfeQ2Dm4oq16R-VbKDF:badmf3j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4eed8ee6f090b1cf826269735e20b1cdbff2c5d0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt#L49)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Should I just make the other function completely independent and just have it the same except it calls EncryptionEventsDoFn with the other Serializable Function calls? I do not think it is infinite recursion now because you suggested passing in types SerializableFunction<Void,ByteString> so if I pass that into HardCodedPepperProvider it should just return whatever pepper and cryptokey the SerializableFunction<Void,ByteString> returns
</blockquote></details>

Try renaming one of the functions and I think it'll become clear why it's infinite recursion.

What I was suggesting is that the one that takes in the ByteStrings (not the SerializableFunctions) can be implemented as:

```
  return preprocessEventsInPipeline(events, maxByteSize, HardCodedPepperProvider(pepper), HardCodedCryptoKeyProvider(cryptoKey))
```


<!-- Sent from Reviewable.io -->

2021-07-28 00:35 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt, line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfeNcuQAKZ_1s3ETb7C:-MfeXQ5iCsTcr1p7aOCj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4eed8ee6f090b1cf826269735e20b1cdbff2c5d0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt#L49)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Try renaming one of the functions and I think it'll become clear why it's infinite recursion.

What I was suggesting is that the one that takes in the ByteStrings (not the SerializableFunctions) can be implemented as:

```
  return preprocessEventsInPipeline(events, maxByteSize, HardCodedPepperProvider(pepper), HardCodedCryptoKeyProvider(cryptoKey))
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-28 00:39 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck and @matthewclegg)



<!-- Sent from Reviewable.io -->

2021-07-28 00:41 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 2 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt, line 38 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfeYN1k-5kZWsVFj6AG:-MfeYN1l5nvgntMab6vp:b-82mlaj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a15ae22e90ac9707316253e37c746fb141a4dea7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt#L38)):*
> ```Kotlin
> }
> 
> fun preprocessEventsInPipeline(
> ```

Documentation please
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfeYf2a4vnC84bSuk7X:-MfeYf2e7Zq5Krpz9mvD:bnlhkti) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a15ae22e90ac9707316253e37c746fb141a4dea7/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L39)):*
> ```Kotlin
>     val events = eventsOf("A" to "B", "C" to "D")
>     val encrypted =
>       preprocessEventsInPipeline(events, 8, "pepper".toByteString(), "cryptokey".toByteString())
> ```

Test the other version too please


<!-- Sent from Reviewable.io -->

2021-07-28 00:47 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt, line 38 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfeYN1k-5kZWsVFj6AG:-Mfe_30-244TF5s5JO81:b-pxp8uj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a15ae22e90ac9707316253e37c746fb141a4dea7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Documentation please
</blockquote></details>

Done.git 
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfeYf2a4vnC84bSuk7X:-Mfe_1xj1zfaLlAXncUa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a15ae22e90ac9707316253e37c746fb141a4dea7/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Test the other version too please
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-28 13:45 UTC, efoxepstein requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 54 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfhLvOC88w27RpDk-AP:-MfhLvOC88w27RpDk-AQ:b-ueen9y) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3e1ffddec4121dd5df4ef8efd41bbc1a2424647b/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L54)):*
> ```Kotlin
>         HardCodedPepperProvider("cryptokey".toByteString())
>       )
>     assertNotNull(encrypted)
> ```

Assertions on PCollections need to use the special assertThat helper -- otherwise they won't work. See BeamTest.kt for example usage.


<!-- Sent from Reviewable.io -->

2021-07-28 14:23 UTC, jmorrrr commented
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 54 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfhLvOC88w27RpDk-AP:-MfhTefYAf1Y0IWQt1ZM:b-uyvo35) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3e1ffddec4121dd5df4ef8efd41bbc1a2424647b/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Assertions on PCollections need to use the special assertThat helper -- otherwise they won't work. See BeamTest.kt for example usage.
</blockquote></details>

Should I just do .toString() and then still AssertNotNull and AssertNotEquals? Because I cannot use containsInAnyOrder or equals because I do not know what the contents of the encrypted data are


<!-- Sent from Reviewable.io -->

2021-07-28 14:48 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 54 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfhLvOC88w27RpDk-AP:-Mfh_Qd_2VVYqaEqdA-_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3e1ffddec4121dd5df4ef8efd41bbc1a2424647b/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L54)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Should I just do .toString() and then still AssertNotNull and AssertNotEquals? Because I cannot use containsInAnyOrder or equals because I do not know what the contents of the encrypted data are
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-28 14:59 UTC, stevenwarejones requested changes
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 51 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfhbZ631QlzSnBFxTco:-MfhbZ631QlzSnBFxTcp:b-bs35g2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4b3338e30d9f9b66631a26b7acc6278658110a7d/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L51)):*
> ```Starlark
> 
> kt_jvm_library(
>     name = "eventpreprocessor",
> ```

@efoxepstein - whats the convention we're using on lib names?


<!-- Sent from Reviewable.io -->

2021-07-28 16:37 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 54 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfhLvOC88w27RpDk-AP:-MfhxF8p-GoJmK2pMEQR:b82jx69) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3e1ffddec4121dd5df4ef8efd41bbc1a2424647b/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L54)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This also won't work. Remember that at this point the pipeline has not been executed so you're making assertions on unresolved PCollections. The test as you have it will always pass.

You can use `.satisfies` and then do arbitrary assertions on the contents:

```
assertThat(somePCollection).satisfies {
  val results: List<KV<Long, ByteString>> = it.toList()  // `it` is an Iterable<KV<...>>
  assertThat(it).hasSize(2)
  assertThat(results.map { it.value }).containsNoneOf("B".toByteString(), "D".toByteString())
}
```


<!-- Sent from Reviewable.io -->

2021-07-28 16:50 UTC, efoxepstein reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 2 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 51 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfhbZ631QlzSnBFxTco:-Mfi08Fb3L8wA72rEVWl:bfu8sel) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4b3338e30d9f9b66631a26b7acc6278658110a7d/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L51)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@efoxepstein - whats the convention we're using on lib names?
</blockquote></details>

In general we use lowercase for everything except tests (and maybe binaries?)

However, in this case I don't think we need separate libraries. @jmorrrr can you just combine all the kt_jvm_libraries into a single one called `eventpreprocessing`? (And just use `srcs = glob(["*.kt"])` in it)


<!-- Sent from Reviewable.io -->

2021-07-28 17:45 UTC, matthewclegg approved these changes

2021-07-28 18:45 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @enfreck, @matthewclegg, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 51 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfhbZ631QlzSnBFxTco:-Mfi5y8U53xxa1jE0oxD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4b3338e30d9f9b66631a26b7acc6278658110a7d/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L51)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

In general we use lowercase for everything except tests (and maybe binaries?)

However, in this case I don't think we need separate libraries. @jmorrrr can you just combine all the kt_jvm_libraries into a single one called `eventpreprocessing`? (And just use `srcs = glob(["*.kt"])` in it)
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 54 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfhLvOC88w27RpDk-AP:-MfiQBxE6G-OjHVnEKSD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3e1ffddec4121dd5df4ef8efd41bbc1a2424647b/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This also won't work. Remember that at this point the pipeline has not been executed so you're making assertions on unresolved PCollections. The test as you have it will always pass.

You can use `.satisfies` and then do arbitrary assertions on the contents:

```
assertThat(somePCollection).satisfies {
  val results: List<KV<Long, ByteString>> = it.toList()  // `it` is an Iterable<KV<...>>
  assertThat(it).hasSize(2)
  assertThat(results.map { it.value }).containsNoneOf("B".toByteString(), "D".toByteString())
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-28 18:51 UTC, enfreck approved these changes
> Reviewed 1 of 5 files at r2, 1 of 2 files at r4, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-28 18:53 UTC, efoxepstein requested changes
> Reviewed 2 of 3 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 5 unresolved discussions (waiting on @jmorrrr and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 19 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiS0aGAgTdTwUGtZA2:-MfiS0aGAgTdTwUGtZA3:b-gsq7s4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/53173667f89e3bb67c0cdedbc34020193fc13037/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L19)):*
> ```Kotlin
> import com.google.protobuf.ByteString
> import kotlin.assert
> import kotlin.test.*
> ```

Please don't do wildcard imports
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 54 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiS3gK03uEOwcPZX3P:-MfiS3gK03uEOwcPZX3Q:b-px66h4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/53173667f89e3bb67c0cdedbc34020193fc13037/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L54)):*
> ```Kotlin
>     assertions(encrypted)
>   }
>   fun assertions(encrypted: PCollection<KV<Long, ByteString>>) {
> ```

Can you rename this something more specific like `assertResultValuesChanged`?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 57 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiSEXEBI5kf_WtuUm2:-MfiSEXEBI5kf_WtuUm3:b-fk5g5u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/53173667f89e3bb67c0cdedbc34020193fc13037/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L57)):*
> ```Kotlin
>     assertThat(encrypted).satisfies {
>       val results: List<KV<Long, ByteString>> = it.toList() // `it` is an Iterable<KV<...>>
>       assertFalse(results.get(0).value.equals("C"))
> ```

This won't work as Beam makes no guarantees on the order of PCollections. Please use the suggestion I provided before.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 59 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiS9He17ne7y_n9gAs:-MfiS9He17ne7y_n9gAt:b-9kkcs8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/53173667f89e3bb67c0cdedbc34020193fc13037/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L59)):*
> ```Kotlin
>       assertFalse(results.get(0).value.equals("C"))
>       assertFalse(results.get(1).value.equals("D"))
>       assert(results.size == (2))
> ```

Please use `assertThat(results).hasSize(2)` instead


<!-- Sent from Reviewable.io -->

2021-07-28 18:54 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @jmorrrr, and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 19 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiS0aGAgTdTwUGtZA2:-MfiSr0X3VeECdGXUB0H:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/53173667f89e3bb67c0cdedbc34020193fc13037/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L19)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please don't do wildcard imports
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-28 18:54 UTC, jmorrrr commented
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 57 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiSEXEBI5kf_WtuUm2:-MfiSvp_-KQ3kjnwLDja:bg9nu5x) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/53173667f89e3bb67c0cdedbc34020193fc13037/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This won't work as Beam makes no guarantees on the order of PCollections. Please use the suggestion I provided before.
</blockquote></details>

When I try to do that the tests always fail because it  says it is not serializable


<!-- Sent from Reviewable.io -->

2021-07-28 18:56 UTC, jmorrrr commented
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 59 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiS9He17ne7y_n9gAs:-MfiTIEz2dvvASA1cbJ6:b-62lyk9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/53173667f89e3bb67c0cdedbc34020193fc13037/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L59)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use `assertThat(results).hasSize(2)` instead
</blockquote></details>

This doesn't work because assertThat needs a PCollection


<!-- Sent from Reviewable.io -->

2021-07-28 18:57 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 4 unresolved discussions (waiting on @jmorrrr and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 57 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiSEXEBI5kf_WtuUm2:-MfiT7ul1LATQgbYyy6m:bn1upqo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/53173667f89e3bb67c0cdedbc34020193fc13037/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L57)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

When I try to do that the tests always fail because it  says it is not serializable
</blockquote></details>

What is it saying is not serializable?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 59 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiS9He17ne7y_n9gAs:-MfiTSppBhTd8ml8OUKp:b-zlum1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/53173667f89e3bb67c0cdedbc34020193fc13037/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L59)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

This doesn't work because assertThat needs a PCollection
</blockquote></details>

Wrong assertThat. Use `import com.google.common.truth.Truth.assertThat`.


<!-- Sent from Reviewable.io -->

2021-07-28 18:58 UTC, jmorrrr commented
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 57 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiSEXEBI5kf_WtuUm2:-MfiTkbm6ld_xYBV0VXp:bonnn7p) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/53173667f89e3bb67c0cdedbc34020193fc13037/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What is it saying is not serializable?
</blockquote></details>

 testEncryptByteStrings(org.wfanet.panelmatch.client.eventpreprocessing.PreprocessEventsInPipelineTest)
java.lang.IllegalArgumentException: unable to serialize DoFnWithExecutionInformation{doFn=org.apache.beam.sdk.testing.PAssert$GroupedValuesCheckerDoFn@4d266391, mainOutputTag=Tag<output>, sideInputMapping={}, schemaInformation=DoFnSchemaInformation{elementConverters=[]}}


<!-- Sent from Reviewable.io -->

2021-07-28 18:58 UTC, jmorrrr commented
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 59 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiS9He17ne7y_n9gAs:-MfiTmzA2rVT__GIVoUo:b-9k1fco) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/53173667f89e3bb67c0cdedbc34020193fc13037/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L59)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Wrong assertThat. Use `import com.google.common.truth.Truth.assertThat`.
</blockquote></details>

Okay thank you


<!-- Sent from Reviewable.io -->

2021-07-28 19:18 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 54 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiS3gK03uEOwcPZX3P:-MfiTCPc6Jx9hLXlwC3S:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/53173667f89e3bb67c0cdedbc34020193fc13037/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you rename this something more specific like `assertResultValuesChanged`?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 57 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiSEXEBI5kf_WtuUm2:-MfiXyX43UOKztAh0JQA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/53173667f89e3bb67c0cdedbc34020193fc13037/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L57)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

 testEncryptByteStrings(org.wfanet.panelmatch.client.eventpreprocessing.PreprocessEventsInPipelineTest)
java.lang.IllegalArgumentException: unable to serialize DoFnWithExecutionInformation{doFn=org.apache.beam.sdk.testing.PAssert$GroupedValuesCheckerDoFn@4d266391, mainOutputTag=Tag<output>, sideInputMapping={}, schemaInformation=DoFnSchemaInformation{elementConverters=[]}}
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 59 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiS9He17ne7y_n9gAs:-MfiTxRECcJGgEvgCJmM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/53173667f89e3bb67c0cdedbc34020193fc13037/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L59)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Okay thank you
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-28 19:23 UTC, efoxepstein requested changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 4 unresolved discussions (waiting on @jmorrrr and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt, line 52 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiYu-G8vpDT98xbPS2:-MfiYu-G8vpDT98xbPS3:b7fqyxd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44c681ab4b0c5dfc8c5d31249b328d8c390b4cc0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt#L52)):*
> ```Kotlin
> ): PCollection<KV<Long, ByteString>> {
>   return events
>     .apply(ParDo.of(BatchingDoFn(maxByteSize, EventSize)))
> ```

Simplification: replace `.apply(ParDo.of(something))` with `.parDo(something)` (import from here: https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt#L54)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt, line 53 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiZF5643V4n2i3wdvl:-MfiZF5643V4n2i3wdvm:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44c681ab4b0c5dfc8c5d31249b328d8c390b4cc0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt#L53)):*
> ```Kotlin
>   return events
>     .apply(ParDo.of(BatchingDoFn(maxByteSize, EventSize)))
>     .apply(ParDo.of(EncryptionEventsDoFn(EncryptEvents(), pepperProvider, cryptoKeyProvider)))
> ```

Ditto
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 57 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiZNlZ8qTSvrRrJpQH:-MfiZNlZ8qTSvrRrJpQI:b-jrd5sp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44c681ab4b0c5dfc8c5d31249b328d8c390b4cc0/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L57)):*
> ```Kotlin
>     assertThat(encrypted).satisfies {
>       val results: List<KV<Long, ByteString>> = it.toList() // `it` is an Iterable<KV<...>>
>       assertFalse(results.get(0).value.equals("C"))
> ```

Delete the `assertFalse` lines please


<!-- Sent from Reviewable.io -->

2021-07-28 19:34 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt, line 52 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiYu-G8vpDT98xbPS2:-MfiaVJ00ZD5cxWEBJ8C:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44c681ab4b0c5dfc8c5d31249b328d8c390b4cc0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt#L52)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Simplification: replace `.apply(ParDo.of(something))` with `.parDo(something)` (import from here: https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt#L54)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt, line 53 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiZF5643V4n2i3wdvl:-MfiaVZ2EY2bNo7Vhemk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44c681ab4b0c5dfc8c5d31249b328d8c390b4cc0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt#L53)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 57 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfiZNlZ8qTSvrRrJpQH:-MfiZmam-cVI_OiNy0ll:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/44c681ab4b0c5dfc8c5d31249b328d8c390b4cc0/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Delete the `assertFalse` lines please
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-28 19:35 UTC, efoxepstein approved these changes
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-28 20:51 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 1 unresolved discussion (waiting on @jmorrrr)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 56 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfisebYELX5K5zxoG1C:-MfisebZ2rOqmWjrlXsM:b-v4hcu1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/15c55876a9481b57537020cdd42e75a56c280a68/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L56)):*
> ```Kotlin
>     assertThat(encrypted).satisfies {
>       val results: List<KV<Long, ByteString>> = it.toList() // `it` is an Iterable<KV<...>>
>       assertThat(results).hasSize(2)
> ```

can you refactor this to have the asserts inside each test function directly? Makes debugging easier.


<!-- Sent from Reviewable.io -->

2021-07-28 21:34 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 2 unresolved discussions (waiting on @jmorrrr)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt, line 21 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfimPLq9-QXAzd0xXj-:-MfimPLq9-QXAzd0xXj0:bgqprzq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/15c55876a9481b57537020cdd42e75a56c280a68/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt#L21)):*
> ```
>     .parDo(BatchingDoFn(maxByteSize, EventSize))
>     .parDo(EncryptionEventsDoFn(EncryptEvents(), pepperProvider, cryptoKeyProvider))
> ```


<!-- Sent from Reviewable.io -->

2021-07-28 21:34 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt, line 56 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64#-MfisebYELX5K5zxoG1C:-Mfj1d5H8oGjTwFCEkDP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/15c55876a9481b57537020cdd42e75a56c280a68/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipelineTest.kt#L56)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you refactor this to have the asserts inside each test function directly? Makes debugging easier.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-28 21:38 UTC, stevenwarejones approved these changes
> Reviewed 2 of 3 files at r6, 1 of 2 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/64)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-28 21:44 UTC, merged