Implement ExchangeStepLauncher class
world-federation-of-advertisers/panel-exchange-client pull request #7
Opened 2021-05-04 00:17 UTC by yunyeng

2021-05-04 01:20 UTC, efoxepstein requested changes
> Reviewed 10 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: 10 of 11 files reviewed, 4 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZowxHi0-iWnO7cpD0c:-MZowxHjEALWQvlp-vJg:b-ds5898) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/71680dd0c105f36b047f14301e2e86b634f38878/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L23)):*
> ```Kotlin
> import org.wfanet.measurement.api.v2alpha.FindReadyExchangeStepResponse
> 
> class ExchangeStepLauncher(private val exchangeStepsClient: ExchangeStepsCoroutineStub) {
> ```

Document this class please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZoxDu84-GMRr-UEhOe:-MZoxDu84-GMRr-UEhOf:b-m1h3j1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/71680dd0c105f36b047f14301e2e86b634f38878/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L32)):*
> ```Kotlin
>    * @throws IllegalArgumentException if ExchangeTask is not valid.
>    */
>   suspend fun findAndRunExchangeTask(dataProviderId: String) {
> ```

This won't change ever per instantiation of ExchangeStepLauncher so maybe move it into the constructor
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZox1xMBEzbcKIwV0dl:-MZox1xMBEzbcKIwV0dm:bghmxdh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/71680dd0c105f36b047f14301e2e86b634f38878/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L33)):*
> ```Kotlin
>    */
>   suspend fun findAndRunExchangeTask(dataProviderId: String) {
>     val exchangeStep = validateExchangeTask(findExchangeTask(dataProviderId))
> ```

It feels a little weird for validateExchangeTask to return something. Maybe just:

```
val exchangeStep = findExchangeStep() ?: return
validateExchangeStep(exchangeStep)
runExchangeStep(exchangeStep)
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZoxSSi1KKkoKfLLwgH:-MZoxSSi1KKkoKfLLwgI:b-arvyxl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/71680dd0c105f36b047f14301e2e86b634f38878/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L55)):*
> ```Kotlin
>       return response.exchangeStep
>     }
>     throw NoSuchElementException("There is not any Exchange Step in Ready state.")
> ```

This can just return null, right?


<!-- Sent from Reviewable.io -->

2021-05-04 03:29 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: 10 of 11 files reviewed, 7 unresolved discussions (waiting on @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZpPQed7si72_O5aeR7:-MZpPQed7si72_O5aeR8:blx9dci) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/71680dd0c105f36b047f14301e2e86b634f38878/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt#L37)):*
> ```Kotlin
> private const val EXCHANGE_ID = "1"
> 
> val EXCHANGE_STEP =
> ```

`private` please
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt, line 63 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZpQ0UI5RwX9NqQ4d1K:-MZpQ0UI5RwX9NqQ4d1L:bkc7hif) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/71680dd0c105f36b047f14301e2e86b634f38878/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt#L63)):*
> ```Kotlin
>     val task = launcher.findExchangeTask(DATA_PROVIDER_ID)
>     assertThat(task).isEqualTo(EXCHANGE_STEP)
>   }
> ```

Can you add a verification that it passes the expected request to `findReadyExchangeStep`?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZpPbcXDfs5ncalpLsx:-MZpPbcXDfs5ncalpLsy:b-mhhs5d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/71680dd0c105f36b047f14301e2e86b634f38878/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt#L68)):*
> ```Kotlin
>   fun `findExchangeTask without exchangeStep`() {
>     val launcher = ExchangeStepLauncher(exchangeStepsStub)
>     Assert.assertThrows(NoSuchElementException::class.java) {
> ```

Please import `assertThrows` directly


<!-- Sent from Reviewable.io -->

2021-05-04 05:47 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: 9 of 11 files reviewed, 7 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZowxHi0-iWnO7cpD0c:-MZpu_j9AbDlGMrznbiO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/71680dd0c105f36b047f14301e2e86b634f38878/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Document this class please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZoxDu84-GMRr-UEhOe:-MZpuZnMAHyySDDZQQNK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/71680dd0c105f36b047f14301e2e86b634f38878/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This won't change ever per instantiation of ExchangeStepLauncher so maybe move it into the constructor
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZox1xMBEzbcKIwV0dl:-MZpu_Ch8Ao4za8WwCnC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/71680dd0c105f36b047f14301e2e86b634f38878/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It feels a little weird for validateExchangeTask to return something. Maybe just:

```
val exchangeStep = findExchangeStep() ?: return
validateExchangeStep(exchangeStep)
runExchangeStep(exchangeStep)
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZoxSSi1KKkoKfLLwgH:-MZpuZFN3WvabObb2UG-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/71680dd0c105f36b047f14301e2e86b634f38878/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This can just return null, right?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZpPQed7si72_O5aeR7:-MZpuYLC9li84Z3oLO4l:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/71680dd0c105f36b047f14301e2e86b634f38878/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`private` please
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt, line 63 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZpQ0UI5RwX9NqQ4d1K:-MZpuXS7-WJM1Q1ylOZT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/71680dd0c105f36b047f14301e2e86b634f38878/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt#L63)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you add a verification that it passes the expected request to `findReadyExchangeStep`?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZpPbcXDfs5ncalpLsx:-MZpuVkBBKmFxBN99ZbT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/71680dd0c105f36b047f14301e2e86b634f38878/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt#L68)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please import `assertThrows` directly
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-04 16:29 UTC, efoxepstein requested changes
> Reviewed 1 of 11 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: all files reviewed, 5 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsALAV4RTRJHV3P8lD:-MZsALAV4RTRJHV3P8lE:b-3gpn23) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L26)):*
> ```Kotlin
> class ExchangeStepLauncher(
>   private val exchangeStepsClient: ExchangeStepsCoroutineStub,
>   private val dataProviderId: String
> ```

This code will be run by both data providers and model providers. Maybe pass an `id` and an enum indicating the party type.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 30 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsAGQqB6z4aJT_RPFG:-MZsAGQqB6z4aJT_RPFH:b-nuwmw4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L30)):*
> ```Kotlin
> 
>   /**
>    * Finds a single Exchange Step and starts executing.
> ```

Can you document the behavior if there are no ready ExchangeSteps?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsB4Ey-9J-bDQCvlDy:-MZsB4Ey-9J-bDQCvlDz:b3kr569) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L32)):*
> ```Kotlin
>    * Finds a single Exchange Step and starts executing.
>    *
>    * @throws IllegalArgumentException if Exchange Step is not valid.
> ```

For invalid ExchangeSteps, we might want to call CreateExchangeStepAttempt followed by an immediate FinishExchangeStepAttempt that permanently fails the step? I'm not sure that throwing an exception here is helpful because next time this runs, it will grab the same ExchangeStep.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 62 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsC2bFAdl0YmYPMNdJ:-MZsC2bFAdl0YmYPMNdK:b-4exw0k) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L62)):*
> ```Kotlin
>    * @param exchangeStep [ExchangeStep].
>    */
>   fun runExchangeStep(exchangeStep: ExchangeStep) {
> ```

Can all methods besides findAndRunExchangeStep be marked `internal` so that they're testable but not used outside the package? 
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt, line 46 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsBao9-ar052iBjBWX:-MZsBao9-ar052iBjBWY:b-twkxpv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt#L46)):*
> ```Kotlin
>     .build()
> private val REQUEST =
>   FindReadyExchangeStepRequest.newBuilder().setDataProvider(
> ```

Simpler with `apply`:

```
FindReadyExchangeStepRequest.newBuilder()
  .apply {
    dataProviderBuilder.dataProviderId = DATA_PROVIDER_ID
  }
  .build()
```


<!-- Sent from Reviewable.io -->

2021-05-04 16:37 UTC, stevenwarejones requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: all files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[WORKSPACE, line 159 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsCJYr1d_wnL1QqfLI:-MZsCJYr1d_wnL1QqfLJ:bwsazyp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/WORKSPACE#L159)):*
> ```Starlark
>     "com.google.code.gson:gson": "2.8.6",
>     "com.google.guava:guava": "30.0-jre",
>     "com.nhaarman.mockitokotlin2:mockito-kotlin": "2.2.0",
> ```

org.mockito.kotlin:mockito-kotlin seems a little more trustworthy potentially
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsB4Ey-9J-bDQCvlDy:-MZsD_Tn-ktiWJL7hVwm:b-j6dlsv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

For invalid ExchangeSteps, we might want to call CreateExchangeStepAttempt followed by an immediate FinishExchangeStepAttempt that permanently fails the step? I'm not sure that throwing an exception here is helpful because next time this runs, it will grab the same ExchangeStep.
</blockquote></details>

@efoxepstein - I thought that was okay? It would run a predetermined number of retries... then fail out completely and findExchangeSteps won't return it that point.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsAliu2rJmubpH4TvL:-MZsAliu2rJmubpH4TvM:b-62hu27) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L34)):*
> ```Kotlin
>    * @throws IllegalArgumentException if Exchange Step is not valid.
>    */
>   suspend fun findAndRunExchangeStep() {
> ```

I think we talked about this elsewhere... but is there a case where we might want to run a specific blocking task? Seems like a good use case for previously failed tasks that are blocking other things. This can be a later release too.


<!-- Sent from Reviewable.io -->

2021-05-04 16:46 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: all files reviewed, 7 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[WORKSPACE, line 159 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsCJYr1d_wnL1QqfLI:-MZsEkOP6H94B9Y6gSfk:b-pll71k) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/WORKSPACE#L159)):*
> org.mockito.kotlin:mockito-kotlin

Agreed -- we should do this change here and propagate it back into all the other repositories too. When we started coding, it was still a separate project.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsB4Ey-9J-bDQCvlDy:-MZsEy05-mCDynqJOEWI:bpdwrya) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L32)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@efoxepstein - I thought that was okay? It would run a predetermined number of retries... then fail out completely and findExchangeSteps won't return it that point.
</blockquote></details>

If it's never "started" with CreateESA, it'll never be counted as a retry.

If we want FindReadyExchangeStep to call CreateESA under the hood, that's a possibility but it would require some larger changes. For now, I feel like the logic can be something like:

```
try {
  validateExchangeStep(exchangeStep)
} catch (e: InvalidExchangeStepException) {
  val attempt = createExchangeStepAttempt(exchangeStep)
  finishExchangeStepAttempt(
      FinishExchangeStepAttemptRequest.newBuilder()
        .apply {
          key = attempt.key
          finalState = ExchangeStepAttempt.State.FAILED_STEP
          addLogEntriesBuilder.apply {
            time = clock.instant().toProto()
            message = e.message
          }
        }
        .build()
  )
}
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsAliu2rJmubpH4TvL:-MZsFDvo9M8Sx1agvaEc:b-heass) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L34)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I think we talked about this elsewhere... but is there a case where we might want to run a specific blocking task? Seems like a good use case for previously failed tasks that are blocking other things. This can be a later release too.
</blockquote></details>

Yeah, in the spirit of YAGNI, not sure we need to worry about that case yet.


<!-- Sent from Reviewable.io -->

2021-05-04 23:09 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: 7 of 12 files reviewed, 7 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[WORKSPACE, line 159 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsCJYr1d_wnL1QqfLI:-MZtd8364joSR-mLCGiT:bu2gh7j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/WORKSPACE#L159)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

> org.mockito.kotlin:mockito-kotlin

Agreed -- we should do this change here and propagate it back into all the other repositories too. When we started coding, it was still a separate project.
</blockquote></details>

Can we address this later once we have the common repo for dependencies?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsALAV4RTRJHV3P8lD:-MZtd6T53gUwFwR1m6Lr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This code will be run by both data providers and model providers. Maybe pass an `id` and an enum indicating the party type.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 30 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsAGQqB6z4aJT_RPFG:-MZtd6m85qeriJiCkau2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L30)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you document the behavior if there are no ready ExchangeSteps?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsB4Ey-9J-bDQCvlDy:-MZtd5gAE3kEMDBdgZo_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

If it's never "started" with CreateESA, it'll never be counted as a retry.

If we want FindReadyExchangeStep to call CreateESA under the hood, that's a possibility but it would require some larger changes. For now, I feel like the logic can be something like:

```
try {
  validateExchangeStep(exchangeStep)
} catch (e: InvalidExchangeStepException) {
  val attempt = createExchangeStepAttempt(exchangeStep)
  finishExchangeStepAttempt(
      FinishExchangeStepAttemptRequest.newBuilder()
        .apply {
          key = attempt.key
          finalState = ExchangeStepAttempt.State.FAILED_STEP
          addLogEntriesBuilder.apply {
            time = clock.instant().toProto()
            message = e.message
          }
        }
        .build()
  )
}
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 62 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsC2bFAdl0YmYPMNdJ:-MZtd-B7ANapq0ZQDosX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can all methods besides findAndRunExchangeStep be marked `internal` so that they're testable but not used outside the package? 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-04 23:10 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: 7 of 12 files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt, line 46 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsBao9-ar052iBjBWX:-MZtdHKi2Kp8T5B12jCN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Simpler with `apply`:

```
FindReadyExchangeStepRequest.newBuilder()
  .apply {
    dataProviderBuilder.dataProviderId = DATA_PROVIDER_ID
  }
  .build()
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-04 23:49 UTC, efoxepstein approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 5 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-:-MZtmHcx7yc_d8lB9eJ9:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[WORKSPACE, line 159 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsCJYr1d_wnL1QqfLI:-MZtilTN4cOC9HqkPrLu:b-ram0hl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/WORKSPACE#L159)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Can we address this later once we have the common repo for dependencies?
</blockquote></details>

Please file a bug on GitHub to update all the repos.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/BUILD.bazel, line 10 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZthdB7DuQVpKHVpJpp:-MZthdB7DuQVpKHVpJpq:b-6o28o1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6cdb7a65502e287d2f71c0798004473d8908b1ce/src/main/kotlin/org/wfanet/panelmatch/client/launcher/BUILD.bazel#L10)):*
> ```Starlark
> ])
> 
> java_proto_library(
> ```

Can you move these `java_proto_library` rules to `//src/main/proto/wfa/measurement/api/v2alpha`?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/BUILD.bazel, line 19 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZtm1IWDMw4O-cjkDM7:-MZtm1IWDMw4O-cjkDM8:bb3oymt) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41a710a0456ffc7b6075c949298cfce4bc18f533/src/test/kotlin/org/wfanet/panelmatch/client/launcher/BUILD.bazel#L19)):*
> ```Starlark
>     name = "ExchangeStepLauncherTest",
>     srcs = ["ExchangeStepLauncherTest.kt"],
>     friends = ["//src/main/kotlin/org/wfanet/panelmatch/client/launcher"],
> ```

Out of curiosity why is this needed?


<!-- Sent from Reviewable.io -->

2021-05-05 00:43 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[WORKSPACE, line 159 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsCJYr1d_wnL1QqfLI:-MZtxFTnDHa9E4I4dFkw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/WORKSPACE#L159)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please file a bug on GitHub to update all the repos.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/BUILD.bazel, line 10 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZthdB7DuQVpKHVpJpp:-MZtyelUBG1hVMcpemF9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6cdb7a65502e287d2f71c0798004473d8908b1ce/src/main/kotlin/org/wfanet/panelmatch/client/launcher/BUILD.bazel#L10)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you move these `java_proto_library` rules to `//src/main/proto/wfa/measurement/api/v2alpha`?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/BUILD.bazel, line 19 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZtm1IWDMw4O-cjkDM7:-MZtsO1T-VWTF98geL1s:b-hqytim) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41a710a0456ffc7b6075c949298cfce4bc18f533/src/test/kotlin/org/wfanet/panelmatch/client/launcher/BUILD.bazel#L19)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Out of curiosity why is this needed?
</blockquote></details>

Advised @sanjayvas on this. It is needed to be able to test internal methods.


<!-- Sent from Reviewable.io -->

2021-05-05 01:26 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: 10 of 13 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsB4Ey-9J-bDQCvlDy:-MZu6VjC5knArvuF_pjW:b-5sv7fj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L32)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm not seeing the change @efoxepstein suggested - am I missing something?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 36 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZu7M2sAa0oMiertVdu:-MZu7M2sAa0oMiertVdv:bq31ylu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41a710a0456ffc7b6075c949298cfce4bc18f533/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L36)):*
> ```Kotlin
>    */
>   suspend fun findAndRunExchangeStep() {
>     val exchangeStep = findExchangeStep() ?: return
> ```

Is this more`FindAndClaimExchangeStepRequest`? We dont want other clients in the meantime trying to validate this same step.


<!-- Sent from Reviewable.io -->

2021-05-05 02:11 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: 10 of 13 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @SanjayVas, @stevenwarejones, and @yunyeng)



<!-- Sent from Reviewable.io -->

2021-05-05 16:56 UTC, efoxepstein approved these changes
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 36 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZu7M2sAa0oMiertVdu:-MZxSBbvDJrvCDUpLVVf:b-fjm03f) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41a710a0456ffc7b6075c949298cfce4bc18f533/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L36)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Is this more`FindAndClaimExchangeStepRequest`? We dont want other clients in the meantime trying to validate this same step.
</blockquote></details>

Yeah, you're probably right that we should update the public API to be `FindAndClaimExchangeStep`. Steven, are you OK with submitting as is for now and then updating after we fix the public API?


<!-- Sent from Reviewable.io -->

2021-05-05 17:36 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: 9 of 13 files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZsB4Ey-9J-bDQCvlDy:-MZxaGH--Qe9ONJlmDlF:b6t7t04) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79f4383b64b0ff2cc8e2522012675fcaed696219/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L32)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm not seeing the change @efoxepstein suggested - am I missing something?
</blockquote></details>

I was thinking of leaving ExchangeStepAttempt actions in the next CL. But updated this method now.


<!-- Sent from Reviewable.io -->

2021-05-05 17:38 UTC, efoxepstein requested changes
> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: all files reviewed, 7 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 32 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZxb0RP9zRo0XCWz41m:-MZxb0RP9zRo0XCWz41n:bo2762a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85a202151cf42b51d5ad78dab6c16639c33ca5f1/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L32)):*
> ```Kotlin
>   private val id: String,
>   private val partyType: PartyType,
>   private val clock: Clock
> ```

Maybe default to Clock.systemUTC()?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 39 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZxaVgQ3xpXWOS4ZlmI:-MZxaVgR62Zogm9lVSS7:b4nixd4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85a202151cf42b51d5ad78dab6c16639c33ca5f1/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L39)):*
> ```Kotlin
>    * validates it, and starts executing. If not found simply returns.
>    *
>    * @throws InvalidExchangeStepException if Exchange Step is not valid.
> ```

Is this still true?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 46 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZxadIbA8_zZTo7gi-X:-MZxadIc22IKPetUdF1S:b-2n55k4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85a202151cf42b51d5ad78dab6c16639c33ca5f1/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L46)):*
> ```Kotlin
>       validateExchangeStep(exchangeStep)
>     } catch (e: InvalidExchangeStepException) {
>       val attempt = createExchangeStepAttempt(exchangeStep)
> ```

This gets tricky -- what if this fails? Or the finishExchangeStepAttempt call fails?

For now can you just put a TODO around here to think through failure modes?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 141 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZxatBO1iwDPVK6dQIB:-MZxatBO1iwDPVK6dQIC:b-7gtbcq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85a202151cf42b51d5ad78dab6c16639c33ca5f1/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L141)):*
> ```Kotlin
> // TODO(@yunyeng): Move to Utils.
> /** Converts Instant to Timestamp. */
> fun Instant.toProtoTime(): Timestamp =
> ```

I think we already have this somewhere in `cross-media-measurement`


<!-- Sent from Reviewable.io -->

2021-05-05 17:58 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: 11 of 13 files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 32 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZxb0RP9zRo0XCWz41m:-MZxfGTnCqQIvoeePFVQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85a202151cf42b51d5ad78dab6c16639c33ca5f1/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe default to Clock.systemUTC()?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 39 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZxaVgQ3xpXWOS4ZlmI:-MZxeYs5Af16-luR-JIx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85a202151cf42b51d5ad78dab6c16639c33ca5f1/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is this still true?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 46 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZxadIbA8_zZTo7gi-X:-MZxeXKtA3WAjyiAPWQL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85a202151cf42b51d5ad78dab6c16639c33ca5f1/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This gets tricky -- what if this fails? Or the finishExchangeStepAttempt call fails?

For now can you just put a TODO around here to think through failure modes?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 141 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZxatBO1iwDPVK6dQIB:-MZxeOcw6Ye1-BYtfh1P:bomddha) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85a202151cf42b51d5ad78dab6c16639c33ca5f1/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L141)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think we already have this somewhere in `cross-media-measurement`
</blockquote></details>

Added todo to import from cross-media-measurement once I changed the visibility of ProtoUtils.


<!-- Sent from Reviewable.io -->

2021-05-05 18:05 UTC, efoxepstein approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-:-MZxhAWx8uUQlaTjivE-:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-05-05 18:18 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 36 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZu7M2sAa0oMiertVdu:-MZxjidNCQJDiVlMgwI1:bf1la2q) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41a710a0456ffc7b6075c949298cfce4bc18f533/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L36)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Yeah, you're probably right that we should update the public API to be `FindAndClaimExchangeStep`. Steven, are you OK with submitting as is for now and then updating after we fix the public API?
</blockquote></details>

Sure - lets put it in the next batch


<!-- Sent from Reviewable.io -->

2021-05-05 18:18 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZxkALDDIowdqvLfyQC:-MZxkALDDIowdqvLfyQD:b-ugd70j) (no related file):*
Needs a rebase... other than that lgrm

---


<!-- Sent from Reviewable.io -->

2021-05-05 19:20 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7)* status: 10 of 28 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZxkALDDIowdqvLfyQC:-MZxyBoe07Xbw_rfeK2i:b-896fix) (no related file):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Needs a rebase... other than that lgrm
</blockquote></details>

Done.

---
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 36 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/7#-MZu7M2sAa0oMiertVdu:-MZxyEOjDcvsubKf8HHc:b-eapff3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/41a710a0456ffc7b6075c949298cfce4bc18f533/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L36)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Sure - lets put it in the next batch
</blockquote></details>

Resolved.


<!-- Sent from Reviewable.io -->

2021-05-05 19:21 UTC, merged