Add PreprocessEventsMain Function
world-federation-of-advertisers/panel-exchange-client pull request #70
Opened 2021-08-02 18:25 UTC by jmorrrr

Adds main function that takes in preprocessed event ids and data using
BigQuery, runs PreprocessEventsInPipeline on them, and writes them to a
specified BigQuery File

2021-08-02 18:43 UTC, efoxepstein requested changes
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 17 unresolved discussions (waiting on @enfreck and @jmorrrr)

___
*[WORKSPACE, line 164 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg77wn43RgFC-rZc1Df:-Mg77wn5DXFCt07mBTgA:b-fer4fv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/WORKSPACE#L164)):*
> ```Starlark
>     "org.apache.beam:beam-runners-google-cloud-dataflow-java": "2.31.0",
>     "org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core": "2.31.0",
>     "org.apache.beam:beam-sdks-java-core": "2.29.0",
> ```

Can you use 2.31.0 for all of them?
___
*[imports/java/com/google/common/BUILD.bazel, line 8 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78DjgCcfUyaEloXon:-Mg78DjgCcfUyaEloXoo:bemhpr8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/com/google/common/BUILD.bazel#L8)):*
> ```Starlark
> )
> 
> alias(
> ```

This `alias` should be in `//imports/java/com/google/api/services/BUILD.bazel
___
*[imports/java/com/google/common/BUILD.bazel, line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78MfaEdjdj1Iqv2Jr:-Mg78MfaEdjdj1Iqv2Js:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/com/google/common/BUILD.bazel#L13)):*
> ```Starlark
> )
> 
> alias(
> ```

Ditto
___
*[imports/java/com/google/common/BUILD.bazel, line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78NIM71_C9gCGt2pk:-Mg78NIM71_C9gCGt2pl:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/com/google/common/BUILD.bazel#L18)):*
> ```Starlark
> )
> 
> alias(
> ```

Ditto
___
*[imports/java/com/google/common/BUILD.bazel, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78O_30JeBZJrgTlAU:-Mg78O_49rmU5W5i_UDw:b-dyaomn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/com/google/common/BUILD.bazel#L23)):*
> ```Starlark
> )
> 
> alias(
> ```

This should probably be in `//imports/java/com/google/api/client`? Basically, just the `import` path
___
*[imports/java/com/google/common/BUILD.bazel, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78WbIDZJS--RiKNBM:-Mg78WbIDZJS--RiKNBN:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/com/google/common/BUILD.bazel#L28)):*
> ```Starlark
> )
> 
> alias(
> ```

Ditto
___
*[imports/java/org/apache/beam/BUILD.bazel, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78l3V3mC1VVKyt_my:-Mg78l3V3mC1VVKyt_mz:bc2jkaz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/org/apache/beam/BUILD.bazel#L15)):*
> ```Starlark
> alias(
>     name = "protobuf",
>     actual = "@maven//:org_apache_beam_beam_sdks_java_extensions_protobuf",
> ```

Can you move `protobuf` and `gcpcore` to an `extensions` subfolder please?
___
*[imports/java/org/apache/beam/BUILD.bazel, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78qAY3S2bPYOM5_mj:-Mg78gzO0i9dDvXEKfgW:b2v645r) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/org/apache/beam/BUILD.bazel#L19)):*
> ```Starlark
> 
> alias(
>     name = "gcpcore",
> ```

`gcp_core` please
___
*[imports/java/org/apache/beam/BUILD.bazel, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg792Ou97DXZnKptrYk:-Mg792Ou97DXZnKptrYl:busa0ot) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/org/apache/beam/BUILD.bazel#L24)):*
> ```Starlark
> 
> alias(
>     name = "iogcp",
> ```

Can you please move this `alias` to an `io` subfolder please and then rename this alias `google_cloud_platform`?
___
*[imports/java/org/apache/beam/BUILD.bazel, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78wTl5aGx4JnuYGdZ:-Mg78wTmECQds7a0NInC:bqebbk4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/org/apache/beam/BUILD.bazel#L29)):*
> ```Starlark
> 
> alias(
>     name = "gcd",
> ```

Please rename to `google_cloud_dataflow`
___
*[imports/java/org/apache/beam/BUILD.bazel, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78s7a10xVqXpcEScg:-Mg78s7a10xVqXpcESch:b-710378) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/org/apache/beam/BUILD.bazel#L30)):*
> ```Starlark
> alias(
>     name = "gcd",
>     actual = "@maven//:org_apache_beam_beam_runners_google_cloud_dataflow_java",
> ```

Can you move `gcd` and `direct_runner` to a `runners` subfolder please?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7ACgP65f_nDBNWbhw:-Mg7ACgQ2FoAGGVU4S8y:bg0n9t5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L44)):*
> ```Kotlin
> 
>   @get:Description("Table to read from, specified as <project_id>:<dataset_id>.<table_id>")
>   @get:Default.String(EVENT_TABLE)
> ```

Can you get rid of the default and just make this required?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7A9wTAEKQM9w4Zipm:-Mg7A9wTAEKQM9w4Zipn:brq2ztn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L45)):*
> ```Kotlin
>   @get:Description("Table to read from, specified as <project_id>:<dataset_id>.<table_id>")
>   @get:Default.String(EVENT_TABLE)
>   var input: String
> ```

Rename to `bigQueryInputTable` maybe?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7A6OZ9BdmPn3YpOAl:-Mg7A6OZ9BdmPn3YpOAm:bygufgk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L51)):*
> ```Kotlin
>   )
>   @get:Validation.Required
>   var outputFile: String
> ```

Rename to `bigQueryOutputTable` maybe?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg79Y_jB3nJVZu-mUzW:-Mg79Y [...]

2021-08-02 19:10 UTC, stevenwarejones requested changes
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 18 unresolved discussions (waiting on @efoxepstein, @enfreck, and @jmorrrr)

___
*[WORKSPACE, line 164 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg77wn43RgFC-rZc1Df:-Mg7Dn7ECiDw08oa-rTv:b-bwzlmm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/WORKSPACE#L164)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you use 2.31.0 for all of them?
</blockquote></details>

to enforce this, can we set a constant for these or a helper to download all the apache beam stuff?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7GSZS7qSrs2Fio-fl:-Mg7GSZS7qSrs2Fio-fm:b-l1k4wo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfa2fe96b1b4e40c0450ad0b2242e869d869ae5f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L54)):*
> ```Kotlin
> }
> 
> fun main(args: Array<String>) {
> ```

how were you planning on testing this?


<!-- Sent from Reviewable.io -->

2021-08-02 19:40 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 18 unresolved discussions (waiting on @efoxepstein, @enfreck, and @jmorrrr)

___
*[WORKSPACE, line 164 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg77wn43RgFC-rZc1Df:-Mg7AzXaANaHsZRCNr5O:b-74qd3q) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/WORKSPACE#L164)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

to enforce this, can we set a constant for these or a helper to download all the apache beam stuff?
</blockquote></details>

I changed for all except beam-runners-google-cloud-dataflow-java
___
*[imports/java/com/google/common/BUILD.bazel, line 8 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78DjgCcfUyaEloXon:-Mg7GAtf3FQdntUpEFpT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/com/google/common/BUILD.bazel#L8)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This `alias` should be in `//imports/java/com/google/api/services/BUILD.bazel
</blockquote></details>

Done.
___
*[imports/java/com/google/common/BUILD.bazel, line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78MfaEdjdj1Iqv2Jr:-Mg7GAIWBuKwtajXwNVN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/com/google/common/BUILD.bazel#L13)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[imports/java/com/google/common/BUILD.bazel, line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78NIM71_C9gCGt2pk:-Mg7GA6tE6OcofbKZEOe:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/com/google/common/BUILD.bazel#L18)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[imports/java/com/google/common/BUILD.bazel, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78O_30JeBZJrgTlAU:-Mg7Gv4L3Zygs1GlRrf1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/com/google/common/BUILD.bazel#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This should probably be in `//imports/java/com/google/api/client`? Basically, just the `import` path
</blockquote></details>

Done.
___
*[imports/java/com/google/common/BUILD.bazel, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78WbIDZJS--RiKNBM:-Mg7GvH15TXDNAA_66ph:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/com/google/common/BUILD.bazel#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[imports/java/org/apache/beam/BUILD.bazel, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78l3V3mC1VVKyt_my:-Mg7HIxjE9KDpHMdWapF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/org/apache/beam/BUILD.bazel#L15)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you move `protobuf` and `gcpcore` to an `extensions` subfolder please?
</blockquote></details>

Done.
___
*[imports/java/org/apache/beam/BUILD.bazel, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78qAY3S2bPYOM5_mj:-Mg7HL4t9_v0_75oZUdA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/org/apache/beam/BUILD.bazel#L19)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`gcp_core` please
</blockquote></details>

Done.
___
*[imports/java/org/apache/beam/BUILD.bazel, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg792Ou97DXZnKptrYk:-Mg7JvSIBG3deZhdyVwr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/org/apache/beam/BUILD.bazel#L24)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you please move this `alias` to an `io` subfolder please and then rename this alias `google_cloud_platform`?
</blockquote></details>

Done.
___
*[imports/java/org/apache/beam/BUILD.bazel, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78wTl5aGx4JnuYGdZ:-Mg7KNAv1bPC2A_4Ha_N:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/org/apache/beam/BUILD.bazel#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please rename to `google_cloud_dataflow`
</blockquote></details>

Done.
___
*[imports/java/org/apache/beam/BUILD.bazel, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg78s7a10xVqXpcEScg:-Mg7KNR03_XAjQB8JEYX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/imports/java/org/apache/beam/BUILD.bazel#L30)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you move `gcd` and `direct_runner` to a `runners` subfolder please?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7ACgP65f_nDBNWbhw:-Mg7Ecoq5b8Z3dVvTKqL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L44)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you get rid of the default and just make this required?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7A9wTAEKQM9w4Zipm:-Mg7EOPo9ry72dFeWOYs:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Rename to `bigQueryInputTable` maybe?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7A6OZ9BdmPn3YpOAl:-Mg7EXHgDKLh6nXbs [...]

2021-08-02 19:42 UTC, jmorrrr commented
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7GSZS7qSrs2Fio-fl:-Mg7NtRBBvYIyCVqg0J9:b-115xmf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfa2fe96b1b4e40c0450ad0b2242e869d869ae5f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L54)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

how were you planning on testing this?
</blockquote></details>

On Google Cloud Platform


<!-- Sent from Reviewable.io -->

2021-08-02 20:29 UTC, efoxepstein requested changes
> Reviewed 16 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 9 unresolved discussions (waiting on @enfreck, @jmorrrr, @matthewclegg, and @stevenwarejones)

___
*[WORKSPACE, line 164 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg77wn43RgFC-rZc1Df:-Mg7V4Ax8XI7AxZkZ50y:b-2d4y41) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/WORKSPACE#L164)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

I changed for all except beam-runners-google-cloud-dataflow-java
</blockquote></details>

Can you add a comment saying why that one can't be 2.31.0?

Also, do you mind extracting these to a file `//build/maven/apache_beam.bzl`? The contents of the file can be like:

```
_VERSION = "2.31.0"

apache_beam_artifacts = {
  "org.apache.beam:beam-whatever": _VERSION,
  ...

  # Some comment here about why this is a different version:
  "org.apache.beam:beam-whatever": "some other version"

  # Also include hamcrest and slf4j stuff here too because it's only for beam
}
```

Then here in WORKSPACE:

```
load("//build/maven/apache_beam.bzl", "apache_beam_artifacts")
MAVEN_ARTIFACTS.update(apache_beam_artifacts)
```
___
*[imports/java/org/apache/beam/extensions/BUILD.bazel, line 9 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7WMU_Cm8MR5h-D_gT:-Mg7WMU_Cm8MR5h-D_gU:bdthn4t) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/imports/java/org/apache/beam/extensions/BUILD.bazel#L9)):*
> ```Starlark
> 
> alias(
>     name = "gcp_core",
> ```

Rename to `google_cloud_platform_core` please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 10 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7XT9_9_SXYS8KrP4L:-Mg7XT9_9_SXYS8KrP4M:b-5zd6js) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L10)):*
> ```Starlark
>     deps = [
>         "//imports/java/com/google/api/client:http",
>         "//imports/java/com/google/api/client:json",
> ```

Are all of these deps actually necessary? It's kind of surprising to me
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7A9wTAEKQM9w4Zipm:-Mg7We9l07HLvWx0QHcV:b-5ydjq6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L45)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

For conssitency, can you put the `@get:Validation` after the `@get:Description` please?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7GSZS7qSrs2Fio-fl:-Mg7Wl_V0a_g4cOE6R72:b-xjuhoi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfa2fe96b1b4e40c0450ad0b2242e869d869ae5f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L54)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

On Google Cloud Platform
</blockquote></details>

The actual logic (besides the trivial transforms in this file) are thoroughly unit tested, too
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7XMy36UqTPWQZloMF:-Mg7XMy40wPJFo6F017N:b-54egmn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L31)):*
> ```Kotlin
> import org.wfanet.panelmatch.common.beam.map
> 
> private const val EVENT_TABLE = "INSERT TABLE ADDRESS HERE"
> ```

Delete this?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 60 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7Y7-663hKv0kn8UHL:-Mg7Y7-663hKv0kn8UHM:b-rebdhq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L60)):*
> ```Kotlin
>       TableFieldSchema().setName("encrypted_data").setType("BYTESTRING")
>     )
>   val schema = TableSchema().setFields(fields)
> ```

Since this (and also `fields`) aren't used until the end of the pipeline, can you move them down to right before they're used?

Or better yet, make a function `fun writeToBigQuery(encrypted_events: PCollection<...>, outputTable: String)` that has both the schema and `val tableRows` and the `BigQueryIO.writeTableRows` call
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 70 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7Xn20CryTahtHih10:-Mg7Xn20CryTahtHih11:bs2id3b) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L70)):*
> ```Kotlin
>         .withSelectedFields(mutableListOf("id", "data"))
>     )
>   val pairs =
> ```

"pairs" is a little generic, maybe "unencrypted_events"
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 87 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7X11G3GdzOWsYz7QL:-Mg7X11G3GdzOWsYz7QM:b1iovw0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L87)):*
> ```Kotlin
>   val tableRows =
>     encrypted.map {
>       val tablerow = TableRow().set("encrypted_id", it.key)
> ```

I think you can just write `TableRow().set("encrypted_id", it.key).set("encrypted_data", it.value)` as a one-liner


<!-- Sent from Reviewable.io -->

2021-08-02 20:45 UTC, stevenwarejones requested changes
> Reviewed 10 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 10 unresolved discussions (waiting on @efoxepstein, @enfreck, @jmorrrr, @matthewclegg, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7GSZS7qSrs2Fio-fl:-Mg7bHFb8JksaSGuOwts:bffm8a9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfa2fe96b1b4e40c0450ad0b2242e869d869ae5f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The actual logic (besides the trivial transforms in this file) are thoroughly unit tested, too
</blockquote></details>

If we can't test this file directly can we add instructions for testing?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 77 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7azPEASvbx43f_PUL:-Mg7azPF93Jud5E6kYBZ:b-c2qo02) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L77)):*
> ```Kotlin
>       )
>     }
>   val encrypted =
> ```

`encryptedEvents`


<!-- Sent from Reviewable.io -->

2021-08-03 15:52 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 10 unresolved discussions (waiting on @efoxepstein, @enfreck, @jmorrrr, @matthewclegg, and @stevenwarejones)

___
*[imports/java/org/apache/beam/extensions/BUILD.bazel, line 9 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7WMU_Cm8MR5h-D_gT:-MgBDliK6Do_jNGRDopG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/imports/java/org/apache/beam/extensions/BUILD.bazel#L9)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Rename to `google_cloud_platform_core` please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 10 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7XT9_9_SXYS8KrP4L:-MgBF31-2r2rQBNij7p9:b-hj25lv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L10)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Are all of these deps actually necessary? It's kind of surprising to me
</blockquote></details>

Separated into preprocess_events_main and eventpreprocessing
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7A9wTAEKQM9w4Zipm:-MgBDwm20XiGZ72fYZaN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

For conssitency, can you put the `@get:Validation` after the `@get:Description` please?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7XMy36UqTPWQZloMF:-MgBDs6P8tRHK2OY9va6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Delete this?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 60 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7Y7-663hKv0kn8UHL:-MgBgpLe0630zrTwWvMM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L60)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since this (and also `fields`) aren't used until the end of the pipeline, can you move them down to right before they're used?

Or better yet, make a function `fun writeToBigQuery(encrypted_events: PCollection<...>, outputTable: String)` that has both the schema and `val tableRows` and the `BigQueryIO.writeTableRows` call
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 70 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7Xn20CryTahtHih10:-Mg7Z4-RCWOaxbxS81BZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L70)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

"pairs" is a little generic, maybe "unencrypted_events"
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 77 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7azPEASvbx43f_PUL:-MgBE24k7gukVQnYS_yE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L77)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`encryptedEvents`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 87 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7X11G3GdzOWsYz7QL:-MgBEBgaDD6BHvc0c5vT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L87)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think you can just write `TableRow().set("encrypted_id", it.key).set("encrypted_data", it.value)` as a one-liner
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-03 16:23 UTC, matthewclegg approved these changes

2021-08-03 16:24 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: 13 of 16 files reviewed, 10 unresolved discussions (waiting on @efoxepstein, @enfreck, @jmorrrr, @matthewclegg, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 70 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7Xn20CryTahtHih10:-MgBokKMAhk4NzgvMzjM:badnndr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L70)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

camel case
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 77 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7azPEASvbx43f_PUL:-MgBogpeCGFw6ZkHNGNx:bzdygce) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L77)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

camelCase I believe


<!-- Sent from Reviewable.io -->

2021-08-03 16:31 UTC, enfreck approved these changes
> Reviewed 12 of 16 files at r3, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 10 unresolved discussions (waiting on @efoxepstein, @jmorrrr, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-03 16:48 UTC, efoxepstein requested changes
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 5 unresolved discussions (waiting on @jmorrrr and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 80 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgBqgwZApEoxxtss3cV:-MgBqgwZApEoxxtss3cW:b-nj074m) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8237dbe3efb179f22c8dc2788799e126a81e6104/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L80)):*
> ```Kotlin
> 
>   val encryptedTableRows =
>     encrypted_events.map { TableRow().set("encrypted_id", it.key).set("encrypted_data", it.value) }
> ```

Can you move this line into `writeToBigQuery` too please?


<!-- Sent from Reviewable.io -->

2021-08-03 20:13 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @jmorrrr, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 70 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7Xn20CryTahtHih10:-MgCawcW5e2F0EUKjKap:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L70)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

camel case
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 77 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7azPEASvbx43f_PUL:-MgCaxC6008UvwKyEEKN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/26afeeb7bb0beb4b0c5c79da4cdb1377fd247963/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L77)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

camelCase I believe
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 80 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgBqgwZApEoxxtss3cV:-MgCbP3P78yM5OJ3cLBO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8237dbe3efb179f22c8dc2788799e126a81e6104/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L80)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you move this line into `writeToBigQuery` too please?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-04 23:48 UTC, efoxepstein reviewed
> Reviewed 4 of 5 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 3 unresolved discussions (waiting on @jmorrrr and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-05 13:43 UTC, efoxepstein requested changes
> Reviewed 1 of 1 files at r8, 11 of 11 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 4 unresolved discussions (waiting on @jmorrrr and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgLYAMM5_zsNt3ZrMod:-MgLYAMNCXYGL038aQe5:b-b7ykb3) (no related file):*
Could you file a GitHub issue to switch java_wrap_cc to support embedding the .so library into a jar? And then reference that issue wherever something is called a hack in this PR?

---


<!-- Sent from Reviewable.io -->

2021-08-05 18:29 UTC, stevenwarejones requested changes
> Reviewed 1 of 16 files at r3, 1 of 3 files at r5, 1 of 5 files at r6, 1 of 1 files at r8, 6 of 11 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein and @jmorrrr)

___
*[WORKSPACE, line 164 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg77wn43RgFC-rZc1Df:-MgMY7qlEFOAm2BEremL:b-73npn5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/WORKSPACE#L164)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you add a comment saying why that one can't be 2.31.0?

Also, do you mind extracting these to a file `//build/maven/apache_beam.bzl`? The contents of the file can be like:

```
_VERSION = "2.31.0"

apache_beam_artifacts = {
  "org.apache.beam:beam-whatever": _VERSION,
  ...

  # Some comment here about why this is a different version:
  "org.apache.beam:beam-whatever": "some other version"

  # Also include hamcrest and slf4j stuff here too because it's only for beam
}
```

Then here in WORKSPACE:

```
load("//build/maven/apache_beam.bzl", "apache_beam_artifacts")
MAVEN_ARTIFACTS.update(apache_beam_artifacts)
```
</blockquote></details>

are we going to let sanjay take care of this one? @efoxepstein 
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 43 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgMZprQ4dj2CyNB9aXg:-MgMZprQ4dj2CyNB9aXh:bvqwkdg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L43)):*
> ```Kotlin
>     init {
>       val directoryPath =
>         "panel_exchange_client/src/main/swig/wfanet/panelmatch/client/eventpreprocessing"
> ```

see my earlier comment about not including `/` to separate directories to make it more platform independent.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/Staging.kt, line 39 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgMYp1IB-9QykYfFwaF:-MgMYp1IB-9QykYfFwaG:bp5bby5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/Staging.kt#L39)):*
> ```Kotlin
> private val extraFilesToStage: List<String> by lazy {
>   val swigPath =
>     Paths.get("panel_exchange_client/src/main/swig/wfanet/panelmatch/client/eventpreprocessing")
> ```

I think we've been generally trying to make this more platform independent like:
https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/CertificateTesting.kt#L26
___
*[src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt, line 27 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgMZLMpB5dBtKVZRLT6:-MgMZLMqEzy_i7pWs2Uu:b-v0brmr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt#L27)):*
> ```Kotlin
>   } catch (e: Exception) {
>     // Last-ditch effort to create working runfiles.
>     val tmpDirPath = Paths.get("/tmp/panel-exchange-client-runfiles")
> ```

what are the scenarios under which Runfiles.create would fail and lead to this path?


<!-- Sent from Reviewable.io -->

2021-08-05 18:33 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 5 unresolved discussions (waiting on @jmorrrr)

___
*[WORKSPACE, line 164 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg77wn43RgFC-rZc1Df:-MgM_dYN6lJUU6npqEVT:b-c7ksgh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fcf3aa30b3c29d3bfadeeea3f35bf3be0ec36197/WORKSPACE#L164)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

are we going to let sanjay take care of this one? @efoxepstein 
</blockquote></details>

We need to do a big cleanup of this WORKSPACE file because we made some simplifications in common_jvm -- so let's defer this one until then.


<!-- Sent from Reviewable.io -->

2021-08-05 18:50 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 5 unresolved discussions (waiting on @jmorrrr and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 43 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgMZprQ4dj2CyNB9aXg:-MgMctyX7N9xCUeibSMG:b6j3pdp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L43)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

see my earlier comment about not including `/` to separate directories to make it more platform independent.
</blockquote></details>

@jmorrrr let's add a helper somewhere something like this:

```
fun pathOf(pathParts: String, separator: String = "/"): Path {
  return Paths.get(*pathPaths.split(separator).toTypedArray())
}
```

And then here:

`val directory = pathOf("panel_exchange_client/src/.../eventpreprocessing")`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7GSZS7qSrs2Fio-fl:-MgMdZzQ7iz_Q3fcW7gL:b-v3p3jr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfa2fe96b1b4e40c0450ad0b2242e869d869ae5f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L54)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

If we can't test this file directly can we add instructions for testing?
</blockquote></details>

+1 -- @jmorrrr please add a big comment about how to run this
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/Staging.kt, line 39 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgMYp1IB-9QykYfFwaF:-MgMdc_GDDS2RmFKXCRH:b-27de0w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/Staging.kt#L39)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I think we've been generally trying to make this more platform independent like:
https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/CertificateTesting.kt#L26
</blockquote></details>

@stevenwarejones @jmorrrr see my other comment
___
*[src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt, line 27 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgMZLMpB5dBtKVZRLT6:-MgMde_78uMdq4ctutwX:b-oi44b3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what are the scenarios under which Runfiles.create would fail and lead to this path?
</blockquote></details>

If the `RUNFILES_DIR` environmental variable isn't set (which is not done by the workers spawned by Google Cloud Dataflow and presumably other runners).


<!-- Sent from Reviewable.io -->

2021-08-05 18:51 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 5 unresolved discussions (waiting on @jmorrrr and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt, line 27 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgMZLMpB5dBtKVZRLT6:-MgMdsjP6Ylc0qkuTcGL:bvevo6h) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

If the `RUNFILES_DIR` environmental variable isn't set (which is not done by the workers spawned by Google Cloud Dataflow and presumably other runners).
</blockquote></details>

@jmorrrr can you add a comment here about this too?


<!-- Sent from Reviewable.io -->

2021-08-05 19:25 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 5 unresolved discussions (waiting on @cs-sswaminathan, @jmorrrr, @kgaynor, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 43 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgMZprQ4dj2CyNB9aXg:-MgMlTMAEcZEfK08Ai-D:bkyzeu2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@jmorrrr let's add a helper somewhere something like this:

```
fun pathOf(pathParts: String, separator: String = "/"): Path {
  return Paths.get(*pathPaths.split(separator).toTypedArray())
}
```

And then here:

`val directory = pathOf("panel_exchange_client/src/.../eventpreprocessing")`
</blockquote></details>

Why include `/` at all - in my other comment is a way to do it without including slashes.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt, line 27 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgMZLMpB5dBtKVZRLT6:-MgMln2h9ej8z1X49iF0:bpxbzv7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@jmorrrr can you add a comment here about this too?
</blockquote></details>

did you encounter this issue then? Is it a problem running it locally or only with certain runners?


<!-- Sent from Reviewable.io -->

2021-08-05 20:04 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 5 unresolved discussions (waiting on @cs-sswaminathan, @jmorrrr, @kgaynor, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 43 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgMZprQ4dj2CyNB9aXg:-MgMuGw48p-aq20udu3S:b-puimds) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L43)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Why include `/` at all - in my other comment is a way to do it without including slashes.
</blockquote></details>

The example you pointed to was super verbose and is a lot harder to read. Everyone is used to reading slash-separated paths, not `",\n  "`-separated paths
___
*[src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt, line 27 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgMZLMpB5dBtKVZRLT6:-MgMuSsr2worDS-G45qz:b-adafnk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

did you encounter this issue then? Is it a problem running it locally or only with certain runners?
</blockquote></details>

I expect it to be a problem with all runners except DirectRunner, which is used locally but no one would use in production (I hope)


<!-- Sent from Reviewable.io -->

2021-08-05 20:41 UTC, stevenwarejones requested changes
> Reviewed 1 of 5 files at r6, 1 of 11 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 5 unresolved discussions (waiting on @cs-sswaminathan, @jmorrrr, @kgaynor, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 43 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgMZprQ4dj2CyNB9aXg:-MgN1yDmBvXrMUFCtCh2:b-124gfr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The example you pointed to was super verbose and is a lot harder to read. Everyone is used to reading slash-separated paths, not `",\n  "`-separated paths
</blockquote></details>

@sanjayvas - wanted to get your perspective too
___
*[src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt, line 27 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgMZLMpB5dBtKVZRLT6:-MgN2DIy7hhxRGDwwyUi:b-zdzxcn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I expect it to be a problem with all runners except DirectRunner, which is used locally but no one would use in production (I hope)
</blockquote></details>

comment this in please


<!-- Sent from Reviewable.io -->

2021-08-05 20:45 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 7 unresolved discussions (waiting on @cs-sswaminathan, @jmorrrr, @kgaynor, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 82 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgN2YR1DZrVR2DMUkOD:-MgN2YR1DZrVR2DMUkOE:b1jm922) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L82)):*
> ```Kotlin
>         .withSelectedFields(mutableListOf("UserId", "UserEvent"))
>     )
>   return rowsFromBigQuery.map {
> ```

`.map(name = "Convert TableRows to ByteStrings") {`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 104 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgN2JeU81k_6aAvJvNy:-MgN2JeU81k_6aAvJvNz:b-1rs0w2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L104)):*
> ```Kotlin
>   // Convert KV<Long,ByteString> to TableRow
>   val encryptedTableRows =
>     encryptedEvents.map {
> ```

`.map(name = "Map Encrypted Events to TableRows") {`


<!-- Sent from Reviewable.io -->

2021-08-05 20:46 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 9 unresolved discussions (waiting on @cs-sswaminathan, @jmorrrr, @kgaynor, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 76 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgN35Wk9ZXtx-Fv6I5r:-MgN35Wl5Gik0rTWjaoU:b4lkvnf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L76)):*
> ```Kotlin
>   // Build the read options proto for the read operation.
>   val rowsFromBigQuery =
>     p.apply(
> ```

`p.apply("Read Unencrypted Event Data from BigQuery", BigQueryIO.readTableRows()...)`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 111 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgN3ExM95V_5XWGdk_u:-MgN3ExM95V_5XWGdk_v:b-kzn6f4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L111)):*
> ```Kotlin
> 
>   // Write to BigQueryIO
>   encryptedTableRows.apply(
> ```

`encryptedTableRows.apply("Write Encrypted Events to BigQuery", BigQueryIO....)`


<!-- Sent from Reviewable.io -->

2021-08-05 22:56 UTC, SanjayVas requested changes
> Reviewed 4 of 16 files at r3, 1 of 3 files at r5, 2 of 5 files at r6, 5 of 11 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 11 unresolved discussions (waiting on @cs-sswaminathan, @jmorrrr, @kgaynor, and @stevenwarejones)

___
*[WORKSPACE, line 150 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgNRVjMDtcLDqOsZyaj:-MgNRVjMDtcLDqOsZyak:bkxwn3j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/WORKSPACE#L150)):*
> ```
>     "com.google.api:gax": "2.0.0",
>     "com.google.api:gax-grpc": "2.0.0",
>     "com.google.apis:google-api-services-bigquery": "v2-rev20210404-1.31.0",
> ```
Why do we need these versions as opposed to the versions automatically pulled in as transitive deps for bigquery?

This artifacts dict should contain only our direct deps and only list transitive deps when we need to override the version of said dep.
___
*[WORKSPACE, line 164 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgNUP6T3zW4WKf_4tih:-MgNUP6T3zW4WKf_4tii:b-4af33s) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/WORKSPACE#L164)):*
> ```
>     "org.apache.beam:beam-sdks-java-core": BEAM_VERSION,
>     "org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core": BEAM_VERSION,
> ```
Aren't these deps of beam-runners-direct-java? Why do they need to be specified here?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 43 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgMZprQ4dj2CyNB9aXg:-MgNUkPsDVjwRvaZ4B4J:bvboc0v) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L43)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@sanjayvas - wanted to get your perspective too
</blockquote></details>

I don't think the verbosity is that bad, and I personally prefer it over doing string parsing just to make things look like platform-dependent path strings but still be platform-independent underneath.

That said, I don't feel terribly strongly about it. If you are going to add a helper, just make it clear that it's creating a `Path` from a POSIX path string as opposed to a generic string with an arbitrary path separator.


<!-- Sent from Reviewable.io -->

2021-08-05 23:22 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 11 unresolved discussions (waiting on @cs-sswaminathan, @jmorrrr, @kgaynor, @SanjayVas, and @stevenwarejones)

___
*[WORKSPACE, line 164 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgNUP6T3zW4WKf_4tih:-MgNbBjG27400PNxsiHo:b47u7yc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/WORKSPACE#L164)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     "org.apache.beam:beam-sdks-java-core": BEAM_VERSION,
>     "org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core": BEAM_VERSION,
> ```
Aren't these deps of beam-runners-direct-java? Why do they need to be specified here?
</blockquote></details>

We have direct deps on both of these.


<!-- Sent from Reviewable.io -->

2021-08-05 23:31 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 11 unresolved discussions (waiting on @cs-sswaminathan, @jmorrrr, @kgaynor, @SanjayVas, and @stevenwarejones)

___
*[WORKSPACE, line 150 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgNRVjMDtcLDqOsZyaj:-MgNctrmE9HhptA-rh0x:b-vfcsgs) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/WORKSPACE#L150)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     "com.google.api:gax": "2.0.0",
>     "com.google.api:gax-grpc": "2.0.0",
>     "com.google.apis:google-api-services-bigquery": "v2-rev20210404-1.31.0",
> ```
Why do we need these versions as opposed to the versions automatically pulled in as transitive deps for bigquery?

This artifacts dict should contain only our direct deps and only list transitive deps when we need to override the version of said dep.
</blockquote></details>

Left to its own devices, it pulls in gax 1.66.0 but we want 2.0.0 because at 1.66.0 we get: `java.lang.NoClassDefFoundError: com/google/api/gax/tracing/NoopApiTracer`


<!-- Sent from Reviewable.io -->

2021-08-05 23:37 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 11 unresolved discussions (waiting on @cs-sswaminathan, @jmorrrr, @kgaynor, @SanjayVas, and @stevenwarejones)

___
*[WORKSPACE, line 150 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgNRVjMDtcLDqOsZyaj:-MgNfHU762TRoXq8euSt:b-onqj4m) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/WORKSPACE#L150)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Left to its own devices, it pulls in gax 1.66.0 but we want 2.0.0 because at 1.66.0 we get: `java.lang.NoClassDefFoundError: com/google/api/gax/tracing/NoopApiTracer`
</blockquote></details>

@jmorrrr can you add a comment above `gax` saying `# Without this, we get java.lang.NoClassDefFoundError: com/google/api/gax/tracing/NoopApiTracer`


<!-- Sent from Reviewable.io -->

2021-08-06 15:14 UTC, kgaynor approved these changes

2021-08-06 16:08 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 11 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgLYAMM5_zsNt3ZrMod:-MgM_6-h7pJMfHa-QqMV:b-896fix) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Could you file a GitHub issue to switch java_wrap_cc to support embedding the .so library into a jar? And then reference that issue wherever something is called a hack in this PR?
</blockquote></details>

Done.

---
___
*[WORKSPACE, line 150 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgNRVjMDtcLDqOsZyaj:-MgQhqSdCCcaeZLGdHL-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/WORKSPACE#L150)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@jmorrrr can you add a comment above `gax` saying `# Without this, we get java.lang.NoClassDefFoundError: com/google/api/gax/tracing/NoopApiTracer`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 43 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgMZprQ4dj2CyNB9aXg:-MgR1lMs6pALGi2HcOMM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think the verbosity is that bad, and I personally prefer it over doing string parsing just to make things look like platform-dependent path strings but still be platform-independent underneath.

That said, I don't feel terribly strongly about it. If you are going to add a helper, just make it clear that it's creating a `Path` from a POSIX path string as opposed to a generic string with an arbitrary path separator.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7GSZS7qSrs2Fio-fl:-MgMy2pU36A5LeUxYoZg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfa2fe96b1b4e40c0450ad0b2242e869d869ae5f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

+1 -- @jmorrrr please add a big comment about how to run this
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 76 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgN35Wk9ZXtx-Fv6I5r:-MgQi5J-5CZMd3H8OvLM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L76)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`p.apply("Read Unencrypted Event Data from BigQuery", BigQueryIO.readTableRows()...)`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 82 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgN2YR1DZrVR2DMUkOD:-MgQiCJP5LoBXBiLRv3B:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L82)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`.map(name = "Convert TableRows to ByteStrings") {`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 104 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgN2JeU81k_6aAvJvNy:-MgQh_q04MF-Rt8T454o:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L104)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`.map(name = "Map Encrypted Events to TableRows") {`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 111 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgN3ExM95V_5XWGdk_u:-MgQhHNNDg1Fuo-pfhdm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L111)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`encryptedTableRows.apply("Write Encrypted Events to BigQuery", BigQueryIO....)`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/Staging.kt, line 39 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgMYp1IB-9QykYfFwaF:-MgR2b8n2OpN5x8mbjDA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/Staging.kt#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@stevenwarejones @jmorrrr see my other comment
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt, line 27 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgMZLMpB5dBtKVZRLT6:-MgQk-Sf4WjLUH2peheX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4ea9ed2c6c50118e98207b7594c64d39c24899f7/src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

comment this in please
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-06 16:59 UTC, stevenwarejones requested changes
> Reviewed 8 of 13 files at r11, 3 of 7 files at r12.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: 21 of 25 files reviewed, 8 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7GSZS7qSrs2Fio-fl:-MgROlpdDTq3k7YlL4Sm:b-z0gvfw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfa2fe96b1b4e40c0450ad0b2242e869d869ae5f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L54)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

is it not possible to run locally? what are the dependencies that prevent that?


<!-- Sent from Reviewable.io -->

2021-08-06 17:10 UTC, efoxepstein requested changes
> Reviewed 7 of 13 files at r11, 7 of 7 files at r12.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 4 unresolved discussions (waiting on @cs-sswaminathan, @jmorrrr, @SanjayVas, and @stevenwarejones)

___
*[.bazelrc, line 8 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgRDi3V9Fa99mkE8dfV:-MgRDi3V9Fa99mkE8dfW:b-4hbdzr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/822700fe1df5e55ec6b9f855a706fc480733e4ce/.bazelrc#L8)):*
> ```
> 
> build --action_env=BAZEL_LINKLIBS=-l%:libstdc++.a:-lm
> build --action_env=BAZEL_LINKOPTS=-static-libgcc
> ```

Please remove this
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7GSZS7qSrs2Fio-fl:-MgRR1ayAb8n2UmsN0MZ:bo1u4ek) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfa2fe96b1b4e40c0450ad0b2242e869d869ae5f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L54)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is it not possible to run locally? what are the dependencies that prevent that?
</blockquote></details>

There are unit tests that run it locally.

We could make another `main` file that uses `DirectRunner` and reads from a local file or something -- but that's not what this PR does. This PR is specifically for Google Cloud Dataflow.


<!-- Sent from Reviewable.io -->

2021-08-06 17:15 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 4 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, @jmorrrr, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7GSZS7qSrs2Fio-fl:-MgRS8RSAK8UZG6Plv9N:byihyvo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfa2fe96b1b4e40c0450ad0b2242e869d869ae5f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

There are unit tests that run it locally.

We could make another `main` file that uses `DirectRunner` and reads from a local file or something -- but that's not what this PR does. This PR is specifically for Google Cloud Dataflow.
</blockquote></details>

Okay - I'd love that as a follow-up. What do you think of
1. Putting this in a googlecloud subfolder
2. Adding a TODO somewhere that would add another `main` that could run as a github test (eg locally using `DirectRunner`?)


<!-- Sent from Reviewable.io -->

2021-08-06 17:19 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 4 unresolved discussions (waiting on @cs-sswaminathan, @jmorrrr, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7GSZS7qSrs2Fio-fl:-MgRSrci5J0u4Wrwj_TQ:b-m5zjgv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfa2fe96b1b4e40c0450ad0b2242e869d869ae5f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L54)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Okay - I'd love that as a follow-up. What do you think of
1. Putting this in a googlecloud subfolder
2. Adding a TODO somewhere that would add another `main` that could run as a github test (eg locally using `DirectRunner`?)
</blockquote></details>

OK, let's move `PreprocessEventsMain.kt` to `src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/` for consistency with how `cross-media-measurement` does cloud-specific stuff.

What is the purpose of (2)? The core pipeline logic is unit-tested, so why do we need to run `DirectRunner` on GitHub outside a unit test environment?


<!-- Sent from Reviewable.io -->

2021-08-06 17:20 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 4 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[.bazelrc, line 8 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgRDi3V9Fa99mkE8dfV:-MgRS655BobKNFHuTOqc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/822700fe1df5e55ec6b9f855a706fc480733e4ce/.bazelrc#L8)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please remove this
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-06 17:20 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 3 unresolved discussions (waiting on @cs-sswaminathan, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-06 17:34 UTC, stevenwarejones requested changes
> Reviewed 1 of 7 files at r12.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 3 unresolved discussions (waiting on @cs-sswaminathan, @jmorrrr, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7GSZS7qSrs2Fio-fl:-MgRWW1G1-0IqIt10P8l:b1qr41t) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfa2fe96b1b4e40c0450ad0b2242e869d869ae5f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

OK, let's move `PreprocessEventsMain.kt` to `src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/` for consistency with how `cross-media-measurement` does cloud-specific stuff.

What is the purpose of (2)? The core pipeline logic is unit-tested, so why do we need to run `DirectRunner` on GitHub outside a unit test environment?
</blockquote></details>

1. +1
2. I thought it would be a way to demonstrate correctness. Its also a nice way for people run and tinker with it locally. Not crucial but a nice-to-have.


<!-- Sent from Reviewable.io -->

2021-08-06 17:37 UTC, cs-sswaminathan approved these changes
> Reviewed 6 of 16 files at r3, 1 of 3 files at r5, 1 of 5 files at r6, 1 of 1 files at r8, 5 of 11 files at r9, 6 of 13 files at r11, 7 of 7 files at r12.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 3 unresolved discussions (waiting on @jmorrrr and @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-08-06 17:51 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mg7GSZS7qSrs2Fio-fl:-MgRVsUfCeozDZgIFpNK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfa2fe96b1b4e40c0450ad0b2242e869d869ae5f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

OK, let's move `PreprocessEventsMain.kt` to `src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/` for consistency with how `cross-media-measurement` does cloud-specific stuff.

What is the purpose of (2)? The core pipeline logic is unit-tested, so why do we need to run `DirectRunner` on GitHub outside a unit test environment?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-06 17:55 UTC, efoxepstein approved these changes
> Reviewed 2 of 3 files at r14, 4 of 4 files at r15.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 41 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgRaSke3NaifL207uwb:-MgRaSkf7kmMcv3f7k8Y:b-ehc2k7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cf133c560e6aa03e3d4226c6134b06c4e7186e19/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L41)):*
> ```Kotlin
>     init {
>       val libraryName = System.mapLibraryName("preprocess_events")
>       val libraryPath = "/main/swig/wfanet/panelmatch/client/eventpreprocessing/$libraryName"
> ```

Preempting any comments on slashes here, Java explicitly says that resource paths are slash-delimited.


<!-- Sent from Reviewable.io -->

2021-08-06 19:58 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-09 15:24 UTC, stevenwarejones requested changes
> Reviewed 1 of 3 files at r14, 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 4 unresolved discussions (waiting on @jmorrrr and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 11 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgfVTsFD-z5tlkAOX_p:-MgfVTsFD-z5tlkAOX_q:b-f0nlw7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f7b6f525dbc17eaeafd1777868eace7cb4e87082/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L11)):*
> ```Starlark
> # See also https://github.com/world-federation-of-advertisers/panel-exchange-client/issues/77.
> java_library(
>     name = "swig_resources",
> ```

do we want to fix this in other places at the same time or leave that for later?
___
*[src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt, line 23 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgfVooZ5PTLXj_ZWQuK:-MgfVooZ5PTLXj_ZWQuL:b6g54qc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/822700fe1df5e55ec6b9f855a706fc480733e4ce/src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt#L23)):*
> ```Kotlin
> 
> private val runfiles: Runfiles by lazy {
>   try {
> ```

is this not needed anymore? what was the workaround?


<!-- Sent from Reviewable.io -->

2021-08-09 15:54 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 4 unresolved discussions (waiting on @jmorrrr, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt, line 23 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgfVooZ5PTLXj_ZWQuK:-MgfbomGBfmP563YS75J:b-qcppry) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/822700fe1df5e55ec6b9f855a706fc480733e4ce/src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt#L23)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is this not needed anymore? what was the workaround?
</blockquote></details>

Deleting Runfiles.kt would likely break a lot of other stuff -- migrating away from it should likely be a separate effort


<!-- Sent from Reviewable.io -->

2021-08-09 16:32 UTC, kgaynor approved these changes

2021-08-09 17:14 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 11 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgfVTsFD-z5tlkAOX_p:-Mgfu2QKCAV891HgIUKM:b-lbut5x) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f7b6f525dbc17eaeafd1777868eace7cb4e87082/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L11)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do we want to fix this in other places at the same time or leave that for later?
</blockquote></details>

What do you mean?


<!-- Sent from Reviewable.io -->

2021-08-09 17:18 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 11 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgfVTsFD-z5tlkAOX_p:-Mgfuxon9zbrmHxJVTz-:bjfkug9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f7b6f525dbc17eaeafd1777868eace7cb4e87082/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L11)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

I think we should have a broader discussion about our strategy for JNI (as this comes up in the Duchies, too) before we make changes like this in other places.


<!-- Sent from Reviewable.io -->

2021-08-09 18:23 UTC, cs-sswaminathan approved these changes
> Reviewed 1 of 3 files at r14, 3 of 4 files at r15, 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-09 19:40 UTC, SanjayVas requested changes
> Reviewed 2 of 16 files at r3, 1 of 1 files at r8, 5 of 13 files at r11, 3 of 7 files at r12, 1 of 3 files at r14, 3 of 4 files at r15, 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 5 unresolved discussions (waiting on @jmorrrr and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 11 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgfVTsFD-z5tlkAOX_p:-MggLgA_4n8_hj4vtk27:b-dqrngw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f7b6f525dbc17eaeafd1777868eace7cb4e87082/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L11)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think we should have a broader discussion about our strategy for JNI (as this comes up in the Duchies, too) before we make changes like this in other places.
</blockquote></details>

Would you mind perhaps adding a TODO to drop this if rules_swig gains support for embedding the native shared library as a resource?
___
*[src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt, line 1 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MggQRkc7lfRMfBvBxiu:-MggQRkc7lfRMfBvBxiv:b-j0lkpe) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f7b6f525dbc17eaeafd1777868eace7cb4e87082/src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt#L1)):*
> ```Kotlin
> // Copyright 2020 The Cross-Media Measurement Authors
> ```

Can't this be referenced from common-jvm?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt, line 60 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MggMu9t81uwmMr7yaPn:-MggMu9t81uwmMr7yaPo:b-yndgt4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f7b6f525dbc17eaeafd1777868eace7cb4e87082/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt#L60)):*
> ```Kotlin
>  * To test this pipeline, it must be run on Google Cloud Platform on a machine that also has the
>  * cross-media-measurement repository cloned and docker installed. The command to run the pipeline
>  * on GCP is: ../cross-media-measurement/tools/bazel-container build
> ```

nit: use either code or code block Markdown for this command, as KDoc supports basic [Markdown syntax](https://daringfireball.net/projects/markdown/syntax)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt, line 75 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MggPqlg2_wboa5KL9Ls:-MggPqlg2_wboa5KL9Lt:buk8e4d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f7b6f525dbc17eaeafd1777868eace7cb4e87082/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt#L75)):*
> ```Kotlin
> fun main(args: Array<String>) {
>   val options = makeOptions(args)
>   val p = Pipeline.create(options)
> ```

nit: Prefer descriptive identifier names. Avoid single-letter variables except for e.g. loop iterators.


<!-- Sent from Reviewable.io -->

2021-08-09 20:50 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt, line 60 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mggelpg7iVCc0CszLqf:-Mggf_m44njTYg7dcMjo:b3aa7jm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b04d13d74dd0695de8eb13c8e3909774ca861bf3/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt#L60)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think the formatting should be:

```
 * on GCP is:
 *
 *```
 * ../cross-media-measurement/tools/bazel-container build ...
 *```
 *
 * Where SIZE is ...
```
</blockquote></details>

Oh it was like that I think git fix changes it (?)


<!-- Sent from Reviewable.io -->

2021-08-09 20:52 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt, line 60 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mggelpg7iVCc0CszLqf:-Mggfy1V08kohzYK3nif:b-pt4n91) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b04d13d74dd0695de8eb13c8e3909774ca861bf3/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt#L60)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Oh it was like that I think git fix changes it (?)
</blockquote></details>

Paging @sanjayvas @sanjayvas @sanjayvas 


<!-- Sent from Reviewable.io -->

2021-08-09 20:54 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt, line 60 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mggelpg7iVCc0CszLqf:-MgggZmaBlmJAoSVQaiB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b04d13d74dd0695de8eb13c8e3909774ca861bf3/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt#L60)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Oh just kidding fixing now
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-09 21:06 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r18.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt, line 60 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mggelpg7iVCc0CszLqf:-Mggj1LZ3MYPZ1yDf-GT:bq1rfq4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b04d13d74dd0695de8eb13c8e3909774ca861bf3/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt#L60)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

https://github.com/facebookincubator/ktfmt/issues/235

Update your ktfmt to v0.27+. I'll see about getting the one in our lint action updated.


<!-- Sent from Reviewable.io -->

2021-08-09 21:10 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt, line 60 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mggelpg7iVCc0CszLqf:-MggjmZS2zprdRYxnbLp:b-6z6955) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b04d13d74dd0695de8eb13c8e3909774ca861bf3/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

https://github.com/facebookincubator/ktfmt/issues/235

Update your ktfmt to v0.27+. I'll see about getting the one in our lint action updated.
</blockquote></details>

Ugh, nvm. I'm using v0.27 and still getting the problem locally. Let me see if there's a workaround.


<!-- Sent from Reviewable.io -->

2021-08-09 21:25 UTC, jmorrrr commented
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt, line 60 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mggelpg7iVCc0CszLqf:-MggnXsmBIw3YBUuVw3x:b-9lymtf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b04d13d74dd0695de8eb13c8e3909774ca861bf3/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ugh, nvm. I'm using v0.27 and still getting the problem locally. Let me see if there's a workaround.
</blockquote></details>

Git fix didn't change it I got it to work I just had to leave a line above and below


<!-- Sent from Reviewable.io -->

2021-08-09 21:26 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 3 unresolved discussions (waiting on @jmorrrr and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt, line 60 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mggelpg7iVCc0CszLqf:-MggnEk74vxn_58-dejp:b686uia) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b04d13d74dd0695de8eb13c8e3909774ca861bf3/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt#L60)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Git fix didn't change it I got it to work I just had to leave a line above and below
</blockquote></details>

Got it. You're using `'''` instead of ` ``` `.

Also, you have line breaks in your command that prevent a safe copy-paste. Try keeping that as one line.

e.g. 
```
 * on GCP is:
 *
 * ```
 * ../cross-media-measurement/tools/bazel-container build //src/main/kotlin/org/wfanet/panelmatch/ client/eventpreprocessing/deploy/gcloud:process_events && bazel-bin/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/process_events '--batchSize=SIZE' '--cryptokey=KEY' '--pepper=PEPPER' '--bigQueryInputTable=INPUT_TABLE' '--bigQueryOutputTable=OUTPUT_TABLE' '--project=PROJECT' '--runner=dataflow' '--region=us-central1' '--tempLocation=TEMP_LOCATION' '--defaultWorkerLogLevel=DEBUG'
 * ```
 *
 * Where SIZE is the desired batch size, KEY is the desired crypto key, PEPPER is the desired
```


<!-- Sent from Reviewable.io -->

2021-08-09 21:27 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 3 unresolved discussions (waiting on @jmorrrr and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-09 21:27 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 3 unresolved discussions (waiting on @jmorrrr and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-09 21:32 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt, line 60 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mggelpg7iVCc0CszLqf:-MggoLYJArTPvYph3sTo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b04d13d74dd0695de8eb13c8e3909774ca861bf3/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Got it. You're using `'''` instead of ` ``` `.

Also, you have line breaks in your command that prevent a safe copy-paste. Try keeping that as one line.

e.g. 
```
 * on GCP is:
 *
 * ```
 * ../cross-media-measurement/tools/bazel-container build //src/main/kotlin/org/wfanet/panelmatch/ client/eventpreprocessing/deploy/gcloud:process_events && bazel-bin/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/process_events '--batchSize=SIZE' '--cryptokey=KEY' '--pepper=PEPPER' '--bigQueryInputTable=INPUT_TABLE' '--bigQueryOutputTable=OUTPUT_TABLE' '--project=PROJECT' '--runner=dataflow' '--region=us-central1' '--tempLocation=TEMP_LOCATION' '--defaultWorkerLogLevel=DEBUG'
 * ```
 *
 * Where SIZE is the desired batch size, KEY is the desired crypto key, PEPPER is the desired
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-09 21:45 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: 25 of 26 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt, line 60 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-Mggelpg7iVCc0CszLqf:-MggrVfoBJoH9RFEL-tP:b-cj6f6i) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b04d13d74dd0695de8eb13c8e3909774ca861bf3/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/PreprocessEventsMain.kt#L60)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like some extra code fences bot added at the end of the KDoc too.

This is what ended up being stable for me:

```
 * on GCP is:
 *
 * ```
 * ../cross-media-measurement/tools/bazel-container build //src/main/kotlin/org/wfanet/panelmatch/ client/eventpreprocessing/deploy/gcloud:process_events && bazel-bin/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/deploy/gcloud/process_events '--batchSize=SIZE' '--cryptokey=KEY' '--pepper=PEPPER' '--bigQueryInputTable=INPUT_TABLE' '--bigQueryOutputTable=OUTPUT_TABLE' '--project=PROJECT' '--runner=dataflow' '--region=us-central1' '--tempLocation=TEMP_LOCATION' '--defaultWorkerLogLevel=DEBUG'
 * ```
 *
 * Where SIZE is the desired batch size, KEY is the desired crypto key, PEPPER is the desired
 * pepper, INPUT_TABLE is the BigQuery table to read from, OUTPUT_TABLE is the BigQuery table to
 * write to, PROJECT is the project name, and TEMP_LOCATION is the desired location to store temp
 * files.
 *
 * Performance and outputs can be tracked on the GCP console.
 */
```


<!-- Sent from Reviewable.io -->

2021-08-09 21:51 UTC, kgaynor approved these changes

2021-08-09 21:52 UTC, efoxepstein reviewed
> Reviewed 1 of 1 files at r19.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 3 unresolved discussions (waiting on @jmorrrr and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-09 22:13 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r20.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 3 unresolved discussions (waiting on @jmorrrr and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-09 23:15 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r20.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-10 14:08 UTC, jmorrrr reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 11 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgfVTsFD-z5tlkAOX_p:-MgkNQ6v4eodyyBVlEPq:bs7wumb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f7b6f525dbc17eaeafd1777868eace7cb4e87082/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L11)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Would you mind perhaps adding a TODO to drop this if rules_swig gains support for embedding the native shared library as a resource?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-10 16:29 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r21.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-10 16:46 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 1 unresolved discussion (waiting on @jmorrrr)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt, line 23 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgfVooZ5PTLXj_ZWQuK:-Mgkx7ur67Qxydzc999V:b-kaqmu3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/822700fe1df5e55ec6b9f855a706fc480733e4ce/src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt#L23)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Deleting Runfiles.kt would likely break a lot of other stuff -- migrating away from it should likely be a separate effort
</blockquote></details>

sorry - thats not what I meant. I. meant you deleted the catch portion. Is that portion not needed anymore?


<!-- Sent from Reviewable.io -->

2021-08-10 16:52 UTC, efoxepstein approved these changes
> Reviewed 2 of 2 files at r21.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt, line 23 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgfVooZ5PTLXj_ZWQuK:-MgkyV_NCJf9IfQiCGI6:bl7li90) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/822700fe1df5e55ec6b9f855a706fc480733e4ce/src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt#L23)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

sorry - thats not what I meant. I. meant you deleted the catch portion. Is that portion not needed anymore?
</blockquote></details>

`Runfiles.kt` is not used in this PR anymore. We load the C++ shared library `.so` from within a `.jar` (via `ClassLoader.getResourceAsStream`) instead of from a local file.


<!-- Sent from Reviewable.io -->

2021-08-10 16:53 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-10 16:59 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @jmorrrr)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt, line 23 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70#-MgfVooZ5PTLXj_ZWQuK:-Mgl-KuGALF5IzEWsXx4:basizg5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/822700fe1df5e55ec6b9f855a706fc480733e4ce/src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`Runfiles.kt` is not used in this PR anymore. We load the C++ shared library `.so` from within a `.jar` (via `ClassLoader.getResourceAsStream`) instead of from a local file.
</blockquote></details>

thanks for the clarification!


<!-- Sent from Reviewable.io -->

2021-08-10 17:00 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/70)* status: all files reviewed, 1 unresolved discussion (waiting on @jmorrrr)



<!-- Sent from Reviewable.io -->

2021-08-10 17:02 UTC, merged