Update task execution to lazily stream inputs and outputs
world-federation-of-advertisers/panel-exchange-client pull request #75
Opened 2021-08-04 23:13 UTC by jonmolle

Uses StorageClient.Blob more directly and adds a method to convert blob
data to bytestring.

Implements an InMemoryStorageClient to make it possible to test.

The goal is to avoid reading in the entirety of an input (or collecting
an entire output before writing) all at once to avoid memory issues.
While the existing exchange task steps can and do collect their inputs,
these will be revisited in a later PR and other tasks with larger inputs
and outputs will leverage these streams.

2021-08-04 23:38 UTC, efoxepstein reviewed
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 6 unresolved discussions (waiting on @jonmolle)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgIUYU3B3tlRnVO292d:-MgIUYU49C0rz3kkmoIJ:bon42rh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/075b072483c0b80f88c453715559d0fc932a9df9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt#L45)):*
> ```Kotlin
>       "Overlap of $currentOverlap is less than $minimumOverlap"
>     }
>     return mapOf("current-data" to requireNotNull(input["current-data"]!!.read())).toMap()
> ```

Does this work? `requireNotNull(input["whatever"]).read()`? It's better to avoid `!!` when we can.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageClient.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgIW3w35PHKnC-jbMHK:-MgIW3w35PHKnC-jbMHL:bzdj0dp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/075b072483c0b80f88c453715559d0fc932a9df9/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageClient.kt#L56)):*
> ```Kotlin
>     // size and to emulate "writing out" to memory.
>     inMemoryStorageMap[mapKey] =
>       Blob(content.fold(ByteString.EMPTY, { agg, chunk -> agg.concat(chunk) }), blobKey)
> ```

Maybe save the Blob to a local variable, assign it into the map, then return it to avoid the obviously unnecessary `!!`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageClient.kt, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgIWymw0VknhRwkvIeg:-MgIWymw0VknhRwkvIeh:b-9x9lot) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/075b072483c0b80f88c453715559d0fc932a9df9/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageClient.kt#L71)):*
> ```Kotlin
>     StorageClient.Blob {
> 
>     override val size: Long
> ```

You should be able to just write `override val size: Long = byteData.size().toLong()` since `byteData` is immutable (I think?)

Ditto for `storageClient`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 77 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgIV8nREXYCUjCBIocg:-MgIV8nREXYCUjCBIoch:b-7xe246) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/075b072483c0b80f88c453715559d0fc932a9df9/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L77)):*
> ```Kotlin
> 
> // TODO: add this as a method to StorageClient.kt as StorageClient.Blob.foldBlob
> suspend fun foldBlob(blob: Blob?): ByteString =
> ```

Can you just make this an extension method for now?

```
fun Blob.toByteString(): ByteString {
  return read().fold(...) { agg, chunk -> acc.concat(chunk) }
}
```
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTaskTest.kt, line 100 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgIVayoCqOYRJ07ciGX:-MgIVayoCqOYRJ07ciGY:bfptjbc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/075b072483c0b80f88c453715559d0fc932a9df9/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTaskTest.kt#L100)):*
> ```Kotlin
>                   "current-data",
>                   makeSerializedSharedInputs(SINGLE_BLINDED_KEYS.dropLast(1))
>                     .asBufferedFlow(mockStorage.defaultBufferSizeBytes)
> ```

Add a helper function for `makeSerializedSharedInputs(...).asBufferedFlow(...)`?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorImplTest.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgIVoq0-Z5jNpLJh83_:-MgIVoq0-Z5jNpLJh83a:b2lu1nr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/075b072483c0b80f88c453715559d0fc932a9df9/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorImplTest.kt#L56)):*
> ```Kotlin
>           ByteString.copyFromUtf8(
>               "Out:${
>             it.value.read(1024)
> ```

Can you pull the calculation out to a local variable?


<!-- Sent from Reviewable.io -->

2021-08-05 21:15 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgIUYU3B3tlRnVO292d:-MgN26zw03fIuZdlfa2_:b-a6x1hz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/075b072483c0b80f88c453715559d0fc932a9df9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Does this work? `requireNotNull(input["whatever"]).read()`? It's better to avoid `!!` when we can.
</blockquote></details>

It does, I did not know that it worked that way in Kotlin. Thanks, I'll keep that practice in mind going forward.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageClient.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgIW3w35PHKnC-jbMHK:-MgN4gQpAZ1kV_qSMNPj:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/075b072483c0b80f88c453715559d0fc932a9df9/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageClient.kt#L56)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe save the Blob to a local variable, assign it into the map, then return it to avoid the obviously unnecessary `!!`
</blockquote></details>

Done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageClient.kt, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgIWymw0VknhRwkvIeg:-MgN9sEI6nPLnFdi0i6c:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/075b072483c0b80f88c453715559d0fc932a9df9/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageClient.kt#L71)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

You should be able to just write `override val size: Long = byteData.size().toLong()` since `byteData` is immutable (I think?)

Ditto for `storageClient`
</blockquote></details>

Done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 77 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgIV8nREXYCUjCBIocg:-MgN0Ntx5JdSQpgkCDup:bbfnn6c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/075b072483c0b80f88c453715559d0fc932a9df9/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L77)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you just make this an extension method for now?

```
fun Blob.toByteString(): ByteString {
  return read().fold(...) { agg, chunk -> acc.concat(chunk) }
}
```
</blockquote></details>

Done, I didn't know that was a thing, thanks for the tip
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTaskTest.kt, line 100 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgIVayoCqOYRJ07ciGX:-MgN0TXWAy01682E73lE:buqqnqc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/075b072483c0b80f88c453715559d0fc932a9df9/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTaskTest.kt#L100)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Add a helper function for `makeSerializedSharedInputs(...).asBufferedFlow(...)`?
</blockquote></details>

Done. I think we'll want to revisit this in a later PR, though. If we're going to validate the input, it should probably be around this step and we might want to redo more around the helpers
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorImplTest.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgIVoq0-Z5jNpLJh83_:-MgN9u7j53R1JDbNZzQX:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/075b072483c0b80f88c453715559d0fc932a9df9/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutorImplTest.kt#L56)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you pull the calculation out to a local variable?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-08-05 21:38 UTC, efoxepstein reviewed
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 4 unresolved discussions (waiting on @jonmolle)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt, line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgNCWgtDAh45w8GzkmQ:-MgNCWgtDAh45w8GzkmR:bof2oiw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/eff302ad8096e68d4a35cab3f85d95f26cf26b6f/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt#L32)):*
> ```Kotlin
>   override suspend fun execute(input: Map<String, Blob>): Map<String, Flow<ByteString>> {
>     val currentData: Set<ByteString> =
>       parseSerializedSharedInputs(input["current-data"].toByteString()).toSet()
> ```

Can you pull out `input["current-data"].toByteString()` and `input["previous-data"].toByteString()` to local variables? I think that'll help me read this code (and avoid the double-read that's happening)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 77 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgIV8nREXYCUjCBIocg:-MgNEcHf3eoxFTb_FupQ:b-o3v9xp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/075b072483c0b80f88c453715559d0fc932a9df9/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L77)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

Done, I didn't know that was a thing, thanks for the tip
</blockquote></details>

I have a slight preference for this not accepting nullable receivers (and pushing the `requireNotNull` and error-handling to callers
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgNF-1O3yUfaS-uJp8n:-MgNF-1O3yUfaS-uJp8o:b5d1g0o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/eff302ad8096e68d4a35cab3f85d95f26cf26b6f/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L77)):*
> ```Kotlin
> 
> // TODO: add this as a method to StorageClient.kt as StorageClient.Blob.toByteString
> suspend fun Blob?.toByteString(): ByteString =
> ```

KDoc please
___
*[src/main/kotlin/org/wfanet/panelmatch/protocol/common/SharedInputs.kt, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgNEv_K-lcpAf7nOenb:-MgNEv_K-lcpAf7nOenc:b5d1g0o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/eff302ad8096e68d4a35cab3f85d95f26cf26b6f/src/main/kotlin/org/wfanet/panelmatch/protocol/common/SharedInputs.kt#L27)):*
> ```Kotlin
> }
> 
> fun makeSerializedSharedInputFlow(data: List<ByteString>, bufferSize: Int): Flow<ByteString> {
> ```

KDoc please


<!-- Sent from Reviewable.io -->

2021-08-05 22:39 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt, line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgNCWgtDAh45w8GzkmQ:-MgNNqxg8y31rFXCGVEr:b-9j1sdn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/eff302ad8096e68d4a35cab3f85d95f26cf26b6f/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you pull out `input["current-data"].toByteString()` and `input["previous-data"].toByteString()` to local variables? I think that'll help me read this code (and avoid the double-read that's happening)
</blockquote></details>

Ah, I just assumed the read abstraction wouldn't actually read (or rebuffer) the return value. Considering we need to read the flow _and_ pass it along here, I don't know if there's a way to avoid double-reading it at some point unless we want to handle the output differently. I think this is the only task where this happens, though, so I think it is ok. I did pull out the flow into a local variable, however.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 77 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgIV8nREXYCUjCBIocg:-MgNSkH46PzSQ2U-Wz2c:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/075b072483c0b80f88c453715559d0fc932a9df9/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L77)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I have a slight preference for this not accepting nullable receivers (and pushing the `requireNotNull` and error-handling to callers
</blockquote></details>

Done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgNF-1O3yUfaS-uJp8n:-MgNQUfZBpxWTMp-0CVu:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/eff302ad8096e68d4a35cab3f85d95f26cf26b6f/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L77)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

KDoc please
</blockquote></details>

Done
___
*[src/main/kotlin/org/wfanet/panelmatch/protocol/common/SharedInputs.kt, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgNEv_K-lcpAf7nOenb:-MgNQRHc0lXBgtbffSd2:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/eff302ad8096e68d4a35cab3f85d95f26cf26b6f/src/main/kotlin/org/wfanet/panelmatch/protocol/common/SharedInputs.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

KDoc please
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-08-05 22:58 UTC, efoxepstein reviewed
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 4 unresolved discussions (waiting on @jonmolle)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt, line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgNCWgtDAh45w8GzkmQ:-MgNWHRB6gPgzB2k06oQ:b-7e10xg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/eff302ad8096e68d4a35cab3f85d95f26cf26b6f/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt#L32)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

Ah, I just assumed the read abstraction wouldn't actually read (or rebuffer) the return value. Considering we need to read the flow _and_ pass it along here, I don't know if there's a way to avoid double-reading it at some point unless we want to handle the output differently. I think this is the only task where this happens, though, so I think it is ok. I did pull out the flow into a local variable, however.
</blockquote></details>

Oh, you raise a good point -- you can't count on being able to execute a flow multiple times.

Here's my recommendation:

1. Leave the local variable
2. Make a new local variable that flattens `currentData` into a `ByteString` (by the way, please use this: https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L99)
3. Use this to create a new flow for the output: https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L139
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/RemoteUrlStorage.not_kt, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgNXNAx5W9giXxIekys:-MgNXNAy4UFvygjMOPn1:b-nczwin) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/87aa35b2b549588e2bdc5c45e5a02feba0eba602/src/main/kotlin/org/wfanet/panelmatch/client/storage/RemoteUrlStorage.not_kt#L1)):*
> ```
> // Copyright 2020 The Cross-Media Measurement Authors
> ```

.not_kt?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/RemoteUrlStorageClient.rename_kt, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgNXPrsE6zxKk7EjTKp:-MgNXPrsE6zxKk7EjTKq:bd72ada) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/87aa35b2b549588e2bdc5c45e5a02feba0eba602/src/main/kotlin/org/wfanet/panelmatch/client/storage/RemoteUrlStorageClient.rename_kt#L1)):*
> ```
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

.rename_kt?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 82 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgNXUU806MjzMldXRx8:-MgNXUU806MjzMldXRx9:b-jkbadi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/87aa35b2b549588e2bdc5c45e5a02feba0eba602/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L82)):*
> ```Kotlin
>  */
> suspend fun Blob.toByteString(): ByteString =
>   this.read().fold(ByteString.EMPTY, { agg, chunk -> agg.concat(chunk) })
> ```

Please use https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L99 here


<!-- Sent from Reviewable.io -->

2021-08-06 18:41 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt, line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgNCWgtDAh45w8GzkmQ:-MgRfDr1DVs9aXJzUoJK:bma6pu4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/eff302ad8096e68d4a35cab3f85d95f26cf26b6f/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/IntersectValidateTask.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Oh, you raise a good point -- you can't count on being able to execute a flow multiple times.

Here's my recommendation:

1. Leave the local variable
2. Make a new local variable that flattens `currentData` into a `ByteString` (by the way, please use this: https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L99)
3. Use this to create a new flow for the output: https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L139
</blockquote></details>

Done. Thanks for the link, I didn't realize there were the bytestring helper classes until you linked them and didn't spend much time looking through them. I'll review them for use going forward.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/RemoteUrlStorage.not_kt, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgNXNAx5W9giXxIekys:-MgRfdLN-W2N4eb-pfQt:b-k289po) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/87aa35b2b549588e2bdc5c45e5a02feba0eba602/src/main/kotlin/org/wfanet/panelmatch/client/storage/RemoteUrlStorage.not_kt#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

.not_kt?
</blockquote></details>

whoops, this wasn't supposed to get added in this PR, I've removed it
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/RemoteUrlStorageClient.rename_kt, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgNXPrsE6zxKk7EjTKp:-MgRfii_0Iji1_W9mocq:b-34vmyd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/87aa35b2b549588e2bdc5c45e5a02feba0eba602/src/main/kotlin/org/wfanet/panelmatch/client/storage/RemoteUrlStorageClient.rename_kt#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

.rename_kt?
</blockquote></details>

See above
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 82 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgNXUU806MjzMldXRx8:-MgRf4nn6rA9N43j8pFB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/87aa35b2b549588e2bdc5c45e5a02feba0eba602/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L82)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L99 here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-06 18:44 UTC, efoxepstein reviewed
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle)



<!-- Sent from Reviewable.io -->

2021-08-09 14:02 UTC, cs-sswaminathan reviewed
> Reviewed 6 of 14 files at r1, 1 of 9 files at r2, 1 of 6 files at r3, 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle, @kgaynor, and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt, line 20 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgfCTmt4R0lI8Evtmg6:-MgfCTmt4R0lI8Evtmg7:b-7pfp0h) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc0233ce543bf02d0a61ea6b362619f91df35c2c/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt#L20)):*
> ```Kotlin
> import com.google.protobuf.ByteString
> import kotlin.test.assertFailsWith
> import kotlinx.coroutines.CoroutineName
> ```

Should this file(and any other tests) be under exchangetasks/testing so that it is consistent with other packages


<!-- Sent from Reviewable.io -->

2021-08-09 15:21 UTC, stevenwarejones requested changes
> Reviewed 5 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 4 unresolved discussions (waiting on @jonmolle and @kgaynor)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CryptorExchangeTask.kt, line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgfTfte8hniwUwdYO49:-MgfTfte8hniwUwdYO4A:b-vw7id0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc0233ce543bf02d0a61ea6b362619f91df35c2c/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CryptorExchangeTask.kt#L46)):*
> ```Kotlin
>     val inputs = parseSerializedSharedInputs(serializedInputs)
>     val result = operation(key, inputs)
>     return mapOf(outputDataLabel to makeSerializedSharedInputFlow(result, 1024))
> ```

how was this number chosen?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt, line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgfUGPm3Qe4262mHUKY:-MgfUGPn68nsgecYJZty:bqkb4ei) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc0233ce543bf02d0a61ea6b362619f91df35c2c/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt#L27)):*
> ```Kotlin
> class InMemoryStorage(private val keyPrefix: String) : Storage {
> 
>   private val storageClient = InMemoryStorageClient(keyPrefix = keyPrefix)
> ```

do we need this file anymore? Why not just use the InMemoryStorageClient directly?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt, line 30 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgfUMftBpRSDrCD2Sdq:-MgfUMftBpRSDrCD2Sdr:b-12iob4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc0233ce543bf02d0a61ea6b362619f91df35c2c/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt#L30)):*
> ```Kotlin
> 
>   override suspend fun read(path: String): StorageClient.Blob {
>     return storageClient.getBlob(path)!!
> ```

avoid `!!`


<!-- Sent from Reviewable.io -->

2021-08-09 15:58 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 4 unresolved discussions (waiting on @cs-sswaminathan, @jonmolle, and @kgaynor)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt, line 20 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgfCTmt4R0lI8Evtmg6:-MgfbydS3KgrMgeWMkCP:b-i4k6bn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc0233ce543bf02d0a61ea6b362619f91df35c2c/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt#L20)):*
<details><summary><i>Previously, cs-sswaminathan wrote…</i></summary><blockquote>

Should this file(and any other tests) be under exchangetasks/testing so that it is consistent with other packages
</blockquote></details>

That would be quite inconsistent, actually. As I described in Slack, the rule that we follow is that we don't put libraries in `src/test`. In other words, no Bazel rule has a dependency on anything in `src/test`. However, the actual test binaries themselves do live in `src/test`. Since this file is compiled into a test binary (it is used in a `kt_jvm_test` rule in the `BUILD.bazel` file), it belongs where it is.


<!-- Sent from Reviewable.io -->

2021-08-09 17:28 UTC, cs-sswaminathan reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @jonmolle, and @kgaynor)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt, line 20 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgfCTmt4R0lI8Evtmg6:-MgfvdIO0_ZX4QUflTTh:b-pv9n7f) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc0233ce543bf02d0a61ea6b362619f91df35c2c/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

That would be quite inconsistent, actually. As I described in Slack, the rule that we follow is that we don't put libraries in `src/test`. In other words, no Bazel rule has a dependency on anything in `src/test`. However, the actual test binaries themselves do live in `src/test`. Since this file is compiled into a test binary (it is used in a `kt_jvm_test` rule in the `BUILD.bazel` file), it belongs where it is.
</blockquote></details>

I meant ```src/main/../exchangetasks/testing``` and not not ```src/test``` 


<!-- Sent from Reviewable.io -->

2021-08-09 17:30 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 4 unresolved discussions (waiting on @cs-sswaminathan, @jonmolle, and @kgaynor)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt, line 20 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgfCTmt4R0lI8Evtmg6:-MgfxaOb1SNLCQKv7SIt:bv9keee) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc0233ce543bf02d0a61ea6b362619f91df35c2c/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt#L20)):*
<details><summary><i>Previously, cs-sswaminathan wrote…</i></summary><blockquote>

I meant ```src/main/../exchangetasks/testing``` and not not ```src/test``` 
</blockquote></details>

I don't follow. The location of this file is correct because it is a unit test and it is not depended on by any other class.


<!-- Sent from Reviewable.io -->

2021-08-09 18:08 UTC, cs-sswaminathan reviewed
> Reviewed 1 of 14 files at r1, 4 of 9 files at r2, 1 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 4 unresolved discussions (waiting on @cs-sswaminathan, @jonmolle, and @kgaynor)



<!-- Sent from Reviewable.io -->

2021-08-09 18:17 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 4 unresolved discussions (waiting on @cs-sswaminathan, @kgaynor, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CryptorExchangeTask.kt, line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgfTfte8hniwUwdYO49:-Mgg4BL10RDBl-Y9sVbs:bi6loau) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc0233ce543bf02d0a61ea6b362619f91df35c2c/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CryptorExchangeTask.kt#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

how was this number chosen?
</blockquote></details>

Chosen at random, to be honest: It is the default chunk size for the cloud storage clients. I didn't intend it to be permanent and sort of added the TODO a few lines up, but I've changed it to be the default buffer size for the storage client for now.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt, line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgfUGPm3Qe4262mHUKY:-Mgg5ER89h3IlfJr8bjL:bstj0wm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc0233ce543bf02d0a61ea6b362619f91df35c2c/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do we need this file anymore? Why not just use the InMemoryStorageClient directly?
</blockquote></details>

We still use the batchRead and batchWrite in the Storage subclass. I'd also like to keep the abstraction the same as the other clients considering this is the "testing" client.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt, line 30 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgfUMftBpRSDrCD2Sdq:-Mgg5Y3j-djI98UEz4Ii:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc0233ce543bf02d0a61ea6b362619f91df35c2c/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt#L30)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

avoid `!!`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-08-09 18:18 UTC, efoxepstein approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 4 unresolved discussions (waiting on @cs-sswaminathan, @kgaynor, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-09 18:24 UTC, cs-sswaminathan approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 4 unresolved discussions (waiting on @cs-sswaminathan, @kgaynor, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-09 18:40 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 4 unresolved discussions (waiting on @cs-sswaminathan, @kgaynor, and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt, line 20 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgfCTmt4R0lI8Evtmg6:-MggCITK8knzA887C5aS:bvkufa8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc0233ce543bf02d0a61ea6b362619f91df35c2c/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't follow. The location of this file is correct because it is a unit test and it is not depended on by any other class.
</blockquote></details>

I'd prefer not to move this file in this PR and, if it turns out to be preferable to have it elsewhere, make it part of a cleanup PR.


<!-- Sent from Reviewable.io -->

2021-08-09 18:55 UTC, cs-sswaminathan approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 3 unresolved discussions (waiting on @kgaynor and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-09 20:57 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 3 unresolved discussions (waiting on @kgaynor and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-09 23:40 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 3 unresolved discussions (waiting on @kgaynor and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt, line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgfUGPm3Qe4262mHUKY:-MghH3uTAPbnPEJDtCaf:blsuh06) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc0233ce543bf02d0a61ea6b362619f91df35c2c/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt#L27)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

We still use the batchRead and batchWrite in the Storage subclass. I'd also like to keep the abstraction the same as the other clients considering this is the "testing" client.
</blockquote></details>

Can we implement `batchRead` and `batchWrite` as extension methods on `StorageClient` and then drop the `Storage` abstraction?


<!-- Sent from Reviewable.io -->

2021-08-10 16:29 UTC, jonmolle commented
@stevenwarejones did you still want further changes? I don't see anything in reviewable that hasn't been addressed.

2021-08-10 16:48 UTC, stevenwarejones requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @jonmolle, and @kgaynor)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt, line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgfUGPm3Qe4262mHUKY:-MgkxagT4wTcG6lrXjG6:bidnhlr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc0233ce543bf02d0a61ea6b362619f91df35c2c/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can we implement `batchRead` and `batchWrite` as extension methods on `StorageClient` and then drop the `Storage` abstraction?
</blockquote></details>

@efoxepstein - is this a TODO for later?


<!-- Sent from Reviewable.io -->

2021-08-10 16:58 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 1 unresolved discussion (waiting on @kgaynor and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt, line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgfUGPm3Qe4262mHUKY:-Mgkzq4r-pQ80G7hygXM:b-sw8iz4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc0233ce543bf02d0a61ea6b362619f91df35c2c/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@efoxepstein - is this a TODO for later?
</blockquote></details>

@jonmolle can you file a GitHub issue to consider dropping `Storage` in favor of extension methods on `StorageClient`?


<!-- Sent from Reviewable.io -->

2021-08-10 19:26 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 2 unresolved discussions (waiting on @jonmolle, @kgaynor, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CryptorExchangeTask.kt, line 40 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MglWeBYDm5En_FZBZma:-MglWeBYDm5En_FZBZmb:b6lxk7e) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1f8de7b7556141a4679c4bf8e4bbd49a0af472ac/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CryptorExchangeTask.kt#L40)):*
> ```Kotlin
>     logger.addToTaskLog("Executing operation: $operation")
> 
>     // TODO See how to update this to not collect the inputs entirely at this step
> ```

also, it is efficient to still compute them in batches across the jni layer.... just don't want to do too many :) - maybe add something like that in the TODO for futures to consider


<!-- Sent from Reviewable.io -->

2021-08-10 21:42 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 2 unresolved discussions (waiting on @kgaynor and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CryptorExchangeTask.kt, line 40 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MglWeBYDm5En_FZBZma:-Mgm0-c7-KDO2VWQIwBn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1f8de7b7556141a4679c4bf8e4bbd49a0af472ac/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CryptorExchangeTask.kt#L40)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

also, it is efficient to still compute them in batches across the jni layer.... just don't want to do too many :) - maybe add something like that in the TODO for futures to consider
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt, line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgfUGPm3Qe4262mHUKY:-Mglmfef4WnWlVCBdtQy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc0233ce543bf02d0a61ea6b362619f91df35c2c/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@jonmolle can you file a GitHub issue to consider dropping `Storage` in favor of extension methods on `StorageClient`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-10 21:43 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 2 unresolved discussions (waiting on @kgaynor and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-10 21:55 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 3 unresolved discussions (waiting on @jonmolle, @kgaynor, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageClient.kt, line 29 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-Mgm2arv5_lDJm5SmsFq:-Mgm2arv5_lDJm5SmsFr:b8pqhho) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/abb0a3ea7a6999e2f1db71c6c961c140783dac94/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageClient.kt#L29)):*
> ```Kotlin
>  *
>  * The optimal size is suggested by
>  * [this article](https://medium.com/@duhroach/optimal-size-of-a-cloud-storage-fetch-8c270b511016).
> ```

Random thought -- this comment doesn't make much sense because this is in-memory, not on GCS. Can you update this?


<!-- Sent from Reviewable.io -->

2021-08-10 22:34 UTC, stevenwarejones approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle and @kgaynor)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt, line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-MgfUGPm3Qe4262mHUKY:-MgmBvAU5OesXf1A-6AM:bb7p5f3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc0233ce543bf02d0a61ea6b362619f91df35c2c/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt#L27)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx.


<!-- Sent from Reviewable.io -->

2021-08-10 23:07 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @kgaynor)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageClient.kt, line 29 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75#-Mgm2arv5_lDJm5SmsFq:-MgmJQz96fdeUWyex8YX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/abb0a3ea7a6999e2f1db71c6c961c140783dac94/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageClient.kt#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Random thought -- this comment doesn't make much sense because this is in-memory, not on GCS. Can you update this?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-10 23:21 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/75)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kgaynor)



<!-- Sent from Reviewable.io -->

2021-08-10 23:31 UTC, merged