Add Model Provider Batch Lookup Creation
world-federation-of-advertisers/panel-exchange-client pull request #86
Opened 2021-08-12 15:45 UTC by stevenwarejones

An Apache Beam reference implementation that does the following:
* Inputs a set of panelist ids and join keys
* Computes hashes of that data and creates query batches
* Encrypts those sets of queries for use in oblivious query expansion
* Can also decrypt a set of encrypted query results computed by another party
For now, this uses a plaintext oblivious query builder.

2021-08-12 16:48 UTC, efoxepstein requested changes
> Reviewed 38 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86)* status: all files reviewed, 19 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgv8ZeOAIY6A1PgwuUW:-Mgv8ZeOAIY6A1PgwuUX:b-q72yfm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt#L27)):*
> ```Kotlin
> /**
>  * Implements a batch query creation engine in Apache Beam using oblivious query expansion and
>  * result decryption
> ```

A couple notes here:

1. Query expansion only happens on the EDP side. What's happening here is query compression.
2. This workflow doesn't do result decryption, right? It just generates the queries?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgv8Bp49CQ6bZgzdlsm:-Mgv8Bp49CQ6bZgzdlsn:b-n930u0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt#L33)):*
> ```Kotlin
>  * decryption
>  */
> class BatchCreationWorkflow(
> ```

Maybe put the word "Query" in the name somewhere? `CreateQueriesWorkflow`? (I kind of feel like I should remove the word Batch 
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgv8t77CWs5pqyAOgfE:-Mgv8t77CWs5pqyAOgfF:b-nh3c75) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt#L44)):*
> ```Kotlin
>    * @property numBucketsPerShard the number of buckets each shard can have
>    */
>   data class Parameters(val numShards: Int, val numBucketsPerShard: Int) : Serializable {
> ```

Do we need some parameter about how many queries per shard we need to generate, too?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgv8y0ZDfm_dI_rvOHC:-Mgv8y0ZDfm_dI_rvOHD:b-z8npra) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt#L55)):*
> ```Kotlin
>     data: PCollection<KV<PanelistKey, JoinKey>>
>   ): PCollection<EncryptQueriesResponse> {
>     val mappeddata = mapToQueryId(data)
> ```

`mappeddata` -> `mappedData`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt, line 88 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgv9OCyE22JSAQBH4vl:-Mgv9OCyE22JSAQBH4vm:bxyxp6x) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt#L88)):*
> ```Kotlin
>     return data
>       .groupByKey("Group by Shard")
>       .map {
> ```

Can you specify a name for each `map` that you use? It really helps when debugging things:

```
  .map(name = "Encrypt Queries") {
    ...
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/Bucketing.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvA01l3l7X4OSBcIrL:-MgvA01l3l7X4OSBcIrM:bz1qh6u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/Bucketing.kt#L28)):*
> ```Kotlin
> 
>   /** Returns the hashed [ShardId] and [BucketId] for a [JoinKey]. */
>   fun apply(joinKey: JoinKey): Pair<ShardId, BucketId> {
> ```

How do you feel about naming this `hashAndApply` to make it super clear what it's doing?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/Bucketing.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgv9jd72b8pi_EwTT1b:-Mgv9jd72b8pi_EwTT1c:b-vpocr5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/Bucketing.kt#L31)):*
> ```Kotlin
>     val hashedValue: Long =
>       hashSha256ToSpace(joinKey.key, numShards.toLong() * numBucketsPerShard.toLong())
>     return shard(hashedValue) to bucket(hashedValue)
> ```

Maybe here just `return apply(hashedValue)`?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvAVdR-xhNdRf8fYpa:-MgvAVdR-xhNdRf8fYpb:b-m2a857) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt#L26)):*
> ```Kotlin
>    * Generates a unique [QueryId], optionally, based on the [PanelistKey]. For privacy, reasons, it
>    * should not be easy to reverse the process. Some options:
>    * 1. Hash the [PanelistKey] using a secret salt
> ```

Is there any reason to prefer (1)?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvAa-i6nH1uBh5Rdzg:-MgvAa-i6nH1uBh5Rdzh:b74ex2o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt#L29)):*
> ```Kotlin
>    * 2. Return a UUID independent of [PanelistKey] and store the mapping
>    */
>   fun queryIdGenerator(panelistKey: PanelistKey): QueryId {
> ```

Does this need to be part of the interface or can we just have it be a standalone function?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvACDn5HEB8h1VdPyv:-MgvACDoDgScC2kR0z7W:bhbe7be) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt#L30)):*
> ```Kotlin
>    */
>   fun queryIdGenerator(panelistKey: PanelistKey): QueryId {
>     return queryIdOf(randomUUID().getLeastSignificantBits().toInt())
> ```

How bad is it if these collide? Would it be better to just use a Long instead of an Int within QueryId?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/Protos.kt, line 76 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvAkVp7oRBeT7driaI:-MgvAkVp7oRBeT7driaJ:bh15h1d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/Protos.kt#L76)):*
> ```Kotlin
> 
> /** Constructs a [UnencryptedQuery]. */
> fun unencryptedQueryOf(shardId: ShardId, bucketId: BucketId, queryId: QueryId): UnencryptedQuery =
> ```

Can you put this next to the other `unencryptedQuery [...]

2021-08-12 19:14 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86)* status: all files reviewed, 21 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgv8ZeOAIY6A1PgwuUW:-MgvSzPrBr5iqyuFQjVB:bp4grmv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

A couple notes here:

1. Query expansion only happens on the EDP side. What's happening here is query compression.
2. This workflow doesn't do result decryption, right? It just generates the queries?
</blockquote></details>

1. Clarified the comment. lmk if its more clear now.
2. Correct. Should it? I wasn't sure if the decrypt library would lend itself to map reduce, but I guess the data is too large to not to. How do I know what ciphertexts I can batch at one time?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgv8Bp49CQ6bZgzdlsm:-MgvUthS0WqQXvg_oBws:b9z69qe) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe put the word "Query" in the name somewhere? `CreateQueriesWorkflow`? (I kind of feel like I should remove the word Batch 
</blockquote></details>

do you think I should move this out of `batchlookup` directory? I'm not sure the word batch is communicating the right thing, in general, then for both `BatchLookupWorklow` then either. Both the lookup and the query creation are done in batches by shard.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgv8t77CWs5pqyAOgfE:-MgvTIR0513pcQ_mgHYj:b-msfj6c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt#L44)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Do we need some parameter about how many queries per shard we need to generate, too?
</blockquote></details>

I was going to add that in a follow up PR hooking in private-membership. Does that work?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgv8y0ZDfm_dI_rvOHC:-MgvV2VL3nhNOLPVr0qZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`mappeddata` -> `mappedData`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt, line 88 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgv9OCyE22JSAQBH4vl:-MgvVQJzBqzJfqTfbuFy:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt#L88)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you specify a name for each `map` that you use? It really helps when debugging things:

```
  .map(name = "Encrypt Queries") {
    ...
```
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/Bucketing.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvA01l3l7X4OSBcIrL:-MgvWIhb74f0V1psgBm3:bb7oryy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/Bucketing.kt#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How do you feel about naming this `hashAndApply` to make it super clear what it's doing?
</blockquote></details>

sure
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/Bucketing.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgv9jd72b8pi_EwTT1b:-MgvWmDS3_h9WfQwS3d2:bjtm9te) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/Bucketing.kt#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe here just `return apply(hashedValue)`?
</blockquote></details>

works for me
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvAVdR-xhNdRf8fYpa:-MgvWsfC1DwOnSUUOYIx:bn2yutw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is there any reason to prefer (1)?
</blockquote></details>

I think the only reason I thought of is you don't need to store a UUID to panelistKey mapping since you can determine it later deterministically. But thats a good reason imo.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvAa-i6nH1uBh5Rdzg:-MgvX2296ErlrYCoGGft:b-noeka9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Does this need to be part of the interface or can we just have it be a standalone function?
</blockquote></details>

probably shouldn't be part of the interface. I wasn't sure best practices here like registering it as a function in beam. Do you suggest registering a function? I can deal with that as part of this PR or add a TODO.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvACDn5HEB8h1VdPyv:-MgvXZa93S2PWJdH4pjE:bwkvxii) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt#L30)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How bad is it if these collide? Would it be better to just use a Long instead of an Int within QueryId?
</blockquote></details>

yes. good call out. I saw a [...]

2021-08-12 19:26 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86)* status: 25 of 41 files reviewed, 21 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/JniQueryEvaluator.kt, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvlmMX94Cks7Qc4zwz:-MgvmmCC1xUz0WScop9N:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/56c0801dfaf760af00f15c542aab418aa2324804/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/JniQueryEvaluator.kt#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you write: `private const val SWIG_BASE = Paths.get("panel_exchange_client", "src", "main", ...)` instead? 
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/JniQueryEvaluator.kt, line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgvm1xDC5GQlP1Y_Ao-:-MgvmSVL8J8kIyxHH1Mg:bbnl8sv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/56c0801dfaf760af00f15c542aab418aa2324804/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/JniQueryEvaluator.kt#L66)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

And here: `SWIG_BASE.resolve("client").resolve("batchlookup").resolve("queryevaluator")`
</blockquote></details>

done.

also, one thing to note is that swig complains if there is more than one swig file per directory. Not sure if you noticed that I moved the two batchlookup swig files into subdirectories.


<!-- Sent from Reviewable.io -->

2021-08-12 20:02 UTC, efoxepstein requested changes
> Reviewed 16 of 16 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86)* status: all files reviewed, 13 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvAa-i6nH1uBh5Rdzg:-Mgvo_L033d1RnJ6RHJV:b4jti58) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

probably shouldn't be part of the interface. I wasn't sure best practices here like registering it as a function in beam. Do you suggest registering a function? I can deal with that as part of this PR or add a TODO.
</blockquote></details>

I'm not sure what you mean by registering a function -- as long as it's serializable then Beam can work with it. Normal functions are. If you use an interface to allow dependency-injecting in a queryIdGenerator, just make the interface serializable
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvACDn5HEB8h1VdPyv:-Mgvp6yA5fu-iCCWrtRC:bl86e4n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt#L30)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yes. good call out. I saw a pdf that claims for 30k entries, the odds of collision in 32 bit space are 1 in 10 and in 64 bit space 1 in 2 billion. Changing to a long.
</blockquote></details>

If you want a zero chance of collision, we can just use the whole 128 bits too
___
*[src/main/kotlin/org/wfanet/panelmatch/common/crypto/Hashing.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvBd1U1BJ_IJ_8XV28:-Mgvsg0X4GMhBAovE81Y:bn9fyqu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/common/crypto/Hashing.kt#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should be (assuming both parties are little endian, which I thought to add in but forgot). Haven't dealt with endian problems in long enough I was hoping to forget.

However, I think keeping them separate might introduce bugs in the future. I see two options:
1. I update my code to reverse the bits based on endianness. I then write tests to make sure we get the same results using the java and c++ libs.
2. Update this to that function for consistency.  If we're going to cross JNI for this, I should batch process them. If so, should I just batch update them all at once or do one at a time. Simplest code change is to just do them one at a time in the map reduce but maybe we shouldn't do it that way for consistency.

</blockquote></details>

Your call
___
*[src/main/proto/wfa/panelmatch/client/batchlookup/query.proto, line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgvt4Ha9sps0J-kCAdm:-Mgvt4Ha9sps0J-kCAdn:b-mrh7z9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/46727b28e1214fe73ebe4c594c780c6de94d0982/src/main/proto/wfa/panelmatch/client/batchlookup/query.proto#L35)):*
> ```protobuf
> // 2 billion.
> message QueryId {
>   int64 id = 1;
> ```

fixed64 please if we expect these to be large numbers
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvE39x925ik-RKyIQU:-MgvtA9d6f3goUZJW4dO:b-dfeinj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L52)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

done. Is this just to save a line of code or are there other advantages?
</blockquote></details>

`new` is almost always to be avoided -- it always makes it harder to reason about memory safety
___
*[src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/BUILD.bazel, line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgvteny6Dha6P-f9zHD:-Mgvtenz6znJJZmC0fv0:b-873wbi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/46727b28e1214fe73ebe4c594c780c6de94d0982/src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/BUILD.bazel#L35)):*
> ```Starlark
> 
> kt_jvm_test(
>     name = "BatchCreationWorkflowTest",
> ```

Update name?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/BUILD.bazel, line 37 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvtgSG8FANXry02eio:-MgvtgSG8FANXry02eip:b-873wbi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/46727b28e1214fe73ebe4c594c780c6de94d0982/src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/BUILD.bazel#L37)):*
> ```Starlark
>     name = "BatchCreationWorkflowTest",
>     srcs = ["CreateQueriesWorkflowTest.kt"],
>     test_class = "org.wfanet.panelmatch.client.batchlookup.BatchCreationWorkflowTest",
> ```

Update name?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/testing/PlaintextObliviousQueryBuilderTest.kt, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvFhSp4XVSWCNGoBGS:-Mgvusym85IXPDKLTi5t:b-94z9ci) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/testing/PlaintextObliviousQueryBuilderTest.kt#L59)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

These were just some random outputs of your queryEvaluator. The numbers just need to be unique.
</blockquote></details>

Do you mind picking smaller numbers then? It's hard to see that they're unique
___
*[src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/testing/PlaintextObliviousQueryBuilderTest.kt, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvFlIh08wHKGNQMMh0:-MgvweVG7_jwmapNHFB0:b-ose39d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/testing/PlaintextObliviousQueryBuilderTest.kt#L75)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

no. I don't exactly like `.containsAtLeastElementsIn` but I don't think it supports `containsInAnyOrder` right?
</blockquote></details>

All container matchers are unordered. You need to specify `.inOrder()` to care about order:

```
assertThat(foo).containsExactlyElementsIn(bar)  // unordered
assertThat(foo).containsExactlyElementsIn(bar).inOrder()  // ordered
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgv8ZeOAIY6A1PgwuUW:-MgvnGdL4eLwvN65tcm5:b-i4aphv) ([raw file](https://github.com/world-federation-of-adverti [...]

2021-08-12 20:22 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86)* status: all files reviewed, 13 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvAa-i6nH1uBh5Rdzg:-MgvzLYJ5CXoGV2Yhv_U:bpdb678) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm not sure what you mean by registering a function -- as long as it's serializable then Beam can work with it. Normal functions are. If you use an interface to allow dependency-injecting in a queryIdGenerator, just make the interface serializable
</blockquote></details>

I earlier tried injecting a lambda into the constructor which doesn't work. Should I make a new interface for queryIdGenerator?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvACDn5HEB8h1VdPyv:-MgvzZfc5Y_3SAy0kkc4:bcc9x9x) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt#L30)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

If you want a zero chance of collision, we can just use the whole 128 bits too
</blockquote></details>

I'm happy with Long. but lmk.
___
*[src/main/proto/wfa/panelmatch/client/batchlookup/query.proto, line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgvt4Ha9sps0J-kCAdm:-Mgw-3xe-Meo31-5ogBI:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/46727b28e1214fe73ebe4c594c780c6de94d0982/src/main/proto/wfa/panelmatch/client/batchlookup/query.proto#L35)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

fixed64 please if we expect these to be large numbers
</blockquote></details>

done
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvE39x925ik-RKyIQU:-Mgw-6qxDVJ8r3mFhLiZ:by4bx31) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L52)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`new` is almost always to be avoided -- it always makes it harder to reason about memory safety
</blockquote></details>

thx for the clarification
___
*[src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/BUILD.bazel, line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgvteny6Dha6P-f9zHD:-Mgw-MPv5DjXT4NNaB5z:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/46727b28e1214fe73ebe4c594c780c6de94d0982/src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/BUILD.bazel#L35)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Update name?
</blockquote></details>

done
___
*[src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/BUILD.bazel, line 37 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvtgSG8FANXry02eio:-Mgw-MzhEZeYCIt3erRy:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/46727b28e1214fe73ebe4c594c780c6de94d0982/src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/BUILD.bazel#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Update name?
</blockquote></details>

done
___
*[src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/testing/PlaintextObliviousQueryBuilderTest.kt, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvFhSp4XVSWCNGoBGS:-Mgw05LkAptw_q_BGWnN:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/testing/PlaintextObliviousQueryBuilderTest.kt#L59)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Do you mind picking smaller numbers then? It's hard to see that they're unique
</blockquote></details>

done
___
*[src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/testing/PlaintextObliviousQueryBuilderTest.kt, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvFlIh08wHKGNQMMh0:-Mgw-Zy21O7p4oP_t75k:bypug18) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/testing/PlaintextObliviousQueryBuilderTest.kt#L75)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

All container matchers are unordered. You need to specify `.inOrder()` to care about order:

```
assertThat(foo).containsExactlyElementsIn(bar)  // unordered
assertThat(foo).containsExactlyElementsIn(bar).inOrder()  // ordered
```
</blockquote></details>

thanks for the clarification
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgv8ZeOAIY6A1PgwuUW:-Mgvxb198qciUZyJ-EXu:b-vevovd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

1. Good
2. Do decryption elsewhere (in another Apache Beam or not)
</blockquote></details>

2. Thats not exactly my question. You answered it on slack. I will put in a separate beam pipeline in a follow-up PR. I already updated the description earlier today with what will be in follow-up PRs. Lmk if that all makes sense.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/CreateQueriesWorkflow.kt, line 76 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgvo4UGDzDfULpoVsog:-MgvzERY0Q3fTe0CMnle:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/46727b28e1214fe73ebe4c594c780c6de94d0982/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/CreateQueriesWorkflow.kt#L76)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

You might want to consider slightly shorter names -- it should improve how user interfaces display the steps. For example, here I'd write just "Map to UnencryptedQueries"
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/CreateQueriesWorkflow.kt, line 88 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgvo2b04N46myzW9Keb:-MgvzGMP5ew9VxyNsuml:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/46727b28e1214fe73ebe4c594c780c6de94d0982/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/CreateQueriesWorkflow.kt# [...]

2021-08-12 22:52 UTC, efoxepstein requested changes
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvAa-i6nH1uBh5Rdzg:-MgwXjokA7N2O8dDXTiP:b9oel2w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I earlier tried injecting a lambda into the constructor which doesn't work. Should I make a new interface for queryIdGenerator?
</blockquote></details>

A new interface is fine or use `SerializableFunction<PanelistKey, QueryId>`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvACDn5HEB8h1VdPyv:-MgwXuRtEW5XZwFHgxMX:b-hxiohq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt#L30)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm happy with Long. but lmk.
</blockquote></details>

Remind me why we aren't just picking sequential ids? Since this happens on "small data" (before doing any heavy crypto that expands the data massively), it should be pretty feasible. The lazy way to do it is something like: `queries.keyBy { 1 }.groupByKey().parDo { kv -> emitAll(kv.value.asSequence().mapIndexed { i, v -> kvOf(queryIdOf(i), v) }) }` -- this'll happen in a single process but there aren't too too many queries, right?


<!-- Sent from Reviewable.io -->

2021-08-14 03:53 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86)* status: 9 of 58 files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflowTest.kt, line 69 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mh1lwlLEV-_49vyA5Pg:-Mh1lwlLEV-_49vyA5Ph:bmx61pa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a6445ca7429526697d3fbcf415420670b5a82f2d/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflowTest.kt#L69)):*
> ```Kotlin
>           yield(it.value.asSequence().map { it.value.id to it.key.id }.toMap())
>         }
>         .apply(View.asSingleton())
> ```

@efoxepstein - I need some help here. Let me know if how I'm doing it is what you recommend plus I have an error I can't figure out.
I'm turning this into a PCollectionView so I can do a parDoWithSideInput below and use it as a map to check to make sure panelist keys line up with expected results.
However, I get the following error
```
java.lang.IllegalStateException: Unable to return a default Coder for ParDo2/ParMultiDo(Anonymous).output...
Cannot provide coder for parameterized type java.util.Map<java.lang.Integer, ? extends java.lang.Long>
```
I spent a while looking into `TypeDescriptors` to fix this (probably too long), but couldn't figure it out.

If you could help me figure out how to write this test to check against both sets of returned PCollections, that would be super helpful.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgv8Bp49CQ6bZgzdlsm:-Mgzk4xyB4wbRCiggD8N:b-r1mvdj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchCreationWorkflow.kt#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe we want to rename all `BatchLookup` stuff to `PrivateMembership`? It's the term we use at Google for this twist on Private Information Retrieval (which has fewer privacy guarantees)

But originally, I was using the term `batch` to be synonymous with the Map-Reduce paradigm of computation (in contrast to e.g. a client-server model with separate individual requests)
</blockquote></details>

renamed `batchlookup` to `privatemembership` and `BatchLookupWorkflow.kt` to `EvaluateQueriesWorkflow.kt`. Hopefully, that works for you. We could also refer to them as `....BatchWorkflow`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvAa-i6nH1uBh5Rdzg:-Mgzpvze0G4RtWoKf9ie:b-4wqs0n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

A new interface is fine or use `SerializableFunction<PanelistKey, QueryId>`
</blockquote></details>

I think this item is nullified by the next item.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvACDn5HEB8h1VdPyv:-MgzjaEFBpW51t1sE0W-:b5rvh2p) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/ObliviousQueryBuilder.kt#L30)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Remind me why we aren't just picking sequential ids? Since this happens on "small data" (before doing any heavy crypto that expands the data massively), it should be pretty feasible. The lazy way to do it is something like: `queries.keyBy { 1 }.groupByKey().parDo { kv -> emitAll(kv.value.asSequence().mapIndexed { i, v -> kvOf(queryIdOf(i), v) }) }` -- this'll happen in a single process but there aren't too too many queries, right?
</blockquote></details>

If we're going to do it that way, we could do it just as a simple data prep function. However, in the spirit of keeping everything in the same flow, I've gone ahead with your suggestion.

The underlying library doesn't support Long so I reverted this change back to int32: https://github.com/google/private-membership/blob/main/private_membership/rlwe/batch/cpp/shared.proto#L89
___
*[src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/CreateQueriesWorkflowTest.kt, line 92 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mgvu0o40m444CTVP5Xe:-Mgzg9-v4vAG8jURXKVl:b-f75na) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/46727b28e1214fe73ebe4c594c780c6de94d0982/src/test/kotlin/org/wfanet/panelmatch/client/batchlookup/CreateQueriesWorkflowTest.kt#L92)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Do these need to be vals? Should this class be Serializable? How about:

```
data class ShardedQuery(val shardId: ShardId, val queryId: QueryId, val bucketId: BucketId) : Serializable {
  constructor(shard: Int, query: Int, bucketId: Int) ...
}
```
</blockquote></details>

changed to vals. I don't think this needs to be made serializable since its just used in this test class.


<!-- Sent from Reviewable.io -->

2021-08-14 19:49 UTC, efoxepstein requested changes
> Reviewed 49 of 49 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflowTest.kt, line 69 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mh1lwlLEV-_49vyA5Pg:-Mh5CVRy5tp-o2I1oih4:b169wo6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a6445ca7429526697d3fbcf415420670b5a82f2d/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflowTest.kt#L69)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@efoxepstein - I need some help here. Let me know if how I'm doing it is what you recommend plus I have an error I can't figure out.
I'm turning this into a PCollectionView so I can do a parDoWithSideInput below and use it as a map to check to make sure panelist keys line up with expected results.
However, I get the following error
```
java.lang.IllegalStateException: Unable to return a default Coder for ParDo2/ParMultiDo(Anonymous).output...
Cannot provide coder for parameterized type java.util.Map<java.lang.Integer, ? extends java.lang.Long>
```
I spent a while looking into `TypeDescriptors` to fix this (probably too long), but couldn't figure it out.

If you could help me figure out how to write this test to check against both sets of returned PCollections, that would be super helpful.
</blockquote></details>

Can you use `.join`?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 71 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mh5B1_o-P_J_IrZ5x23:-Mh5B1_o-P_J_IrZ5x24:b-qpiar3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a6445ca7429526697d3fbcf415420670b5a82f2d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L71)):*
> ```Kotlin
>         .value
>         .asSequence()
>         .shuffled()
> ```

Alas, this will require loading the whole set into memory -- probably fine but the theoretician in me wants to solve this in a streaming way. Can you just add a TODO here to consider generating a random permutation lazily instead of shuffling and using mapIndexed?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 76 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mh5BTgB7lTaFgA2MdHo:-Mh5BTgB7lTaFgA2MdHp:b-j31452) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a6445ca7429526697d3fbcf415420670b5a82f2d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L76)):*
> ```Kotlin
>         }
>         .asSequence()
>         .forEach { yield(it) }
> ```

More efficient: `.also { yieldAll(it) }`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniObliviousQueryBuilder.kt, line 52 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mh5Bh5Z1-4aGCbjFeEN:-Mh5Bh5Z1-4aGCbjFeEO:b-tcbz2g) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a6445ca7429526697d3fbcf415420670b5a82f2d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniObliviousQueryBuilder.kt#L52)):*
> ```Kotlin
> 
>     init {
>       val SWIG_PATH =
> ```

While you're here: this should be private


<!-- Sent from Reviewable.io -->

2021-08-17 16:50 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/crypto/Hashing.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvBd1U1BJ_IJ_8XV28:-MhJy2lb74rV8rvgLUGC:bmfsdsk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/common/crypto/Hashing.kt#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Your call
</blockquote></details>

So, I thought about this and I think I should just make it batching using the C++ underlying functions. I can either make that a precursor PR or a follow-up later this week. I'm okay with either. lmk what you prefer. Depends on if you're okay with merging as is with a TODO or not.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 71 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mh5B1_o-P_J_IrZ5x23:-MhACe7Q6NNopnNqeqvL:b-fgb2gy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a6445ca7429526697d3fbcf415420670b5a82f2d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L71)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Alas, this will require loading the whole set into memory -- probably fine but the theoretician in me wants to solve this in a streaming way. Can you just add a TODO here to consider generating a random permutation lazily instead of shuffling and using mapIndexed?
</blockquote></details>

i think if we want streaming, we need a random hash. 1 in 2 billion isn't bad for a 64 bit space. I'll add a TODO for now.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 76 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mh5BTgB7lTaFgA2MdHo:-MhJzhxOC7HWotZiQD0n:b-kb55vj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a6445ca7429526697d3fbcf415420670b5a82f2d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L76)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

More efficient: `.also { yieldAll(it) }`
</blockquote></details>

this was refactored. See PlaintextPrivateMembershipCryptorHelper.kt for the update
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniObliviousQueryBuilder.kt, line 52 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mh5Bh5Z1-4aGCbjFeEN:-MhJyOe13jQ4leRPejiE:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a6445ca7429526697d3fbcf415420670b5a82f2d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniObliviousQueryBuilder.kt#L52)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

While you're here: this should be private
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-08-17 17:42 UTC, efoxepstein requested changes
> Reviewed 13 of 13 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86)* status: all files reviewed, 9 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt, line 59 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKBPdY7BADHT0WHSxE:-MhKBPdY7BADHT0WHSxF:b-janr2l) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67a6d1cbf91820d4a5391c78d887e8ea6ed88b39/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt#L59)):*
> ```Kotlin
>           .map { decodeQueryBundle(it) }
>           .flatten()
>           .asSequence()
> ```

Move `asSequence()` up as high as possible? It's kind of arbitrarily in the middle here
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt, line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKBmB5EyaDAeR6FKpM:-MhKBmB5EyaDAeR6FKpN:b5d1g0o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67a6d1cbf91820d4a5391c78d887e8ea6ed88b39/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt#L33)):*
> ```Kotlin
> interface PrivateMembershipCryptorHelper : Serializable {
> 
>   fun decodeEncryptedQuery(
> ```

KDoc please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt, line 37 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKBdcU9eyT43yxHWoO:-MhKBdcU9eyT43yxHWoP:bjp1t1n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67a6d1cbf91820d4a5391c78d887e8ea6ed88b39/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt#L37)):*
> ```Kotlin
>   ): PCollection<KV<QueryId, ShardedQuery>>
> 
>   fun getPanelistQueries(
> ```

Does this need to be overwritten by subclasses? If not, can it just be a free function?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt, line 55 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKBp7s-FeooSOou1Vc:-MhKBp7s-FeooSOou1Vd:b-18vzsb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67a6d1cbf91820d4a5391c78d887e8ea6ed88b39/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt#L55)):*
> ```Kotlin
> }
> 
> data class ShardedQuery(private val shard: Int, private val query: Int, private val bucket: Int) :
> ```

Ditto my last comment about this -- there's no need to store shard, query, and bucket as fields since they're totally inaccessible.

```
data class ShardedQuery(val shardId: ShardId, ...) {
  constructor(shard: Int, ...)
}
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt, line 62 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKBzhzAgruQtEbHhWW:-MhKBzhzAgruQtEbHhWX:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67a6d1cbf91820d4a5391c78d887e8ea6ed88b39/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt#L62)):*
> ```Kotlin
> }
> 
> data class PanelistQuery(
> ```

Ditto
___
*[src/main/kotlin/org/wfanet/panelmatch/common/crypto/Hashing.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvBd1U1BJ_IJ_8XV28:-MhKCB9z4Gc-yQJzqhwE:b-jyukd2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/common/crypto/Hashing.kt#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

So, I thought about this and I think I should just make it batching using the C++ underlying functions. I can either make that a precursor PR or a follow-up later this week. I'm okay with either. lmk what you prefer. Depends on if you're okay with merging as is with a TODO or not.
</blockquote></details>

It's fine as a TODO in this
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 71 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mh5B1_o-P_J_IrZ5x23:-MhK7mlYDdqTrs1gzoam:bipswwp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a6445ca7429526697d3fbcf415420670b5a82f2d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L71)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i think if we want streaming, we need a random hash. 1 in 2 billion isn't bad for a 64 bit space. I'll add a TODO for now.
</blockquote></details>

A simple, streaming way to get a dense range:

```
val ids = iterator {
  val seen = BitSet()
  while (seen.cardinality() < maxSize) {
    val id = GenerateRandomInt(0, maxSize)
    if (!seen.get(id)) {
      seen.set(id)
      yield(id)
    }
  }
}
```

Of course this gets into trouble as `seen` gets dense, but that's easy to fix: just switch over to sampling from an `unseen` set once `seen` gets sufficiently dense (probably 96% full).
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 76 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mh5BTgB7lTaFgA2MdHo:-MhKAfThElJsbxLxGwO2:b-y5efj2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a6445ca7429526697d3fbcf415420670b5a82f2d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L76)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this was refactored. See PlaintextPrivateMembershipCryptorHelper.kt for the update
</blockquote></details>

How was this refactored? I see see `.forEach { yield(id) }`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/PrivateMembershipCryptor.kt, line 19 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKB5T31cNd5enwJCWx:-MhKB5T31cNd5enwJCWy:bj2h5hm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67a6d1cbf91820d4a5391c78d887e8ea6ed88b39/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/PrivateMembershipCryptor.kt#L19)):*
> ```Kotlin
> import java.io.Serializable
> 
> /** Provides oblvious query compression encryption for us in private information retrieval */
> ```

typo in "oblivious" and "use"


<!-- Sent from Reviewable.io -->

2021-08-17 19:49 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86)* status: all files reviewed, 9 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt, line 59 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKBPdY7BADHT0WHSxE:-MhKIcj8CqD0dJ4PYkUy:b-gqyzjm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67a6d1cbf91820d4a5391c78d887e8ea6ed88b39/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt#L59)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Move `asSequence()` up as high as possible? It's kind of arbitrarily in the middle here
</blockquote></details>

moved up. why should it be as high as possible?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt, line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKBmB5EyaDAeR6FKpM:-MhKJADI96QbEaZqhkfF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67a6d1cbf91820d4a5391c78d887e8ea6ed88b39/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

KDoc please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt, line 37 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKBdcU9eyT43yxHWoO:-MhKIlbI9tdHhRPd9lzb:b9t8ku6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67a6d1cbf91820d4a5391c78d887e8ea6ed88b39/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Does this need to be overwritten by subclasses? If not, can it just be a free function?
</blockquote></details>

I had originally was thinking it wouldn't but obviously as coded does not need to be. Moved it out of this class to the test.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt, line 55 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKBp7s-FeooSOou1Vc:-MhKNgPF-DaGzvZf85-f:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67a6d1cbf91820d4a5391c78d887e8ea6ed88b39/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto my last comment about this -- there's no need to store shard, query, and bucket as fields since they're totally inaccessible.

```
data class ShardedQuery(val shardId: ShardId, ...) {
  constructor(shard: Int, ...)
}
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt, line 62 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKBzhzAgruQtEbHhWW:-MhKNgrZ1yzyid-XaRJB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67a6d1cbf91820d4a5391c78d887e8ea6ed88b39/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/crypto/Hashing.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MgvBd1U1BJ_IJ_8XV28:-MhKJfYcECH00isyikkj:bw5tla2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c4419b611d1762c83103a0850f203778978cb58/src/main/kotlin/org/wfanet/panelmatch/common/crypto/Hashing.kt#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's fine as a TODO in this
</blockquote></details>

added the TODO
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 71 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mh5B1_o-P_J_IrZ5x23:-MhKd5GA9vGgwtaSAx4v:bteyit4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a6445ca7429526697d3fbcf415420670b5a82f2d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L71)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

A simple, streaming way to get a dense range:

```
val ids = iterator {
  val seen = BitSet()
  while (seen.cardinality() < maxSize) {
    val id = GenerateRandomInt(0, maxSize)
    if (!seen.get(id)) {
      seen.set(id)
      yield(id)
    }
  }
}
```

Of course this gets into trouble as `seen` gets dense, but that's easy to fix: just switch over to sampling from an `unseen` set once `seen` gets sufficiently dense (probably 96% full).
</blockquote></details>

Redid this using your iterator.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 76 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mh5BTgB7lTaFgA2MdHo:-MhKIHPVCuAGAJ8s7IOf:b-qmgksc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a6445ca7429526697d3fbcf415420670b5a82f2d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L76)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How was this refactored? I see see `.forEach { yield(id) }`
</blockquote></details>

yes. I got this mixed up with a different piece of similar code. done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/PrivateMembershipCryptor.kt, line 19 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKB5T31cNd5enwJCWx:-MhKIWnp7vorCdwJDr85:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67a6d1cbf91820d4a5391c78d887e8ea6ed88b39/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/PrivateMembershipCryptor.kt#L19)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

typo in "oblivious" and "use"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-17 20:53 UTC, efoxepstein requested changes
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86)* status: all files reviewed, 6 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesWorkflowTest.kt, line 65 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKrNwJ02AondIccygb:-MhKrNwJ02AondIccygc:b-uwycvn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0e8995c8c929b03308306937e689a72d0fa21c62/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesWorkflowTest.kt#L65)):*
> ```Kotlin
>     return panelistKeyQueryId.join(decryptedQueries) {
>       key: QueryId,
>       lefts: Iterable<PanelistKey>,
> ```

Maybe name `lefts` and `rights` `panelistKeys` and `shardedQueries` instead?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt, line 59 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKBPdY7BADHT0WHSxE:-MhKrXem5M719KjaxQTQ:bq0e5e) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67a6d1cbf91820d4a5391c78d887e8ea6ed88b39/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt#L59)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

moved up. why should it be as high as possible?
</blockquote></details>

Sequences are lazy, whereas operations over lists are not. In practice, this will mean that it will parse and decode each query bundle before moving onto the next one -- which should end up being more efficient. This is more obvious when there are filter operations.

Of course, it doesn't really matter here in a test helper, but it would be consistent with other code. The most important thing is just that it's not in an arbitrary position. If there is an `asSequence` it should most likely be the first or last thing in the chain.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt, line 58 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKsiSxAIr6t0wkciv7:-MhKsiSxAIr6t0wkciv8:b8mo31f) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0e8995c8c929b03308306937e689a72d0fa21c62/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt#L58)):*
> ```Kotlin
>           .asSequence()
>           .map { QueryBundle.parseFrom(it) }
>           .map { decodeQueryBundle(it) }
> ```

does `.flatMap` work instead of `.map -> .flatten`?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 71 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mh5B1_o-P_J_IrZ5x23:-MhKq0_y21yIQMgHvxYd:bpggkw8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a6445ca7429526697d3fbcf415420670b5a82f2d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L71)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Redid this using your iterator.
</blockquote></details>

Looks good to me -- except that this could take up something like Int.MAX_VALUE / 8 = 268 MiB (since I don't think the implementation is guaranteed to exploit sparsity). Ideally `maxSize` would be something like `totalNumberOfQueries * 2`. 
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 51 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKphN1AcgqtGBNDmcm:-MhKphN1AcgqtGBNDmcn:b4riyji) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0e8995c8c929b03308306937e689a72d0fa21c62/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L51)):*
> ```Kotlin
>    * number of queries. TODO: Implement this property
>    */
>   data class Parameters(val numShards: Int, val numBucketsPerShard: Int, val padQueries: Boolean) :
> ```

This should probably be something like an `Int?` to indicate how many queries there should be for a shard (where null indicates no padding/truncation)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 95 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKr6-N7NpiPOvS4V06:-MhKr6-N7NpiPOvS4V07:bjbmdms) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0e8995c8c929b03308306937e689a72d0fa21c62/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L95)):*
> ```Kotlin
>         .asSequence()
>         .mapIndexed { index, kv ->
>           if (index > maxSize) throw Exception("Too many queries")
> ```

Maybe just `check(index < maxSize) { ... }`?


<!-- Sent from Reviewable.io -->

2021-08-17 21:12 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesWorkflowTest.kt, line 65 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKrNwJ02AondIccygb:-MhKwWd89KPyBNrdszCu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0e8995c8c929b03308306937e689a72d0fa21c62/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesWorkflowTest.kt#L65)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe name `lefts` and `rights` `panelistKeys` and `shardedQueries` instead?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt, line 59 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKBPdY7BADHT0WHSxE:-MhKw159BWh5lnqJncpw:bb7p5eq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/67a6d1cbf91820d4a5391c78d887e8ea6ed88b39/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt#L59)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Sequences are lazy, whereas operations over lists are not. In practice, this will mean that it will parse and decode each query bundle before moving onto the next one -- which should end up being more efficient. This is more obvious when there are filter operations.

Of course, it doesn't really matter here in a test helper, but it would be consistent with other code. The most important thing is just that it's not in an arbitrary position. If there is an `asSequence` it should most likely be the first or last thing in the chain.
</blockquote></details>

thx!
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt, line 58 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKsiSxAIr6t0wkciv7:-MhKwfF5BPKLtRjAbCha:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0e8995c8c929b03308306937e689a72d0fa21c62/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt#L58)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

does `.flatMap` work instead of `.map -> .flatten`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 71 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mh5B1_o-P_J_IrZ5x23:-MhKtfxz1IUAf5kdPuW8:b-st00vl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a6445ca7429526697d3fbcf415420670b5a82f2d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L71)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Looks good to me -- except that this could take up something like Int.MAX_VALUE / 8 = 268 MiB (since I don't think the implementation is guaranteed to exploit sparsity). Ideally `maxSize` would be something like `totalNumberOfQueries * 2`. 
</blockquote></details>

done, but what is the best way to make an iterator that only generates as needed?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 51 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKphN1AcgqtGBNDmcm:-MhKvj4Z53zXuzO4CQI8:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0e8995c8c929b03308306937e689a72d0fa21c62/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L51)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This should probably be something like an `Int?` to indicate how many queries there should be for a shard (where null indicates no padding/truncation)
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 95 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKr6-N7NpiPOvS4V06:-MhKutHt1DTMbtrS-CVz:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0e8995c8c929b03308306937e689a72d0fa21c62/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L95)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe just `check(index < maxSize) { ... }`?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-08-17 21:54 UTC, efoxepstein approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt, line 58 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKsiSxAIr6t0wkciv7:-MhL5xPF5CsvJ3N2LBFq:b-8ttciq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0e8995c8c929b03308306937e689a72d0fa21c62/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt#L58)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove commented-out flatten please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 71 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mh5B1_o-P_J_IrZ5x23:-MhL5D_U6k9ktZkeUyfz:b-izbbvc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a6445ca7429526697d3fbcf415420670b5a82f2d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L71)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

done, but what is the best way to make an iterator that only generates as needed?
</blockquote></details>

Normally the total number of queries will just be `parameters.numShards * parameters.totalQueriesPerShard` -- if you just make that required, then that's true.

In the event that it's not, you can take the size as a side input:

```
return data.keyBy { 1 }.groupByKey().parDoWithSideInput(data.count) { queries, numQueries -> ...
```


<!-- Sent from Reviewable.io -->

2021-08-17 23:31 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt, line 58 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-MhKsiSxAIr6t0wkciv7:-MhLO_pCCt231WIWCV3z:b22cx17) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0e8995c8c929b03308306937e689a72d0fa21c62/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt#L58)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Remove commented-out flatten please
</blockquote></details>

thx. done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 71 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/86#-Mh5B1_o-P_J_IrZ5x23:-MhLR1eo6jnTyotvqud7:bhbmuqa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a6445ca7429526697d3fbcf415420670b5a82f2d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L71)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Normally the total number of queries will just be `parameters.numShards * parameters.totalQueriesPerShard` -- if you just make that required, then that's true.

In the event that it's not, you can take the size as a side input:

```
return data.keyBy { 1 }.groupByKey().parDoWithSideInput(data.count) { queries, numQueries -> ...
```
</blockquote></details>

good point. do I need to use side input or can it just be part of the parent class? Whats the advantage of each? Did it for now as part of the `data class Parameters...`


<!-- Sent from Reviewable.io -->

2021-08-17 23:44 UTC, merged