add wrapper for query_prepaper and event_data_decryptor
world-federation-of-advertisers/panel-exchange-client pull request #93
Opened 2021-08-18 17:07 UTC by stevenwarejones

2021-08-18 18:10 UTC, efoxepstein requested changes
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93)* status: all files reviewed, 24 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.h, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPDETCheHRiGJd_KG:-MhPPDEU5uFuQfsanvBj:b1m6sb4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.h#L27)):*
> ```objc
> namespace wfa::panelmatch::client::privatemembership {
> absl::StatusOr<
>     wfa::panelmatch::client::privatemembership::DecryptEventDataResponse>
> ```

No qualification needed here
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.h, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPFQUBV4WXLsLVrqL:-MhPPFQUBV4WXLsLVrqM:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.h#L29)):*
> ```objc
>     wfa::panelmatch::client::privatemembership::DecryptEventDataResponse>
> DecryptEventData(
>     const wfa::panelmatch::client::privatemembership::DecryptEventDataRequest&
> ```

Ditto
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPH688xQ3K8zjl2fO:-MhPPH688xQ3K8zjl2fP:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L43)):*
> ```cpp
> 
> absl::StatusOr<
>     wfa::panelmatch::client::privatemembership::DecryptEventDataResponse>
> ```

Ditto
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPHgqEd1_uD6b4fSg:-MhPPHgqEd1_uD6b4fSh:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L45)):*
> ```cpp
>     wfa::panelmatch::client::privatemembership::DecryptEventDataResponse>
> DecryptEventData(
>     const wfa::panelmatch::client::privatemembership::DecryptEventDataRequest&
> ```

Ditto
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPJe20Yarj-bji4Xx:-MhPPJe20Yarj-bji4Xy:b-2nmkts) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L59)):*
> ```cpp
>   for (const std::string& encrypted_event : request.encrypted_event_data()) {
>     ASSIGN_OR_RETURN(
>         const std::string& decrypted_event,
> ```

Don't use a reference here -- the type here is `std::string`, not `std::string&`
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor_wrapper.cc, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPc_BD2h8ado0trzK:-MhPPc_BD2h8ado0trzL:b-w3poin) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor_wrapper.cc#L21)):*
> ```cpp
> #include "absl/status/statusor.h"
> #include "common_cpp/jni/jni_wrap.h"
> #include "wfa/panelmatch/client/privatemembership/decrypt_event_data.pb.h"
> ```

Is this include needed?
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor_wrapper.cc, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPXfR6vwMRS1fyGCI:-MhPPXfR6vwMRS1fyGCJ:b1m6sb4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor_wrapper.cc#L27)):*
> ```cpp
> absl::StatusOr<std::string> DecryptEventDataWrapper(
>     const std::string& serialized_request) {
>   return wfa::JniWrap(serialized_request, DecryptEventData);
> ```

No qualification needed here
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.h, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPhRQ-XAJlW2ax6YW:-MhPPhRQ-XAJlW2ax6YX:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.h#L26)):*
> ```objc
> 
> namespace wfa::panelmatch::client::privatemembership {
> absl::StatusOr<wfa::panelmatch::client::privatemembership::PrepareQueryResponse>
> ```

Ditto
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.h, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPi4G7ROytXnELRyP:-MhPPi4G7ROytXnELRyQ:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.h#L28)):*
> ```objc
> absl::StatusOr<wfa::panelmatch::client::privatemembership::PrepareQueryResponse>
> PrepareQuery(
>     const wfa::panelmatch::client::privatemembership::PrepareQueryRequest&
> ```

Ditto
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPucx0VHOkxvhsya2:-MhPPucx0VHOkxvhsya3:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc#L36)):*
> ```cpp
> using ::crypto::tink::util::SecretDataFromStringView;
> 
> absl::StatusOr<wfa::panelmatch::client::privatemembership::PrepareQueryResponse>
> ```

Ditto
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPvGH1LD_ZDqzuznd:-MhPPvGH1LD_ZDqzuzne:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc#L38)):*
> ```cpp
> absl::StatusOr<wfa::panelmatch::client::privatemembership::PrepareQueryResponse>
> PrepareQuery(
>     const wfa::panelmatch::client::privatemembership::PrepareQueryRequest&
> ```

Ditto
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPxpI-ERX7NO6GqcA:-MhPPxpI-ERX7NO6GqcB:b-ojuypf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc#L45)):*
> ```cpp
>   const Fingerprinter& fingerprinter = GetSha256Fingerprinter();
>   std::unique_ptr<Fingerprinter> peppered_fingerprinter =
>       common::crypto::GetPepperedFingerprinter(
> ```

To make sure this is unambiguous, please write `wfa::panelmatch::common::crypto::GetPe [...]

2021-08-18 22:42 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93)* status: all files reviewed, 24 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/proto/wfa/panelmatch/client/privatemembership/decrypt_event_data.proto, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPQPWj57fsZFzQcc1_:-MhQQ67mAWBSxBWieFgS:brtrklc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/proto/wfa/panelmatch/client/privatemembership/decrypt_event_data.proto#L24)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

From a design perspective, is there a reason we're doing this in a separate stage of the pipeline from stripping off RLWE encryption? In other words, can/should it happen in a single JNI call?
</blockquote></details>

that's a good point. I can make this a todo and add it in when I add in the actual private membership repo. what do you think?


<!-- Sent from Reviewable.io -->

2021-08-18 22:51 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93)* status: all files reviewed, 24 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/proto/wfa/panelmatch/client/privatemembership/decrypt_event_data.proto, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPQPWj57fsZFzQcc1_:-MhQSWtGDnuwvth9YQPE:b-1qn7mu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/proto/wfa/panelmatch/client/privatemembership/decrypt_event_data.proto#L24)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

that's a good point. I can make this a todo and add it in when I add in the actual private membership repo. what do you think?
</blockquote></details>

Sounds good. Please add a TODO.


<!-- Sent from Reviewable.io -->

2021-08-19 17:36 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93)* status: all files reviewed, 24 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.h, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPDETCheHRiGJd_KG:-MhU3RCO-kaE6MvLvTWN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.h#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

No qualification needed here
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.h, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPFQUBV4WXLsLVrqL:-MhU3RXH0d3-cDb7XXz9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.h#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPH688xQ3K8zjl2fO:-MhU3b88-GRxW4Yh0Ohf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPHgqEd1_uD6b4fSg:-MhU3bcGCRT4FnVUD3Dd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPJe20Yarj-bji4Xx:-MhU3e9u7vhqOHn9b91N:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L59)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Don't use a reference here -- the type here is `std::string`, not `std::string&`
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor_wrapper.cc, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPc_BD2h8ado0trzK:-MhUFgCR8ROmDGRmJYnE:b-tza4a5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor_wrapper.cc#L21)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is this include needed?
</blockquote></details>

Done. forgot to put it in the .h file.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor_wrapper.cc, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPXfR6vwMRS1fyGCI:-MhU3rho9vaSX3FWSFDB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor_wrapper.cc#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

No qualification needed here
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.h, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPhRQ-XAJlW2ax6YW:-MhU41cY0p9PwC9vkyUh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.h#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.h, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPi4G7ROytXnELRyP:-MhU42260QpdB5VdOAHP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.h#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPucx0VHOkxvhsya2:-MhU42j112qV3bAFK-r3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc#L36)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPvGH1LD_ZDqzuznd:-MhU42yqC7iwhNCuVNkk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPxpI-ERX7NO6GqcA:-MhU4dVI9LqfnfWbQwoT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer.cc#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

To make sure this is unambiguous, please write `wfa::panelmatch::common::crypto::GetPepperedFingerprinter` (or add a using-decl)
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer_wrapper.cc, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPQ7Y-B0h8Gob-uQ9l:-MhUGmEt0DePZWNNzSfT:b-yiz1v5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer_wrapper.cc#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrot [...]

2021-08-19 18:57 UTC, efoxepstein requested changes
> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93)* status: all files reviewed, 10 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhUjjM7A4ChbwI-zlJd:-MhUjjM7A4ChbwI-zlJe:b7os0e) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L27)):*
> ```cpp
> #include "common_cpp/macros/macros.h"
> #include "tink/util/secret_data.h"
> #include "wfa/panelmatch/client/privatemembership/decrypt_event_data.pb.h"
> ```

This header looks necessary here, since this file directly refers to symbols exported by the header.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhUjrUz2EoIy6TTaTZe:-MhUjrUz2EoIy6TTaTZf:bnhaeul) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/db24f93fa5f211f9c063bcd6b5dfb053029c5be9/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L55)):*
> ```cpp
>   for (const std::string& encrypted_event : request.encrypted_event_data()) {
>     ASSIGN_OR_RETURN(
>         const std::string decrypted_event,
> ```

Note that you can do this in one statement: `ASSIGN_OR_RETURN(*decrypted_event_data.add_decrypted_event_data(), ...)`. If you want an intermediate variable, you'll want to `std::move` it into `add_decrypted_event_data`, which probably means making it non-const.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor_wrapper.h, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhUk71K0qMI43gibT7H:-MhUk71K0qMI43gibT7I:b-cga4ka) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/db24f93fa5f211f9c063bcd6b5dfb053029c5be9/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor_wrapper.h#L23)):*
> ```objc
> 
> #include "absl/status/statusor.h"
> #include "wfa/panelmatch/client/privatemembership/decrypt_event_data.pb.h"
> ```

Please remove this. Since symbols exported by this header are not DIRECTLY used in this file, the #include is not needed.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor_wrapper.cc, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPc_BD2h8ado0trzK:-MhUkDWv-hXZmgD-Lh3I:b-u9cty0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor_wrapper.cc#L21)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Done. forgot to put it in the .h file.
</blockquote></details>

It's not needed there either. The rule is very simple: if some file uses some symbol, it should have a header defining that symbol. Subject to that, the set of includes should be minimal.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer_wrapper.h, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhUkWW87J0YLF_obDxS:-MhUkWW87J0YLF_obDxT:b-t9dsij) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/db24f93fa5f211f9c063bcd6b5dfb053029c5be9/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer_wrapper.h#L23)):*
> ```objc
> 
> #include "absl/status/statusor.h"
> #include "wfa/panelmatch/client/privatemembership/prepare_query.pb.h"
> ```

Not needed here.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer_wrapper.cc, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPQ7Y-B0h8Gob-uQ9l:-MhUkXfB5bLajAgR4b34:b-n5mvpi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer_wrapper.cc#L20)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

moved to .h file
</blockquote></details>

Not needed there either
___
*[src/main/proto/wfa/panelmatch/client/eventpreprocessing/BUILD.bazel, line 3 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhUk_FSBwfXEVqD4Opj:-MhUk_FSBwfXEVqD4Opk:b-drtqx3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/db24f93fa5f211f9c063bcd6b5dfb053029c5be9/src/main/proto/wfa/panelmatch/client/eventpreprocessing/BUILD.bazel#L3)):*
> ```Starlark
> load("@rules_proto//proto:defs.bzl", "proto_library")
> load("@rules_java//java:defs.bzl", "java_proto_library")
> load("@wfa_common_jvm//build:kt_jvm_proto_library.bzl", "kt_jvm_proto_library")
> ```

Duplicate?
___
*[src/main/proto/wfa/panelmatch/client/privatemembership/BUILD.bazel, line 3 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhUkagI5RGJFNnoH_bV:-MhUkagI5RGJFNnoH_bW:b-drtqx3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/db24f93fa5f211f9c063bcd6b5dfb053029c5be9/src/main/proto/wfa/panelmatch/client/privatemembership/BUILD.bazel#L3)):*
> ```Starlark
> load("@rules_proto//proto:defs.bzl", "proto_library")
> load("@rules_java//java:defs.bzl", "java_proto_library")
> load("@wfa_common_jvm//build:kt_jvm_proto_library.bzl", "kt_jvm_proto_library")
> ```

Duplicate?
___
*[src/main/proto/wfa/panelmatch/protocol/crypto/BUILD.bazel, line 3 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhUkmydCObxnSet28xs:-MhUkmydCObxnSet28xt:b-witi0q) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/db24f93fa5f211f9c063bcd6b5dfb053029c5be9/src/main/proto/wfa/panelmatch/protocol/crypto/BUILD.bazel#L3)):*
> ```Starlark
> load("@rules_proto//proto:defs.bzl", "proto_library")
> load("@rules_java//java:defs.bzl", "java_proto_library")
> load("@wfa_common_jvm//build:kt_jvm_proto_library.bzl", "kt_jvm_proto_library")
> ```

Duplicate
___
*[src/test/cc/wfa/panelmatch/client/privatemembership/decrypt_event_data_test.cc, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPQggR1miigjGKvnPA:-MhUkpfUDhKAuZu8ft_1:b-igb311) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/test/cc/wfa/panelmatch/client/privatemembership/decrypt_event_data_test.cc#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you fix the ones starting with `using crypto` too?


<!-- Sent from Reviewable.io -->

2021-08-19 19:12 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93)* status: all files reviewed, 10 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhUjjM7A4ChbwI-zlJd:-MhUmwAc5bPD2bX4vgyp:bq6cqmx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This header looks necessary here, since this file directly refers to symbols exported by the header.
</blockquote></details>

Done. but I'm confused why it should be removed since this file refers to SecretData from Tink
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhUjrUz2EoIy6TTaTZe:-MhUoSshAAKp6G0yDOxp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/db24f93fa5f211f9c063bcd6b5dfb053029c5be9/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Note that you can do this in one statement: `ASSIGN_OR_RETURN(*decrypted_event_data.add_decrypted_event_data(), ...)`. If you want an intermediate variable, you'll want to `std::move` it into `add_decrypted_event_data`, which probably means making it non-const.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor_wrapper.h, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhUk71K0qMI43gibT7H:-MhUmuUdAPViHjDYds2u:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/db24f93fa5f211f9c063bcd6b5dfb053029c5be9/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor_wrapper.h#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please remove this. Since symbols exported by this header are not DIRECTLY used in this file, the #include is not needed.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor_wrapper.cc, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPPc_BD2h8ado0trzK:-MhUnzOZ7IaBJfQFEyRl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor_wrapper.cc#L21)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's not needed there either. The rule is very simple: if some file uses some symbol, it should have a header defining that symbol. Subject to that, the set of includes should be minimal.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer_wrapper.h, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhUkWW87J0YLF_obDxS:-MhUntBF57v9ejguJx9B:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/db24f93fa5f211f9c063bcd6b5dfb053029c5be9/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer_wrapper.h#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Not needed here.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer_wrapper.cc, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPQ7Y-B0h8Gob-uQ9l:-MhUnphM80yIprtG5-MG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/query_preparer_wrapper.cc#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Not needed there either
</blockquote></details>

Done.
___
*[src/main/proto/wfa/panelmatch/client/eventpreprocessing/BUILD.bazel, line 3 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhUk_FSBwfXEVqD4Opj:-MhUnIhY7uuwzQzzQVRG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/db24f93fa5f211f9c063bcd6b5dfb053029c5be9/src/main/proto/wfa/panelmatch/client/eventpreprocessing/BUILD.bazel#L3)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Duplicate?
</blockquote></details>

Done.
___
*[src/main/proto/wfa/panelmatch/client/privatemembership/BUILD.bazel, line 3 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhUkagI5RGJFNnoH_bV:-MhUnGtZCNjPk39ZLGD0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/db24f93fa5f211f9c063bcd6b5dfb053029c5be9/src/main/proto/wfa/panelmatch/client/privatemembership/BUILD.bazel#L3)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Duplicate?
</blockquote></details>

Done.
___
*[src/main/proto/wfa/panelmatch/protocol/crypto/BUILD.bazel, line 3 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhUkmydCObxnSet28xs:-MhUnEjv78Yblh447crS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/db24f93fa5f211f9c063bcd6b5dfb053029c5be9/src/main/proto/wfa/panelmatch/protocol/crypto/BUILD.bazel#L3)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Duplicate
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/client/privatemembership/decrypt_event_data_test.cc, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhPQggR1miigjGKvnPA:-MhUn7SX7E08FKU_NNd-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/test/cc/wfa/panelmatch/client/privatemembership/decrypt_event_data_test.cc#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you fix the ones starting with `using crypto` too?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-19 19:16 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93)* status: 12 of 21 files reviewed, 10 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhUjjM7A4ChbwI-zlJd:-MhUpicoAyveyyGgA45R:b55y3l1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Done. but I'm confused why it should be removed since this file refers to SecretData from Tink
</blockquote></details>

Reviewable did something weird, this comment was supposed to be elsewhere.... Tink Secret Data should definitely be included, sorry about that!


<!-- Sent from Reviewable.io -->

2021-08-19 19:27 UTC, efoxepstein approved these changes
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-19 19:44 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/93#-MhUjjM7A4ChbwI-zlJd:-MhUvJ3JE5W5jYyd3caO:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/da924194640d76333231c439d004e8c24d3025b1/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Reviewable did something weird, this comment was supposed to be elsewhere.... Tink Secret Data should definitely be included, sorry about that!
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-08-19 19:54 UTC, merged