start integrating google private membership repo
world-federation-of-advertisers/panel-exchange-client pull request #96
Opened 2021-08-20 01:18 UTC by stevenwarejones

2021-08-20 01:20 UTC, stevenwarejones reviewed
@efoxepstein - I wanted some early feedback if you are okay with me replacing the existing oblvious_query directly with google private membership. I also had a dependency question below.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-:-MhW85F77Ko6ofJgwnJh:b5ui16f)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhW7uHG9G7P7iVleLK5:-MhW7uHG9G7P7iVleLK6:b-ql2h4e) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/91f81fd6c07e4176f1398e5ea6b5e4495f6f1568/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L29)):*
> ```Kotlin
> import org.wfanet.panelmatch.common.beam.parDo
> import org.wfanet.panelmatch.common.beam.values
> import private_membership.batch.EncryptQueriesResponse
> ```

@efoxepstein - what is the right way to import private membership into kotlin? Its working for me in cpp. Not sure what I'm doing wrong here.


<!-- Sent from Reviewable.io -->

2021-08-20 01:21 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/test/cc/wfa/panelmatch/client/privatemembership/oblivious_query_test.cc, line 0 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhW8K7V6NltVNub248h:-MhW8K7V6NltVNub248i:b-yd34qu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/91f81fd6c07e4176f1398e5ea6b5e4495f6f1568/src/test/cc/wfa/panelmatch/client/privatemembership/oblivious_query_test.cc#L0)):*
I don't think we would need this test anymore, right? We could just write kotlin tests. What do you think?


<!-- Sent from Reviewable.io -->

2021-08-20 02:04 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhW7uHG9G7P7iVleLK5:-MhWHcLDEXzhNHKCcNIO:b-lqabc1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/91f81fd6c07e4176f1398e5ea6b5e4495f6f1568/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@efoxepstein - what is the right way to import private membership into kotlin? Its working for me in cpp. Not sure what I'm doing wrong here.
</blockquote></details>

It looks like the .proto file is missing an option for a Java package. I'll send a PR to private-membership tomorrow morning. If you want to be unblocked you could see if the symbols are available in the root (blank) package, not sure how that works. You should also be able to find the generated Java and Kotlin files somewhere in bazel-out...


<!-- Sent from Reviewable.io -->

2021-08-20 05:20 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhW7uHG9G7P7iVleLK5:-MhX-16o7uyjjiKgVHYv:b-nvhxeq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/91f81fd6c07e4176f1398e5ea6b5e4495f6f1568/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It looks like the .proto file is missing an option for a Java package. I'll send a PR to private-membership tomorrow morning. If you want to be unblocked you could see if the symbols are available in the root (blank) package, not sure how that works. You should also be able to find the generated Java and Kotlin files somewhere in bazel-out...
</blockquote></details>

Also if you need to get unblocked, just duplicate that .proto file and add the java_package option yourself for now. Hoping by noon tomorrow we can have the fix pushed, though.


<!-- Sent from Reviewable.io -->

2021-08-23 20:25 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96)* status: 0 of 23 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptorTest.kt, line 80 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhofrocC5VTfdSHjqU4:-MhofrocC5VTfdSHjqU5:be6yg8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptorTest.kt#L80)):*
> ```Kotlin
>   @Test
>   fun `Decrypt Encrypted Result`() {
>     // TODO
> ```

@efoxepstein - You may have already done this but I need some encrypted result data to test against. Not sure how to generate that.


<!-- Sent from Reviewable.io -->

2021-08-23 20:47 UTC, efoxepstein requested changes
> Reviewed 6 of 13 files at r1, 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96)* status: all files reviewed, 17 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/oblivious_query_wrapper.cc, line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-Mhogaek1K56xyWOpx8d:-Mhogaek1K56xyWOpx8e:b-5v0xix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/cc/wfa/panelmatch/client/privatemembership/oblivious_query_wrapper.cc#L25)):*
> ```cpp
> 
> namespace wfa::panelmatch::client::privatemembership {
> using private_membership::batch::DecryptQueries;
> ```

Fully qualify please (https://abseil.io/tips/119)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 151 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhogkcG4wC4P0GxxBTH:-MhogkcG4wC4P0GxxBTI:b-trwk60) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L151)):*
> ```Kotlin
>       ) {
>         val encryptQueriesRequest =
>           EncryptQueriesRequest.newBuilder().addAllUnencryptedQuery(it.value).build()
> ```

OOC why did you move this back to a Java builder?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptor.kt, line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-Mhogvt85SLv0V7uzW_J:-Mhogvt85SLv0V7uzW_K:b-uskdnd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptor.kt#L53)):*
> ```Kotlin
>         ClientGenerateKeysResponse.parseFrom(
>           ObliviousQueryWrapper.generateKeysWrapper(clientRequest.toByteArray())
>         )
> ```

```
val keys = wrapJniException { ... }
return generateKeysResponse { ... }
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptor.kt, line 79 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-Mhoh4jd-Ty3zDnVwIPZ:-Mhoh4jd-Ty3zDnVwIP_:b-145jjp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptor.kt#L79)):*
> ```Kotlin
>       this.plaintextQueries += plaintextQueries
>     }
>     return wrapJniException {
> ```

Ditto -- `wrapJniException` should wrap as little as possible
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Protos.kt, line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhohRns-SiGnAXXPs1Z:-MhohRns-SiGnAXXPs1_:b5d1g0o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Protos.kt#L39)):*
> ```Kotlin
> }
> 
> fun encryptedQueryOf(shard: Int, query: Int): EncryptedQuery =
> ```

KDoc please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Protos.kt, line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhohTKZ9JA78Jaj_0Ly:-MhohTKZ9JA78Jaj_0Lz:b5d1g0o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Protos.kt#L48)):*
> ```Kotlin
> }
> 
> fun plaintextOf(plaintext: ByteString, query: Int, shard: Int): DecryptedQueryResult {
> ```

KDoc please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Protos.kt, line 63 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhohU2Y3V6od9sqi79B:-MhohU2Y3V6od9sqi79C:b5d1g0o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Protos.kt#L63)):*
> ```Kotlin
> // TODO some of the tests don't verify the plaintext lines up with the correct queryId. Delete the
> // following after that is implemented
> fun plaintextOf(plaintext: String): DecryptedQueryResult {
> ```

KDoc please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt, line 107 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhohibbC9cMt2uIl2Hi:-MhohibcEWDUVtjs3Qsa:b-thhvab) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt#L107)):*
> ```Kotlin
>       encryptedQueryResults
>         .map { result ->
>           decodeResultData(Result.parseFrom(result.ciphertextList.first())).toStringUtf8()
> ```

Do we expect there will always be exactly one ciphertext here or are we deliberately ignoring the rest? If exactly one, please use `.single()` -- which will throw if there isn't exactly one.
___
*[src/main/proto/wfa/panelmatch/client/privatemembership/BUILD.bazel, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-Mhoi7eu0lVHrS9w9Lsm:-Mhoi7ez31II1Z-Tn35b:bftpd8f) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/proto/wfa/panelmatch/client/privatemembership/BUILD.bazel#L70)):*
> ```Starlark
> )
> 
> cc_proto_library(
> ```

Can we just refer to this? https://github.com/google/private-membership/blob/main/private_membership/rlwe/batch/cpp/client/BUILD#L18
___
*[src/main/proto/wfa/panelmatch/client/privatemembership/oblivious_query.proto, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhoiMaHCuR5OiiXd7Ap:-MhoiMaHCuR5OiiXd7Aq:b-r4n9n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/proto/wfa/panelmatch/client/privatemembership/oblivious_query.proto#L70)):*
> ```protobuf
>   ShardId shard_id = 1;
>   QueryId query_id = 2;
>   repeated bytes ciphertext = 3;
> ```

Please pluralize repeated fields. If this is actually just one thing, then is `repeated` needed at all?
___
*[src/test/cc/wfa/panelmatch/client/privatemembership/oblivious_query_test.cc, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhW8K7V6NltVNub248h:-MhoifeS-jCf7RS0tPbs:bb74ce2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/91f81fd6c07e4176f1398e5ea6b5e4495f6f1568/src/test/cc/wfa/panelmatch/client/privatemembership/oblivious_query_test.cc#L)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I don't think we would need this test anymore, right? We could just write kotlin tests. What do you think?
</blockquote></details>

Sure
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptorTest.kt, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhoihGi3-v9sB-jlp-R:-MhoihGi3-v9sB-jlp-S:bavj5eg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a82 [...]

2021-08-23 21:26 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96)* status: 22 of 23 files reviewed, 16 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/oblivious_query_wrapper.cc, line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-Mhogaek1K56xyWOpx8d:-Mhood0yExb89KhXLRFn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/cc/wfa/panelmatch/client/privatemembership/oblivious_query_wrapper.cc#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Fully qualify please (https://abseil.io/tips/119)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 151 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhogkcG4wC4P0GxxBTH:-Mhook1r4mbhCo4hXnid:b-3u8he5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L151)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

OOC why did you move this back to a Java builder?
</blockquote></details>

I think I was playing with incorporating the `private-membership` protos before reverting. thanks for pointing that out.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptor.kt, line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-Mhogvt85SLv0V7uzW_J:-MhoszJp2sJeMlTNpwez:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptor.kt#L53)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

```
val keys = wrapJniException { ... }
return generateKeysResponse { ... }
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptor.kt, line 79 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-Mhoh4jd-Ty3zDnVwIPZ:-Mhoszky9nozGTTQDMC6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptor.kt#L79)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto -- `wrapJniException` should wrap as little as possible
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Protos.kt, line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhohRns-SiGnAXXPs1Z:-MhopJxkBwEyNqpNENXR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Protos.kt#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

KDoc please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Protos.kt, line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhohTKZ9JA78Jaj_0Ly:-MhopKQz9XNIcIYhJYwS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Protos.kt#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

KDoc please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Protos.kt, line 63 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhohU2Y3V6od9sqi79B:-MhopKu29EneNaYLN9ws:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Protos.kt#L63)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

KDoc please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt, line 107 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhohibbC9cMt2uIl2Hi:-MhopMdy2F1iuB7Tpiok:b-ky7bh5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt#L107)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Do we expect there will always be exactly one ciphertext here or are we deliberately ignoring the rest? If exactly one, please use `.single()` -- which will throw if there isn't exactly one.
</blockquote></details>

The plaintext private membership cryptor currently only populates the first ciphertext. Changed to single and added a comment. The JNI one populates many, of course.
___
*[src/main/proto/wfa/panelmatch/client/privatemembership/BUILD.bazel, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-Mhoi7eu0lVHrS9w9Lsm:-MhopjKr7MKgSMH4l0YZ:b-z9pspq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/proto/wfa/panelmatch/client/privatemembership/BUILD.bazel#L70)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can we just refer to this? https://github.com/google/private-membership/blob/main/private_membership/rlwe/batch/cpp/client/BUILD#L18
</blockquote></details>

Yes. I thought we might want to have a wrapper in case we don't want to at some point. That way, if many many files ended up referring this dependency, we only need to change one thing on our end to re-map it.
___
*[src/main/proto/wfa/panelmatch/client/privatemembership/oblivious_query.proto, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhoiMaHCuR5OiiXd7Ap:-Mhopup_1I_qAQdx30L3:b-ed3vaf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/proto/wfa/panelmatch/client/privatemembership/oblivious_query.proto#L70)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please pluralize repeated fields. If this is actually just one thing, then is `repeated` needed at all?
</blockquote></details>

pluralized
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptorTest.kt, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhoihGi3-v9sB-jlp-R:-MhoqD55BSfmFPl7IYji:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptorTest.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Unnecessary parens
</blockquote></details>

Done.
___
*[src/test/kotl [...]

2021-08-23 21:51 UTC, efoxepstein requested changes
> Reviewed 1 of 1 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptor.kt, line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-Mhogvt85SLv0V7uzW_J:-MhozBXSBQCMLVLfJmsw:b-ut7np8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptor.kt#L53)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptorTest.kt, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhojFCUBWPnmfR8Q673:-MhoyrwS9v5VIg0e62T-:b-g4wln7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptorTest.kt#L33)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I was having issues importing these two protos using the new DSL. I guess because they are sub-messages inside Private-Membership repo. Whats the right import?
</blockquote></details>

"private_membership_shared_kt_jvm_proto" should give it -- I'd expect the import to be import com.google.privatemembership.batch.ShardParametersKt.shardParameters maybe? Something like that. Sync intellij and have it find it for you?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt, line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhogIB0-IG7Vne7ME5I:-MhozlkWBDHJzv5uDjb7:b-9playo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt#L32)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't look done


<!-- Sent from Reviewable.io -->

2021-08-24 00:36 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptor.kt, line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-Mhogvt85SLv0V7uzW_J:-MhpVZDW5cWCM-yeSbyE:b-n61fs0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptor.kt#L53)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't see it
</blockquote></details>

oh I see what I did. you made two comments about it but 3 places needed fixing. I fixed one you didn't comment about. Fixed this one too.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptorTest.kt, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhojFCUBWPnmfR8Q673:-MhpZt9dD_vyatmTFdkM:b-7rl0kd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptorTest.kt#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

"private_membership_shared_kt_jvm_proto" should give it -- I'd expect the import to be import com.google.privatemembership.batch.ShardParametersKt.shardParameters maybe? Something like that. Sync intellij and have it find it for you?
</blockquote></details>

done
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptorTest.kt, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhojHmf1WNmf9Zy_S64:-MhpZuUTDAmRCeorA3tI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptorTest.kt#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Use Kotlin DSL?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt, line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96#-MhogIB0-IG7Vne7ME5I:-MhpVLaz9BSW2JshnKGl:bmaecq0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/110b2b15320f9a455c8525b5e6cfd261a8274ca1/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Doesn't look done
</blockquote></details>

done again :)


<!-- Sent from Reviewable.io -->

2021-08-24 00:41 UTC, efoxepstein approved these changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/96)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-24 01:01 UTC, merged